
-- Оплата информации осведомителю.
function has_money_for_informer_1(actor, npc)
	return actor:money() >= 400
end

function give_money_for_informer_1(actor, npc)
	dialogs.relocate_money(npc, 400, "out")
end

function has_money_for_informer_2(actor, npc)
	return actor:money() >= 200
end

function give_money_for_informer_2(actor, npc)	
	dialogs.relocate_money(npc, 200, "out")
end

function has_money_for_informer_3(actor, npc)
	return actor:money() >= 350
end

function give_money_for_informer_3(actor, npc)	
	dialogs.relocate_money(npc, 350, "out")
end


-- Проверка на открытие склада охранником (ночью, плюсом когда Крыса уехал после Греховцев на пару дней)
function can_ohrana_bar_open_sklad()
    if has_alife_info("olr_traders_night") then
        return true
    end
    if has_alife_info("greh_leader_key_taken_docs_vetri") and not has_alife_info("bar_krisa_vernulsya_after_greh") then
        return true
    end
    return false
end
