
local repaintnow = false

local att
local ptatt

function init(obj)
	local new_binder = CInventoryBoxBinder(obj)
	obj:bind_object(new_binder)
end

class "CInventoryBoxBinder" (object_binder)
function CInventoryBoxBinder:__init(obj) super(obj)
end 

function CInventoryBoxBinder:reload(section)
	object_binder.reload(self, section)
end

function CInventoryBoxBinder:reinit()
	object_binder.reinit(self)
 
        self.object:set_callback(callback.on_inv_box_item_take, self.on_inv_box_item_take, self)
        self.object:set_callback(callback.on_inv_box_item_drop, self.on_inv_box_item_drop, self)

end

function CInventoryBoxBinder:on_inv_box_item_take(obj)

	if not obj or obj == nil then
		return
	end

	bind_inventory_box.repaint()
	bind_inventory_box.repaint()
end


function CInventoryBoxBinder:on_inv_box_item_drop(obj)
	bind_inventory_box.repaint()
	bind_inventory_box.repaint()
end

function CInventoryBoxBinder:update(delta)
	if db.actor == nil then
		return
	end
	if db.actor:has_info("ui_car_body") and repaintnow == false then
		local loked_obj = bind_stalker.loked_obj_state()
		local loked_obj_name = bind_stalker.loked_obj_name_state()
		if ui.get_car_body_wnd() and not att and loked_obj ~= nil and loked_obj_name == self.object:name() then
			ptatt = ui.get_car_body_wnd()
			att = bind_inventory_box.ui_trade()
			ptatt:AttachChild(att)
			att:SetAutoDelete(true)
			att:Show(true)
			--log1("show true")
		end	
	else
		if att and ptatt then
			att:Show(false)
			ptatt:DetachChild(att)
			att = nil
			ptatt = nil
		end
	end
end

function CInventoryBoxBinder:net_spawn(data)
	if not object_binder.net_spawn(self, data) then
		return false
	end
	--log1("netspawn box - "..self.object:name().."")
	return true
end

function CInventoryBoxBinder:net_destroy()
	object_binder.net_destroy(self)	
	self.object:set_callback(callback.on_inv_box_item_take, nil)
        self.object:set_callback(callback.on_inv_box_item_drop, nil)
end

function CInventoryBoxBinder:net_save_relevant()
	return true
end

---------------------------------------------------------------------------------------------------------------------

function repaint()
	repaintnow = true
	local wait_time = 0
  	wait_time = time_global() + 5
  	level.add_call(
    	function() return time_global() > wait_time end,
    	function() repaintnow = false end
  	)
end	

class "ui_trade" (CUIScriptWnd)

function ui_trade:__init(owner) super()
	self.owner = owner
	self:InitControls()
	--log1("show true 0")
end

function ui_trade:__finalize() end

function ui_trade:InitControls()
	self:Init(0,0,1024,768)
	--log1("show true 1")

end