--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
-- name: bind_anomaly.script
-- desc: Биндер аномалий, не сильно нужен
-- author: theysani
-- date: 19.12.2025
-- last edit: 19.12.2025
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

function Init(obj)
	local oNewBinder = anomaly_binder(obj)
	obj:bind_object(oNewBinder)	
end

class "anomaly_binder" (object_binder)

function anomaly_binder:__init(obj) super(obj)
end

function anomaly_binder:reload(section)
	object_binder.reload(self, section)
end

function anomaly_binder:reinit()
	object_binder.reinit(self)
end

function anomaly_binder:net_save_relevant()
	return true
end

function anomaly_binder:save(packet)
	object_binder.save(self, packet)	
end

function anomaly_binder:load(reader)
	object_binder.load(self, reader)
	
end

function anomaly_binder:net_spawn(data)
	if not object_binder.net_spawn(self, data) then
		return false
	end

	db.anoms_online[self.object:id()] = self.object

	return true
end
	
function anomaly_binder:net_destroy()
	object_binder.net_destroy(self)
	db.anoms_online[self.object:id()] = nil
	--anomaly_evader.DestroyAnom(self.object)
end

function anomaly_binder:update(delta)
	object_binder.update(self, delta)
end

-----------------------------------------------------------------------------------------------------------------
-- by AMK team

function get_anomaly_list_for_pos(posn, radius)
    local ret = {}
    if db.anoms_online then
        for id, o in pairs(db.anoms_online) do
            local obj = level.object_by_id(id)
            if obj then
                local dist = posn:distance_to(obj:position()) - obj:get_shape_radius()
                if dist < radius then
                    table.insert(ret, {id = id, name = obj:name(), pos = obj:position(), radius = obj:get_shape_radius()})
                end
            end
        end
    end
    return ret
end