function init    (obj)
	xr_motivator.AddToMotivator(obj)
end

function actor_init    (npc)
	npc:bind_object(actor_binder(npc))
end

local game_difficulty_by_num = {
	[0] = "gd_novice",
	[1] = "gd_stalker",
	[2] = "gd_veteran",
	[3] = "gd_master"
}

max_item_amount = 0
lasthealth  = 0
lasttime	= 0
post_process = 0

quitting_game = false
local weapon_hide = false

local loked_obj = nil
local loked_obj_name = ""

local dbg_time = false -- выводит время на худ используя статик debug_time

----------------------------------------------------------------------------------------------------------------------
class "actor_binder" (object_binder)
----------------------------------------------------------------------------------------------------------------------
function actor_binder:__init (obj) super(obj)
	self.bCheckStart = false
	self.surge_manager = surge_manager.get_surge_manager()
	self.weather_manager = level_weathers.WeatherManager()
	self.actor_detector = xr_detector.actor_detector()
	_G.xvars = get_stored_vars()
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_spawn(data)		

	level.show_indicators()

	self.bCheckStart = true
	self.weapon_hide = false -- спрятано или нет оружие при разговоре.
	weapon_hide = false -- устанавливаем глобальный дефолтовый флаг.

	if object_binder.net_spawn(self,data) == false then
		return false
	end

	db.add_actor(self.object)

	if self.st.disable_input_time == nil then
		level.enable_input()
	end

	self.weather_manager:reset()

	if(actor_stats.add_to_ranking~=nil)then
		actor_stats.add_to_ranking(self.object:id())
	end

	-- Загружаем настройки дропа
	death_manager.init_drop_settings()

	core.tc("actor_net_spawn")
	olr.actor_net_spawn()

	if (news_main) then
		news_main.init()
	end
	
	if (amk_offline_alife) then
		amk_offline_alife.init()
	end
	
	if (amk_offline_alife) then
		amk_offline_alife.update_npc_tables()
	end

	if xvars.chang_lev ~= level.name() then
		xvars.chang_lev = level.name()
		olr.change_level()
	end
	
	xvars.cur_fov = device():get_fov() -- заполняем cur_fov на момент нет-спавна актора, если вдруг дадим менять его то надо будет что-то еще придумывать
	
	get_console():execute("ph_timefactor 1") -- на всякий случай если вдруг мы вылезем из схемы sr_water а таймфактор физики не сбросится на единицу. Репорты были по этой кривой схеме. Решение пока такое.

	return true
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_destroy()
    if (actor_stats.remove_from_ranking ~= nil) then
        actor_stats.remove_from_ranking(self.object:id())
    end

    db.del_actor(self.object)

    sr_light.clean_up()

    self.object:set_callback(callback.inventory_info, nil)
    self.object:set_callback(callback.article_info, nil)
    self.object:set_callback(callback.on_item_take, nil)
    self.object:set_callback(callback.on_item_drop, nil)
    self.object:set_callback(callback.task_state, nil)
    self.object:set_callback(callback.level_border_enter, nil)
    self.object:set_callback(callback.level_border_exit, nil)
    self.object:set_callback(callback.take_item_from_box, nil)
    self.object:set_callback(callback.use_object, nil)
    self.object:set_callback(callback.on_item_belt, nil)
    self.object:set_callback(callback.on_item_slot, nil)
    self.object:set_callback(callback.on_item_ruck, nil)
    self.object:set_callback(callback.on_inv_item_select, nil)
    self.object:set_callback(callback.on_actor_weapon_fire, nil)
    self.object:set_callback(callback.on_eat_hud_object, nil)
    self.object:set_callback(callback.on_trade_btn_click, nil)
    self.object:set_callback(callback.on_actor_landed, nil)
    self.object:set_callback(callback.on_key_press, nil)
    self.object:set_callback(callback.on_mouse_press, nil)
	self.object:set_callback(callback.on_level_map_click, nil)

	self.object:set_callback(callback.on_item_volume_exceeded, nil)
	self.object:set_callback_bool(callback.on_item_can_take, nil)
	
	--theysani added
	self.object:set_callback(callback.on_drop_item_on_item, nil)
	self.object:set_callback(callback.on_obj_look, nil)
	self.object:set_callback(callback.on_obj_not_look, nil)
	
    ---self.object:set_callback(callback.on_actor_death, nil)

    if sr_psy_antenna.psy_antenna then
        sr_psy_antenna.psy_antenna:destroy()
        sr_psy_antenna.psy_antenna = false
    end

    xr_sound.stop_all_sound_object()

    bind_car.net_destroy(self.object)

    object_binder.net_destroy(self)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:reinit()
	object_binder.reinit(self)
	
	local npc_id = self.object:id()

	db.storage[npc_id] = { }

	self.st = db.storage[npc_id]

	if alife() then
		self.st.pstor = nil
	end

	self.next_restrictors_update_time = -10000

	self.object:set_callback(callback.inventory_info, self.info_callback, self)
	self.object:set_callback(callback.article_info, self.article_callback, self)
	self.object:set_callback(callback.on_item_take, self.on_item_take, self)
	self.object:set_callback(callback.on_item_drop, self.on_item_drop, self)
	self.object:set_callback(callback.trade_sell_buy_item, self.on_trade, self) -- for game stats
	self.object:set_callback(callback.task_state, self.task_callback, self)
	self.object:set_callback(callback.level_border_enter, self.level_border_enter, self)
	self.object:set_callback(callback.level_border_exit, self.level_border_exit, self)
	self.object:set_callback(callback.take_item_from_box, self.take_item_from_box, self)
    self.object:set_callback(callback.hit, self.on_hit, self)
    self.object:set_callback(callback.use_object, self.use_obj, self)
    self.object:set_callback(callback.on_item_belt, self.obj_to_belt, self)       
	self.object:set_callback(callback.on_item_ruck, self.obj_to_ruck, self)
	self.object:set_callback(callback.on_inv_item_select, self.on_select_item, self)
    self.object:set_callback(callback.on_item_slot, self.obj_to_slot, self) 
    self.object:set_callback(callback.on_eat_hud_object, self.OnEatHudObj, self)
    self.object:set_callback(callback.on_trade_btn_click, self.OnTrdBtnClick, self)
    self.object:set_callback(callback.on_actor_landed, self.actor_landed, self)
    self.object:set_callback(callback.on_actor_weapon_fire, self.on_actor_shoot, self)
    self.object:set_callback(callback.on_key_press, self.OnKey, self)
    self.object:set_callback(callback.on_mouse_press, self.mouse_press, self)
	self.object:set_callback(callback.on_level_map_click, self.on_map_click, self)

	self.object:set_callback(callback.on_item_volume_exceeded, self.on_item_volume_exceeded, self)
	self.object:set_callback_bool(callback.on_item_can_take, self.on_item_can_take, self)
	
	--theysani added
	self.object:set_callback(callback.on_drop_item_on_item, self.on_drop_item_on_item, self)
	self.object:set_callback(callback.on_obj_look, self.on_look, self) 
	self.object:set_callback(callback.on_obj_not_look, self.on_not_look, self)
	
    --self.object:set_callback(callback.on_actor_death, self.OnActorDeath, self)

    bind_car.reinit(self.object)
end

function actor_binder:on_drop_item_on_item(item1, item2)
    --log1("on_drop_item_on_item: item1 = "..item1:name()..", item 2 = "..item2:name().."")
    
    -- Если предметы одинаковые - выходим
    if item1:name() == item2:name() then return end
    
    local section1 = item1:section()
    local section2 = item2:section()

    -- Функции проверки типов предметов
    local function is_detector(section)
        return section == "detector_simple" or 
               section == "detector_advances" or 
               section == "detector_elite" or
			   section == "psivizor_detector"
    end

    local function is_torch(section)
        return section == "device_torch"
    end

    local function is_torch_battery(section)
        return section == "battery_change_headlamp"
    end

    local function is_detector_battery(section)
        return section == "battery_change"
    end

    local function is_medical_combo(s1, s2)
        return (s1 == "med_injector_empty" and s2 == "med_injector_capsule") or
               (s1 == "med_injector_capsule" and s2 == "med_injector_empty")
    end

    -- 1. Обработка медицинских предметов (высший приоритет)
    if is_medical_combo(section1, section2) then
        olr.del(item1)
        olr.del(item2)
		alife():create("med_injector", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
        olr.snd([[interface\inv_slot]])
        return
    end

    -- 2. Зарядка ФОНАРИКА (только battery_change_headlamp)
    if (is_torch(section1) and is_torch_battery(section2)) or
       (is_torch_battery(section1) and is_torch(section2)) then
        
        local torch = is_torch(section1) and item1 or item2
        local battery = is_torch_battery(section1) and item1 or item2
		
        if torch:condition() < 1 then
			torch:set_condition(1)
			olr.del(battery)
			
			local message = game.translate_string("st_olr_item_efs_charge").." ["..torch:get_name().."] - 100%"
			news_manager.send_tip(db.actor, message, nil, "info", 3000)
			olr.snd([[interface\inv_slot]])
		end
        return
    end

    -- 3. Зарядка ДЕТЕКТОРА (только battery_change)
    if (is_detector(section1) and is_detector_battery(section2)) or
       (is_detector_battery(section1) and is_detector(section2)) then
        
        local detector = is_detector(section1) and item1 or item2
        local battery = is_detector_battery(section1) and item1 or item2
        
        if detector:condition() < 1 then
            detector:set_condition(1)
            olr.del(battery)
            
            local message = game.translate_string("st_olr_item_efs_charge").." ["..detector:get_name().."] - 100%"
            news_manager.send_tip(db.actor, message, nil, "info", 3000)
            olr.snd([[interface\inv_slot]])
        end
        return
    end

    -- 4. Блокировка всех нежелательных комбинаций
    if (is_torch(section1) or is_detector(section1) or
        is_torch(section2) or is_detector(section2)) then
        -- Если один из предметов - устройство, а второй не батарейка - игнорируем
        return
    end
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:take_item_from_box(box, item)
	local story_id = box:story_id()
	if story_id == nil then
		return
	end
	if box:section() == "box_rukzak_treasure" and box:is_inv_box_empty() then
		level.start_stop_menu(level.main_input_receiver(), true)
		olr.give_item("custom_treasure_rukzak")
		olr.del(box)
	end
end
----------------------------------------------------------------------------------------------------------------------

function actor_binder:on_map_click(pos, level)
	--news_manager.send_tip(db.actor, " "..pos.x..""..pos.y..""..pos.z.." -  "..level.."", nil, "freedom", 9000)
end

-- hi_flyer 21/04/17
local prev_id = -1
function actor_binder:on_look(obj)
    if obj then
		olr_on_look.look_item(obj)
        if obj:id() ~= prev_id then
            prev_id = obj:id()
            loked_obj = obj
            --log1("loked_obj is "..loked_obj:name().."")
            loked_obj_name = obj:name() -- for debug
            olr_on_look.look_change(obj)
        end
    end
end

function actor_binder:on_not_look()
	if loked_obj ~= nil then 
		prev_id = -1
		loked_obj = nil
		loked_obj_name = nil
		--log1("loked_obj is nil")
	end
end

function loked_obj_state()
	return loked_obj
end

function loked_obj_name_state()
	return loked_obj_name
end

local timej = 0
local ftup = math.random(500,600)
-- hi_flyer 05/03/17
function actor_binder:actor_landed(power)
	--log1("landed")
	if power >= 0.1 then
		if device().precache_frame < 1 then
			if time_global() > timej then
				timej = time_global() + ftup
				local outfit = db.actor:get_current_outfit()
				if outfit then
					local snd_obj = xr_sound.get_safe_sound_object([[actor\landing]])
					if not snd_obj:playing() then 
						snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
					end
				end
			end
		end
	end
	if power > 0.6 then
		local snd_obj = xr_sound.get_safe_sound_object([[actor\bones_crack]])
		if not snd_obj:playing() then 
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
			--level.add_cam_effector2("camera_effects\\fusker.anm", 1523, false, "")
			--level.add_pp_effector("snd_shock.ppe", 20131, false)
			local outfit = db.actor:get_current_outfit()
			if outfit then
				if outfit:section() == "exo_outfit" then
					local snd_obj = xr_sound.get_safe_sound_object([[actor\exo_landing]])
					if not snd_obj:playing() then 
						snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
					end
				end
			end
		end
	end
	if power > 0.7 then
		db.actor.health = -1
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\heartbeat_fast]])
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end


function actor_binder:mouse_press()

end

function actor_binder:on_select_item(obj)
	olr_items_inv_click.klick_item_inv(obj)	
end


function actor_binder:obj_to_belt(obj)
	if obj then
		local section = obj:section()
		if (section == "detector_simple" or section == "detector_advances" or section == "detector_elite") and not has_alife_info("tutor_detector_charge") then
			db.actor:give_info_portion("tutor_detector_charge")
		end
	end
end

function actor_binder:obj_to_ruck(obj)
end

function actor_binder:obj_to_slot(obj)
	core.tc("on_item_slot", obj)
	olr.to_slot(obj)
end


function actor_binder:OnEatHudObj()
	olr_items_efs.use_hud_item()
end


function actor_binder:OnTrdBtnClick(id)
	olr_trade_manager.trading_start(id)
end


function actor_binder:OnKey(dik)
	if not alife() then
		return
	end

	bind_car.onKeyPress(dik)
    olr.on_key(dik)
	
	bind_kampfire.on_key_press(dik)
end

function actor_binder:on_hit(obj, amount, local_direction, who, bone_index) 
	olr.on_actor_hit(obj, amount, local_direction, who, bone_index) 
	--log1(""..obj:name().." - "..who:name().." - "..amount.."")
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_border_enter(npc, info_id)
	self.actor_detector:actor_enter()
	--if level.name() == "l12_barrow_downs" then
	--	xr_effects.kill_actor()
	--end
end 
----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_border_exit(npc, info_id)
	self.actor_detector:actor_exit()
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:info_callback(npc, info_id)
	--log1(string.format("*INFO*: npc='%s' id='%s'", npc:name(), info_id)) -- лог полученных инфопорций
	-- Сюжет
	level_tasks.proceed(self.object)

	if info_id == "ui_inventory" then
		olr_ui_inv_acinfo.on_inventory_show()
	elseif info_id == "ui_inventory_hide" then
		olr_ui_inv_acinfo.on_inventory_hide()
	end

	-- Отметки на карте
	level_tasks.process_info_portion(info_id)

	if info_id == "ui_talk_hide" then
		local new = xvars.quest_new_count or 0
		local complete = xvars.quest_complete_count or 0
		
		if new > 0 and complete > 0 then
			save_manager.create_quest_save("both")
		elseif complete > 0 then
			save_manager.create_quest_save("complete", complete)
		elseif new > 0 then
			save_manager.create_quest_save("new", new)
		end
	end
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_trade(item, sell_bye, money)
	--log1(" trade startt")
	if sell_bye == true then
		game_stats.money_trade_update(money)
	else
		--log1(" покупаем")
		game_stats.money_trade_update(-money)
	end
	if item:is_weapon_magazined() then
		--item:unload_magazine(false)
		-- Крайне сомнительный прикол продавать не заряженное оружие, убрал
	end
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:article_callback(npc, group, name)

	if device().precache_frame > 1 then return end
	
	if group == "Diary" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_pda_note", "flash", "tips", nil, 10000)
	elseif group == "Mutants" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_information_mutants", "flash", "tips", nil, 10000)
	elseif group == "Social" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_information_faction", "flash", "tips", nil, 10000)
	elseif group == "Artifacts" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_information_artifacts", "flash", "tips", nil, 10000)
	elseif group == "Anomalies" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_information_anomalies", "flash", "tips", nil, 10000)
	elseif group == "Locations" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_information_level", "flash", "tips", nil, 10000)
	elseif group == "memuars" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_notes", "flash", "tips", nil, 10000)
	elseif group == "zone_sevenparts" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_info_received", "flash", "tips", nil, 10000)
	elseif group == "zone_zakazy" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_order_received", "flash", "tips", nil, 10000)
	elseif group == "zone_prosby" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_stalkers_requests", "flash", "tips", nil, 10000)
	elseif group == "Recipes_olr" then
		news_manager.send_tip_new_dlg(name, "st_news_manager_new_recipe", "flash", "tips", nil, 10000)
	else
		news_manager.send_tip_new_dlg(name, "st_news_manager_info_received", "flash", "tips", nil, 10000)
	end

end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_item_take (obj)

	if device().precache_frame > 1 then return end -- per NatVac: don't check existing inventory during synchronizing

    level_tasks.proceed(self.object)

	core.tc("on_item_take", obj)

	olr_wep_sound.on_take(obj)

	olr_on_take.on_take(obj)

	olr_fix_ammo.on_take(obj)

	------ Weapouns Count
	if device().precache_frame <1 and obj:is_weapon() and alife() then
		xvars.ac_weapon_count = xvars.ac_weapon_count + 1
		--log1("sobral orujia "..xvars.ac_weapon_count.." now")
	end

	------ Обработчик выдачи поршня с конфига
	if obj then
		if device().precache_frame < 1 then
			if ini_sys:line_exist(obj:section(), "take_info") then
				local known_inf = ini_sys:r_string(obj:section(), "take_info") or ""
				if not has_alife_info(known_inf) then
					--log1("give info from item - " .. known_inf .. "")
					self.object:give_info_portion(known_inf)
				end
			end
		end
	end
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_item_drop (obj)

	if quitting_game then return end -- per NatVac: keep game from processing dropped items when quitting game

    level_tasks.proceed(self.object)

	olr_items_drop.drop_item(obj)

	core.tc("on_item_drop", obj)

	--event("actor_item_drop"):trigger({obj = obj})
	
	--if db.actor:has_info("ui_inventory") then
	--	db.actor:invalidate_inventory()	-- Странные костыли флаера
	--end

end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:use_obj(obj) 
	olr.on_use(obj)
	core.tc("on_item_use", obj)
	-- Для анабиотика (надо или нет сами решите, для примера повесил на энергос)
	--[[
	if obj:section() == "energy_drink" then
		xr_effects.disable_ui(db.actor, nil)
		level.add_cam_effector("camera_effects\\surge_02.anm", 10, false, "bind_stalker.anabiotic_callback")
		level.add_pp_effector("surge_fade.ppe", 11, false)
		db.actor:give_info_portion("anabiotic_in_process")
	end
	--]]
end

function anabiotic_callback()
	level.add_cam_effector("camera_effects\\surge_01.anm", 10, false, "bind_stalker.anabiotic_callback_end")
	local rnd = math.random(35, 45)
	local m = surge_manager.get_surge_manager()
	if (m.started) then
		local diff_sec = math.ceil(game.get_game_time():diffSec(m.inited_time) / level.get_time_factor())
		if (rnd > (m.surge_time - diff_sec) * level.get_time_factor() / 60) then
			m.time_forwarded = true
			m.ui_disabled = true
			m:kill_all_unhided()
			m:end_surge()
		end
	end
	level.change_game_time(0, 0, rnd)
	log1("anabiotic_callback: time forwarded on [%d]", rnd)
end

function anabiotic_callback_end()
	xr_effects.enable_ui(db.actor, nil)
	db.actor:disable_info_portion("anabiotic_in_process")
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_actor_shoot() 
	olr_on_shoot.actor_shoot()
end
----------------------------------------------------------------------------------------------------------------------

function actor_binder:task_callback(_task, _objective, _state)
	if _objective:get_idx() == 0 then
		if _state == task.fail then
			news_manager.send_task(db.actor, "fail", _task, _objective)
		elseif _state == task.completed then
			news_manager.send_task(db.actor, "complete", _task, _objective)
		else
			news_manager.send_task(db.actor, "new", _task, _objective)
		end
	else
		if _task:get_objective(0):get_state() == task.in_progress then
			news_manager.send_task(db.actor, "update", _task, _objective)
		end
	end
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:map_location_added_callback(spot_type_str, object_id)
	if (false==app_ready()) or (device().precache_frame>1) then return end
	--news_manager.send_task(db.actor, "new")
end
----------------------------------------------------------------------------------------------------------------------

-- Проверка по объёму выполняется в движке, если true то можно поднять, если false то подъема не будет
-- Если установили false нужно будет тут же сделать вывод почему, так как превышение объема считается далее и до него не дойдёт вообще
function actor_binder:on_item_can_take(obj)
	return true
end

-- Коллбэк вызывается только когда у нас превышение объема и нужно что-то сделать. Пока что будет только вывод сообщения о том что нет места в рюкзаке
function actor_binder:on_item_volume_exceeded(item, cur_volume, max_volume)
	--log1("Пытаемся поднять предмет - ["..tostring(item:section()).."] скока будет с предметом cur_volume - ["..tostring(cur_volume).."] нынешний макс объем max_volume - ["..tostring(max_volume).."]")
	local item_name = item:get_name()
	local text_all = game.translate_string("st_on_item_volume_exceeded").." "..item_name
	local hud = get_hud()
	local custom_static = hud:GetCustomStatic("custom_sms_text_actor")
	hud:AddCustomStatic("custom_sms_text_actor", true)
	hud:GetCustomStatic("custom_sms_text_actor"):wnd():SetTextST(tostring(text_all))
	hud:GetCustomStatic("custom_sms_text_actor").m_endTime = time_global()/1000 + 5	
end

function actor_binder:update(delta)
	local tostr = tostring
	if db.actor == nil then
		return
	end
	object_binder.update(self, delta)

	local time_ = time_global()
	
	game_stats.update (delta, self.object)

	if (self.surge_manager) then
		if (self.f_surge_manager_loaded ~= true) then
			self.surge_manager:initialize()
			self.f_surge_manager_loaded = true
		end
		self.surge_manager:update()
	end

	-- пораньше запустим проверки на сон
	-- ставить тут проверки на 0.01 не стоит, так как это значение является критическим после которого хп начнёт убывать!
	if olr_sleep.check_actor_sleep() then
		if db.actor.satiety < 0.025 then
			db.actor.satiety = 0.025
		end
		if db.actor.thirst < 0.025 then
			db.actor.thirst = 0.025
		end
	end
	
	-- апдейт погоды
	self.weather_manager:update()
	
	-- апдейт схемы детектора
	self.actor_detector:update()

	-- апдейт звуковой схемы актера
	xr_sound.update_actor()

	-- обновление схемы субтитров
	game_subtitles.update_subtitles()
		
	-- Обновление отключения ввода с клавиатуры.
	if self.st.disable_input_time ~= nil and
	   game.get_game_time():diffSec(self.st.disable_input_time) >= self.st.disable_input_idle 
	then
		level.enable_input()
		self.st.disable_input_time = nil
	end
	-- Обновление сна с переносом чувака в указанную позицию
	if self.st.sleep_relocate_time ~= nil and
	   game.get_game_time():diffSec(self.st.sleep_relocate_time) >= self.st.sleep_relocate_idle 
	then
		self.object:set_actor_position(self.st.sleep_relocate_point)
		local dir = self.st.sleep_relocate_point:sub(self.st.sleep_relocate_look)
		self.object:set_actor_direction(dir:getH())
		self.st.sleep_relocate_time = nil
	end

	-- Апдейт прятание оружия игрока во время диалога
	if weapon_hide == true or self.object:is_talking() and olr_pda.is_not_pda_dialog() then
		if self.weapon_hide == false then
			self.object:hide_weapon()
			self.weapon_hide = true
		end
	else
		if self.weapon_hide == true then
			self.object:restore_weapon()
			self.weapon_hide = false
		end
	end	

	-- обновление рестрикторов, которые под логикой, срабатывает через интервалы времени
	if self.next_restrictors_update_time < time_ then
		bind_restrictor.actor_update(delta)
		self.next_restrictors_update_time = time_ + 200
	end

	-- обновление постпроцессов
	if post_process ~= 0 then
		if post_process:update () == true then
		   post_process = 0
		end
	end

	-- обновление пси-антенны
	if sr_psy_antenna.psy_antenna then
		sr_psy_antenna.psy_antenna:update(delta)
	end

 	if self.bCheckStart then
		
		if not has_alife_info("start_olr_mod") and alife() then
			self.object:give_info_portion("start_olr_mod")
			_G.g_start_avi = true
			olr.start_game_vars()
		end

		if not has_alife_info("global_dialogs") then
			self.object:give_info_portion("global_dialogs")
		end

		if not has_alife_info("level_changer_icons") then
			self.object:give_info_portion("level_changer_icons")
		end
		
		if alife() then -- на всякий случай, я хуй знает чё там компиляторам надо не надо
			-- Один раз запускаем таймер проверки игровых новостей АМК
			-- Далее он будет сам себя запускать
			news_main.init_check_news_timer()
			
			-- Один раз запускаем таймер автосейвов
			-- Далее он будет сам себя запускать
			save_manager.check_autosave_timer()
			
			-- Проверка на мини-карту
			-- Если пда не сдох то включим принудительно на первом апдейте
			if not nick.is_pda_dead() then
				olr.show_minimap(true)
			else
				olr.show_minimap(false)
			end
		end
		
		level_tasks.add_lchanger_location()

		self.bCheckStart = false		
	end	


	amk.on_actor_upade()
	olr_debug.upd()
	core.tc("actor_update", delta)
	
	if dbg_time then
	
		local hud = get_hud()
		local StatCS = hud:GetCustomStatic("debug_time")
		local current_time = game.time()

		-- Получаем time_factor из конфига
		local alife_time_factor = ini_sys:r_float("alife", "time_factor")

		-- Расчет времени из game.time()
		local hours_from_game = math.floor(current_time / 3600000)
		local minutes_from_game = math.floor(current_time / 60000 - hours_from_game * 60)
		local seconds = math.floor((current_time % 60000) / 1000)	
		local formatted_game_time = string.format("%02d:%02d:%02d", hours_from_game, minutes_from_game, seconds)

		-- Получение времени из level
		local time_h = level.get_time_hours()
		local time_m = level.get_time_minutes()
		local formatted_level_time = string.format("%02d:%02d", time_h, time_m)

		-- Расчет delay (время с учетом time_factor)
		local delay = current_time * 1000 * alife_time_factor
		
		-- Получаем текущее время
		local current_time_real = os.time()
		-- Форматируем время в строку ЧЧ:ММ:СС
		local formatted_time_real = os.date("%H:%M:%S", current_time_real)
		
		-- Создание HUD элемента если он не существует
		if StatCS == nil then
			hud:AddCustomStatic("debug_time", true)
			StatCS = hud:GetCustomStatic("debug_time")
		end

		-- Формирование текста для отображения
		if StatCS ~= nil then
			local display_text = 
				--"Реальное время: " .. tostr(formatted_time_real) .. "\\n" ..
				--"Расчетное время из game.time(): " .. tostr(formatted_game_time) .. "\\n" ..
				--"Игровое время (level): " .. tostr(formatted_level_time) .. "\\n" ..
				"time_global(): " .. tostr(time_global()) .. "\\n" ..
				"game.time(): " .. tostr(game.time()) .. "\\n" ..
				"game.time64(): " .. tostr(game.time64()) .. "\\n" ..
				"get_game_seconds_srp(): " .. tostr(get_game_seconds_srp()) .. "\\n" ..
				"get_game_seconds(): " .. tostr(get_game_seconds()) .. "\\n" ..
				"get_game_minutes(): " .. tostr(get_game_minutes()) .. "\\n"
			
			StatCS:wnd():SetTextST(display_text)
		end	
	
	end
end

------------------------------------------------------------------
function actor_binder:save(packet)
	set_save_marker(packet, "save", false, "actor_binder")
	if packet:w_tell() == 0 then
		news_manager.send_tip(db.actor, game.translate_string("actor_bindersave_0"), nil, "freedom", 9000)
	end

	xvars.saves_count = xvars.saves_count + 1

	--printf("actor_binder:save(): self.object:name()='%s'", self.object:name())
	object_binder.save(self, packet)

	core.tc("actor_save",packet)

	--local pos_before

	-- Game difficulty
	--pos_before = packet:w_tell()
	packet:w_u8(level.get_game_difficulty())
	--log1(string.format("[SAVE actor_binder] game_difficulty: %d byte(s)", packet:w_tell() - pos_before))

	-- disable_input_time
	--pos_before = packet:w_tell()
	if self.st.disable_input_time == nil then
		packet:w_bool(false)
	else
		packet:w_bool(true)
		utils.w_CTime(packet, self.st.disable_input_time)
	end
	--log1(string.format("[SAVE actor_binder] disable_input_time: %d byte(s)", packet:w_tell() - pos_before))

	-- pstor
	--pos_before = packet:w_tell()
	xr_logic.pstor_save_all(self.object, packet)
	--log1(string.format("[SAVE actor_binder] pstor: %d byte(s)", packet:w_tell() - pos_before))

	-- weather
	--pos_before = packet:w_tell()
	self.weather_manager:save(packet)
	--log1(string.format("[SAVE actor_binder] weather: %d byte(s)", packet:w_tell() - pos_before))
	
	-- surge manager
	--pos_before = packet:w_tell()
	self.surge_manager:save(packet)
	--log1(string.format("[SAVE actor_binder] surge manager: %d byte(s)", packet:w_tell() - pos_before))
	

	-- psy_antenna
	--pos_before = packet:w_tell()
	sr_psy_antenna.save( packet )
	--log1(string.format("[SAVE actor_binder] psy_antenna: %d byte(s)", packet:w_tell() - pos_before))

	-- actor_detector
	--pos_before = packet:w_tell()
	self.actor_detector:save(packet)
	--log1(string.format("[SAVE actor_binder] detector: %d byte(s)", packet:w_tell() - pos_before))

	set_save_marker(packet, "save", true, "actor_binder")

	--log1(string.format("[SAVE actor_binder] TOTAL: %d bytes", packet:w_tell()))
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:load(reader)
	set_save_marker(reader, "load", false, "actor_binder")
	--printf("actor_binder:load(): self.object:name()='%s'", self.object:name())
	object_binder.load(self, reader)
	--printf("actor_binder:object_binder.load(): self.object:name()='%s'", self.object:name())

	--safe_r(reader, "r_u8", 1, "actor_binder.game_difficulty")
	local game_difficulty = reader:r_u8()
	--log1(string.format("[LOAD actor_binder] game_difficulty=%s", tostring(game_difficulty)))
	get_console():execute("g_game_difficulty "..game_difficulty_by_num[game_difficulty] or 0)

	--safe_r(reader, "r_u8", 1, "actor_binder.disable_input_time_flag")
	local stored_input_time = reader:r_u8()
	if stored_input_time == true then
		utils.r_CTime(reader)
	end

	--safe_r(reader, "r_u32", 4, "actor_binder.pstor_count")
	xr_logic.pstor_load_all(self.object, reader)

	--safe_r(reader, "r_stringZ", 1, "actor_binder.weather")
	self.weather_manager:load(reader)
	
	--safe_r(reader, "r_stringZ", 1, "actor_binder.surge_manager")
	self.surge_manager:load(reader)
	self.f_surge_manager_loaded = true

	--safe_r(reader, "r_bool", 1, "actor_binder.psy_antenna_flag")
	sr_psy_antenna.load(reader)
	

	--safe_r(reader, "r_u8", 1, "actor_binder.detector")
	self.actor_detector:load(reader)

	set_save_marker(reader, "load", true, "actor_binder")
end
----------------------------------------------------------------------------------------------------------------------

--старт префетча звуков
--if string.find(command_line(), "-noprefetch") == nil then
--	sound_prefetch.prefetch_sounds()
--end


-- Weapon functions
function hide_weapon()
	weapon_hide = true
end
function restore_weapon()
	weapon_hide = false
end

-- this is test for section iteration
--[[
local function test_section_iteration(file_name, section_name)
	printf			("file    : %s",file_name)
	printf			("section : %s",section_name)
	
	local			file = ini_file(file_name)
	local			n = file:line_count(section_name)
	printf			("lines   : %d",n)
	
	local			id, value = "", "", result
	for i=0,n-1 do
		result, id, value	= file:r_line(section_name,i,"","")
		printf		("line %d : %s = %s",i,id,value)
	end
end

test_section_iteration("system.ltx","space_restrictor")
--]]
