-- hi_flyer 11/03/17

function init(obj)
	local new_binder = crow_binder(obj)
	obj:bind_object(new_binder)
end

class "crow_binder" (object_binder)

function crow_binder:__init(obj) super(obj)
end 

function crow_binder:reinit()
	object_binder.reinit(self)
	self.object:set_callback(callback.hit,	self.hit_callback, self)
	self.object:set_callback( callback.use_object, self.use_callback, self )
end

function crow_binder:net_destroy()
	object_binder.net_destroy(self)
	self.object:set_callback(callback.hit,	nil)
	self.object:set_callback( callback.use_object, nil )
end

function crow_binder:net_save_relevant()
	return true
end

function crow_binder:hit_callback(obj, amount, local_direction, who, bone_index)
	--news_manager.send_tip(db.actor, game.translate_string("crow_binderhit_callback_0"), nil, "default", 9000)
end

--[[

st_butcher_badluck_1
st_butcher_badluck_2
st_butcher_badluck_3
st_butcher_badluck_4

game.translate_string("st_butcher_badluck_"..tostring(math.random(1,4)))

st_butcher_success_1
st_butcher_success_2
st_butcher_success_3
st_butcher_success_4

game.translate_string("st_butcher_success_"..tostring(math.random(1,4)))

st_butcher_damaged_1
st_butcher_damaged_2
st_butcher_damaged_3
st_butcher_damaged_4

game.translate_string("st_butcher_damaged_"..tostring(math.random(1,4)))

st_butcher_unknown_1
st_butcher_unknown_2
st_butcher_unknown_3
st_butcher_unknown_4

game.translate_string("st_butcher_unknown_"..tostring(math.random(1,4)))

--]]

function crow_binder:use_callback(obj,who)
	if not self.object:alive()  then
		self.sound_knife = sound_object("material\\collide\\knife\\knife_"..tostring(math.random(1, 2)))
		if math.random(1, 3) == 1 then
			olr.hud_tip("", game.translate_string("st_butcher_damaged_"..tostring(math.random(1,4))), 2, true)
			self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)	
			
			local h = hit()
			h.power = 0
			h.direction = db.actor:position():sub(obj:position())
			h.direction:normalize()
			h.direction.y = h.direction.y + 0.3 + math.random() * 0.2  -- 0.3-0.5 вверх
			h.direction:normalize()
			h.draftsman = db.actor
			h.impulse = 100 + math.random(0, 200)
			h.type = hit.wound
			obj:hit(h)			
			
			olr.delete_object(self.object) -- Удаляем тушку крысы
		else
			olr.hud_tip("", game.translate_string("st_butcher_success_"..tostring(math.random(1,4))), 2, true) -- активируем снятие
			local item = alife():create("crow_food", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			if item then
				level.client_spawn_manager():add(item.id, 0,
					function(id, obj)
						if obj and g_food_table[obj:section()] then
							obj:set_condition(math.random(35, 98) / 100) -- Состояние от 35 до 98%
							xvars.foods[tostring(obj:id())] = {sec = obj:section(), rad = math.random() < 0.5} -- заносим в таблицу xvars.foods, шансы пока 50 на 50 как и везде
						end
					end
				)
			end
			
			local h = hit()
			h.power = 0
			h.direction = db.actor:position():sub(obj:position())
			h.direction:normalize()
			h.direction.y = h.direction.y + 0.3 + math.random() * 0.2  -- 0.3-0.5 вверх
			h.direction:normalize()
			h.draftsman = db.actor
			h.impulse = 100 + math.random(0, 200)
			h.type = hit.wound
			obj:hit(h)			
			
			self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)			
			news_manager.relocate_item(db.actor, "in", "crow_food") -- мессага
			olr.delete_object(self.object) -- Удаляем тушку крысы
		end
	end	
end