-- биндер еды и частей мутантов
-- hi_flyer 10/03/15

local time_apdeyta = 0
local timerup = 1000

function Init(obj)
	local oNewBinder = CItemBinder(obj)
	obj:bind_object(oNewBinder)
end

class "CItemBinder"(object_binder)
function CItemBinder:__init(obj)
	super(obj)
	self.raded = false
	self.drop_del = false
end

function CItemBinder:reload(section)
	object_binder.reload(self, section)
end

function CItemBinder:reinit()
	object_binder.reinit(self)
end

function CItemBinder:net_save_relevant()
	return true
end

function CItemBinder:save(packet)
	object_binder.save(self, packet)
end

function CItemBinder:load(reader)
	object_binder.load(self, reader)
end

function CItemBinder:net_spawn(data)
	if not object_binder.net_spawn(self, data) then
		return false
	end
	return true
end

function CItemBinder:net_destroy()
	object_binder.net_destroy(self)
end

local trader_sections = { -- секции торговцев для исключения заражения, хорошего состояния и медленной порчи
	m_trader = true,
	m_barman = true,
	stalker_sakharov = true
}

local food_sections = { -- все секции еды
    kolbasa = true,
    bread = true,
    conserva = true,
	rat_food = true,
	rat_food_coocked = true,
	crow_food = true,
	crow_food_coocked = true,
	mutant_flesh_eye = true,
	mutant_flesh_eye_coocked = true,
	mutant_boar_leg = true,
	mutant_boar_leg_coocked = true,
	mutant_dog_tail = true,
	mutant_dog_tail_coocked = true,
	mutant_psevdodog_tail = true,
	mutant_psevdodog_tail_coocked = true,
	mutant_krovosos_jaw = true,
	mutant_krovosos_jaw_coocked = true,
	mutant_burer_hand = true,
	mutant_burer_hand_coocked = true,
	mutant_zombie_hand = true,
	mutant_zombie_hand_coocked = true
    -- остальные секции еды
}

local food_sections_neportit = { -- еда которая не должна портится (по крайней мере очень быстро)
								 -- не используется на данный момент
	conserva = true
}

local food_sections_coocked = { -- приготовленная еда портится медленее
	rat_food_coocked = true,
	crow_food_coocked = true,
	mutant_flesh_eye_coocked = true,
	mutant_boar_leg_coocked = true,
	mutant_dog_tail_coocked = true,
	mutant_psevdodog_tail_coocked = true,
	mutant_krovosos_jaw_coocked = true,
	mutant_burer_hand_coocked = true,
	mutant_zombie_hand_coocked = true
}

function CItemBinder:update(delta)
	object_binder.update(self, delta)
	
	-- порядок заражения итемов радиацией
	-- проверяем что xvars и xvars.foods есть и что имя айтема у нас пуст, т.е nil
	-- проверяем какой класс родителя у нас, если не clsid.script_trader то заражаем, иначе ставим флаг не заражённого (т.е у торгоша будет не заражена еда)
	if xvars and xvars.foods and xvars.foods[self.object:name()] == nil then -- проверяем xvars и то что айтема по id там нет, т.е nil
		if self.object:parent() ~= nil and trader_sections[self.object:parent():section()] then
			--log1("! Еда у торговца: name = "..self.object:name().." id = "..self.object:id().."")
			xvars.foods[self.object:name()] = false -- прописываем еде торгоша что еда не заражена
		else
			--log1("! Еда не у торговца: name = "..self.object:name().." id = "..self.object:id().."")
			set_radfood_flag(self.object) -- заражаем или нет
		end
	end
	
	-- состояние еды у торговцев будет всегда от 90 до 99%
	local cond = self.object:condition()
	if cond == 1 and food_sections[self.object:section()] then
		if self.object:parent() ~= nil and trader_sections[self.object:parent():section()] then
			--log1("! Меняем состояние еды у торговца: name = "..self.object:name().." id = "..self.object:id().."")
			self.object:set_condition((math.random(90, 99) / 100)) -- у торговцев еда всегда почти идеальна
		else
			--log1("! Меняем состояние еды не у торговца: name = "..self.object:name().." id = "..self.object:id().."")
			self.object:set_condition((math.random(45, 95) / 100)) -- у не торгашей как повезёт
		end
	end

	-- тут на апдейте портим еду раз в секунду
	if time_global() > time_apdeyta then
		time_apdeyta = time_global() + timerup
		if ini_sys:line_exist(self.object:section(), "cor_time") and cond > 0.01 then
			if not (self.object:parent() ~= nil and trader_sections[self.object:parent():section()]) then
				self.object:set_condition(cond - (self:TimeCondLost()*0.25)) -- у торговецв еда портится в 4 раза дольше
				--log1("! Меняем состояние еды в апдейте у торговца - ["..self.object:name().."]  -- ["..self.object:condition().."] ")
			else
				if food_sections_coocked[self.object:section()] then
					self.object:set_condition(cond - (self:TimeCondLost()*0.5)) -- приготовленная будет в два раза медленее чем сырая
					--log1("! Меняем состояние приготовленной еды в апдейте не у торговца - ["..self.object:name().."]  -- ["..self.object:condition().."] ")
				else
					self.object:set_condition(cond - self:TimeCondLost())
					--log1("! Меняем состояние еды в апдейте не у торговца - ["..self.object:name().."]  -- ["..self.object:condition().."] ")				
				end
			end
		end
	end
end

function CItemBinder:TimeCondLost()
	local skis = ini_sys:r_float(self.object:section(), "cor_time")
	if skis < 0 then
		return 0
	end
	return 100 / skis / 24 / 100 / 60 * 100
end

function set_radfood_flag(obj)
	-- надо бы для таких штук ввести некие множители, а не 50 на 50
	if math.random(1, 2) == 1 then
		xvars.foods[obj:name()] = true
	else
		xvars.foods[obj:name()] = false
	end
end