
local controller_timer2 = 0
local insect_particle = particles_object("anomaly2\\group_items\\pux_attack_00")
local mozg_particle = particles_object("monsters\\pseudo_phantom_death_00")
local mozg_light = alife():object("mozg_for_light_object")
local mozg_light_flag = false
local actor_close_mozg = false

local parasits = {
	["zombie_plague"] = true,
	["zombie_plague_strong"] = true
}

-- Таблицу с крысами будем держать тут, нех её инитить постоянно
local is_rat_variant = {
	["m_rat_e"] = true,
	["m_rat_e2"] = true,
	["m_rat_e3"] = true,
	["m_rat_e4"] = true,
	["m_rat_new"] = true
}

function bind(obj)
	printf("_bp: monster.bind: name='%s', id='%d'", obj:name(), obj:id())

	local new_binder = generic_object_binder(obj)
	obj:bind_object(new_binder)
end

------------------------------------------------------------------------------------
class "generic_object_binder" (object_binder)

function generic_object_binder:__init(obj) super(obj)
	self.loaded = false
	self.load_flag_ph = false
end 

function generic_object_binder:reload(section)
	object_binder.reload(self, section)
end

function generic_object_binder:reinit()
	object_binder.reinit(self)

	-- У торговца нет поддержки перемещения
	if self.object:clsid() ~= clsid.script_trader then
		self.object:set_patrol_extrapolate_callback(generic_object_binder.extrapolate_callback, self)
	end

	db.storage[self.object:id()] = { }

	self.st = db.storage[self.object:id()]
	if (self.object:alive()) then
		self.object:set_callback(callback.patrol_path_in_point, self.waypoint_callback, self)
		self.object:set_callback(callback.hit,					self.hit_callback,		self)
		self.object:set_callback(callback.death,				self.death_callback,	self)
	end
	
	--self.object:set_callback( callback.use_object, self.use_callback, self )
end


function generic_object_binder:net_destroy()
	self.object:set_callback(callback.death,				nil)
	self.object:set_callback(callback.patrol_path_in_point, nil)
	self.object:set_callback(callback.hit,					nil)
	self.object:set_callback( callback.use_object, nil )

	local st = db.storage[self.object:id()]
	if st and st.active_scheme then
		xr_logic.issue_event(self.object, st[st.active_scheme], "net_destroy")
	end
	
	db.del_obj(self.object)
	db.storage[self.object:id()] = nil

	object_binder.net_destroy(self)
end


---------------------------------------------------------------------------------------------------------------------

function generic_object_binder:update(delta)
	local mrandom = math.random
	object_binder.update(self, delta)

	local cls = self.object:clsid()
	local spos = self.object:position()
	local sec = self.object:section()
	local act = db.actor
	local dist_to_actor = act:position():distance_to(spos)

--	local npc_test_name = self.object:name()
--	local npc_test_section = self.object:section()
--	local npc_test_id = self.object:id()

	--log1("check bind_monster: clsid = "..tostring(cls)..", npc name = "..tostring(npc_test_name)..", section = "..tostring(npc_test_section)..", id = "..tostring(npc_test_id).."") -- для теста

	-- фикс физики
	if self.load_flag_ph == false then
		self.load_flag_ph = true
		core.tc("monster_first_update", self)
		if not self.object:alive() then
			if xvars and xvars.dead_in_offline[self.object:name()] == true then
				local shelbone = self.object:get_physics_shell():get_element_by_bone_id(0)
				if shelbone then
					shelbone:apply_force(0, 0.1, 0)
				end
			end
		end
	end
	
	-- Обработка трупа для срезки частей
	-- Если труп то дальнейший апдейт гасим, ибо смысла нет (возможно только паразиты, но это формально еще "живой" зомбу делает а не мёртвый
	-- Если что это можно будет и овердрайвить потом
	if not self.object:alive() then
		local looted = xr_logic.pstor_retrieve(self.object, "looted", nil)
		if not looted then
			self.object:set_callback(callback.use_object, self.use_callback, self)
			self.object:set_tip_text("st_butcher_field_dress")
		else
			self.object:set_callback(callback.use_object, nil)
			self.object:set_tip_text("")
		end
		return
	end
	
	-- Заготовка на потом
	--[[
	if not (self.object:alive()) then
		local looted = utils.se_obj_load_var(self.object:id(),self.object:name(),"looted") == "true"
		if (not looted) and (knife_manager.is_equipped()) then
			if (knife_manager.get_condition() < 0.15) then
				self.object:set_callback(callback.use_object, nil)
				self.object:set_tip_text(game.translate_string("st_body_knife_bad"))
			elseif (not knife_manager.can_loot(self.object:section())) then
				self.object:set_callback(callback.use_object, nil)
				self.object:set_tip_text(game.translate_string("st_body_knife_weak"))
			else
				self.object:set_callback(callback.use_object, self.use_callback, self)
				self.object:set_tip_text(game.translate_string("st_body_loot"))
			end
		else
			self.object:set_callback(callback.use_object, nil)
			
			if (not looted) and (not (knife_manager.is_equipped())) then
				self.object:set_callback(callback.use_object, nil)
				self.object:set_tip_text(game.translate_string("st_body_knife_needed"))
			else
				self.object:set_callback(callback.use_object, nil)
				self.object:set_tip_text("")
			end
		end
		return
	end	
	--]]
	
	if self.object:alive() then

		core.tc("monster_update", self, delta)

		if self.object:is_talk_enabled() then
			self.object:set_tip_text("character_use")
		else
			self.object:set_tip_text("")
		end

		--	not olr_protected.is_no_offline_alife_obj(self.object:name()) and
		local m = surge_manager.get_surge_manager()
		if (m.started) then
			local diff_sec = math.ceil(game.get_game_time():diffSec(m.inited_time) / level.get_time_factor())
			if not olr_blowout.no_blow_levels[level.name()] then
				if diff_sec >= 35 and (not self.control_override) then
					if not self.object:action() then
						-- Захватываем зверушку
						xr_logic.mob_capture(self.object, true)
						self.control_override = true
					end
				elseif self.control_override and diff_sec >= 35 then
					if not self.object:action() then
						self.object:set_custom_panic_threshold(1)
						local snds = {sound.take_damage, sound.panic, sound.idle}
						local snd = snds[mrandom(1, table.getn(snds))]
						action(self.object, anim(anim.lie_idle, 0), sound(snd), cond(cond.sound_end))
					end
				elseif self.control_override and diff_sec < 35 then
					-- отпускаем зверушку
					self.control_override = nil
					xr_logic.mob_release(self.object)
					self.object:set_default_panic_threshold()
				elseif self.st.active_section ~= nil then
					xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "update", delta)
				end
			end
		end

		---------------------------------------------------------__hi_flyer__start__-------------------------------------------------------------

		-- жаба
		if cls == clsid.script_trader then
			trade_manager.update(self.object)
			if has_alife_info("olr_traders_night") then
				self.object:disable_trade()
			else
				self.object:enable_trade()
			end
		end

		-- чтоб жаба не выебывался, мутант куёв
		if cls ~= clsid.script_trader then
			-- паника от костров или когда ГГ в авто, чтобы не кусались
			if bind_kampfire.check_actor_near_kampfire() == true or bind_car.act_in_car_now() == true then
				local npc = self.object:get_enemy()
				if npc and npc:id() == act:id() then
					if self.object:see(npc) then
						self.object:set_custom_panic_threshold(1)
					else
						self.object:set_default_panic_threshold()
					end
				end
			end

			-- паника от мёртвой головы
			if cls ~= clsid.controller_s then
				local has_art = act:object("af_deadhead")
				if has_art and act:is_on_belt(has_art) then
					local art_cond = has_art:condition()
					local npc = self.object:get_enemy()
					if npc and npc:id() == act:id() then
						if self.object:see(npc) then
							has_art:set_condition(art_cond - 0.0005)
							if art_cond <= 0.05 then
								if has_art then
									act:drop_item(has_art)
									olr.del(has_art)
									self.object:set_default_panic_threshold()
								end
								self.object:set_default_panic_threshold()
							end
							self.object:set_custom_panic_threshold(1)
							local bol_var = mrandom(1, 3000)
							if bol_var == 1 then
								alife():create("m_controller_e", act:position():add(act:direction():add(140)), act:level_vertex_id(), act:game_vertex_id())
							end
						else
							self.object:set_default_panic_threshold()
						end
					end
				end
			end

			-- фантазмы
			if sec == "observer" or sec == "phantasm" then
				if dist_to_actor < 25 then
					act.psy_health = -0.001
				end
				if self.object:see(act) then
					if dist_to_actor < 15 then
						act.psy_health = -0.09
						level.add_pp_effector("dead_zone.ppe", 10101, true)
						level.set_pp_effector_factor(220001, dist_to_actor / 5)
					else
						level.remove_pp_effector(10101)
					end
				end
			end

			-- пси от полтера
			if cls == clsid.poltergeist_s and self.object:see(act) then
				if dist_to_actor < 8 then
					act.psy_health = -0.005
				end
				if dist_to_actor < 3 then
					local aitem = db.actor:active_item()
					if aitem and mrandom() < 0.5 and (db.actor:active_slot() == 1 or db.actor:active_slot() == 2) then
						local wobj = level.object_by_id(aitem:id())
						db.actor:drop_item(aitem)
						local wait_time = 0
						wait_time = time_global() + 400
						level.add_call(
							function()
								return time_global() > wait_time
							end,
							function()
								olr.polter_throw_wpn(wobj)
							end
						)
					end
				end
			end

			-- кровосос
			if cls == clsid.bloodsucker or cls == clsid.bloodsucker_s then
				local target = self.object:get_enemy()
				if target and self.object:see(target) then
					local dist = self.object:position():distance_to(target:position())
					if dist <= 4 then
						if not self.get_hit then
							self.object:set_invisible(true)
							self.get_hit = time_global() + mrandom(3000, 6500)
						elseif self.get_hit <= time_global() then
							self.object:set_invisible(false)
						end
					end
				end
			end

			-- Атака спор паразита
			if parasits[sec] and self.object:see(act) then
				if dist_to_actor < 12 then
					level.add_pp_effector("dead_zone.ppe", 1001, true)
					level.set_pp_effector_factor(1001, 12 - dist_to_actor * 10)
					local actorpos = db.actor:position()
					db.actor.health = -0.00255
					local par_varb = mrandom(1, 22)
					if par_varb == 1 then
						--zarazjenie_parazitom() -- пока уберём обработку заражения паразитом вообще
					end
					local par_var = mrandom(1, 35)
					if par_var == 1 then
						olr.partice_on_obj(self.object:name(), [[anomaly2\group_items\pux_attack_00]])
						olr.cough()
						local zh = hit()
						zh.draftsman = db.actor
						zh.type = hit.wound
						zh.direction = self.object:position():sub(actorpos)
						zh:bone("bip01_pelvis")
						zh.power = 0.0025
						zh.impulse = 0.000001
						db.actor:hit(zh)
					end
					if not insect_particle:playing() then
						insect_particle:play_at_pos(vector():set(actorpos.x, actorpos.y + 1.8, actorpos.z))
					end
				end
			else
				level.remove_pp_effector(1001)
			end

			-- конторолёр берущий под контроль ГГ
			if cls == clsid.controller_s and controller_timer2 < time_global() then
				if dist_to_actor < 75 then
					if self.object:section() == "m_pseudohuman_e" then
						return
					end
					if level.name() == "lvl13_prip" then
						if actor_close_mozg == true then
							self.object:set_fov(5)
							if db.actor and db.actor:see(self.object) then
								self.object.health = -0.1
							end
						else
							self.object:set_fov(xvars.cur_fov)
						end
					end
					-- защита от контра и фантомов
					local psystab = db.actor:object("psystab_helmet")
					if psystab ~= nil then
						local pscond = psystab:condition()
						if pscond < 0.1 then
							if psystab then
								alife():release(psystab, true)
							end
						end
						return
					end
					-- под защитой мозга колбы
					if actor_close_mozg == true then
						return
					end
					-- харакири
					local bol_var = mrandom(1, 6)
					if bol_var == 1 then
						get_actor_obj():block_action(32)
					end
					if bol_var == 2 then
						get_actor_obj():block_action(36)
					end
					if bol_var == 3 then
						get_actor_obj():block_action(4)
					end
					if bol_var == 4 then
						olr.rnd_camera_direction()
					end
					if bol_var == 5 then
						if bind_car.act_in_car_now() then
							return
						end
						local active_item = db.actor:active_item()
						if active_item and db.actor:active_slot() == 2 then
							olr.emu_shoot()
						end
					end
					if bol_var == 6 then
						level.add_pp_effector("proba_gray.ppe", 3937, false)
						get_actor_obj():hold_action(9)
					end
				end
				controller_timer2 = time_global() + mrandom(1000, 9550)
				get_actor_obj():unblock_action(4)
				get_actor_obj():unblock_action(36)
				get_actor_obj():unblock_action(32)
				get_actor_obj():release_action(9)
			end
		end

		---------------------------------------------------------__hi_flyer__end__-------------------------------------------------------------

		-- Удар контролёра руками (Автор: demover123)
		if cls == clsid.controller_s then
			local target = self.object:get_enemy()
			if target and self.object:see(target) and IsStalker(target) then
				local dist = self.object:position():distance_to(target:position())
				if dist <= 1.7 then
					if not self.get_hit then
						self.get_hit = time_global() + 200
						self.start_anim_hit_cont = true
					elseif self.get_hit <= time_global() then
						if self.start_anim_hit_cont then
--							if self.object:animation_count() > 0 then
--								self.object:clear_animations()
--							end
							self.object:play_cycle("stand_attack_1", true)

							local song_start = xr_sound.get_safe_sound_object("monsters\\controller\\take_damage_0")
							song_start:play_at_pos(self.object, self.object:position(), sound_object.s3d)
							self.start_anim_hit_cont = false
						end
						if not self.hit_to_enemy then
							self.hit_to_enemy = time_global() + 500
						elseif self.hit_to_enemy <= time_global() then
							level.add_cam_effector("camera_effects\\hit_front.anm", 8, false, "")

							local h = hit()
							h.draftsman = self.object
							h.direction = vector():set(0, 0, 0)
							h:bone("bip01_spine")
							h.power = 0.40
							h.impulse = 10
							h.type = hit.wound
							target:hit(h)

							self.hit_to_enemy = nil
							self.get_hit = nil
						end
					end
				else
					self.hit_to_enemy = nil
					self.get_hit = nil
				end
			end
		--if self.object:animation_count() < 1 then
			--local i = math.random(0,5)
			--self.object:add_animation("stand_walk_fwd_"..i, true)
		--end
		end
	end

	if self.st.active_section ~= nil then
		xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "update", delta)
	end
end

--[[

st_butcher_badluck_1
st_butcher_badluck_2
st_butcher_badluck_3
st_butcher_badluck_4

game.translate_string("st_butcher_badluck_"..tostring(math.random(1,4)))

st_butcher_success_1
st_butcher_success_2
st_butcher_success_3
st_butcher_success_4

game.translate_string("st_butcher_success_"..tostring(math.random(1,4)))

st_butcher_damaged_1
st_butcher_damaged_2
st_butcher_damaged_3
st_butcher_damaged_4

game.translate_string("st_butcher_damaged_"..tostring(math.random(1,4)))

st_butcher_unknown_1
st_butcher_unknown_2
st_butcher_unknown_3
st_butcher_unknown_4

game.translate_string("st_butcher_unknown_"..tostring(math.random(1,4)))

--]]

function generic_object_binder:use_callback(obj, who)

	if not (self.object) then
		return
	end
	
	-- проверяем в псторе тушки наличие looted, если вернёт тру то значит она обыскана, можно уходить
	local looted = xr_logic.pstor_retrieve(obj, "looted", nil)
	if looted then return end
	
	local self_object_sec = obj:section()
	
	self.sound_knife = sound_object("material\\collide\\knife\\knife_0"..tostring(math.random(1, 2)))
	
	if is_rat_variant[self_object_sec] then
		if math.random(1, 3) == 1 then
			olr.hud_tip("", game.translate_string("st_butcher_badluck_"..tostring(math.random(1,4))), 2, true) -- мессага
			self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)

			local h = hit()
			h.power = 0
			h.direction = db.actor:position():sub(obj:position())
			h.direction:normalize()
			h.direction.y = h.direction.y + 0.3 + math.random() * 0.2  -- 0.3-0.5 вверх
			h.direction:normalize()
			h.draftsman = db.actor
			h.impulse = 100 + math.random(0, 200)
			h.type = hit.wound
			obj:hit(h)
			
			olr.delete_object(obj) -- Удаляем тушку крысы
		else
			olr.hud_tip("", game.translate_string("st_butcher_success_"..tostring(math.random(1,4))), 2, true) -- мессага
			local item = alife():create("rat_food", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			if item then
				level.client_spawn_manager():add(item.id, 0,
					function(id, obj)
						if obj and g_food_table[obj:section()] then
							obj:set_condition(math.random(35, 98) / 100) -- Состояние от 35 до 98%
							xvars.foods[tostring(obj:id())] = {sec = obj:section(), rad = math.random() < 0.5} -- заносим в таблицу xvars.foods, шансы пока 50 на 50 как и везде
						end
					end
				)
			end
			
			local h = hit()
			h.power = 0
			h.direction = db.actor:position():sub(obj:position())
			h.direction:normalize()
			h.direction.y = h.direction.y + 0.3 + math.random() * 0.2  -- 0.3-0.5 вверх
			h.direction:normalize()
			h.draftsman = db.actor
			h.impulse = 100 + math.random(0, 200)
			h.type = hit.wound
			obj:hit(h)
			
			self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)		
			news_manager.relocate_item(db.actor, "in", "rat_food") -- мессага
			olr.delete_object(obj) -- Удаляем тушку крысы
		end

		return -- можно уходить, по крысе отработали
	end
	
	if ini_sys:line_exist(self_object_sec, "mutant_parts_section") then
		if ini_sys:line_exist(self_object_sec, "known_info") then
			local known_inf = ini_sys:r_string(self_object_sec, "known_info") or ""
			local meat_sectiion = ini_sys:r_string(self_object_sec, "mutant_parts_section") or ""
			if has_alife_info(known_inf) then
				-- Можем попытаться отрезать
				-- Биномиальное распределение
				local count = 0
				local max_count = ini_sys:r_u32(self_object_sec, "mutant_parts_max") or 1
				local p = ini_sys:r_float(self_object_sec, "mutant_parts_prob") or 0.6 -- пик будет 2-3 при макс 4 при p = 0.6
				for i = 1, max_count do
					if math.random() < p then
						count = count + 1
					end
				end
				if count ~= 0 then
					if math.random(1, 25) == 1 then
						self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)		
						olr.hud_tip("", game.translate_string("st_butcher_badluck_"..tostring(math.random(1,4))), 2, true) -- подлянка
					else
						for i = 1, count do
							local item = alife():create(meat_sectiion, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
							if item then
								level.client_spawn_manager():add(item.id, 0,
									function(id, obj)
										if obj and g_food_table[obj:section()] then
											obj:set_condition(math.random(35, 98) / 100) -- Состояние от 35 до 98%
											xvars.foods[tostring(obj:id())] = {sec = obj:section(), rad = math.random() < 0.5} -- заносим в таблицу xvars, шансы пока 50 на 50 как и везде
										end
									end
								)
							end
						end
						self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)						
						news_manager.relocate_item(db.actor, "in", meat_sectiion, count) -- скока получили
						olr.hud_tip("", game.translate_string("st_butcher_success_"..tostring(math.random(1,4))), 2, true) -- мессага
					end
				else
					self.sound_knife:play_at_pos(self.object, self.object:position(), sound_object.s3d)
					olr.hud_tip("", game.translate_string("st_butcher_damaged_"..tostring(math.random(1,4))), 2, true) -- не повезло
				end
				
				local h = hit()
				h.power = 0
				h.direction = db.actor:position():sub(obj:position())
				h.direction:normalize()
				h.direction.y = h.direction.y + 0.3 + math.random() * 0.2  -- 0.3-0.5 вверх
				h.direction:normalize()
				h.draftsman = db.actor
				h.impulse = 400 + math.random(0, 200)
				h.type = hit.wound
				obj:hit(h)
				
				xr_logic.pstor_store(obj, "looted", true) -- пишем в пстор тушки что её облутали
			else
				-- Мы не знаем что отрезать, в пстор не пишем, если что бы вдруг потом облутать
				olr.hud_tip("", game.translate_string("st_butcher_unknown_"..tostring(math.random(1,4))), 2, true) -- нет инфы
			end
		end
	end
	
	return
end

function generic_object_binder:extrapolate_callback()
	if self.object == nil then
		return false
	end

	if self.object:get_script() == false then 
		return false
	end 
	
	local cur_pt = self.object:get_current_point_index() 
	local patr = self.object:patrol()
	if patr == "" then
		--Такая ситуация - это норма, просто ванильный движок не вылетал при вызове patrol(""), а новый вылетает, проверено.
		--abort("!!["..script_name().."] Invalid patrol path name ["..patr.."] for object ["..self.object:name().."]")
		log1("!!["..script_name().."] Invalid patrol path name ["..patr.."] for object ["..self.object:name().."]")
		return false
	elseif patrol(patr):flags(cur_pt):get() == 0 then
		return true
	end
	
	return false
end



function generic_object_binder:waypoint_callback(obj, action_type, index)
	if self.st.active_section ~= nil then
		xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "waypoint_callback", obj, action_type, index)
	end
end


function generic_object_binder:death_callback(victim, who)

	if (who) then
		if (who:id() == db.actor:id()) then
			xr_statistic.addKillCount(who, self.object)
			if victim:clsid() == clsid.zombie or victim:clsid() == clsid.zombie_s then
				bb_mod.npcondeath(victim, who)
			end
			local sobj = game.translate_string(xvars.quest_two_target_yan)
			if sobj and sobj == game.translate_string(self.object:name()) and has_alife_info("doska_two_taken_yan") then
				news_manager.send_tip(db.actor, game.translate_string("generic_object_binderdeath_callback_0"), 1, "mutants", 9000)
				level.map_remove_object_spot(self.object:id(), "monster_part_location")
				db.actor:change_character_reputation(15)
			end
		elseif (IsStalker(who) and who:alive()) then
			local se_who = alife():object(who:id())
			-- Дадим немного очков ранга за убийство мутанта
			if (se_who) then
				who:set_character_rank(who:character_rank()+math.random(5,15))
			end
		end
	end	

	if self.st.mob_death then
		xr_logic.issue_event(self.object, self.st.mob_death, "death_callback", victim, who)
	end

	if self.st.active_section then
		xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "death_callback", victim, who)
	end
	
	-- Отрубаем коллбэки
	victim:set_callback(callback.death,nil)
	victim:set_callback(callback.patrol_path_in_point,nil)
	victim:set_callback(callback.hit,nil)

	smart_terrain.on_death( self.object:id() )

end




function generic_object_binder:hit_callback(obj, amount, local_direction, who, bone_index)

	if self.st.hit then
		xr_logic.issue_event(self.object, self.st.hit, "hit_callback", obj, amount, local_direction, who, bone_index)
	end

	local self_object_name = self.object:name()
    if self_object_name == "lab_burer_elder_1" or self_object_name == "lab_burer_elder_2" then
        if who:id() == db.actor:id() then
            db.actor:kill(db.actor)
        end
    end

end


function generic_object_binder:net_spawn(sobject)

    if not object_binder.net_spawn(self, sobject) then
        return false
    end

	local self_object_cls = self.object:clsid()
	if self_object_cls == clsid.fracture or self_object_cls == clsid.fracture_s or
		self_object_cls == clsid.flesh_s or
		self_object_cls == clsid.flesh or
		self_object_cls == clsid.dog or
		self_object_cls == clsid.dog_s or
		self_object_cls == clsid.zombie_s or
		self_object_cls == clsid.zombie or
		self_object_cls == clsid.tushkano or
		self_object_cls == clsid.tushkano_s
	then
		self.object:disable_trade()
    end

    --db.add_obj(self.object)

    xr_gulag.setup_gulag_and_logic_on_spawn(self.object, self.st, sobject, modules.stype_mobile, self.loaded)

    return true
end

function generic_object_binder:net_save_relevant()
	return true
end

function generic_object_binder:save(packet)

	object_binder.save(self, packet)
	xr_logic.save_obj(self.object, packet)
	if self.object:clsid() == clsid.script_trader then
		trade_manager.save(self.object, packet)
	end
	
end

function generic_object_binder:load(reader)

	self.loaded = true

	printf("generic_object_binder:load(): self.object:name()='%s'", self.object:name())
	object_binder.load(self, reader)

	if reader:r_eof() then
		abort("SAVE FILE IS CORRUPT - monster_binder, object - "..self.object:name().."")
	end

	xr_logic.load_obj(self.object, reader)
	if self.object:clsid() == clsid.script_trader then
		trade_manager.load(self.object, reader)
	end
	
end

-----------------------------------------------------------------------------------------------------------------------
local vaild_outfits = {
    ["ecolog_outfit"] = true,
    ["exo_outfit"] = true,
    ["scientific_outfit"] = true,
    ["outfit_antirad"] = true
}

function zarazjenie_parazitom()
    local par_var = math.random(1, 10)
    if par_var == 1 then
        local currout = db.actor:item_in_slot(6)

        if not currout or currout:condition() < 0.8 or not vaild_outfits[currout:section()] then
            --log1(" paras try ")

            local has_art = db.actor:object("af_studen_m1")
            if has_art and db.actor:is_on_belt(has_art) then
                --news_manager.send_tip(db.actor, game.translate_string("zarazjenie_parazitom_0"))
                return
            end

            if olr_timers.has_timer("bolezn_parasite_timer") then
                --news_manager.send_tip(db.actor, game.translate_string("zarazjenie_parazitom_1"))
                return
            end

            if olr_timers.has_timer("bolezn_parasite_timer_m") then
                --news_manager.send_tip(db.actor, game.translate_string("zarazjenie_parazitom_2"))
                return
            end

            if olr_timers.has_timer("bolezn_parasite_timer_d") then
                --news_manager.send_tip(db.actor, game.translate_string("zarazjenie_parazitom_3"))
                return
            end

            if not has_alife_info("bolezn_parazity_info") then
                olr_timers.st_timer("bolezn_parasite_timer", 2250, "nick.bolezn_parasite_timer()")
                --news_manager.send_tip(db.actor, game.translate_string("zarazjenie_parazitom_4"))
                db.actor:give_info_portion("bolezn_parazity_info")
            end
        end
    end
end
