--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
-- name: bind_anomaly.script
-- desc: Биндер аномалий, не сильно нужен
-- author: theysani
-- date: 19.12.2025
-- last edit: 19.12.2025
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

function Init(obj)
	local oNewBinder = anomaly_binder(obj)
	obj:bind_object(oNewBinder)	
end

class "anomaly_binder" (object_binder)

function anomaly_binder:__init(obj) super(obj)
end

function anomaly_binder:reload(section)
	object_binder.reload(self, section)
end

function anomaly_binder:reinit()
	object_binder.reinit(self)
end

function anomaly_binder:net_save_relevant()
	return true
end

function anomaly_binder:save(packet)
	object_binder.save(self, packet)	
end

function anomaly_binder:load(reader)
	object_binder.load(self, reader)
end


function anomaly_binder:net_spawn(data)
	if not object_binder.net_spawn(self, data) then
		return false
	end
	

	return true
end
	
function anomaly_binder:net_destroy()
	object_binder.net_destroy(self)
end

function anomaly_binder:update(delta)
	object_binder.update(self, delta)
end
