

function transfer_vodka (player, stalker)
    if player:object ("vodka") == nil then return end
    dialogs.relocate_item (stalker, player:object ("vodka"), "out")
end    

function have_a_vodka (stalker, player)
    return stalker:object ("vodka") ~= nil
end

function transfer_scope (npc, actor)
    dialogs.relocate_item_section(npc, "af_dummy_glassbeads", "in") 
    dialogs.relocate_item_section(npc, "vodka", "out")
end


