function allow_break_dialog(first_speaker, second_speaker, id)
	if second_speaker:profile_name() == "osoznanie" then
		return false
	end
	return true
end

function precond_pda_trade(first_speaker, second_speaker)
	local npc = who_is_npc(first_speaker, second_speaker)
	local timer_name = "trade_agree_remove_spot_" .. tostring(npc:id())
	if olr_timers.has_timer(timer_name) then
		return false
	else
		return true
	end
end

function is_zakurit_prec(first_speaker, second_speaker, id)
	local stk_rank = first_speaker:character_rank()
	if stk_rank > 100 and stk_rank < 250 then
		local siga = second_speaker:object("sigaret")
		if siga == nil then
			return true
		end
	end
	return false
end

function pda_dialog_trade_can(first_speaker, second_speaker, id)
	--log1("  - "..first_speaker:name().." -- "..second_speaker:name().."  ")
	local act_rank = db.actor:character_rank()
	local stk_rank = first_speaker:character_rank()
	if act_rank >= stk_rank then
		return true
	end
	local be = first_speaker:best_enemy()
	if not be then
		return true
	end
	return false
end

function pda_dialog_trade_not(first_speaker, second_speaker, id)
	local act_rank = db.actor:character_rank()
	local stk_rank = first_speaker:character_rank()
	if act_rank < stk_rank then
		return true
	end
	return false
end

function break_dialog(first_speaker, second_speaker, id)
	first_speaker:stop_talk()
	second_speaker:stop_talk()
	soundtrack.s_stop()
end

function disable_talk_self(first_speaker, second_speaker)
	first_speaker:disable_talk()
end

function disable_talk_victim(first_speaker, second_speaker)
	second_speaker:disable_talk()
end

function no_trade_trader(first_speaker, second_speaker, id)
	first_speaker:disable_trade()
	--second_speaker:disable_trade()
end
function no_trade(first_speaker, second_speaker, id)
	--first_speaker:disable_trade()
	second_speaker:disable_trade()
end

function punch(first_speaker, second_speaker)
	--abort("KICK ASS !!!!")
	--xr_punch.punch[first_speaker:id()] = second_speaker
	db.storage[second_speaker:id()].punch.enabled = true
end

function get_money_then_leave(first_speaker, second_speaker)
	db.storage[first_speaker:id()].meet.enabled = false
	db.storage[first_speaker:id()].robber.enabled = true
end

function who_is_npc(first_speaker, second_speaker)
	local npc = second_speaker
	if db.actor:id() == npc:id() then
		npc = first_speaker
	end
	return npc
end

function is_wounded(first_speaker, second_speaker)
	local npc = who_is_npc(first_speaker, second_speaker)
	return xr_wounded.is_wounded(npc)
end

function is_opp_wounded(first_speaker, second_speaker, dialog_id)
	local npc = who_is_npc(first_speaker, second_speaker)
	if npc == nil then
		return false
	end
	local npc_storage = db.storage[npc:id()]
	if npc_storage ~= nil and npc_storage.wounded ~= nil and npc_storage.wounded.wound_manager.can_use_medkit == true then
		return false
	end
	return xr_wounded.is_wounded(npc)
end

function is_not_wounded(first_speaker, second_speaker)
	return not this.is_wounded(first_speaker, second_speaker)
end

function actor_have_medkit(first_speaker, second_speaker)
	return first_speaker:object("medkit") ~= nil
end

function actor_have_bandage(first_speaker, second_speaker)
	return first_speaker:object("bandage") ~= nil
end

function actor_no_medkit(first_speaker, second_speaker)
	return first_speaker:object("medkit") == nil
end

function transfer_medkit(first_speaker, second_speaker)
	local giver, receiver = first_speaker, second_speaker
	if db.actor and first_speaker:id() ~= db.actor:id() then
		giver, receiver = second_speaker, first_speaker
	end
	if giver:object("medkit") ~= nil then
		dialogs.relocate_item_section(receiver, "medkit", "out")
		xr_wounded.unlock_medkit(receiver)
		if receiver:relation(giver) ~= game_object.enemy then
			receiver:set_relation(game_object.friend, giver)
			receiver:enable_trade()
			giver:enable_trade()
		end
		xr_sound.set_sound_play(receiver, "help_thanx")
		giver:change_character_reputation(20)
		if receiver:character_rank() <= giver:character_rank() then
			olr_treasure.create_treasure()
		end
	end
end

function set_enemy_npc(first_speaker, second_speaker)
	second_speaker:set_relation(game_object.enemy, first_speaker)
	first_speaker:set_relation(game_object.enemy, second_speaker)
end

function transfer_bandage(first_speaker, second_speaker)
	local giver, receiver = first_speaker, second_speaker
	if db.actor and first_speaker:id() ~= db.actor:id() then
		giver, receiver = second_speaker, first_speaker
	end
	dialogs.relocate_item_section(receiver, "bandage", "out")
	receiver:set_relation(game_object.friend, giver)
end

function kill_yourself(npc, actor)
	npc:kill(actor)
end

-- Obsolete, do not use!!!
function relocate_item(victim, obj, type)
	if db.actor and victim then
		if type == "in" then
			victim:transfer_item(obj, db.actor)
		elseif type == "out" then
			db.actor:transfer_item(obj, victim)
		end
	--news_manager.relocate_item(db.actor, type, obj)
	end
end

-- Use this function instead.
-- При передаче предмета игроку нужно для еды и оружия выставлять флаги что они не заражены
function relocate_item_section(victim, section, type, amount)
	if db.actor then
		if not amount then
			amount = 1
		end
		for i = 1, amount do
			if type == "in" then
				local item = alife():create(section, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
				if item then
					level.client_spawn_manager():add(item.id, 0,
						function(id, obj)
							if obj and g_food_table[obj:section()] then
								obj:set_condition(0.99) -- Для еды что бы была в идеале сразу
								xvars.foods[tostring(obj:id())] = {sec = obj:section(), rad = false}
							elseif obj and g_weapon_table[obj:section()] then
								xvars.weapons[tostring(obj:id())] = {sec = obj:section(), rad = false}
							end
						end
					)
				end
			elseif type == "out" then
				if victim == nil then
					log1("#WARN: [dialogs.relocate_item_section] Couldn't relocate item to NULL")
				end
				db.actor:transfer_item(db.actor:object(section), victim)
			end
		end
		news_manager.relocate_item(db.actor, type, section, amount)
	end
end

function relocate_money(victim, num, type)
	if db.actor and victim then
		if type == "in" then
			db.actor:give_money(num)
			game_stats.money_quest_update(num)
		elseif type == "out" then
			db.actor:transfer_money(num, victim)
			game_stats.money_quest_update(-num)
		end
		news_manager.relocate_money(db.actor, type, num)
	end
end

function relocate_money_no_sms(victim, num, type)
	if db.actor and victim then
		if type == "in" then
			db.actor:give_money(num)
			game_stats.money_quest_update(num)
		elseif type == "out" then
			db.actor:transfer_money(num, victim)
			game_stats.money_quest_update(-num)
		end
	end
end

-----------------------------------------------------------------------------------
-- DIALOG ALLOWED
-----------------------------------------------------------------------------------
function dialog_allowed(object, victim, id)
	if id ~= nil then
		--printf("*DIALOGS*: dialog_allowed: %s", id)
	else
		--printf("*DIALOGS*: dialog_allowed: nil")
	end
	if db.storage[victim:id()].actor_dialogs ~= nil then
		for k, v in pairs(db.storage[victim:id()].actor_dialogs) do
			if v == id then
				return true
			end
		end
	end
	return false
end

function dialog_not_disable(object, victim, id)
	if id ~= nil then
		--printf("*DIALOGS*: dialog_disable:%s", id)
	else
		--printf("*DIALOGS*: dialog_disable:nil")
	end
	if db.storage[victim:id()].actor_disable ~= nil then
		for k, v in pairs(db.storage[victim:id()].actor_disable) do
			if v == id then
				return false
			end
		end
	end
	return true
end

function allow_wounded_dialog(object, victim, id)
	local npc = who_is_npc(object, victim)
	if npc == nil then
		return false
	end
	local npc_storage = db.storage[npc:id()]
	if npc_storage == nil or npc_storage.wounded == nil then
		return false
	end
	return npc_storage.wounded.help_dialog == id
end

-----------------------------------------------------------------------------------
-- LEVELS
-----------------------------------------------------------------------------------
function level_escape(first_speaker, second_speaker)
	return level.name() == "l01_escape"
end

function level_garbage(first_speaker, second_speaker)
	return level.name() == "l02_garbage"
end

function level_agroprom(first_speaker, second_speaker)
	return level.name() == "l03_agroprom"
end

-----------------------------------------------------------------------------------
-- Relation functions
-----------------------------------------------------------------------------------
function is_friend(first_speaker, second_speaker)
	return first_speaker:relation(second_speaker) == game_object.friend
end

function is_not_friend(first_speaker, second_speaker)
	return not is_friend(first_speaker, second_speaker)
end

function become_friend(first_speaker, second_speaker)
	first_speaker:set_relation(game_object.friend, second_speaker)
end

-----------------------------------------------------------------------------------
-- Community
-----------------------------------------------------------------------------------
function actor_in_dolg(actor, npc)
	if db.actor then
		return db.actor:character_community() == "actor_dolg"
	end
	return false
end

function actor_not_in_dolg(actor, npc)
	return not actor_in_dolg(actor, npc)
end

function actor_set_dolg(actor, npc)
	printf("ACTOR NOW IN [DOLG] COMMUNITY")
	if db.actor then
		db.actor:set_character_community("actor_dolg", 0, 0)
	end
	return true
end

function actor_clear_community(actor, npc)
	printf("ACTOR NOW IN [NEUTRAL] COMMUNITY")
	if db.actor then
		db.actor:set_character_community("actor", 0, 0)
	end
	return true
end

-----------------------------------------------------------------------------------
-- Money functions
-----------------------------------------------------------------------------------
function has_2000_money(first_speaker, second_speaker)
	return first_speaker:money() >= 2000
end

-----------------------------------------------------------------------------------
-- TRADE
-----------------------------------------------------------------------------------
-- Инициализация торговли
function trade_init(seller, buyer)
	local seller_id = seller:id()
	db.storage[seller_id].meet.begin_wait_to_see.begin = time_global() / 1000
	xr_position.setPosition(db.storage[seller_id].meet.Seller, db.storage[seller_id].meet.Seller:level_vertex_id())
	db.storage[seller_id].meet.Buyer = buyer
end

function want_trade(seller, buyer)
	if seller:relation(buyer) == game_object.friend or seller:relation(buyer) == game_object.neutral then
		return true
	else
		return false
	end
end

function dont_want_trade(seller, buyer)
	return not want_trade(seller, buyer)
end
