-- Ночная работа
function trader_has_night_job(trader, actor)
	if (has_alife_info("medyasik_done") and not has_alife_info("medyasik_2_start") and nick.has_esc_timer_one_timer()) or
	   (has_alife_info("bar_pre_doks_talkerd") and not has_alife_info("jaba_start_phanrom_start"))
	then
		return true
	end
	return false 
end

function trader_dont_has_night_job(first_speaker, second_speaker)
	return not trader_has_night_job(first_speaker, second_speaker)
end
