function register(object_factory)
	if (editor() == false) then
	end
end

function get_game_clsid(game_type_option,is_server)

	if(is_server==true) then
		if(game_type_option == "single") then 
			  return "SV_SINGL"	end

		if(game_type_option == "deathmatch") then 
			return "SV_DM" end

		if(game_type_option == "teamdeathmatch") then 
			return "SV_TDM" end

		if(game_type_option == "artefacthunt") then 
			return "SV_AHUNT" end

		if(game_type_option == "laststanding") then 
			return "SV_LAST" end
		
	end	

	if(is_server==false) then
		if(game_type_option == "single") then 
			  return "CL_SINGL"	end

		if(game_type_option == "deathmatch") then 
			return "CL_DM" end

		if(game_type_option == "teamdeathmatch") then 
			return "CL_TDM" end

		if(game_type_option == "artefacthunt") then 
			return "CL_AHUNT" end


		if(game_type_option == "laststanding") then 
			return "CL_LAST" end
	end
	return ""
end
