
function add_subtitle(text_all, timeout)
	local hud = get_hud()
	local custom_static = hud:GetCustomStatic("subtitles_scene_text")
	hud:AddCustomStatic("subtitles_scene_text", true)
	hud:GetCustomStatic("subtitles_scene_text"):wnd():SetTextST(tostring(text_all))
	hud:GetCustomStatic("subtitles_scene_text").m_endTime = time_global()/1000 + timeout
end

function add_subtitle2(text_all, timeout)
	local hud = get_hud()
	local custom_static = hud:GetCustomStatic("subtitles_scene_text2") -- во избежание перезаписи текста(lanim может не включиться) чередуем
	hud:AddCustomStatic("subtitles_scene_text2", true)
	hud:GetCustomStatic("subtitles_scene_text2"):wnd():SetTextST(tostring(text_all))
	hud:GetCustomStatic("subtitles_scene_text2").m_endTime = time_global()/1000 + timeout
end

function start_scene(scene_name)
	if scene_name == "military_radio_peredacha" then
		olr_timers.st_timer("military_radio_peredacha1", 13, "game_subtitles.military_radio_peredacha1()")
		olr_timers.st_timer("military_radio_peredacha2", 20, "game_subtitles.military_radio_peredacha2()")
		olr_timers.st_timer("military_radio_peredacha3", 32, "game_subtitles.military_radio_peredacha3()")
		olr_timers.st_timer("military_radio_peredacha4", 44, "game_subtitles.military_radio_peredacha4()")
		olr_timers.st_timer("military_radio_peredacha5", 55.5, "game_subtitles.military_radio_peredacha5()")
		olr_timers.st_timer("military_radio_peredacha6", 75.5, "game_subtitles.military_radio_peredacha6()")
		olr_timers.st_timer("military_radio_peredacha7", 89.4, "game_subtitles.military_radio_peredacha7()")
		olr_timers.st_timer("military_radio_peredacha8", 108, "game_subtitles.military_radio_peredacha8()")
		olr_timers.st_timer("military_radio_peredacha9", 126, "game_subtitles.military_radio_peredacha9()")
		olr_timers.st_timer("military_radio_peredacha10", 142, "game_subtitles.military_radio_peredacha10()")
		olr_timers.st_timer("military_radio_peredacha11", 154, "game_subtitles.military_radio_peredacha11()")
	end
end

function military_radio_peredacha1()
	add_subtitle("st_military_radio_peredacha_phrase_01", 7.1)
end

function military_radio_peredacha2()
	add_subtitle2("st_military_radio_peredacha_phrase_02", 11.8)
end

function military_radio_peredacha3()
	add_subtitle("st_military_radio_peredacha_phrase_03", 12)
end

function military_radio_peredacha4()
	add_subtitle2("st_military_radio_peredacha_phrase_04", 11)
end

function military_radio_peredacha5()
	add_subtitle("st_military_radio_peredacha_phrase_05", 20)
end

function military_radio_peredacha6()
	add_subtitle2("st_military_radio_peredacha_phrase_06", 14)
end

function military_radio_peredacha7()
	add_subtitle("st_military_radio_peredacha_phrase_07", 20.5)
end

function military_radio_peredacha8()
	add_subtitle2("st_military_radio_peredacha_phrase_08", 21)
end

function military_radio_peredacha9()
	add_subtitle("st_military_radio_peredacha_phrase_09", 23)
end

function military_radio_peredacha10()
	add_subtitle2("st_military_radio_peredacha_phrase_10", 12)
end

function military_radio_peredacha11()
	add_subtitle("st_military_radio_peredacha_phrase_11", 25)
end
