
function load_job(sj, gname, type, squad, groups)

	if type == "agr_military_stalkers_smart" then
		t = { section = "logic@agr_military_stalkers_smart_patrol_1",
			idle = 0,
			prior = 1, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@agr_military_stalkers_smart_search_1",
			idle = 0,
			prior = 2, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@agr_military_stalkers_smart_search_2",
			idle = 0,
			prior = 2, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@agr_military_stalkers_smart_search_3",
			idle = 0,
			prior = 2, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
end

function load_states(gname, type)	
    if type == "agr_military_stalkers_smart" then
		return function(gulag)
			return 0
		end
    end
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)
	if gulag_type == "agr_military_stalkers_smart" then
		return npc_community == "voenstals"
	end
	
	return false
end

function checkMonster(npc_community, gulag_type, npc_rank, se_obj)
	return false
end
