local t = {}

function load_job(sj, gname, type, squad, groups)

	-- Посетители Долга      ------------- ЮЗАЕМ
	if type == "bar_visitors" then

		t = { section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 9, state = {0,1}, 
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 8, state = {0,1}, 
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 7, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp2",
			idle = 0, 
			prior = 6, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp2",
			idle = 0, 
			prior = 5, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 4, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 9, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 8, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 7, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 6, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp3",
			idle = 0, 
			prior = 5, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@bar_visitors_kamp4",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp4",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_kamp4",
			idle = 0, 
			prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@bar_visitors_walker",
			idle = 0, 
			prior = 7, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_walker",
			idle = 0, timeout = math.random(10,20)*60,
			prior = 7, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_walker",
			idle = 0, timeout = math.random(10,20)*60,
			prior = 7, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_walker",
			idle = 0, timeout = math.random(10,20)*60,
			prior = 7, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@bar_visitors_walker",
			idle = 0, timeout = math.random(10,20)*60,
			prior = 7, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end












	
	-- Гулаг ламеров Долга внутри базы Долга
	if type == "bar_dolg_general" then
		t = { section = "logic1@bar_dolg_general_guard_left",
			idle = 0,
			prior = 8, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)		    
		t = { section = "logic2@bar_dolg_general_guard_right",
			idle = 0,
			prior = 8, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)		    
		t = { section = "logic3@bar_dolg_general_guard_center",
			idle = 0,
			prior = 9, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}",
			predicate = function(obj_info)
			           	return obj_info.profile_name == "bar_dolg_guard_commander"
			        end
			
        }
		table.insert(sj, t)		
        
      	t = { section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)


		t = { section = "logic5@bar_dolg_general_patrol1", 
			idle = 5*60*60,
			prior = 6, state = {0}, squad = squad, group = groups[2],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic6@bar_dolg_general_patrol2", 
			idle = 5*60*60,
			prior = 6, state = {0}, squad = squad, group = groups[2],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)


		t = { section = "logic6@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic7@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic8@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic9@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic10@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)


	end







	-- Гулаг ветеранов Долга внутри базы Долга  -------- ЮЗАЕМ
	if type == "bar_dolg_veterans" then
		t = { section = "logic3@bar_dolg_veterans_gates1", 
			idle = 0,
			prior = 7, state = {0,1},
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic4@bar_dolg_veterans_gates2", 
			idle = 0,
			prior = 7, state = {0,1},
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic1@bar_dolg_veterans_guard_bunker1", 
			idle = 0,
			prior = 9, state = {0,1,2},
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic2@bar_dolg_veterans_guard_bunker2", 
			idle = 0,
			prior = 9, state = {0,1,2},
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = { section = "logic5@bar_dolg_veterans_gates_alarm1", 
			idle = 0,
			prior = 5, state = {2},
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)	
		t = { section = "logic6@bar_dolg_veterans_gates_alarm2", 
			idle = 0,
			prior = 5, state = {2},
			in_rest = "", out_rest = "",
					online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
	end

	-- Гулаг в бункере Долга   -------- ЮЗАЕМ                
	if type == "bar_dolg_bunker" then
		t = { section = "logic2@bar_dolg_bunker", 
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest =  ""
		}
		table.insert(sj, t)		    
		t = { section = "logic3@bar_dolg_bunker", 
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest =  ""
		}
		table.insert(sj, t)		    
		t = { section = "logic4@bar_dolg_bunker", 
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest =  ""
		}
		table.insert(sj, t)		    
		t = { section = "logic5@bar_dolg_bunker", 
			idle = 0,
			prior = 4, state = {0},
			in_rest = "", out_rest =  ""
		}
		table.insert(sj, t)		    
		
	end



    -- Гулаг сталкеров на заставе 1       -------- ЮЗАЕМ

    if type == "bar_zastava" then 
        t = { section = "logic@bar_dolg_zastava1_cammander_1",
        idle = 0,
        prior = 9, state = {0},
        in_rest = "", 
	out_rest = "",   --"bar_zastava_restrictor",
	online = "{=actor_in_zone(bar_zastava_online_restrictor)}",
	predicate = function(obj_info)
        return obj_info.profile_name == "bar_zastava_commander_1"
	end
        }

		table.insert(sj, t)
	
        for i = 1,3 do
            t = { section = "logic@bar_dolg_zastava1_walker"..i,
                    idle = 0,
                    prior = 8, state = {0},
                    in_rest = "", 
	            out_rest = "",   -- "bar_zastava_restrictor",
		    online = "{=actor_in_zone(bar_zastava_online_restrictor)}"

                }
		    table.insert(sj, t)
        end
    end




    -- Гулаг сталкеров на заставе 2   -------- ЮЗАЕМ

    if type == "bar_zastava_2" then 
        for i = 1,3 do
            t = { section = "logic@bar_dolg_zastava2_walker"..i,
                    idle = 0,
                    prior = 9, state = {0},
                    in_rest = "", 
		     out_rest = "",  -- bar_zastava_restrictor_2
			online = "{=actor_in_zone(bar_zastava2_online_restrictor)}"   
                }
		    table.insert(sj, t)
        end
    end


	-- Гулаг бандитов на северной площадке   -------- ЮЗАЕМ
	if type == "agr_u_bandits" then
		for i = 1, 7 do
			t = { section = "logic@agr_u_bandits"..i,  
				idle = 0,
				prior = 5, state = {0},
				squad = squad, group = groups[1],
				in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end
end

function load_states(gname, type)
	if type == "bar_visitors" then
		return function(gulag)
			if level.rain_factor() > 0.07 then
				return 1
			end
			return 0
		end
	end

    if type == "bar_zastava" then
		return function(gulag)
			return 0
		end
    end

    if type == "bar_zastava_2" then
		return function(gulag)
			return 0
		end
    end
	if type == "bar_dolg_general" then
		return function (gulag)
				for k,v in pairs(gulag.Object) do
					if v ~= true and v:best_enemy() ~= nil then
   						gulag.alarm_start = game.get_game_time()
   						return 2 -- тревога
					end
				end		
		
				if gulag.alarm_start == nil or
					game.get_game_time():diffSec(gulag.alarm_start) > 300 then
					if level.get_time_hours() >= 6 and level.get_time_hours() <= 22 then
						return 0  -- день
					else
						return 1  -- ночь
					end
				else
					return 2
				end
		end
	end
	if type == "bar_dolg_veterans" then        
		return function (gulag)
				for k,v in pairs(gulag.Object) do
					if v ~= true and v:best_enemy() ~= nil then
   						gulag.alarm_start = game.get_game_time()
   						return 2 -- тревога
					end
				end		
		
				if gulag.alarm_start == nil or
					game.get_game_time():diffSec(gulag.alarm_start) > 300 then
					if level.get_time_hours() >= 6 and level.get_time_hours() <= 22 then
						return 0  -- день
					else
						return 1  -- ночь
					end
				else
					return 2
				end
		end
	end
	if type == "bar_dolg_bunker" then        
		return function (gulag)
				return 0
		end
	end

	if type == "agr_u_bandits" then
		return function(gulag)
			return 0
		end
	end
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------

function load_ltx(gname, type)
	if type == "agr_u_bandits" then
		return load_ltx_agr_u_bandits(gname, type)
	end
end

function load_ltx_agr_u_bandits(gname, type)
    local i, res = 0, ""
	for i = 1, 1 do
	res = res .. "[logic@" .. gname ..  i .. "]\n" ..
				"active = walker@" .. gname ..  i .. "\n" ..
				"combat_ignore = combat_ignore@" .. gname .. "\n" ..

				"[walker@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				
				"on_actor_in_zone = kat_bandit_trigger3 | walker2@" .. gname ..  i .. "\n" ..
				"danger=danger_condition@" .. gname .. "\n" ..

				"[walker2@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				"danger=danger_condition@" .. gname .. "\n"

	end
	for i = 2, 5 do
	res = res .. "[logic@" .. gname ..  i .. "]\n" ..
				"active = walker@" .. gname ..  i .. "\n" ..
				"combat_ignore = combat_ignore@" .. gname .. "\n" ..

				"[walker@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				
				"on_actor_in_zone = kat_bandit_trigger3 | walker2@" .. gname ..  i .. "\n" ..
				"danger=danger_condition@" .. gname .. "\n" ..

				"[walker2@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				"danger=danger_condition@" .. gname .. "\n" 

	end

	for i = 6, 6 do
	res = res .. "[logic@" .. gname ..  i .. "]\n" ..
				"active = walker@" .. gname ..  i .. "\n" ..
				"combat_ignore = combat_ignore@" .. gname .. "\n" ..

				"[walker@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				
				"on_actor_in_zone = kat_bandit_trigger4 | walker2@" .. gname ..  i .. "\n" ..
				"danger=danger_condition@" .. gname .. "\n" ..

				"[walker2@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				"danger=danger_condition@" .. gname .. "\n" 

	end
	for i = 7, 7 do
	res = res .. "[logic@" .. gname ..  i .. "]\n" ..
				"active = walker@" .. gname ..  i .. "\n" ..
				"combat_ignore = combat_ignore@" .. gname .. "\n" ..

				"[walker@" .. gname ..  i .. "]\n" ..
				"path_walk = walk".. i.. "\n" ..
				"path_look = look".. i.. "\n" ..
				
				"danger=danger_condition@" .. gname .. "\n" 

	end

	res = res .."[combat_ignore@" .. gname .. "]\n" ..

				"[danger_condition@" .. gname .. "]\n" ..
				"danger_expiration_time = 60000\n" ..
				"danger_inertion_time =  90000\n"

	return res
end

function checkStalker(npc_community, gulag_type)


	if gulag_type == "bar_dolg_general" then
		return npc_community == "dolg"
	end
	if gulag_type == "bar_dolg_veterans" then
		return npc_community == "dolg"
	end
	if gulag_type == "bar_dolg_bunker" then
		return npc_community == "dolg"
	end
	if gulag_type == "bar_zastava" then
		return npc_community == "dolg"
	end
	if gulag_type == "bar_zastava_2" then
		return npc_community == "dolg"
	end

	if gulag_type == "bar_visitors" then
		return true
	end

	if gulag_type == "agr_u_bandits"  then
		return npc_community == "bandit"
	end
	
	return false
end

function checkMonster(npc_community, gulag_type, npc_rank, se_obj)
	return false
end