local t = {}

function load_job(sj, gname, type, squad, groups)
----------------------------------------------------------------------------	
-- GARBAGE
----------------------------------------------------------------------------	

	-- Dolg_blokpost
	if type == "gar_dolg_blokpost" then
		t = { section = "logic@gar_dolg_blokpost_camper1",
			idle = 0,
			prior = 5, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_camper2",
			idle = 0,
			prior = 5, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_camper3",
			idle = 0,
			prior = 5, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_zoneguard1",
			idle = 0,
			prior = 10, state = {0,1},
			in_rest = "", out_rest = "",
			predicate = function(obj_info) 
        					return obj_info.profile_name == "gar_dolg_blokpost_commander"			           
						end
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_zoneguard2",
			idle = 0,
			prior = 7, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_zoneguard3",
			idle = 0,
			prior = 7, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_kamp1",
			idle = 0,
			prior = 3, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_kamp2",
			idle = 0,
			prior = 3, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_kamp3",
			idle = 0,
			prior = 3, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_kamp4",
			idle = 0,
			prior = 3, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_kamp5",
			idle = 0,
			prior = 3, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_patrol",
			idle = 0,
			prior = 5, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		

		t = { section = "logic@gar_dolg_blokpost_alarm1",
			idle = 0,
			prior = 9, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_alarm2",
			idle = 0,
			prior = 9, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_alarm3",
			idle = 0,
			prior = 9, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_alarm4",
			idle = 0,
			prior = 9, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gar_dolg_blokpost_alarm5",
			idle = 0,
			prior = 9, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
--		t = { section = "logic@gar_dolg_blokpost_zoneguard1",
--			idle = 0,
--			prior = 10, state = {1},
--			in_rest = "", out_rest = "",
--			predicate = function(obj_info) 
--        					return obj_info.profile_name == "gar_dolg_blokpost_commander"			           
--						end
--		}
--		table.insert(sj, t)
	end
end

function load_states(gname, type)
	if type == "gar_dolg_blokpost" then
		return function(gulag)
			if has_alife_info("gar_test_info2") then
				return 1 -- кабаны атакуют
			else
				return 0 -- спокойное состояние
			end
		end
	end
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)
	if gulag_type == "gar_dolg_blokpost" then
		return npc_community == "dolg"
	end
	
	return false
end

function checkMonster(npc_community, gulag_type)
	return false
end
