local t = {}

function load_job(sj, gname, type, squad, groups)
----------------------------------------------------------------------------
-- ESCAPE
----------------------------------------------------------------------------
	--- ƒЋя ¬џ¬ќƒј ¬ ќ‘Ћј…Ќ_ќЌЋ…ј…Ќ «ј ќћ≈Ќ“»Ћ online = true,
	-- Escape blockpost
	if type == "esc_blokpost" then
		t = { section = "logic@esc_blockpost_patrol1",
			idle = 0,
			prior = 8, state = {0},
			position_threshold = 100,
			online = true,
			in_rest = "", out_rest = "esc_blockpost_patrol_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_follower1",
			idle = 0,
			prior = 7, state = {0},
			position_threshold = 100,
			online = true,
			in_rest = "", out_rest = "esc_blockpost_patrol_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_follower2",
			idle = 0,
			prior = 7, state = {0},
			position_threshold = 100,
			online = true,
			in_rest = "", out_rest = "esc_blockpost_patrol_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_commander_day",
			idle = 0,
			prior = 100, state = {0,2},
			position_threshold = 100,
			--online = true,
		in_rest = "", out_rest = "escape_blockpost_zone",
		predicate = function(obj_info)
		            	return obj_info.name == "esc_blokpost_commander"
		            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_post1",
			idle = 0,
			prior = 8, state = {0,1,2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_post2",
			idle = 0,
			prior = 8, state = {0,1,2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_camper_day",
			idle = 0,
			prior = 6, state = {0,2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_patrol_yard",
			idle = 0,
			prior = 5, state = {0,1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_watch_tv1",
			idle = 0,
			prior = 2, state = {0},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_watch_tv2",
			idle = 0,
			prior = 2, state = {0},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_kamp1",
			idle = 0,
			prior = 4, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_kamp1",
			idle = 0,
			prior = 4, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_kamp2",
			idle = 0,
			prior = 10, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone",
			predicate = function(obj_info)
							return obj_info.name == "esc_blokpost_commander"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep1",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep2",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep3",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep4",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_comander_guard1",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_comander_guard2",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_camper1",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_camper2",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_alarm_patrol1",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_alarm_patrol2",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
				--online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
	end

	-- Ћагерь новичков на Escape
	if type == "esc_lager" then
		-- охранники
		t = { section = "logic@esc_lager_zoneguard1",
			idle = 0,
			prior = 9, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_zoneguard2",
			idle = 0,
			prior = 9, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_walker3",
			idle = 0,
			prior = 8, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_walker4",
			idle = 0,
			prior = 8, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		-- у костра днЄм
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)

		-- сп€щие ночью
		t = { section = "logic@esc_lager_sleeper1",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_sleeper2",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		-- сп€щие ночью и днЄи
		t = { section = "logic@esc_lager_sleeper5",
			idle = 0,
			prior = 5, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 0, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_sleeper7",
			idle = 0,
			prior = 0, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
	end
end

function load_states(gname, type)

	if type == "esc_blokpost" then
		return function (gulag)
			local actor = db.actor
			if not actor then
				return gulag.state
			end

			for k,v in pairs(gulag.Object) do
				if v ~= true and v:best_enemy() ~= nil then
					local bo = v:best_enemy()
					if bo and v:position():distance_to_sqr(bo:position()) <= 10 then
						gulag.alarm_start = game.get_game_time()
						actor:give_info_portion("esc_blockpost_alarm")
						return 2 -- тревога
					end
				end
			end

			if gulag.alarm_start == nil or
				game.get_game_time():diffSec(gulag.alarm_start) > 300 then
				if level.get_time_hours() >= 6 and level.get_time_hours() <= 22 then
				actor:give_info_portion("esc_blockpost_normal")
					return 0  -- день
				else
					return 1  -- ночь
				end
			else
				return 2
			end
		end
	end

	if type == "esc_lager" then
		return function(gulag)
			local actor = db.actor
			if not actor then
				return gulag.state
			end
			if level.get_time_hours() >= 5 and level.get_time_hours() <= 22 then
				return 0  -- день
			else
				return 1  -- ночь
			end
		end
	end
end



--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)

	if gulag_type == "esc_blokpost" then
		return npc_community == "military"
	end

	if gulag_type == "esc_lager" then
		return npc_community == "stalker"
	end
	
	return false
end

function checkMonster(npc_community, gulag_type)
	return false
end