
--------------------------------------------------------------------------
-- Member counts
--------------------------------------------------------------------------
local mob_spring_count = 20

--------------------------------------------------------------------------
-- States
--------------------------------------------------------------------------
local state_normal = 0
local state_alarm = 1
local state_alarm_actor_inside = 2
local state_fight = 1

--------------------------------------------------------------------------
-- General
--------------------------------------------------------------------------
local t = {}
local gulags = { val_lager_bandits = {comm = {"bandit"}}}
-- Job -------------------------------------------------------------------
function load_job(sj, gname, type, squad, groups)
    local g = gulags[type]
    if g then
        g.job(sj, gname, type, squad, groups)
    end
end

-- State -----------------------------------------------------------------
function check_state_stub(gulag)
    return 0
end

function load_states(gname, type)
    local g = gulags[type]

    if g then
        return g.state or check_state_stub
    end

    return nil
end
        
-- Dynamic ltx -----------------------------------------------------------
function load_ltx(gname, type)
    local g = gulags[type]
    if g then
        return g.ltx
    end

    return nil
end

-- Check communities -----------------------------------------------------
local function checkCommon(npc_community, gulag_type, npc_rank, se_obj, stalker)
    local g = gulags[gulag_type]
    if g then
        if g.comm then
            if type(g.comm) == "function" then
                return g.comm(npc_community, gulag_type, npc_rank, se_obj, stalker)
            end
            if type(g.comm) == "boolean" then
                return g.comm == stalker
            end

            local i, v = 0, 0
            for i, v in pairs(g.comm) do
                if npc_community == v then
                    return true
                end
            end
            if i > 0 then
                return false
            end
        end
        return true
    end
    return false
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)
   -- return checkCommon(npc_community, gulag_type, npc_rank, se_obj, true)
	if gulag_type == "val_lager_bandits" then
		return npc_community == "bandit"
	end
	return false
end

function checkMonster(npc_community, gulag_type, npc_rank, se_obj)
    return false
end


--------------------------------------------------------------------------
-- Gulags
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- Bandits („Î‡‚Ì‡ˇ ·‡Á‡ ·‡Ì‰ËÚÓ‚)
--------------------------------------------------------------------------
-- Predicates ------------------------------------------------------------
function lb_predicate1(npc_info) 
    return npc_info.profile_name == "val_bandit_borov"
end

function lb_predicate_bg(npc_info) 
    return npc_info.profile_name == "val_bandit_bodyguard"
end

function lb_predicate2(npc_info) 
    return npc_info.profile_name == "val_bandit_veteran"
end

function lb_predicate3(npc_info) 
    return npc_info.profile_name == "val_bandit_general"
end

-- Jobs ------------------------------------------------------------------
gulags.val_lager_bandits.job = function(sj, gname, type, squad, groups)
    local i, v, j = 0, 0, 0
    local restr = 0
    local ltx = ""
    --local combat_ignore = "combat_ignore_cond = {=val_bandits_ci}\n"
    --local combat_ignore = "combat_ignore_cond = {=check_fighting(400) -val_escort_captive_enemy}, {=check_fighting(401) -val_sacrifice_finish}, {=check_fighting(402) -val_prisoner_free}\n"
    local combat_ignore = "{=check_fighting(400) -val_escort_captive_enemy}, {=check_fighting(401) -val_sacrifice_finish}, {=check_fighting(402) -val_prisoner_free}\n"

    -- ¡Œ–Œ¬
    t = { section = "logic@" .. gname .. "_leader_normal",
        idle = 0,
		position_threshold = "graph",
        prior = 9, state = {state_normal},
        squad = squad, group = groups[1],
        online = "{+val_lager_bandits_show_leader_company}",
        in_rest    = "",
        out_rest   = gname .. "_borov_restrictor",
        predicate  = lb_predicate1
    }
    table.insert(sj, t)

    t = { section = "logic@" .. gname .. "_leader_alarm",
        idle = 0,
		position_threshold = "graph",
        prior = 9, state = {state_alarm},
        squad = squad, group = groups[1],
        online = "{+val_lager_bandits_show_leader_company}",
        in_rest    = "",
        out_rest   = gname .. "_borov_restrictor",
        predicate  = lb_predicate1
    }
    table.insert(sj, t)

    t = { section = "logic@" .. gname .. "_leader_alarm",
        idle = 0,
		position_threshold = "graph",
        prior = 9, state = {state_alarm_actor_inside},
        squad = squad, group = groups[1],
        online = "{+val_lager_bandits_show_leader_company}",
        in_rest    = "",
        out_rest   = gname .. "_borov_restrictor",
        predicate  = lb_predicate1
    }
    table.insert(sj, t)

    ltx = ltx.."[logic@" .. gname .. "_leader_normal]\n" ..
               "active = walker@" .. gname .. "_leader_normal\n" ..
               "on_death = death@" .. gname .. "_borov\n" ..
               "combat_ignore = combat_ignore\n" ..

               "[death@" .. gname .. "_borov]\n" ..
               "on_info = %+val_borov_dead%\n" ..

               "[walker@" .. gname .. "_leader_normal]\n" ..
               "path_walk = leader_walk\n" ..
               "path_look = leader_look\n" ..
               --"show_spot = false\n" ..
               "combat_ignore_cond = " .. combat_ignore ..

               "[logic@" .. gname .. "_leader_alarm]\n" ..
               "active = camper@" .. gname .. "_leader_alarm\n" ..
               "combat_ignore = combat_ignore\n" ..

               "[camper@" .. gname .. "_leader_alarm]\n" ..
               "path_walk = leader_alarm_walk\n" ..
               "path_look = leader_alarm_look\n" ..
               "radius    = 15\n" ..
               --"show_spot = false\n" ..
               "combat_ignore_cond = " .. combat_ignore

    -- Œ’–¿ÕÕ» » ¡Œ–Œ¬¿
    for i = 1, 3 do
        t = { section = "logic@" .. gname .. "_bodyguard_normal" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 8, state = {state_normal},
            squad = squad, group = groups[1],
            online = "{+val_lager_bandits_show_leader_company}",
            in_rest    = "",
            out_rest   = gname .. "_main_building_restrictor",
            predicate  = lb_predicate_bg
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_bodyguard_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 8, state = {state_alarm},
            squad = squad, group = groups[1],
            online = "{+val_lager_bandits_show_leader_company}",
            in_rest    = "",
            out_rest   = gname .. "_main_building_restrictor",
            predicate  = lb_predicate_bg
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_bodyguard_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 8, state = {state_alarm_actor_inside},
            squad = squad, group = groups[1],
            online = "{+val_lager_bandits_show_leader_company}",
            in_rest    = "",
            out_rest   = gname .. "_main_building_restrictor",
            predicate  = lb_predicate_bg
        }
        table.insert(sj, t)

        ltx = ltx.."[logic@" .. gname .. "_bodyguard_normal" .. i .. "]\n" ..
                   "active = walker@" .. gname .. "_bodyguard_normal" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..

                   "[walker@" .. gname .. "_bodyguard_normal" .. i .. "]\n" ..
                   "path_walk = bodyguard_walk" .. i .. "\n" ..
                   "path_look = bodyguard_look" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore ..

                   "[logic@" .. gname .. "_bodyguard_alarm" .. i .. "]\n" ..
                   "active = camper@" .. gname .. "_bodyguard_alarm" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..

                   "[camper@" .. gname .. "_bodyguard_alarm" .. i .. "]\n" ..
                   "path_walk = bodyguard_alarm_walk" .. i .. "\n" ..
                   "path_look = bodyguard_alarm_look" .. i .. "\n" ..
                   "radius = 10\n" ..
                   "combat_ignore_cond = " .. combat_ignore
    end

    -- —»ƒﬂŸ»≈ ¬  ≈Ãœ≈ 1 ¬Œ«À≈ ¡Œ–Œ¬¿ » ¬  ≈Ãœ≈ 2 Õ¿ ¬“Œ–ŒÃ ›“¿∆≈
    restr = {gname .. "_main_building_restrictor", gname .. "_nedostroyka_restrictor", gname .. "_nedostroyka_restrictor", gname .. "_restrictor"}
    onlineid = {"{+val_lager_bandits_show_leader_company}", "{+val_lager_bandits_show_nedostroyka_company}", "{+val_lager_bandits_show_nedostroyka_company}"}
    local pr = {7, 5, 5, 2}
    for i, v in pairs({3, 4, 2, 3}) do
        ltx = ltx.."[logic@" .. gname .. "_kamp" .. i .. "_normal]\n" ..
                   "active = kamp@" .. gname .. "_kamp" .. i .. "_normal\n" ..
                   "combat_ignore = combat_ignore\n" ..

                   "[kamp@" .. gname .. "_kamp" .. i .. "_normal]\n" ..
                   "center_point = kamp" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore

        for j = 1, v do
            t = { section = "logic@" .. gname .. "_kamp" .. i .. "_normal",
                idle = 0,
				position_threshold = "graph",
                prior = pr[i], state = {state_normal},
                squad = squad, group = groups[i],
                online = onlineid[i],
                in_rest = "", out_rest = restr[i]
            }
            table.insert(sj, t)

            t = { section = "logic@" .. gname .. "_kamp" .. i .. "_alarm" .. j,
                idle = 0,
				position_threshold = "graph",
                prior = pr[i], state = {state_alarm},
                squad = squad, group = groups[i],
                online = onlineid[i],
                in_rest = "", out_rest = restr[i]
            }
            table.insert(sj, t)

            t = { section = "logic@" .. gname .. "_kamp" .. i .. "_alarm" .. j,
                idle = 0,
				position_threshold = "graph",
                prior = 7, state = {state_alarm_actor_inside},
                squad = squad, group = groups[i],
                online = onlineid[i],
                in_rest = "", out_rest = restr[i]
            }
            table.insert(sj, t)

            ltx = ltx.."[logic@" .. gname .. "_kamp" .. i .. "_alarm" .. j .. "]\n" ..
                       "active = camper@" .. gname .. "_kamp" .. i .. "_alarm" .. j .. "\n" ..
                       "combat_ignore = combat_ignore\n" ..

                       "[camper@" .. gname .. "_kamp" .. i .. "_alarm" .. j .. "]\n" ..
                       "path_walk = kamp" .. i .. "_alarm_walk" .. j .. "\n" ..
                       "path_look = kamp" .. i .. "_alarm_look" .. j .. "\n" ..
                       "def_state_moving = assault\n" ..
                       "radius = 8\n" ..
                       --"combat_ignore_cond = {=val_bandits_ci_actor(35)}\n"
                       "combat_ignore_cond = {=fighting_actor =dist_to_actor_ge(35)}, " .. combat_ignore
        end
    end

    -- ¡¿Õƒ»“€
    local quantity = {2, 4, 1, 4}

    -- guards
    restr = {gname .. "_main_side_restrictor", gname .. "_restrictor"}
    for i = 1, quantity[1] do
        t = { section = "logic@" .. gname .. "_guard_normal" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 6, state = {state_normal},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_guard_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_alarm},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_guard_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_alarm_actor_inside},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        ltx = ltx.."[logic@" .. gname .. "_guard_normal" .. i .. "]\n" ..
                   "active = walker@" .. gname .. "_guard_normal" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..

                   "[walker@" .. gname .. "_guard_normal" .. i .. "]\n" ..
                   "path_walk = guard_walk" .. i .. "\n" ..
                   "path_look = guard_look" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore ..

                   "[logic@" .. gname .. "_guard_alarm" .. i .. "]\n" ..
                   "active = walker@" .. gname .. "_guard_alarm" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..
                   
                   "[walker@" .. gname .. "_guard_alarm" .. i .. "]\n" ..
                   "path_walk = guard_alarm_walk" .. i .. "\n" ..
                   "path_look = guard_alarm_look" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore
    end

    -- patrols
    restr = {gname .. "_main_side_restrictor", gname .. "_restrictor", gname .. "_restrictor", gname .. "_restrictor"}
    for i = 1, quantity[2] do
        t = { section = "logic@" .. gname .. "_patrol_normal" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 5, state = {state_normal},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_patrol_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_alarm},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_patrol_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_alarm_actor_inside},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        ltx = ltx.."[logic@" .. gname .. "_patrol_normal" .. i .. "]\n" ..
                   "active = walker@" .. gname .. "_patrol_normal" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..
                    
                   "[walker@" .. gname .. "_patrol_normal" .. i .. "]\n" ..
                   "path_walk = patrol_walk" .. i .. "\n" ..
                   "path_look = patrol_look" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore ..
                    
                   "[logic@" .. gname .. "_patrol_alarm" .. i .. "]\n" ..
                   "active = walker@" .. gname .. "_patrol_alarm" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..
                    
                   "[walker@" .. gname .. "_patrol_alarm" .. i .. "]\n" ..
                   "path_walk = patrol_alarm_walk" .. i .. "\n" ..
                   "path_look = patrol_alarm_look" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore
    end

    -- snipers
    restr = {gname .. "_restrictor"}
    for i = 1, quantity[3] do
        t = { section = "logic@" .. gname .. "_sniper_normal" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 4, state = {state_normal},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_sniper_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 4, state = {state_alarm},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_sniper_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_alarm_actor_inside},
            squad = squad, group = groups[1],
            in_rest = "", out_rest = restr[i]
        }
        table.insert(sj, t)

        ltx = ltx.."[logic@" .. gname .. "_sniper_normal" .. i .. "]\n" ..
                   "active = camper@" .. gname .. "_sniper_normal" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..

                   "[camper@" .. gname .. "_sniper_normal" .. i .. "]\n" ..
                   "path_walk = sniper_walk" .. i .. "\n" ..
                   "path_look = sniper_look" .. i .. "\n" ..
                   "def_state_moving = patrol\n" ..
                   "def_state_moving_fire = patrol_fire\n" ..
                   "def_state_campering = guard\n" ..
                   "def_state_campering_fire = guard_fire\n" ..
                   "combat_ignore_cond = " .. combat_ignore ..

                   "[logic@" .. gname .. "_sniper_alarm" .. i .. "]\n" ..
                   "active = camper@" .. gname .. "_sniper_alarm" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..

                   "[camper@" .. gname .. "_sniper_alarm" .. i .. "]\n" ..
                   "path_walk = sniper_alarm_walk" .. i .. "\n" ..
                   "path_look = sniper_alarm_look" .. i .. "\n" ..
                   "def_state_moving = sneak\n" ..
                   "def_state_moving_fire = sneak_fire\n" ..
                   "def_state_campering = threat\n" ..
                   "def_state_campering_fire = threat_sniper_fire\n" ..
                   "sniper = true\n" ..
                   --"combat_ignore_cond = {=val_bandits_ci_actor(35)}\n"
                   "combat_ignore_cond = {=fighting_actor =dist_to_actor_ge(35)}, " .. combat_ignore
    end

    -- sleepers
    for i = 1, quantity[4] do
        t = { section = "logic@" .. gname .. "_sleeper_normal" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_normal},
            squad = squad, group = groups[2],
            online = "{+val_lager_bandits_show_nedostroyka_company}",
            in_rest = "", out_rest = gname .. "_nedostroyka_restrictor", --info_restr = gname .. "_nedostroyka_info_restr"
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_sleeper_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 3, state = {state_alarm},
            squad = squad, group = groups[2],
            online = "{+val_lager_bandits_show_nedostroyka_company}",
            in_rest = "", out_rest = gname .. "_nedostroyka_restrictor", --info_restr = gname .. "_nedostroyka_info_restr"
        }
        table.insert(sj, t)

        t = { section = "logic@" .. gname .. "_sleeper_alarm" .. i,
            idle = 0,
			position_threshold = "graph",
            prior = 6, state = {state_alarm_actor_inside},
            squad = squad, group = groups[2],
            online = "{+val_lager_bandits_show_nedostroyka_company}",
            in_rest = "", out_rest = gname .. "_nedostroyka_restrictor", --info_restr = gname .. "_nedostroyka_info_restr"
        }
        table.insert(sj, t)

        ltx = ltx.."[logic@" .. gname .. "_sleeper_normal" .. i .. "]\n" ..
                   "active = sleeper@" .. gname .. "_sleeper_normal" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..
                    
                   "[sleeper@" .. gname .. "_sleeper_normal" .. i .. "]\n" ..
                   "path_main = sleeper" .. i .. "\n" ..
                   "combat_ignore_cond = " .. combat_ignore ..
                    
                   "[logic@" .. gname .. "_sleeper_alarm" .. i .. "]\n" ..
                   "active = camper@" .. gname .. "_sleeper_alarm" .. i .. "\n" ..
                   "combat_ignore = combat_ignore\n" ..
                    
                   "[camper@" .. gname .. "_sleeper_alarm" .. i .. "]\n" ..
                   "path_walk = sleeper_alarm_walk" .. i .. "\n" ..
                   "path_look = sleeper_alarm_look" .. i .. "\n" ..
                   "def_state_moving = assault\n" ..
                   "radius = 8\n" ..
                   --"combat_ignore_cond = {=val_bandits_ci_actor(30)}\n"
                   "combat_ignore_cond = {=fighting_actor =dist_to_actor_ge(30)}, " .. combat_ignore
    end

    --ltx = ltx.."#include \"misc\\gulag_dark_valley.ltx\"\n"

    gulags.val_lager_bandits.ltx = ltx
end

-- States ----------------------------------------------------------------
gulags.val_lager_bandits.state = function(gulag)
    if (gulag.state == state_alarm or gulag.state == state_alarm_actor_inside) and
        game.get_game_time():diffSec(gulag.stateBegin) < 12000 -- 20 minutes
    then
        return gulag.state
    else
        for k,v in pairs(gulag.Object) do
            if v ~= true then
                local enemy = v:best_enemy()
                if enemy ~= nil then
                    local enemy_type = get_clsid(enemy)
                    if enemy_type == clsid.actor and
                        utils.npc_in_zone(db.actor, db.zone_by_name["val_lager_bandits_restrictor"]) then
                        printf("gulag <val_lager_bandits>: STATE ALARM ACTOR")
                        return state_alarm_actor_inside
                    end
                    if enemy_type == clsid.actor or enemy_type == clsid.script_stalker then --or enemy_type == clsid.trader
                        printf("gulag <val_lager_bandits>: STATE ALARM")
                        return state_alarm
                    end
                end
            end
        end
    end
    
    printf("gulag <val_lager_bandits>: STATE NORMAL")
    return state_normal
end
