-- отключил мусор из ТЧ / HF 09/02

local level_scripts = {
	olr_tasks
}

function proceed()
	if db.actor == nil then
		return
	end
	for k, v in pairs(level_scripts) do
		v.proceed()
	end
end

function process_info_portion(info_id)
	if db.actor == nil then
		return
	end
	for k, v in pairs(level_scripts) do
		if v.process_info_portion(info_id) then
			return
		end
	end
end

function add_location(sid, location, hint)
	local sim = alife()
	if sim then
		local obj = sim:story_object(sid)

		if obj then
			if hint then
				level.map_add_object_spot(obj.id, location, hint)
			else
				level.map_add_object_spot(obj.id, location, "")
			end
		end
	end
end

function remove_location(sid, location)
	local sim = alife()
	if sim then
		local obj = sim:story_object(sid)
		if obj and level.map_has_object_spot(obj.id, location) then
			level.map_remove_object_spot(obj.id, location)
		end
	end
end

function remove_location_safe(sid, location)
	local sim = alife()
	if sim then
		local obj = sim:story_object(sid)
		if obj then
			for a = 1, level.map_has_object_spot(obj.id, location), 1 do
				level.map_remove_object_spot(obj.id, location)
			end
		end
	end
end

function is_map_spot_present(sid, location)
	local sim = alife()
	if sim then
		local obj = sim:story_object(sid)
		if obj and level.map_has_object_spot(obj.id, location) ~= 0 then
			return true
		end
	end
	return false
end

function set_lchanger_mapspot(obj, hint, spot)
	if obj then
		if spot == nil then
			spot = ""
		end
		local spot_out = "level_changer"..spot
		local obj_id = obj.id
		local ce_obj = level.object_by_id(obj_id)
		if ce_obj then
			if level.map_has_object_spot(obj_id, spot_out) == 0 then
				level.map_add_object_spot(obj_id, spot_out, hint)
			end
			if not ce_obj:is_level_changer_enabled() then
				ce_obj:enable_level_changer(true)
				ce_obj:set_level_changer_invitation("level_changer_invitation_enabled")
			end
		else
			if level.map_has_object_spot(obj_id, spot_out) == 0 then
				level.map_add_object_spot(obj_id, spot_out, hint)
			end
		end
	end
end

function del_lchanger_mapspot(sid)
	local ce_obj = level_object_by_sid(sid)
	if ce_obj then
		local spot = "level_changer"
		if level.map_has_object_spot(ce_obj:id(), spot) ~= 0 then
			level.map_remove_object_spot(ce_obj:id(), spot)
		end
	end
end

function add_lchanger_location()
	if not alife() then
		return
	end
	--log1("upd add_lchanger_location")
	local sim = alife()
	if sim then
		-- escape
		local obj = sim:story_object(701)
		if obj then
			--and has_alife_info("kv_4_done_go_timer")
			set_lchanger_mapspot(obj, "l01_escape_level_changer", "_up")
		end

		-- garbage
		obj = sim:story_object(193)
		if obj and has_alife_info("gar_first") then
			set_lchanger_mapspot(obj, "l02_garbage_level_changer", "_down") -- to escape
		end
		obj = sim:story_object(191)
		if obj and has_alife_info("gar_first") then
			set_lchanger_mapspot(obj, "l02_garbage_level_changer_0002", "_left") -- to agroprom 1
		end
		obj = sim:story_object(192)
		if obj and has_alife_info("gar_first") then
			set_lchanger_mapspot(obj, "l02_garbage_level_changer_0000", "_left") -- to agroprom 2
		end
		obj = sim:story_object(194)
		if obj and has_alife_info("gar_first") then
			set_lchanger_mapspot(obj, "l02_garbage_level_changer_0003", "_up") -- to bar
		end
		obj = sim:story_object(196)
		if obj and has_alife_info("gar_first") then
			set_lchanger_mapspot(obj, "l02_garbage_level_changer_0004", "_right") -- to darkvalley 2
		end
		obj = sim:story_object(195)
		if obj and has_alife_info("gar_first") then
			set_lchanger_mapspot(obj, "l02_garbage_level_changer_0001", "_right") -- to darkvalley 1
		end

		-- agroprom
		obj = sim:story_object(391)
		if obj and has_alife_info("agr_first") then
			set_lchanger_mapspot(obj, "l03_agroprom_level_changer_0000", "_right") -- to garbage
		end

		obj = sim:story_object(392)
		if obj and has_alife_info("agr_first") then
			set_lchanger_mapspot(obj, "l03_agroprom_level_changer", "_right") -- to garbage
		end

		obj = sim:story_object(5432)
		if obj and has_alife_info("agr_first") then
			set_lchanger_mapspot(obj, "l03_agroprom_level_changer_0001", "_up") -- to yantar
		end

		--radar
		obj = sim:story_object(1007)
		if obj and has_alife_info("rad_first") then
			set_lchanger_mapspot(obj, "l10_radar_level_changer_0001", "_left")
		end

		obj = sim:story_object(1008)
		if obj and has_alife_info("rad_first") then
			set_lchanger_mapspot(obj, "l10_radar_level_changer", "_down")
		end

		obj = sim:story_object(1090)
		if obj and has_alife_info("rad_first") then
			set_lchanger_mapspot(obj, "l10_radar_level_changer_0000")
		end

		obj = sim:story_object(18035) --- to level 12
		if obj and has_alife_info("rad_first") and has_alife_info("aes_antenna_off_jaba_sms") then
			set_lchanger_mapspot(obj, "l10_radar_level_changer_0002", "_up")
		end

		--pripyat
		obj = sim:story_object(833)
		if obj and has_alife_info("prp_first") then
			set_lchanger_mapspot(obj, "l13_pripyat_level_changer", "_down")
		end

		obj = sim:story_object(832)
		if obj and has_alife_info("prp_first") then
			set_lchanger_mapspot(obj, "l13_pripyat_level_changer_0000", "_up")
		end

		obj = sim:story_object(834)
		if obj and has_alife_info("prp_first") and has_alife_info("aes_antenna_off_jaba_sms") then
			set_lchanger_mapspot(obj, "l13_pripyat_level_changer_0002", "_right")
		end

		--deadcity
		obj = sim:story_object(432)
		if obj and has_alife_info("dec_first") then
			set_lchanger_mapspot(obj, "l11_deadcity_level_changer_0001", "_down") -- to mill
		end

		obj = sim:story_object(433)
		if obj and has_alife_info("dec_first") then
			set_lchanger_mapspot(obj, "l11_deadcity_level_changer", "_left") -- to yan
		end
		
		obj = sim:story_object(3001)
		if obj and has_alife_info("dec_first") then
			set_lchanger_mapspot(obj, "from_dc_to_swamp", "_up") -- to swamps
		end		

		--generators
		obj = sim:story_object(829)
		if obj and has_alife_info("stan_first") then
			set_lchanger_mapspot(obj, "l15_generators_level_changer")
		end

		obj = sim:story_object(5480)
		if obj and has_alife_info("stan_first") then
			set_lchanger_mapspot(obj, "level_prefix_level_changer_glue")
		end

		-- yantar
		obj = sim:story_object(925)
		if obj and has_alife_info("yan_first") then
			set_lchanger_mapspot(obj, "l07_yantar_level_changer", "_right") -- to bar
		end
		obj = sim:story_object(18021)
		if obj and has_alife_info("yan_first") then
			set_lchanger_mapspot(obj, "l07_yantar_level_changer_0001", "_up") -- to swamps
		end
		obj = sim:story_object(5431)
		if obj and has_alife_info("yan_first") then
			set_lchanger_mapspot(obj, "l07_yantar_level_changer_0000", "_down") -- to agroprom
		end

		obj = sim:story_object(5430)
		if obj and has_alife_info("yan_first") then
			set_lchanger_mapspot(obj, "l07_yantar_level_changer_0002", "_right") -- to deadcity
		end

		--stancia
		obj = sim:story_object(5479)
		if obj and has_alife_info("stan_first") then
			set_lchanger_mapspot(obj, "l14_stancia_level_changer_0001")
		end

		obj = sim:story_object(5478)
		if obj and has_alife_info("stan_first") then
			set_lchanger_mapspot(obj, "l14_stancia_level_changer_0000")
		end

		obj = sim:story_object(5477)
		if obj and has_alife_info("stan_first") then
			set_lchanger_mapspot(obj, "l14_stancia_level_changer")
		end
		
		obj = sim:story_object(20006)
		if obj and has_alife_info("stan_first") then
			set_lchanger_mapspot(obj, "l14_stancia_level_changer_0002", "_down")
		end		

		--darkvalley
		obj = sim:story_object(416)
		if obj and has_alife_info("dol_first") then
			set_lchanger_mapspot(obj, "l04_darkvalley_level_changer_0001", "_left") -- to garbage
		end

		obj = sim:story_object(417)
		if obj and has_alife_info("dol_first") then
			set_lchanger_mapspot(obj, "l04_darkvalley_level_changer_0000", "_left") -- to garbage
		end

		--rostok
		obj = sim:story_object(591)
		if obj and has_alife_info("ros_first") then
			set_lchanger_mapspot(obj, "l06_rostok_level_changer")
		end
		
		obj = sim:story_object(20009)
		if obj and has_alife_info("ros_first") then
			set_lchanger_mapspot(obj, game.translate_string("st_spot_to_bar"))
		end		

		--bar
		obj = sim:story_object(592)
		if obj and has_alife_info("bar_first") then
			set_lchanger_mapspot(obj, "l05_bar_level_changer_0001", "_right") -- to military
		end

		obj = sim:story_object(593)
		if obj and has_alife_info("bar_first") then
			set_lchanger_mapspot(obj, "level_prefix_level_changer", "_down") -- to garbage
		end

		obj = sim:story_object(594)
		if obj and has_alife_info("bar_first") then
			set_lchanger_mapspot(obj, "l05_bar_level_changer")
		end

		obj = sim:story_object(706)
		if obj and has_alife_info("bar_first") then
			set_lchanger_mapspot(obj, "l05_bar_level_changer_0000", "_down") -- to yantar
		end
		
		obj = sim:story_object(20008)
		if obj and has_alife_info("bar_first") then
			set_lchanger_mapspot(obj, "l05_bar_level_changer_0002")
		end		

		--swamp

		obj = sim:story_object(18023)
		if obj and has_alife_info("swp_first") then
			set_lchanger_mapspot(obj, "l08_swamp_level_changer", "_right") -- to yantar
		end

		obj = sim:story_object(18020)
		if obj and has_alife_info("swp_first") then
			set_lchanger_mapspot(obj, "l08_swamp_level_changer_0000")
		end

		--military
		obj = sim:story_object(771)
		if obj and has_alife_info("mil_first") then
			set_lchanger_mapspot(obj, "lvl10_military_level_changer", "_left") -- to bar
		end
		obj = sim:story_object(772)
		if obj and has_alife_info("mil_first") then
			set_lchanger_mapspot(obj, "l09_military_level_changer_0000", "_left") -- to deadcity
		end

		obj = sim:story_object(773)
		if obj and has_alife_info("mil_first") then
			set_lchanger_mapspot(obj, "l09_military_level_changer", "_up") -- to radar
		end

		------------------------------------------------------------------------------------------------------------------------------------------------

		obj = sim:story_object(18032) --- to radar
		if obj and has_alife_info("lvl12_first") then
			set_lchanger_mapspot(obj, "level12_level_changer")
		end

		obj = sim:story_object(18033) --- to prip
		if obj and has_alife_info("lvl12_first") then
			set_lchanger_mapspot(obj, "level12_level_changer_0000")
		end

		obj = sim:story_object(18034) --- to chaes
		if obj and has_alife_info("lvl12_first") then
			set_lchanger_mapspot(obj, "level12_level_changer_0001")
		end
		
		-- underground 
		
		obj = sim:story_object(20005) --- to radar from bunker
		if obj then
			set_lchanger_mapspot(obj, "l09_military_level_changer")
		end			
		
		obj = sim:story_object(20007) --- from sar to aes
		if obj then
			set_lchanger_mapspot(obj, "level12_level_changer_0001")
		end		

		------------------------------------------------------------------------------------------------------------------------------------------------
	end
end

function set_task_state(id_state, id_task, id_subtask)
	if db.actor then
		db.actor:set_task_state(id_state, id_task, id_subtask)
	end
end

function notify_new_task()
end
