pda_news = xr_sound.get_safe_sound_object([[device\pda\pda_news]])
pda_tips = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
pda_task = xr_sound.get_safe_sound_object([[device\pda\pda_objective]])
pda_task_update = xr_sound.get_safe_sound_object([[device\pda\pda_objective]])
pda_sos = xr_sound.get_safe_sound_object([[device\pda\pda_sos]])

tips_icons = {
	act         	= { 100, 0},
	ohranik         = { 450, 0},
	default         = { 350, 150},
	item        	= { 400, 100},
	heli        	= { 150, 200},
	dok        		= { 350, 200},
	artefact        = { 50, 0},
	unknown         = { 100, 200},
	sos       		= { 100, 100},
	zombied       	= { 250, 150},
	flash       	= { 200, 100},
	medkit       	= { 250, 0},
	vagon       	= { 200, 0},
	military       	= { 250, 50},
	exo_neutral     = { 100, 150},
	bandits       	= { 50, 50},
	treasure       	= { 50, 200},
	af_merger       = { 350, 0},
	volna_plots     = { 400, 0},
	novice			= { 400, 150},
	trader			= { 50, 100},
	dolg			= { 150, 0},
	dolg_mask1		= { 150, 0},
	dolg_prapor		= { 150, 0},
	dolg_voronin	= { 150, 0},
	freedom			= { 0, 150},
	freedom_max		= { 150, 150},
	freedom_cap		= { 0, 150},
	freedom_lukash	= { 0, 150},
	freedom_bydlo	= { 0, 150},
	ecolog			= { 450, 100},
	ecolog_red		= { 450, 100},
	arena			= { 400, 150},
	stalker			= { 400, 150},
	krot			= { 200, 50},
	hellcar			= { 0, 50},
	barman			= { 400, 50},
	wolf			= { 0, 50},
	o_soznanie		= { 350, 50},
	monolith		= { 300, 150},
	saharov			= { 450, 150},
	prizrak			= { 350, 50},
	money			= { 450, 50},
	fanat			= { 400, 150},
	killer			= { 0, 200},
	killer_volkodav	= { 0, 200},
	new_task		= { 150, 100},	-- 486, 486 в фляроскриптах на старом атласе
	jaba			= { 0, 100},	-- 332,950 в фляроскриптах на старом атласе (жаба в зелёной рамке щас)
	kill_messer		= { 0, 0},		-- вообще не используется
	-- для амк типсов
	trade     = { 450, 50},
	uniq     =  {498, 47}, -- не используется, похуй, в АМК это был "общий канал"
	gen_info  = { 350, 150},
	death     = { 250, 200},	
}


function send_tip(actor, news_id, timeout, sender, showtime, sender_id, kostyl, show_tip_top, sender_name)
	if news_id == nil then return false end

	printf("try to send tips for [%s]", tostring(sender_id))
	if sender_id ~= nil then
		local sim = alife()
		if sim ~= nil then
			local npc = sim:story_object(sender_id)
			if npc ~= nil then
				if npc.online then
					--в онлайне проверяем на раненность
					if xr_wounded.is_heavy_wounded_by_id(npc.id) then
						printf("[PDA]Cannot send tips [%s], sender is heavy wounded", tostring(news_id))
						return false
					end
				end
				-- в других случаях только на смерть
				if npc:alive() == 1 then
					printf("[PDA]Cannot send tips [%s], sender is dead", tostring(news_id))
					return false
				end
			end
		end
	end

    -- Настройка параметров по умолчанию
    timeout = timeout or 0
    showtime = showtime or 5000
    sender = sender or "default"
	show_tip_top = (show_tip_top ~= false)

	-- Играем дефолтный звук или костыльно другой звук
	local sound_map = {
		pda_news = pda_news,
		pda_tip = pda_tips,
		pda_objective = pda_task,
		pda_sos = pda_sos
	}
	
    -- Определение задержки (в миллисекундах)
    local timeout_msg
	local timeout_snd = timeout
    if timeout >= 100 then
        -- Если timeout уже в миллисекундах (>=100), используем как есть
        timeout_msg = timeout
		timeout_snd = timeout / 1000 -- переводим из мс в сек
    else
        -- Иначе конвертируем секунды в миллисекунды
        timeout_msg = timeout * 1000
    end		

	local sound_to_play = sound_map[kostyl] or pda_tips
	sound_to_play:play(db.actor, timeout_snd, sound_object.s2d)
	
	if sender == nil then
		sender = "default"
	end
	local x = tips_icons[sender][1]
	local y = tips_icons[sender][2]
	
	-- Определение текста сообщения в зависимости от show_tip_top
	local news_text
	if show_tip_top ~= false then
		news_text = "%c[255,160,181,169]"..game.translate_string("st_tip")..":".."\\n".."%c[255,245,240,218]"..game.translate_string(news_id)
	else
		news_text = "%c[255,255,255,255]"..game.translate_string(news_id) -- для сообщений где всё сформировано в одну строку
	end
	
	if sender_name then
		actor:give_game_news(news_text, game.translate_string(sender_name), "ui\\icons\\icons_task", Frect():set(x,y,50,50), timeout_msg, showtime)
	else
		actor:give_game_news(news_text, "", "ui\\icons\\icons_task", Frect():set(x,y,50,50), timeout_msg, showtime)
	end
	
	return true
end

local news = {} -- тут должны хранится специальные саунды озвучки, в тч это всякие звуковые сообщения.
				-- например сообщение Сидоровича про аномалии или коды от дверей в лабах

function send_tip_nosound(actor, news_id, timeout, sender) -- хоть эта функция и не используется в олр сделаю чтоб всё работало как надо
	if news_id == nil then return end
	timeout = 0
	-- Играем дефолтный звук
	pda_tips:play(db.actor, timeout, sound_object.s2d)
	local news_sound = news[news_id]
	return news_sound
end

local action_descr_by_type = {
	new = "general_new_task",
	update = "general_update_task",
	complete = "general_complete_task",
	fail = "general_fail_task"
}

function send_task(actor, type, task, objective)
	if db.actor == nil then return false end
	
	-- Берем координаты из текстуры таска
    	local task_texture, task_rect = get_texture_info("ui_iconsTotal_"..task:get_id(), "ui_iconsTotal_update_task")

	local news_text = "%c[255,160,181,169]"..game.translate_string(action_descr_by_type[type]).."\\n".."%c[default]"..game.translate_string(task:get_title())
	local news_text_static = ""..game.translate_string(action_descr_by_type[type]).." "..game.translate_string(task:get_title())

	if type == "new" then

		--local STbron = db.actor:object("device_pda")
		--if STbron:condition() <= 0.05 then 
		--	STbron:set_condition(STbron:condition() + 0.05)
		--end

		local task_texture_new, task_rect = get_texture_info("ui_iconsTotal_"..task:get_id(), "ui_iconsTotal_new_task")	
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture_new, task_rect,"iconed_answer_item")
			if task:get_objectives_cnt() == objective:get_idx()+1 then
				return
			end
			news_text = game.translate_string(task:get_objective(objective:get_idx() + 1):get_description())
		end
		local hud = get_hud()
		local text = ""..news_text_static..""
		hud:AddCustomStatic("job_task", true)
		hud:GetCustomStatic("job_task"):wnd():SetTextST(text)
		hud:GetCustomStatic("job_task").m_endTime = time_global()/1000 + 8
		pda_task:play(db.actor, 0, sound_object.s2d)

	elseif type == "complete" then
		pda_tips:play(db.actor, 0, sound_object.s2d)
	end

	if type == "new" or type == "update" or type == "complete" then
		if not olr_timers.has_timer("autosave_quest") then
			olr_timers.st_timer("autosave_quest", 3, "nick.autosave_quest()")
		end
	end

	if type == "update" or type == "complete" then
		if db.actor:is_talking() then	
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end	
		pda_task_update:play(db.actor, 0, sound_object.s2d)
	end


	if type == "new" then
		xvars.quests_started = xvars.quests_started + 1
	end

end

function send_encyclopedy(type, title)
	if type == "Diary" then
		pda_news:play(db.actor, 0, sound_object.s2d)
		-- Берем координаты из текстуры таска
		local task_texture, task_rect = get_texture_info("ui_iconsTotal_pda_info")
		local news_text = "%c[255,160,181,169]"..game.translate_string("st_found_another_pda").."\\n".."%c[default]"..game.translate_string(title)
		if db.actor:is_talking() then	
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end	
	end
end

function get_inv_name(section)
	return system_ini():r_string(section,"inv_name")
end

function relocate_item(actor, type, item)
	if db.actor == nil then return false end
	-- Играем дефолтный звук
	if type == "in" then
		local task_texture, task_rect = get_texture_info("ui_iconsTotal_found_thing")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_in_item").."\\n".."%c[default]"..game.translate_string(get_inv_name(item))		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	elseif type == "out" then
		local task_texture, task_rect = get_texture_info("ui_iconsTotal_lost_thing")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_out_item").."\\n".."%c[default]"..game.translate_string(get_inv_name(item))		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	end
	
end

function relocate_money(actor, type, amount)
	if db.actor == nil then return false end
	-- Играем дефолтный звук
	if type == "in" then
		local task_texture, task_rect = get_texture_info("ui_iconsTotal_found_money")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_in_money").."\\n".."%c[default]"..game.translate_string(tostring(amount))
		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	elseif type == "out" then
		local task_texture, task_rect = get_texture_info("ui_iconsTotal_lost_money")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_out_money").."\\n".."%c[default]"..game.translate_string(tostring(amount))
		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	end
	
end