

 level_name = {}
 community_name = {}
 rate_name = {}
 monster_classes = {}
 anomaly_classes = {}
 rate_prefix = {}
 rate_postfix = {}
 monster_prefix = {}
 monster_suffix = {}
 weapon_classes = {}
 common = {}
 seen_prefix = {}
 spawn_prefix = {}
 anomaly_prefix = {}
 anomaly_postfix = {}

function Init()
--
end

-- Добавить список вариантов для text, text0
-- Добавить радиус для text0
base_points = {
     ["l01_escape"] = {
          [1] = { name = "st_news_manager_data_esc_1_1", text = "st_news_manager_data_esc_1_2", text0 = "st_news_manager_data_esc_1_3", p = {-10, 4.35, 107 } },
          [2] = { name = "st_news_manager_data_esc_2_1", text = "st_news_manager_data_esc_2_2", text0 = "st_news_manager_data_esc_2_3", p = {-52, 0.91, 226.39 } },
          [3] = { name = "st_news_manager_data_esc_3_1", text = "st_news_manager_data_esc_3_2", text0 = "st_news_manager_data_esc_3_3", p = {127, -0.35, -27} },
          [4] = { name = "st_news_manager_data_esc_4_1", text = "st_news_manager_data_esc_4_2", text0 = "st_news_manager_data_esc_4_3", p = {55.13, -0.32, 160.36} },
          [5] = { name = "st_news_manager_data_esc_5_1", text = "st_news_manager_data_esc_5_2", text0 = "st_news_manager_data_esc_5_3", p = {-155.74, -29.49, -355.21} },
          [6] = { name = "st_news_manager_data_esc_6_1", text = "st_news_manager_data_esc_6_2", text0 = "st_news_manager_data_esc_6_3", p = {14.08, 17.45, 673.28} },
          [7] = { name = "st_news_manager_data_esc_7_1", text = "st_news_manager_data_esc_7_2", text0 = "st_news_manager_data_esc_7_3", p = {-215.57, -7.49, -135.71} }
     },
     ["l02_garbage"] = {
          [1] = { name = "st_news_manager_data_gar_1_1", text = "st_news_manager_data_gar_1_2", text0 = "st_news_manager_data_gar_1_3", p = {-41.43, 3.78, 269.83} },
          [2] = { name = "st_news_manager_data_gar_2_1", text = "st_news_manager_data_gar_2_2", text0 = "st_news_manager_data_gar_2_3", p = {4.32, 30.21, 31.70} },
          [3] = { name = "st_news_manager_data_gar_3_1", text = "st_news_manager_data_gar_3_2", text0 = "st_news_manager_data_gar_3_3", p = {116.81, 5.74, 155.74} },
          [4] = { name = "st_news_manager_data_gar_4_1", text = "st_news_manager_data_gar_4_2", text0 = "st_news_manager_data_gar_4_3", p = {37.86, 22.75, -143.29} },
          [5] = { name = "st_news_manager_data_gar_5_1", text = "st_news_manager_data_gar_5_2", text0 ="st_news_manager_data_gar_5_3", p = {91.58, 6.84, 500.29} },
          [6] = { name = "st_news_manager_data_gar_6_1", text = "st_news_manager_data_gar_6_2", text0 = "st_news_manager_data_gar_6_3", p = {148.68, 2.29, 15.92 } }
     },
     ["l03_agroprom"] = {
          [1] = { name = "st_news_manager_data_agr_1_1", text = "st_news_manager_data_agr_1_2", text0 = "st_news_manager_data_agr_1_3", p = {5.16, 0.00, 9.80} },
          [2] = { name = "st_news_manager_data_agr_2_1", text = "st_news_manager_data_agr_2_2", text0 = "st_news_manager_data_agr_2_3", p = {-181.84, 2.99, 70.09} },
          [3] = { name = "st_news_manager_data_agr_3_1", text = "st_news_manager_data_agr_3_2", text0 = "st_news_manager_data_agr_3_3", p = {-138.95, -0.21, -182.71} },
          [4] = { name = "st_news_manager_data_agr_4_1", text = "st_news_manager_data_agr_4_2", text0 = "st_news_manager_data_agr_4_3", p = {183.79, 0.26, -236.51} },
          [5] = { name = "st_news_manager_data_agr_5_1", text = "st_news_manager_data_agr_5_2", text0 = "st_news_manager_data_agr_5_3", p = {187.12, -0.20, 45.23} }     
     },
     ["l04_darkvalley"] = {
          [1] = { name = "st_news_manager_data_dar_1_1", text = "st_news_manager_data_dar_1_2", text0 = "st_news_manager_data_dar_1_3", p = {90.69, 2.80, 231.05} },
          [2] = { name = "st_news_manager_data_dar_2_1", text = "st_news_manager_data_dar_2_2", text0 = "st_news_manager_data_dar_2_3", p = {-174.09, 3.05, 125.35} },
          [3] = { name = "st_news_manager_data_dar_3_1", text = "st_news_manager_data_dar_3_2", text0 = "st_news_manager_data_dar_3_3", p = {-118.19, 2.41, -172.89} },
          [4] = { name = "st_news_manager_data_dar_4_1", text = "st_news_manager_data_dar_4_2", text0 = "st_news_manager_data_dar_4_3", p = {38.22, 3.61, 26.06} },
          [5] = { name = "st_news_manager_data_dar_5_1", text = "st_news_manager_data_dar_5_2", text0 = "st_news_manager_data_dar_5_3", p = {-186.91, 3.34, -211.37} },
          [6] = { name = "st_news_manager_data_dar_6_1", text = "st_news_manager_data_dar_6_2", text0 = "st_news_manager_data_dar_6_3", p = {69.87, -6.94, 128.07} },
     },                
     ["l05_bar"] = {
          [1] = { name = "st_news_manager_data_bar_1_1", text = "st_news_manager_data_bar_1_2", text0 = "st_news_manager_data_bar_1_3", p = {180.99, -87.32, -270.64} },
          [2] = { name = "st_news_manager_data_bar_2_1", text = "st_news_manager_data_bar_2_2", text0 = "st_news_manager_data_bar_2_3", p = {68.84, -91.94, -248.97} },
          [3] = { name = "st_news_manager_data_bar_3_1", text = "st_news_manager_data_bar_3_2", text0 = "st_news_manager_data_bar_3_3", p = {113.36, -87.76, -118.96} },
          [4] = { name = "st_news_manager_data_bar_4_1", text = "st_news_manager_data_bar_4_2", text0 = "st_news_manager_data_bar_4_3", p = {-335.53, -81.88, -154.77} },
          [5] = { name = "st_news_manager_data_bar_5_1", text = "st_news_manager_data_bar_5_2", text0 = "st_news_manager_data_bar_5_3", p = {-75.90, -91.29, -235.26} }
     },
     ["l06_rostok"] = {
          [1] = { name = "st_news_manager_data_ros_1_1", text = "st_news_manager_data_ros_1_2", text0 = "st_news_manager_data_ros_1_3", p = {-167.68, -36.00, -111.16} },
          [2] = { name = "st_news_manager_data_ros_2_1", text = "st_news_manager_data_ros_2_2", text0 = "st_news_manager_data_ros_2_3", p = {-184.60, -35.94, 71.47} },
          [3] = { name = "st_news_manager_data_ros_3_1", text = "st_news_manager_data_ros_3_2", text0 = "st_news_manager_data_ros_3_3", p = {-42.71, -42.61, -50.33} },
          [4] = { name = "st_news_manager_data_ros_4_1", text = "st_news_manager_data_ros_4_2", text0 = "st_news_manager_data_ros_4_3", p = {47.79, -37.80, 14.10} }
     },
     ["l07_yantar"] = {
          [1] = { name = "st_news_manager_data_yan_1_1", text = "st_news_manager_data_yan_1_2", text0 = "st_news_manager_data_yan_1_3", p = {-180.01, 14.18, 182.08} },
          [2] = { name = "st_news_manager_data_yan_2_1", text = "st_news_manager_data_yan_2_2", text0 = "st_news_manager_data_yan_2_3", p = {34.12, 5.45, -157.11} },
          [3] = { name = "st_news_manager_data_yan_3_1", text = "st_news_manager_data_yan_3_2", text0 = "st_news_manager_data_yan_3_3", p = {74.80, 13.86, -38.20} },
          [4] = { name = "st_news_manager_data_yan_4_1", text = "st_news_manager_data_yan_4_2", text0 = "st_news_manager_data_yan_4_3", p = {-158.80, 4.86, -170.20} }
     },
     ["l08_swamp"] = {
          [1] = { name = "st_news_manager_data_mar_1_1", text = "st_news_manager_data_mar_1_2", text0 = "st_news_manager_data_mar_1_3", p = {214.01, 2.18, 66.08} },
          [2] = { name = "st_news_manager_data_mar_2_1", text = "st_news_manager_data_mar_2_2", text0 = "st_news_manager_data_mar_2_3", p = {66.12, 5.45, 68.11} }
     },
     ["l09_military"] = {         
          [1] = { name = "st_news_manager_data_mil_1_1", text = "st_news_manager_data_mil_1_2", text0 = "st_news_manager_data_mil_1_3", p = {-235.53, -11.48, 44.28} },
          [2] = { name = "st_news_manager_data_mil_2_1", text = "st_news_manager_data_mil_2_2", text0 = "st_news_manager_data_mil_2_3", p = {-7.72, -6.94, 2.05} },
          [3] = { name = "st_news_manager_data_mil_3_1", text = "st_news_manager_data_mil_3_2", text0 = "st_news_manager_data_mil_3_3", p = {-287.41, -21.61, 238.97} },
          [4] = { name = "st_news_manager_data_mil_4_1", text = "st_news_manager_data_mil_4_2", text0 = "st_news_manager_data_mil_4_3", p = {-344.72, -11.02, 389.12} },
          [5] = { name = "st_news_manager_data_mil_5_1", text = "st_news_manager_data_mil_5_2", text0 = "st_news_manager_data_mil_5_3", p = {53.84, -16.50, 365.99} },
          [6] = { name = "st_news_manager_data_mil_6_1", text = "st_news_manager_data_mil_6_2", text0 = "st_news_manager_data_mil_6_3", p = {102.94, -10.33, 165.34} },
          [7] = { name = "st_news_manager_data_mil_7_1", text = "st_news_manager_data_mil_7_2", text0 = "st_news_manager_data_mil_7_3", p = {-93.25, -19.23, 221.38} }
     },
     ["l10_radar"] = {
          [1] = { name = "st_news_manager_data_rad_1_1", text = "st_news_manager_data_rad_1_2", text0 = "st_news_manager_data_rad_1_3", p = {1.01, 3.18, -22.08} },
          [2] = { name = "st_news_manager_data_rad_2_1", text = "st_news_manager_data_rad_2_2", text0 = "st_news_manager_data_rad_2_3", p = {466.12, -45.45, -148.11} }
     },
     ["l11_deadcity"] = {
          [1] = { name = "st_news_manager_data_cit_1_1", text = "st_news_manager_data_cit_1_2", text0 = "st_news_manager_data_cit_1_3", p = { -204.966,-1.306,-164.434 } },
          [2] = { name = "st_news_manager_data_cit_2_1", text = "st_news_manager_data_cit_2_2", text0 = "st_news_manager_data_cit_2_3", p = { -259.180,-9.995,171.575 } },
          [3] = { name = "st_news_manager_data_cit_3_1", text = "st_news_manager_data_cit_3_2", text0 = "st_news_manager_data_cit_3_3", p = { -21.606,1.080,-118.720 } }
     }
}

levels = {	
"l01_escape", 
"l02_garbage", 
"l03_agroprom", 
"l04_darkvalley", 
"l05_bar", 
"l06_rostok", 
"l07_yantar", 
"l08_swamp", 
"l09_military", 
"l10_radar", 
"l11_deadcity", 
"l10u_bunker", 
"l13_pripyat", 
"l14_stancia", 
"l14u_sarcofag", 
"l15_generators", 
"l12_barrow_downs"
}

levels_types={
	l01_escape=0,
	l02_garbage=0,
	l03_agroprom=0,
	l04_darkvalley=0,
	l05_bar=0,
	l06_rostok=0,
	l07_yantar=0,
	l08_swamp=0,
	l09_military=0,
	l10_radar=0,
        l11_deadcity=0,
	l10u_bunker=1,
	l13_pripyat=0,
	l14_stancia=0,
	l14u_sarcofag=1,
	l15_generators=0,
	l12_barrow_downs=0,
}

level_name = {
	["l01_escape"] = {"st_news_manager_data_l01_escape_1", "st_news_manager_data_l01_escape_2"},
	["l02_garbage"] = {"st_news_manager_data_l02_garbage_1", "st_news_manager_data_l02_garbage_2"},
	["l03_agroprom"] = {"st_news_manager_data_l03_agroprom_1", "st_news_manager_data_l03_agroprom_2"},
	["l04_darkvalley"] = {"st_news_manager_data_l04_darkvalley_1", "st_news_manager_data_l04_darkvalley_2"},
	["l05_bar"] = {"st_news_manager_data_l05_bar_1", "st_news_manager_data_l05_bar_2"},
	["l06_rostok"] = {"st_news_manager_data_l06_rostok_1", "st_news_manager_data_l06_rostok_2"},
	["l07_yantar"] = {"st_news_manager_data_l07_yantar_1", "st_news_manager_data_l07_yantar_2"},
	["l08_swamp"] = {"st_news_manager_data_l08_swamp_1", "st_news_manager_data_l08_swamp_2"},
	["l09_military"] = {"st_news_manager_data_l09_military_1", "st_news_manager_data_l09_military_2"},
	["l10_radar"] = {"st_news_manager_data_l10_radar_1", "st_news_manager_data_l10_radar_2"},
	["l11_deadcity"] = {"st_news_manager_data_l11_deadcity_1", "st_news_manager_data_l11_deadcity_2"},
	["l10u_bunker"] = {"st_news_manager_data_l10u_bunker_1", "st_news_manager_data_l10u_bunker_2"},
	["l13_pripyat"] = {"st_news_manager_data_l13_pripyat_1", "st_news_manager_data_l13_pripyat_2"},
	["l14_stancia"] = {"st_news_manager_data_l14_stancia_1", "st_news_manager_data_l14_stancia_2"},
	["l14u_sarcofag"] = {"st_news_manager_data_l14u_sarcofag_1", "st_news_manager_data_l14u_sarcofag_2"},
	["l15_generators"] = {"st_news_manager_data_l15_generators_1", "st_news_manager_data_l15_generators_2"},
	["l12_barrow_downs"] = {"st_news_manager_data_l12_barrow_downs_1", "st_news_manager_data_l12_barrow_downs_2"}
}

community_name["stalker"] 	= {"st_news_manager_data_stalker_1","st_news_manager_data_stalker_2","st_news_manager_data_stalker_3", "st_news_manager_data_stalker_4"}
community_name["monolith"] 	={"st_news_manager_data_monolith_1","st_news_manager_data_monolith_2","st_news_manager_data_monolith_3", "st_news_manager_data_monolith_4"}
community_name["military"] 	= {"st_news_manager_data_military_1","st_news_manager_data_military_2","st_news_manager_data_military_3", "st_news_manager_data_military_4"}
community_name["killer"] 	= {"st_news_manager_data_killer_1","st_news_manager_data_killer_2","st_news_manager_data_killer_3", "st_news_manager_data_killer_4"}
community_name["ecolog"] 	= {"st_news_manager_data_ecolog_1","st_news_manager_data_ecolog_2","st_news_manager_data_ecolog_3", "st_news_manager_data_ecolog_4"}
community_name["dolg"] 		= {"st_news_manager_data_dolg_1","st_news_manager_data_dolg_2","st_news_manager_data_dolg_3", "st_news_manager_data_dolg_4"}
community_name["freedom"] 	= {"st_news_manager_data_freedom_1","st_news_manager_data_freedom_2","st_news_manager_data_freedom_3", "st_news_manager_data_freedom_4"}
community_name["bandit"] 	= {"st_news_manager_data_bandit_1","st_news_manager_data_bandit_2","st_news_manager_data_bandit_3", "st_news_manager_data_bandit_4"}
community_name["zombied"] 	= {"st_news_manager_data_zombied_1","st_news_manager_data_zombied_2","st_news_manager_data_zombied_3", "st_news_manager_data_zombied_4"}
community_name["sin"] 	        = {"st_news_manager_data_sin_1","st_news_manager_data_sin_2","st_news_manager_data_sin_3", "st_news_manager_data_sin_4"}
community_name["sky"] 	        = {"st_news_manager_data_sky_1","st_news_manager_data_sky_2","st_news_manager_data_sky_3", "st_news_manager_data_sky_4"}
community_name["sliznyaki"] 	= {"st_news_manager_data_sliznyaki_1","st_news_manager_data_sliznyaki_2","st_news_manager_data_sliznyaki_3", "st_news_manager_data_sliznyaki_4"}
community_name["deads"] 	= {"st_news_manager_data_deads_1","st_news_manager_data_deads_2","st_news_manager_data_deads_3", "st_news_manager_data_deads_4"}
community_name["voenstals"] 	= {"st_news_manager_data_voenstals_1","st_news_manager_data_voenstals_2","st_news_manager_data_voenstals_3", "st_news_manager_data_voenstals_4"}


rate_name["novice"] 		= {"st_news_manager_data_rate_novice_1", "st_news_manager_data_rate_novice_2", "st_news_manager_data_rate_novice_3", "st_news_manager_data_rate_novice_4", "st_news_manager_data_rate_novice_5"}
rate_name["experienced"] 	= {"st_news_manager_data_rate_experienced_1", "st_news_manager_data_rate_experienced_2", "st_news_manager_data_rate_experienced_3", "st_news_manager_data_rate_experienced_4"}
rate_name["veteran"] 		= {"st_news_manager_data_rate_veteran_1", "st_news_manager_data_rate_veteran_2", "st_news_manager_data_rate_veteran_3"}
rate_name["master"] 		= {"st_news_manager_data_rate_master_1", "st_news_manager_data_rate_master_2", "st_news_manager_data_rate_master_3", "st_news_manager_data_rate_master_4"}
rate_prefix 				= {"st_news_manager_data_rate_pref_1", "st_news_manager_data_rate_pref_2","st_news_manager_data_rate_pref_3", "st_news_manager_data_rate_pref_4", "st_news_manager_data_rate_pref_5", "st_news_manager_data_rate_pref_6", "st_news_manager_data_rate_pref_7"}
rate_postfix 				= {"st_news_manager_data_rate_post_1", "st_news_manager_data_rate_post_2", "st_news_manager_data_rate_post_3", "st_news_manager_data_rate_post_4", "st_news_manager_data_rate_post_5"}

common["sad_a"] 			= {"st_news_manager_data_sad_a_1", "st_news_manager_data_sad_a_2", "st_news_manager_data_sad_a_3", "st_news_manager_data_sad_a_4", "st_news_manager_data_sad_a_5", "st_news_manager_data_sad_a_6", "st_news_manager_data_sad_a_7", "st_news_manager_data_sad_a_8", "st_news_manager_data_sad_a_9", "st_news_manager_data_sad_a_10"}
common["sad_z"] 			= {"st_news_manager_data_sad_z_1", "st_news_manager_data_sad_z_2", "st_news_manager_data_sad_z_3", "st_news_manager_data_sad_z_4", "st_news_manager_data_sad_z_5", "st_news_manager_data_sad_z_6", "st_news_manager_data_sad_z_7", "st_news_manager_data_sad_z_8", "st_news_manager_data_sad_z_9", "st_news_manager_data_sad_z_10"}
common["fun_a"] 			= {"st_news_manager_data_fun_a_1", "st_news_manager_data_fun_a_2", "st_news_manager_data_fun_a_3", "st_news_manager_data_fun_a_4"}
common["fun_z"] 			= {"st_news_manager_data_fun_z_1", "st_news_manager_data_fun_z_2", "st_news_manager_data_fun_z_3", "st_news_manager_data_fun_z_4", "st_news_manager_data_fun_z_5"}
common["prob_a"] 			= {"st_news_manager_data_prob_a_1", "st_news_manager_data_prob_a_2", "st_news_manager_data_prob_a_3", "st_news_manager_data_prob_a_4", "st_news_manager_data_prob_a_5", "st_news_manager_data_prob_a_6", "st_news_manager_data_prob_a_7", "st_news_manager_data_prob_a_8", "st_news_manager_data_prob_a_9"}
common["prob_z"] 			= {"st_news_manager_data_prob_z_1", "st_news_manager_data_prob_z_2", "st_news_manager_data_prob_z_3"}
common["kill_a"] 			= {"st_news_manager_data_kill_a_1", "st_news_manager_data_kill_a_2", "st_news_manager_data_kill_a_3", "st_news_manager_data_kill_a_4", "st_news_manager_data_kill_a_5", "st_news_manager_data_kill_a_6"}
common["kill_z"] 			= {"st_news_manager_data_kill_z_1", "st_news_manager_data_kill_z_2", "st_news_manager_data_kill_z_3", "st_news_manager_data_kill_z_4", "st_news_manager_data_kill_z_5", "st_news_manager_data_kill_z_6"}
common["spawn_seen_a"] 			= {"st_news_manager_data_spawn_seen_a_1", "st_news_manager_data_spawn_seen_a_2", "st_news_manager_data_spawn_seen_a_3", "st_news_manager_data_spawn_seen_a_4", "st_news_manager_data_spawn_seen_a_5", "st_news_manager_data_spawn_seen_a_6", "st_news_manager_data_spawn_seen_a_7"}
common["spawn_seen_z"] 			= {"st_news_manager_data_spawn_seen_z_1", "st_news_manager_data_spawn_seen_z_2", "st_news_manager_data_spawn_seen_z_3", "st_news_manager_data_spawn_seen_z_4", "st_news_manager_data_spawn_seen_z_5", "st_news_manager_data_spawn_seen_z_6", "st_news_manager_data_spawn_seen_z_7"}
common["seen_a"] 			= {"st_news_manager_data_seen_a_1", "st_news_manager_data_seen_a_2", "st_news_manager_data_seen_a_3", "st_news_manager_data_seen_a_4"}
common["seen_z"] 			= {"st_news_manager_data_seen_z_1", "st_news_manager_data_seen_z_2", "st_news_manager_data_seen_z_3", "st_news_manager_data_seen_z_4"}
common["corpse_a"] 			= {"st_news_manager_data_corpse_a_1", "st_news_manager_data_corpse_a_2", "st_news_manager_data_corpse_a_3", "st_news_manager_data_corpse_a_4"}
common["corpse_z"] 			= {"st_news_manager_data_corpse_z_1", "st_news_manager_data_corpse_z_2", "st_news_manager_data_corpse_z_3", "st_news_manager_data_corpse_z_4"}
common["corpse_name_a"] 		= {"st_news_manager_data_corpse_name_a_1", "st_news_manager_data_corpse_name_a_2", "st_news_manager_data_corpse_name_a_3"}
common["corpse_name_z"] 		= {"st_news_manager_data_corpse_name_z_1", "st_news_manager_data_corpse_name_z_2", "st_news_manager_data_corpse_name_z_3"}
common["carefull_a"] 			= {"st_news_manager_data_carefull_a_1", "st_news_manager_data_carefull_a_2", "st_news_manager_data_carefull_a_3", "st_news_manager_data_carefull_a_4", "st_news_manager_data_carefull_a_5"}
common["carefull_z"] 			= {"st_news_manager_data_carefull_z_1", "st_news_manager_data_carefull_z_2", "st_news_manager_data_carefull_z_3", "st_news_manager_data_carefull_z_4", "st_news_manager_data_carefull_z_5"}
common["when_a"] 			= {"st_news_manager_data_when_a_1", "st_news_manager_data_when_a_2", "st_news_manager_data_when_a_3", "st_news_manager_data_when_a_4", "st_news_manager_data_when_a_5"}
common["when_z"] 			= {"st_news_manager_data_when_z_1", "st_news_manager_data_when_z_2", "st_news_manager_data_when_z_3", "st_news_manager_data_when_z_4", "st_news_manager_data_when_z_5"}
common["kill_seen_a"] 			= {"st_news_manager_data_kill_seen_a_1", "st_news_manager_data_kill_seen_a_2", "st_news_manager_data_kill_seen_a_3", "st_news_manager_data_kill_seen_a_4", "st_news_manager_data_kill_seen_a_5", "st_news_manager_data_kill_seen_a_6"}
common["kill_seen_z"] 			= {"st_news_manager_data_kill_seen_z_1", "st_news_manager_data_kill_seen_z_2", "st_news_manager_data_kill_seen_z_3", "st_news_manager_data_kill_seen_z_4", "st_news_manager_data_kill_seen_z_5", "st_news_manager_data_kill_seen_z_6"}
common["killed_a"] 			= {"st_news_manager_data_killed_a_1", "st_news_manager_data_killed_a_2", "st_news_manager_data_killed_a_3", "st_news_manager_data_killed_a_4", "st_news_manager_data_killed_a_5", "st_news_manager_data_killed_a_6"}
common["killed_z"] 			= {"st_news_manager_data_killed_z_1", "st_news_manager_data_killed_z_2", "st_news_manager_data_killed_z_3", "st_news_manager_data_killed_z_4", "st_news_manager_data_killed_z_5", "st_news_manager_data_killed_z_6"}
common["cool_a"] 			= {"st_news_manager_data_cool_a_1", "st_news_manager_data_cool_a_2", "st_news_manager_data_cool_a_3", "st_news_manager_data_cool_a_4"}
common["cool_z"] 			= {"st_news_manager_data_cool_z_1", "st_news_manager_data_cool_z_2", "st_news_manager_data_cool_z_3", "st_news_manager_data_cool_z_4"}
common["meet_a"] 			= {"st_news_manager_data_meet_a_1", "st_news_manager_data_meet_a_2", "st_news_manager_data_meet_a_3", "st_news_manager_data_meet_a_4", "st_news_manager_data_meet_a_5"}
common["meet_z"] 			= {"st_news_manager_data_meet_z_1", "st_news_manager_data_meet_z_2", "st_news_manager_data_meet_z_3", "st_news_manager_data_meet_z_4", "st_news_manager_data_meet_z_5"}
common["hard_a"] 			= {"st_news_manager_data_hard_a_1", "st_news_manager_data_hard_a_2", "st_news_manager_data_hard_a_3", "st_news_manager_data_hard_a_4", "st_news_manager_data_hard_a_5", "st_news_manager_data_hard_a_6", "st_news_manager_data_hard_a_7", "st_news_manager_data_hard_a_8", "st_news_manager_data_hard_a_9"}
common["hard_z"] 			= {"st_news_manager_data_hard_z_1", "st_news_manager_data_hard_z_2", "st_news_manager_data_hard_z_3", "st_news_manager_data_hard_z_4", "st_news_manager_data_hard_z_5", "st_news_manager_data_hard_z_6", "st_news_manager_data_hard_z_7", "st_news_manager_data_hard_z_8", "st_news_manager_data_hard_z_9"}

monsters = { "st_news_manager_data_mutant_pseudo_gigant", "st_news_manager_data_mutant_snork", "st_news_manager_data_mutant_bloodsucker", "st_news_manager_data_mutant_poltergeist", "st_news_manager_data_mutant_burer", "st_news_manager_data_mutant_chimera", "st_news_manager_data_mutant_zombie", "st_news_manager_data_mutant_controller", "st_news_manager_data_mutant_pseudodog", "st_news_manager_data_mutant_dog", "st_news_manager_data_mutant_flesh", "st_news_manager_data_mutant_snork", "st_news_manager_data_mutant_boar"}

monster_classes[clsid.controller_s] 	= {"controller", "st_news_manager_data_mutant_controller", "st_news_manager_data_mutant_controller_1", "st_news_manager_data_mutant_controller_2", "st_news_manager_data_mutant_controller_3", "st_news_manager_data_mutant_controller_4"}
monster_classes[clsid.chimera_s] 		= {"chimera", "st_news_manager_data_mutant_chimera", "st_news_manager_data_mutant_chimera_1", "st_news_manager_data_mutant_chimera_2", "st_news_manager_data_mutant_chimera_3", "st_news_manager_data_mutant_chimera_4"}
monster_classes[clsid.poltergeist_s] 	= {"poltergeist", "st_news_manager_data_mutant_poltergeist", "st_news_manager_data_mutant_poltergeist_1", "st_news_manager_data_mutant_poltergeist_2", "st_news_manager_data_mutant_poltergeist_3", "st_news_manager_data_mutant_poltergeist_4"}
monster_classes[clsid.snork_s] 			= {"snork", "st_news_manager_data_mutant_snork", "st_news_manager_data_mutant_snork_1", "st_news_manager_data_mutant_snork_2", "st_news_manager_data_mutant_snork_3", "st_news_manager_data_mutant_snork_4"}
monster_classes[clsid.gigant_s] 		= {"pseudo_gigant", "st_news_manager_data_mutant_pseudo_gigant", "st_news_manager_data_mutant_pseudo_gigant_1", "st_news_manager_data_mutant_pseudo_gigant_2", "st_news_manager_data_mutant_pseudo_gigant_3", "st_news_manager_data_mutant_pseudo_gigant_4"}
monster_classes[clsid.burer_s] 			= {"burer", "st_news_manager_data_mutant_burer", "st_news_manager_data_mutant_burer_1", "st_news_manager_data_mutant_burer_2", "st_news_manager_data_mutant_burer_3", "st_news_manager_data_mutant_burer_4"}
monster_classes[clsid.bloodsucker_s] 	= {"bloodsucker", "st_news_manager_data_mutant_bloodsucker", "st_news_manager_data_mutant_bloodsucker_1", "st_news_manager_data_mutant_bloodsucker_2", "st_news_manager_data_mutant_bloodsucker_3", "st_news_manager_data_mutant_bloodsucker_4"}
monster_classes[clsid.zombie_s] 		= {"zombie", "st_news_manager_data_mutant_zombie", "st_news_manager_data_mutant_zombie_1", "st_news_manager_data_mutant_zombie_2", "st_news_manager_data_mutant_zombie_3", "st_news_manager_data_mutant_zombie_4"}
monster_classes[clsid.boar_s] 			= {"boar", "st_news_manager_data_mutant_boar", "st_news_manager_data_mutant_boar_1", "st_news_manager_data_mutant_boar_2", "st_news_manager_data_mutant_boar_3", "st_news_manager_data_mutant_boar_4"}
monster_classes[clsid.cat_s] 			= {"cat", "st_news_manager_data_mutant_cat", "st_news_manager_data_mutant_cat_1", "st_news_manager_data_mutant_cat_2", "st_news_manager_data_mutant_cat_3", "st_news_manager_data_mutant_cat_4"}
monster_classes[clsid.pseudodog_s] 		= {"pseudodog", "st_news_manager_data_mutant_pseudodog", "st_news_manager_data_mutant_pseudodog_1", "st_news_manager_data_mutant_pseudodog_2", "st_news_manager_data_mutant_pseudodog_3", "st_news_manager_data_mutant_pseudodog_4"}
monster_classes[clsid.dog_s] 			= {"dog", "st_news_manager_data_mutant_dog", "st_news_manager_data_mutant_dog_1", "st_news_manager_data_mutant_dog_2", "st_news_manager_data_mutant_dog_3", "st_news_manager_data_mutant_dog_4"}
monster_classes[clsid.flesh_s] 			= {"flesh", "st_news_manager_data_mutant_flesh", "st_news_manager_data_mutant_flesh_1", "st_news_manager_data_mutant_flesh_2", "st_news_manager_data_mutant_flesh_3", "st_news_manager_data_mutant_flesh_4"}
--monster_classes[clsid.tushkano_s] 		= {"corpus", "st_news_manager_data_mutant_corpus", "st_news_manager_data_mutant_corpus_1", "st_news_manager_data_mutant_corpus_2", "st_news_manager_data_mutant_corpus_3", "st_news_manager_data_mutant_corpus_4"}
monster_classes[clsid.fracture_s] 		= {"fracture", "st_news_manager_data_mutant_fracture", "st_news_manager_data_mutant_fracture_1", "st_news_manager_data_mutant_fracture_2", "st_news_manager_data_mutant_fracture_3", "st_news_manager_data_mutant_fracture_4"}

monster_prefix 		= {"","st_news_manager_data_monster_pref_1","st_news_manager_data_monster_pref_2", "st_news_manager_data_monster_pref_3", "st_news_manager_data_monster_pref_4"}
monster_suffix[1] 	= {"st_news_manager_data_monster_suff_1", "st_news_manager_data_monster_suff_2", "st_news_manager_data_monster_suff_3", "st_news_manager_data_monster_suff_4", "st_news_manager_data_monster_suff_5"}
monster_suffix[2] 	= {"st_news_manager_data_monster_suff_6", "st_news_manager_data_monster_suff_7"}
monster_suffix[3] 	= {"st_news_manager_data_monster_suff_8", "st_news_manager_data_monster_suff_9"}
monster_suffix[4] 	= {"st_news_manager_data_monster_suff_10", "st_news_manager_data_monster_suff_11"}

anomalies = { "st_news_manager_data_anomalies_buzz", "st_news_manager_data_anomalies_gravi", "st_news_manager_data_anomalies_mincer", "st_news_manager_data_anomalies_mincer", "st_news_manager_data_anomalies_mosquito", "st_news_manager_data_anomalies_witches", "st_news_manager_data_anomalies_zharka" }

anomaly_classes["burning_fuzz"] 			= {"st_news_manager_data_anomalies_burning_fuzz", "st_news_manager_data_anomalies_burning_fuzz_1", "st_news_manager_data_anomalies_burning_fuzz_2", "st_news_manager_data_anomalies_burning_fuzz_3"}
anomaly_classes["buzz"] 					= {"st_news_manager_data_anomalies_buzz", "st_news_manager_data_anomalies_buzz_1", "st_news_manager_data_anomalies_buzz_2", "st_news_manager_data_anomalies_buzz_3", "st_news_manager_data_anomalies_buzz_4"}
anomaly_classes["gravi"] 					= {"st_news_manager_data_anomalies_gravi", "st_news_manager_data_anomalies_gravi_1", "st_news_manager_data_anomalies_gravi_2", "st_news_manager_data_anomalies_gravi_3", "st_news_manager_data_anomalies_gravi_4"}
anomaly_classes["mincer"] 					= {"st_news_manager_data_anomalies_mincer", "st_news_manager_data_anomalies_mincer_1", "st_news_manager_data_anomalies_mincer_2", "st_news_manager_data_anomalies_mincer_3", "st_news_manager_data_anomalies_mincer_4"}
anomaly_classes["witches"] 					= {"st_news_manager_data_anomalies_witches", "st_news_manager_data_anomalies_witches_1", "st_news_manager_data_anomalies_witches_2", "st_news_manager_data_anomalies_witches_3", "st_news_manager_data_anomalies_witches_4"}
anomaly_classes["mosquito"] 				= {"st_news_manager_data_anomalies_mosquito", "st_news_manager_data_anomalies_mosquito_1", "st_news_manager_data_anomalies_mosquito_2", "st_news_manager_data_anomalies_mosquito_3", "st_news_manager_data_anomalies_mosquito_4"}
anomaly_classes["zharka"] 					= {"st_news_manager_data_anomalies_zharka", "st_news_manager_data_anomalies_zharka_1", "st_news_manager_data_anomalies_zharka_2", "st_news_manager_data_anomalies_zharka_3"}
anomaly_classes["radioactive"] 				= {"st_news_manager_data_anomalies_radioactive", "st_news_manager_data_anomalies_radioactive_1", "st_news_manager_data_anomalies_radioactive_2", "st_news_manager_data_anomalies_radioactive_3"}
anomaly_classes["ice"] 						= {"st_news_manager_data_anomalies_ice", "st_news_manager_data_anomalies_ice_1", "st_news_manager_data_anomalies_ice_2", "st_news_manager_data_anomalies_ice_3", "st_news_manager_data_anomalies_ice_4"}


anomaly_prefix						= {"st_news_manager_data_anom_pref_1", "st_news_manager_data_anom_pref_2", "st_news_manager_data_anom_pref_3", "st_news_manager_data_anom_pref_4"}
anomaly_postfix						= {"", "st_news_manager_data_anom_post_1", "st_news_manager_data_anom_post_2", "st_news_manager_data_anom_post_3", "st_news_manager_data_anom_post_4"}

spawn_prefix = {"st_news_manager_data_spawn_prefix_2", "st_news_manager_data_spawn_prefix_1"}

weapon_classes = {
	[1] = {
			["name"]   = {"st_news_manager_data_wpn_1_name_1", "st_news_manager_data_wpn_1_name_2", "st_news_manager_data_wpn_1_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_1_hit_a_1", "st_news_manager_data_wpn_1_hit_a_2", "st_news_manager_data_wpn_1_hit_a_3", "st_news_manager_data_wpn_1_hit_a_4", "st_news_manager_data_wpn_1_hit_a_5", "st_news_manager_data_wpn_1_hit_a_6"},
			["hit_z"]  = {"st_news_manager_data_wpn_1_hit_z_1", "st_news_manager_data_wpn_1_hit_z_2", "st_news_manager_data_wpn_1_hit_z_3", "st_news_manager_data_wpn_1_hit_z_4", "st_news_manager_data_wpn_1_hit_z_5", "st_news_manager_data_wpn_1_hit_z_6"},
			["hear_a"] = {"st_news_manager_data_wpn_1_hear_a_1", "st_news_manager_data_wpn_1_hear_a_2", "st_news_manager_data_wpn_1_hear_a_3"},
			["hear_z"] = {"st_news_manager_data_wpn_1_hear_z_1", "st_news_manager_data_wpn_1_hear_z_2", "st_news_manager_data_wpn_1_hear_z_3"},
			["hear_p"] = 0.4
	},
	[2] = {
			["name"]   = {"st_news_manager_data_wpn_2_name_1", "st_news_manager_data_wpn_2_name_2", "st_news_manager_data_wpn_2_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_2_hit_a_1", "st_news_manager_data_wpn_2_hit_a_2", "st_news_manager_data_wpn_2_hit_a_3", "st_news_manager_data_wpn_2_hit_a_4"},
			["hit_z"]  = {"st_news_manager_data_wpn_2_hit_z_1", "st_news_manager_data_wpn_2_hit_z_2", "st_news_manager_data_wpn_2_hit_z_3", "st_news_manager_data_wpn_2_hit_z_4"},
			["hear_a"] = {"st_news_manager_data_wpn_2_hear_a_1", "st_news_manager_data_wpn_2_hear_a_2", "st_news_manager_data_wpn_2_hear_a_3"},
			["hear_z"] = {"st_news_manager_data_wpn_2_hear_z_1", "st_news_manager_data_wpn_2_hear_z_2", "st_news_manager_data_wpn_2_hear_z_3"},
			["hear_p"] = 0.3
	},
	[3] = {
			["name"]   = {"st_news_manager_data_wpn_3_name_1", "st_news_manager_data_wpn_3_name_2", "st_news_manager_data_wpn_3_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_3_hit_a_1", "st_news_manager_data_wpn_3_hit_a_2", "st_news_manager_data_wpn_3_hit_a_3", "st_news_manager_data_wpn_3_hit_a_4", "st_news_manager_data_wpn_3_hit_a_5"},
			["hit_z"]  = {"st_news_manager_data_wpn_3_hit_z_1", "st_news_manager_data_wpn_3_hit_z_2", "st_news_manager_data_wpn_3_hit_z_3", "st_news_manager_data_wpn_3_hit_z_4", "st_news_manager_data_wpn_3_hit_z_5"},
			["hear_a"] = {"st_news_manager_data_wpn_3_hear_a_1", "st_news_manager_data_wpn_3_hear_a_2", "st_news_manager_data_wpn_3_hear_a_3"},
			["hear_z"] = {"st_news_manager_data_wpn_3_hear_z_1", "st_news_manager_data_wpn_3_hear_z_2", "st_news_manager_data_wpn_3_hear_z_3"},
			["hear_p"] = 0.6
	},
	[4] = {
			["name"]   = {"st_news_manager_data_wpn_4_name_1", "st_news_manager_data_wpn_4_name_2", "st_news_manager_data_wpn_4_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_4_hit_a_1", "st_news_manager_data_wpn_4_hit_a_2", "st_news_manager_data_wpn_4_hit_a_3"},
			["hit_z"]  = {"st_news_manager_data_wpn_4_hit_z_1", "st_news_manager_data_wpn_4_hit_z_2", "st_news_manager_data_wpn_4_hit_z_3"},
			["hear_a"] = {"st_news_manager_data_wpn_4_hear_a_1", "st_news_manager_data_wpn_4_hear_a_2"},
			["hear_z"] = {"st_news_manager_data_wpn_4_hear_z_1", "st_news_manager_data_wpn_4_hear_z_2"},
			["hear_p"] = 0.8
	},
	[5] = {
			["name"]   = {"st_news_manager_data_wpn_5_name_1", "st_news_manager_data_wpn_5_name_2", "st_news_manager_data_wpn_5_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_5_hit_a_1", "st_news_manager_data_wpn_5_hit_a_2", "st_news_manager_data_wpn_5_hit_a_3"},
			["hit_z"]  = {"st_news_manager_data_wpn_5_hit_z_1", "st_news_manager_data_wpn_5_hit_z_2", "st_news_manager_data_wpn_5_hit_z_3"},
			["hear_a"] = {"st_news_manager_data_wpn_5_hear_a_1", "st_news_manager_data_wpn_5_hear_a_2", "st_news_manager_data_wpn_5_hear_a_3"},
			["hear_z"] = {"st_news_manager_data_wpn_5_hear_z_1", "st_news_manager_data_wpn_5_hear_z_2", "st_news_manager_data_wpn_5_hear_z_3"},
			["hear_p"] = 0.9
	},
	[6] = {
			["name"]   = {"st_news_manager_data_wpn_6_name_1", "st_news_manager_data_wpn_6_name_2", "st_news_manager_data_wpn_6_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_6_hit_a_1", "st_news_manager_data_wpn_6_hit_a_2", "st_news_manager_data_wpn_6_hit_a_3", "st_news_manager_data_wpn_6_hit_a_4"},
			["hit_z"]  = {"st_news_manager_data_wpn_6_hit_z_1", "st_news_manager_data_wpn_6_hit_z_2", "st_news_manager_data_wpn_6_hit_z_3", "st_news_manager_data_wpn_6_hit_z_4"},
			["hear_a"] = {""}, -- Ну не слышали мы ножик :"
			["hear_z"] = {""}, -- Ну не слышали мы ножик :"
			["hear_p"] = 0.0
	},
	[7] = {
			["name"]   = {"st_news_manager_data_wpn_7_name_1", "st_news_manager_data_wpn_7_name_2", "st_news_manager_data_wpn_7_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_7_hit_a_1", "st_news_manager_data_wpn_7_hit_a_2", "st_news_manager_data_wpn_7_hit_a_3", "st_news_manager_data_wpn_7_hit_a_4"},
			["hit_z"]  = {"st_news_manager_data_wpn_7_hit_z_1", "st_news_manager_data_wpn_7_hit_z_2", "st_news_manager_data_wpn_7_hit_z_3", "st_news_manager_data_wpn_7_hit_z_4"},
			["hear_a"] = {"st_news_manager_data_wpn_7_hear_a_1", "st_news_manager_data_wpn_7_hear_a_2", "st_news_manager_data_wpn_7_hear_a_3"},
			["hear_z"] = {"st_news_manager_data_wpn_7_hear_z_1", "st_news_manager_data_wpn_7_hear_z_2", "st_news_manager_data_wpn_7_hear_z_3"},
			["hear_p"] = 0.9
	},
	[8] = {
			["name"]   = {"st_news_manager_data_wpn_8_name_1", "st_news_manager_data_wpn_8_name_2", "st_news_manager_data_wpn_8_name_3"},
			["hit_a"]  = {"st_news_manager_data_wpn_8_hit_a_1", "st_news_manager_data_wpn_8_hit_a_2", "st_news_manager_data_wpn_8_hit_a_3"},
			["hit_z"]  = {"st_news_manager_data_wpn_8_hit_z_1", "st_news_manager_data_wpn_8_hit_z_2", "st_news_manager_data_wpn_8_hit_z_3"},
			["hear_a"] = {""},
			["hear_z"] = {""},
			["hear_p"] = 0.0
	}
}

 weapon_templates = {
"st_news_manager_data_weapon_template_1",
"st_news_manager_data_weapon_template_2",
"st_news_manager_data_weapon_template_3",
"st_news_manager_data_weapon_template_4",
"st_news_manager_data_weapon_template_4_2",
"st_news_manager_data_weapon_template_5",
"st_news_manager_data_weapon_template_6",
"st_news_manager_data_weapon_template_7",
"st_news_manager_data_weapon_template_8",
"st_news_manager_data_weapon_template_9",
"st_news_manager_data_weapon_template_10",
"st_news_manager_data_weapon_template_11",
"st_news_manager_data_weapon_template_12",
"st_news_manager_data_weapon_template_13",
"st_news_manager_data_weapon_template_14",
"st_news_manager_data_weapon_template_15"
}

 stalker_corpse_templates = {
"st_news_manager_data_corpse_template_1",
"st_news_manager_data_corpse_template_2",
"st_news_manager_data_corpse_template_3",
"st_news_manager_data_corpse_template_4",
"st_news_manager_data_corpse_template_5",
"st_news_manager_data_corpse_template_6",
"st_news_manager_data_corpse_template_7",
"st_news_manager_data_corpse_template_8",
"st_news_manager_data_corpse_template_9",
"st_news_manager_data_corpse_template_10",
"st_news_manager_data_corpse_template_11",
"st_news_manager_data_corpse_template_12",
"st_news_manager_data_corpse_template_13",
"st_news_manager_data_corpse_template_14",
"st_news_manager_data_corpse_template_15",
"st_news_manager_data_corpse_template_16",
"st_news_manager_data_corpse_template_17",
"st_news_manager_data_corpse_template_18",
"st_news_manager_data_corpse_template_19",
"st_news_manager_data_corpse_template_20",
"st_news_manager_data_corpse_template_21",
"st_news_manager_data_corpse_template_22",
"st_news_manager_data_corpse_template_23",
"st_news_manager_data_corpse_template_24",
"st_news_manager_data_corpse_template_25",
"st_news_manager_data_corpse_template_26"
}

 npc_corpse_templates = {
"st_news_manager_data_npc_corpse_template_1",
"st_news_manager_data_npc_corpse_template_2",
"st_news_manager_data_npc_corpse_template_3",
"st_news_manager_data_npc_corpse_template_4",
"st_news_manager_data_npc_corpse_template_5",
"st_news_manager_data_npc_corpse_template_6",
"st_news_manager_data_npc_corpse_template_7",
"st_news_manager_data_npc_corpse_template_8",
"st_news_manager_data_npc_corpse_template_9",
"st_news_manager_data_npc_corpse_template_10",
"st_news_manager_data_npc_corpse_template_11",
"st_news_manager_data_npc_corpse_template_12",
"st_news_manager_data_npc_corpse_template_13"
}

 monster_corpse_templates = {
"st_news_manager_data_monster_corpse_template_1",
"st_news_manager_data_monster_corpse_template_2",
"st_news_manager_data_monster_corpse_template_3",
"st_news_manager_data_monster_corpse_template_4",
"st_news_manager_data_monster_corpse_template_5",
"st_news_manager_data_monster_corpse_template_6",
"st_news_manager_data_monster_corpse_template_7",
"st_news_manager_data_monster_corpse_template_8",
"st_news_manager_data_monster_corpse_template_9",
"st_news_manager_data_monster_corpse_template_10",
"st_news_manager_data_monster_corpse_template_11",
"st_news_manager_data_monster_corpse_template_12",
"st_news_manager_data_monster_corpse_template_13",
"st_news_manager_data_monster_corpse_template_14",
"st_news_manager_data_monster_corpse_template_15",
"st_news_manager_data_monster_corpse_template_16",
"st_news_manager_data_monster_corpse_template_17",
"st_news_manager_data_monster_corpse_template_18",
"st_news_manager_data_monster_corpse_template_19",
"st_news_manager_data_monster_corpse_template_20",
"st_news_manager_data_monster_corpse_template_21",
"st_news_manager_data_monster_corpse_template_22",
"st_news_manager_data_monster_corpse_template_23",
"st_news_manager_data_monster_corpse_template_24",
"st_news_manager_data_monster_corpse_template_25",
"st_news_manager_data_monster_corpse_template_26"
}

killer_act_templates = {
"st_news_manager_data_killer_act_template_1",
"st_news_manager_data_killer_act_template_2",
"st_news_manager_data_killer_act_template_3",
"st_news_manager_data_killer_act_template_4",
"st_news_manager_data_killer_act_template_5",
"st_news_manager_data_killer_act_template_6",
"st_news_manager_data_killer_act_template_7",
"st_news_manager_data_killer_act_template_8",
"st_news_manager_data_killer_act_template_9",
"st_news_manager_data_killer_act_template_10"
}

 hear_sounds_tempates = {
"st_news_manager_data_hear_sounds_template_1",
"st_news_manager_data_hear_sounds_template_2",
"st_news_manager_data_hear_sounds_template_3",
"st_news_manager_data_hear_sounds_template_4",
"st_news_manager_data_hear_sounds_template_5",
"st_news_manager_data_hear_sounds_template_6",
"st_news_manager_data_hear_sounds_template_7",
"st_news_manager_data_hear_sounds_template_8",
"st_news_manager_data_hear_sounds_template_9",
"st_news_manager_data_hear_sounds_template_10",
"st_news_manager_data_hear_sounds_template_11",
"st_news_manager_data_hear_sounds_template_12",
"st_news_manager_data_hear_sounds_template_13",
"st_news_manager_data_hear_sounds_template_14",
"st_news_manager_data_hear_sounds_template_15",
"st_news_manager_data_hear_sounds_template_16",
"st_news_manager_data_hear_sounds_template_17",
"st_news_manager_data_hear_sounds_template_18",
"st_news_manager_data_hear_sounds_template_19"
}

 spawn_templates = {
"st_news_manager_data_spawn_template_1",
"st_news_manager_data_spawn_template_2",
"st_news_manager_data_spawn_template_3",
"st_news_manager_data_spawn_template_4",
"st_news_manager_data_spawn_template_5",
"st_news_manager_data_spawn_template_6",
"st_news_manager_data_spawn_template_7",
"st_news_manager_data_spawn_template_8",
"st_news_manager_data_spawn_template_9",
"st_news_manager_data_spawn_template_10",
"st_news_manager_data_spawn_template_11",
"st_news_manager_data_spawn_template_12",
"st_news_manager_data_spawn_template_13",
"st_news_manager_data_spawn_template_14",
"st_news_manager_data_spawn_template_15",
"st_news_manager_data_spawn_template_16",
"st_news_manager_data_spawn_template_17",
"st_news_manager_data_spawn_template_18"
}

spawn_templates_group = {
"st_news_manager_data_spawn_group_template_1",
"st_news_manager_data_spawn_group_template_2",
"st_news_manager_data_spawn_group_template_3",
"st_news_manager_data_spawn_group_template_4",
"st_news_manager_data_spawn_group_template_5",
"st_news_manager_data_spawn_group_template_6",
"st_news_manager_data_spawn_group_template_7",
"st_news_manager_data_spawn_group_template_8",
"st_news_manager_data_spawn_group_template_9",
"st_news_manager_data_spawn_group_template_10",
"st_news_manager_data_spawn_group_template_11",
"st_news_manager_data_spawn_group_template_12",
"st_news_manager_data_spawn_group_template_13",
"st_news_manager_data_spawn_group_template_14",
"st_news_manager_data_spawn_group_template_15",
"st_news_manager_data_spawn_group_template_16",
"st_news_manager_data_spawn_group_template_17",
"st_news_manager_data_spawn_group_template_18"
}

actor_seen_public_templates = {
"st_news_manager_data_seen_public_template_1",
"st_news_manager_data_seen_public_template_2",
"st_news_manager_data_seen_public_template_3",
"st_news_manager_data_seen_public_template_4",
"st_news_manager_data_seen_public_template_5",
"st_news_manager_data_seen_public_template_6",
"st_news_manager_data_seen_public_template_7",
"st_news_manager_data_seen_public_template_8",
"st_news_manager_data_seen_public_template_9",
"st_news_manager_data_seen_public_template_10"
}

actor_seen_public_templates_group = {
"st_news_manager_data_seen_public_group_template_1",
"st_news_manager_data_seen_public_group_template_2",
"st_news_manager_data_seen_public_group_template_3",
"st_news_manager_data_seen_public_group_template_4",
"st_news_manager_data_seen_public_group_template_5",
"st_news_manager_data_seen_public_group_template_6",
"st_news_manager_data_seen_public_group_template_7",
"st_news_manager_data_seen_public_group_template_8",
"st_news_manager_data_seen_public_group_template_9",
"st_news_manager_data_seen_public_group_template_10"
}

wound_templates = {
	["single"] = {"st_news_manager_data_wound_template_single_1", "st_news_manager_data_wound_template_single_2", "st_news_manager_data_wound_template_single_3", "st_news_manager_data_wound_template_single_4", "st_news_manager_data_wound_template_single_5", "st_news_manager_data_wound_template_single_6", "st_news_manager_data_wound_template_single_7", "st_news_manager_data_wound_template_single_8", "st_news_manager_data_wound_template_single_9", "st_news_manager_data_wound_template_single_10" },
	["group"] = {"st_news_manager_data_wound_template_group_1", "st_news_manager_data_wound_template_group_2", "st_news_manager_data_wound_template_group_3", "st_news_manager_data_wound_template_group_4", "st_news_manager_data_wound_template_group_5", "st_news_manager_data_wound_template_group_6", "st_news_manager_data_wound_template_group_7", "st_news_manager_data_wound_template_group_8", "st_news_manager_data_wound_template_group_9", "st_news_manager_data_wound_template_group_10" }
}


trade_templates = {
"st_news_manager_data_trade_template_1",
"st_news_manager_data_trade_template_2",
"st_news_manager_data_trade_template_3",
"st_news_manager_data_trade_template_4",
"st_news_manager_data_trade_template_5",
"st_news_manager_data_trade_template_6",
"st_news_manager_data_trade_template_7",
"st_news_manager_data_trade_template_8",
"st_news_manager_data_trade_template_9",
"st_news_manager_data_trade_template_10",
"st_news_manager_data_trade_template_11",
"st_news_manager_data_trade_template_12",
"st_news_manager_data_trade_template_13",
"st_news_manager_data_trade_template_14",
"st_news_manager_data_trade_template_15",
"st_news_manager_data_trade_template_16",
"st_news_manager_data_trade_template_17"
}


docs_templates = {
"st_news_manager_data_docs_template_1",
"st_news_manager_data_docs_template_2",
"st_news_manager_data_docs_template_3",
"st_news_manager_data_docs_template_4",
"st_news_manager_data_docs_template_5"
}


art_templates = {
"st_news_manager_data_art_template_1",
"st_news_manager_data_art_template_2",
"st_news_manager_data_art_template_3",
"st_news_manager_data_art_template_4",
"st_news_manager_data_art_template_5",
"st_news_manager_data_art_template_6",
"st_news_manager_data_art_template_7",
"st_news_manager_data_art_template_8",
"st_news_manager_data_art_template_9",
"st_news_manager_data_art_template_10",
"st_news_manager_data_art_template_11"
}


weapons_templates = {
"st_news_manager_data_weapons_template_1",
"st_news_manager_data_weapons_template_2",
"st_news_manager_data_weapons_template_3",
"st_news_manager_data_weapons_template_4",
"st_news_manager_data_weapons_template_5",
"st_news_manager_data_weapons_template_6",
"st_news_manager_data_weapons_template_7",
"st_news_manager_data_weapons_template_8",
"st_news_manager_data_weapons_template_9"
}


-- 23:00 - 04:00
night_templates = {
	{	texts = {
		"st_news_manager_data_night_template_1",
		"st_news_manager_data_night_template_2",
		"st_news_manager_data_night_template_3"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_4",
		"st_news_manager_data_night_template_5",
		"st_news_manager_data_night_template_6"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_7",
		"st_news_manager_data_night_template_8",
		"st_news_manager_data_night_template_9"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_10",
		"st_news_manager_data_night_template_11",
		"st_news_manager_data_night_template_12"
		}, comments = "strange", prob=0.6
	},
	{	texts = {
		"st_news_manager_data_night_template_13",
		"st_news_manager_data_night_template_14"
		}, comments = "strange", prob=0.8
	},
	{	texts = {
		"st_news_manager_data_night_template_17",
		"st_news_manager_data_night_template_17_2",
		"st_news_manager_data_night_template_18",
		"st_news_manager_data_night_template_19"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_15",
		"st_news_manager_data_night_template_16"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_20",
		"st_news_manager_data_night_template_21"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_22",
		"st_news_manager_data_night_template_22_1"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_23",
		"st_news_manager_data_night_template_24",
		"st_news_manager_data_night_template_25"
		}
	},
	{	texts = {
		"st_news_manager_data_night_template_26",
		"st_news_manager_data_night_template_27"
		}, comments = "strange", prob=0.4
	},
	{	texts = {
		"st_news_manager_data_night_template_28",
		"st_news_manager_data_night_template_29"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_30",
		"st_news_manager_data_night_template_31"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_32",
		"st_news_manager_data_night_template_33"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_34",
		"st_news_manager_data_night_template_35"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_36"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_37"
		}, comments = "strange", prob=0.7
	},
	{	texts = {
		"st_news_manager_data_night_template_38"
		}, comments = "strange", prob=0.4
	},
	{	texts = {
		"st_news_manager_data_night_template_39"
		}, comments = "strange", prob=0.4
	},
	{	texts = {
		"st_news_manager_data_night_template_40"
		}, comments = "strange", prob=0.4
	},
	{	texts = {
		"st_news_manager_data_night_template_41"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_42"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_43"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_44"
		}, comments = "strange", prob=0.4
	},
	{	texts = {
		"st_news_manager_data_night_template_45"
		}, comments = "strange", prob=0.5
	},
	{	texts = {
		"st_news_manager_data_night_template_46"
		}, comments = "strange", prob=0.01
	},
	{	texts = {
		"st_news_manager_data_night_template_47"
		}, comments = "strange", prob=0.001
	},
	{	texts = {
		"st_news_manager_data_night_template_48"
		}, comments = "strange", prob=0.6
	},
	{	texts = {
		"st_news_manager_data_night_template_49",
		"st_news_manager_data_night_template_50",
		"st_news_manager_data_night_template_51"
		}
	}, 
	{	texts = {
		"st_news_manager_data_night_template_52",
		"st_news_manager_data_night_template_53",
		"st_news_manager_data_night_template_54"
		}, comments = "strange", prob=0.5
	},
	{	texts = {
		"st_news_manager_data_night_template_55",
		"st_news_manager_data_night_template_56",
		"st_news_manager_data_night_template_57"
		}, comments = "strange", prob=0.5
	},
	{	texts = {
		"st_news_manager_data_night_template_58"
		}, comments = "strange", prob=0.3
	},
	{	texts = {
		"st_news_manager_data_night_template_59",
		"st_news_manager_data_night_template_60",
		"st_news_manager_data_night_template_61"
		}, comments = "strange", prob=0.4
	},
	{	texts = {
		"st_news_manager_data_night_template_62",
		"st_news_manager_data_night_template_63"
		}, comments = "strange", prob=0.8
	},
	{	texts = {
		"st_news_manager_data_night_template_64",
		"st_news_manager_data_night_template_65"
		}, comments = "strange", prob=0.2
	},
	{	texts = {
		"st_news_manager_data_night_template_66",
		"st_news_manager_data_night_template_67"
		}, comments = "strange", prob=0.2
	},
	{	texts = {
		"st_news_manager_data_night_template_68",
		"st_news_manager_data_night_template_69"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_70",
		"st_news_manager_data_night_template_71"
		}, comments = "strange", prob=0.1
	},
	{	texts = {
		"st_news_manager_data_night_template_72"
		}, comments = "strange", prob=0.5
	},
	{	texts = {
		"st_news_manager_data_night_template_73",
		"st_news_manager_data_night_template_74"
		}, comments = "strange", prob=0.8
	}
}

-- 04:30 - 07:00
morning_templates = {
	"st_news_manager_data_morning_template_1",
	"st_news_manager_data_morning_template_2",
	"st_news_manager_data_morning_template_3",
	"st_news_manager_data_morning_template_4",
	"st_news_manager_data_morning_template_5",
	"st_news_manager_data_morning_template_6",
	"st_news_manager_data_morning_template_7"
}

-- 20:30 - 22:00
evening_templates = {
	"st_news_manager_data_evening_template_1",
	"st_news_manager_data_evening_template_2",
	"st_news_manager_data_evening_template_3",
	"st_news_manager_data_evening_template_4",
	"st_news_manager_data_evening_template_5",
	"st_news_manager_data_evening_template_6",
	"st_news_manager_data_evening_template_7",
	"st_news_manager_data_evening_template_8"
}

comments_templates = {
	["strange"] = {
		"st_news_manager_data_comments_template_1",
		"st_news_manager_data_comments_template_2",
		"st_news_manager_data_comments_template_3",
		"st_news_manager_data_comments_template_4",
		"st_news_manager_data_comments_template_5",
		"st_news_manager_data_comments_template_6",
		"st_news_manager_data_comments_template_7",
		"st_news_manager_data_comments_template_8",
		"st_news_manager_data_comments_template_9",
		"st_news_manager_data_comments_template_10",
		"st_news_manager_data_comments_template_11",
		"st_news_manager_data_comments_template_12",
		"st_news_manager_data_comments_template_13",
		"st_news_manager_data_comments_template_14"
	}
}

smart_filters = {
	["military"] = {"esc_blokpost"},
	["zombied"] = {"yantar_zombies"},
	["zombie"] = {"yantar_zombies"},
}







