pda_news = xr_sound.get_safe_sound_object([[device\pda\pda_news]])
pda_tips = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
pda_task = xr_sound.get_safe_sound_object([[device\pda\pda_objective]])
pda_sos = xr_sound.get_safe_sound_object([[device\pda\pda_sos]])

tips_icons = {
	default     = 						{ 3, 215},
	
	money_found     = 					{ 3, 3},
	task_update     = 					{ 56, 3},
	military_stalker     = 				{ 109, 3},
	helicopter     = 					{ 162, 3},
	novice     = 						{ 215, 3},
	security    = 						{ 268, 3},
	
	money_lost    = 					{ 3, 56},
	trade    = 							{ 56, 56},
	hero    = 							{ 109, 56},
	documents    = 						{ 162, 56},
	flash     = 						{ 215, 56},
	major     = 						{ 268, 56},	
	
	item    = 							{ 3, 109},
	professor    = 						{ 56, 109},
	unknown    = 						{ 109, 109},
	kill_stalker    = 					{ 162, 109},
	artifact_merger     = 				{ 215, 109},
	lone_wolf     = 				    { 268, 109},
	
	item_lost    = 						{ 3, 162},
	freedom    = 						{ 56, 162},
	neutral    = 						{ 109, 162},
	stalker    = 						{ 109, 162},
	sos    = 							{ 162, 162},
	freedom_leader    = 				{ 215, 162},
	treasure    = 						{ 268, 162},

	death    = 							{ 3, 215},
	clear_sky    = 						{ 56, 215},
	trader    = 						{ 109, 215},
	info    = 							{ 162, 215},
	dolg_leader    = 					{ 215, 215},

	news    = 							{ 3, 268},
	dolg    = 							{ 56, 268},
	killer    = 						{ 109, 268},
	money_update    = 					{ 162, 268},
	specops    = 						{ 215, 321},
	
	task_new    = 						{ 3, 321},
	barman    = 						{ 56, 321},
	bandit_leader    = 					{ 109, 321},
	bandit    = 						{ 162, 321},
	trader_order    = 					{ 215, 321},
	
	task_completed    = 				{ 3, 374},
	monolith    = 						{ 56, 374},
	soldier    = 						{ 109, 374},
	artifact    = 						{ 162, 374},
	signal_lost    = 					{ 215, 374},
	
	task_failed    = 					{ 3, 427},
	ecolog    = 						{ 56, 427},
	doctor    = 						{ 109, 427},
	mutants    = 						{ 162, 427},
	weapon    = 						{ 215, 427},
	
}


function send_tip(actor, news_id, timeout, sender, showtime, sender_id, kostyl, show_tip_top, sender_name)
	if news_id == nil then return false end

	printf("try to send tips for [%s]", tostring(sender_id))
	if sender_id ~= nil then
		local sim = alife()
		if sim ~= nil then
			local npc = sim:story_object(sender_id)
			if npc ~= nil then
				if npc.online then
					--в онлайне проверяем на раненность
					if xr_wounded.is_heavy_wounded_by_id(npc.id) then
						printf("[PDA]Cannot send tips [%s], sender is heavy wounded", tostring(news_id))
						return false
					end
				end
				-- в других случаях только на смерть
				if npc:alive() == 1 then
					printf("[PDA]Cannot send tips [%s], sender is dead", tostring(news_id))
					return false
				end
			end
		end
	end

    -- Настройка параметров по умолчанию
    timeout = timeout or 0
    showtime = showtime or 5000
	show_tip_top = (show_tip_top ~= false)
	sender = sender or "default"
	
	-- Проверка существования sender в таблице tips_icons
	if tips_icons[sender] == nil then
		log1(string.format("~~~ В sender '%s' отправили ту иконку которой нет в таблице", tostring(sender)))
		sender = "default"
	end	

	-- Играем дефолтный звук или костыльно другой звук
	local sound_map = {
		pda_news = pda_news,
		pda_tip = pda_tips,
		pda_objective = pda_task,
		pda_sos = pda_sos
	}
	
    -- Определение задержки (в миллисекундах)
    local timeout_msg
	local timeout_snd = timeout
    if timeout >= 100 then
        -- Если timeout уже в миллисекундах (>=100), используем как есть
        timeout_msg = timeout
		timeout_snd = timeout / 1000 -- переводим из мс в сек
    else
        -- Иначе конвертируем секунды в миллисекунды
        timeout_msg = timeout * 1000
    end		

	local sound_to_play = sound_map[kostyl] or pda_tips
	sound_to_play:play(db.actor, timeout_snd, sound_object.s2d)
	
	if sender == nil then
		sender = "default"
	end
	local x = tips_icons[sender][1]
	local y = tips_icons[sender][2]
	
	-- Определение текста сообщения в зависимости от show_tip_top
	-- Переделать нахуй, надо убирать show_tip_top и оставлять только sender_name
	local news_text, sender_text
	if show_tip_top ~= false then
		if sender_name then
			sender_text = "%c[255,160,181,169]"..game.translate_string(sender_name)
			news_text = "%c[255,245,240,218]"..game.translate_string(news_id)
		else
			sender_text = "%c[255,160,181,169]"..game.translate_string("st_tip")
			news_text = "%c[255,245,240,218]"..game.translate_string(news_id)
		end
	else
		sender_text = "%c[255,160,181,169]"..game.translate_string("st_tip")
		news_text = "%c[255,255,255,255]"..game.translate_string(news_id) -- для сообщений где всё сформировано в одну строку
	end
	
	db.actor:give_game_news(news_text, game.translate_string(sender_text), "ui\\icons\\icons_notifications", Frect():set(x,y,50,50), timeout_msg, showtime)
	
	return true
end

local news = {} -- тут должны хранится специальные саунды озвучки, в тч это всякие звуковые сообщения.
				-- например сообщение Сидоровича про аномалии или коды от дверей в лабах

function send_tip_nosound(actor, news_id, timeout, sender) -- хоть эта функция и не используется в олр сделаю чтоб всё работало как надо
	if news_id == nil then return end
	timeout = 0
	-- Играем дефолтный звук
	pda_tips:play(db.actor, timeout, sound_object.s2d)
	local news_sound = news[news_id]
	return news_sound
end

local action_descr_by_type = {
	new = "general_new_task",
	update = "general_update_task", 
	complete = "general_complete_task",
	fail = "general_fail_task"
}

local texture_by_action_type = {
	new = "ui_notification_new_task",
	update = "ui_notification_update_task", 
	complete = "ui_notification_completed_task",
	fail = "ui_notification_failed_task"
}

function send_task(actor, type, task, objective)
	if db.actor == nil then return false end

	-- Получаем текстуру для текущего типа действия
	local texture_name = texture_by_action_type[type] or "ui_iconsTotal_update_task"
	local task_texture, task_rect = get_texture_info("ui_iconsTotal_" .. task:get_id(), texture_name)
	
	local news_text = ""
	if db.actor:is_talking() then
		news_text = "%c[255,160,181,169]" .. game.translate_string(action_descr_by_type[type]) .. "\\n" .. "%c[default]" .. game.translate_string(task:get_title())
	else
		news_text =  game.translate_string(task:get_title())
	end
	local news_text_static = game.translate_string(action_descr_by_type[type]) .. " " .. game.translate_string(task:get_title())

	-- Обработка нового задания
	if type == "new" then
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
			if task:get_objectives_cnt() == objective:get_idx() + 1 then
				return
			end
			news_text = game.translate_string(task:get_objective(objective:get_idx() + 1):get_description())
		end
		
		local hud = get_hud()
		hud:AddCustomStatic("job_task", true)
		hud:GetCustomStatic("job_task"):wnd():SetTextST(news_text_static)
		hud:GetCustomStatic("job_task").m_endTime = time_global() / 1000 + 8
		pda_task:play(db.actor, 0, sound_object.s2d)
		
		xvars.quests_started = xvars.quests_started + 1
		nick.autosave_quest()

	-- Обработка завершения задания
	elseif type == "complete" then
		pda_tips:play(db.actor, 0, sound_object.s2d)
		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "%c[255,160,181,169]" .. game.translate_string(action_descr_by_type[type]), task_texture, task_rect, 0, 3000)
		end
		pda_task:play(db.actor, 0, sound_object.s2d)
		actor_stats.add_points("quests", task:get_title(), 1, 1)
		nick.autosave_quest()

	-- Обработка обновления задания
	elseif type == "update" then
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "%c[255,160,181,169]" .. game.translate_string(action_descr_by_type[type]), task_texture, task_rect, 0, 3000)
		end
		pda_task:play(db.actor, 0, sound_object.s2d)
		nick.autosave_quest()
	end
end

function send_encyclopedy(type, title)
	if type == "Diary" then
		pda_news:play(db.actor, 0, sound_object.s2d)
		-- Берем координаты из текстуры таска
		local task_texture, task_rect = get_texture_info("ui_notification_info")
		local news_text = "%c[255,160,181,169]"..game.translate_string("st_found_another_pda").."\\n".."%c[default]"..game.translate_string(title)
		if db.actor:is_talking() then	
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end	
	end
end

function get_inv_name(section)
	return system_ini():r_string(section,"inv_name")
end

function relocate_item(actor, type, item)
	if db.actor == nil then return false end
	-- Играем дефолтный звук
	if type == "in" then
		local task_texture, task_rect = get_texture_info("ui_notification_found_item")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_in_item").."\\n".."%c[default]"..game.translate_string(get_inv_name(item))		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	elseif type == "out" then
		local task_texture, task_rect = get_texture_info("ui_notification_lost_item")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_out_item").."\\n".."%c[default]"..game.translate_string(get_inv_name(item))		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect,"iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	end
	
end

function relocate_money(actor, type, amount)
	if db.actor == nil then return false end
	-- Играем дефолтный звук
	if type == "in" then
		local task_texture, task_rect = get_texture_info("ui_notification_found_money")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_in_money").."\\n".."%c[default]"..game.translate_string(tostring(amount))
		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	elseif type == "out" then
		local task_texture, task_rect = get_texture_info("ui_notification_lost_money")
		local news_text = "%c[255,160,181,169]"..game.translate_string("general_out_money").."\\n".."%c[default]"..game.translate_string(tostring(amount))
		
		if db.actor:is_talking() then
			db.actor:give_talk_message(news_text, task_texture, task_rect, "iconed_answer_item")
		else
			db.actor:give_game_news(news_text, "", task_texture, task_rect, 0, 3000)
		end		
	end
	
end