-- ухудшение зрени€ неписей ночью -- учитывает опыт непис€ - подразумева€ наличи ѕЌ¬ --
--------------------------- Copyright 2009 KamikaZze дл€ OGSE -------------------------

local laststate={}

local warn_timer = time_global()
local warn_check_timer = {}

-- как вы€снилось, озвучка "reactions" в папке "human_01" есть не у всех коммунити - при попытке выбрать еЄ будет вылет
-- кроме того, она у всех коммунити одинакова€ абсолютно, поэтому выбирать по коммунити еЄ бессмысленно... 

local nothing_there = {

[1] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_1]],
[2] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_2]],
[3] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_3]],
[4] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_4]],
[5] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_5]],
[6] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_6]],
[7] = [[characters_voice\human_01\dolg\reactions\nothing\nothing_7]]

}

--уровни, где Ќѕ—и круглосуточно вид€т одинаково (отключаем скрипт, где нет €вной ночи)
function blind_level()
	if level.name() == "lvl12_radar_bunker" or
	   level.name() == "lvl15_sarcofag"
        then
		return true 
	else
		return false
	end
end

function check_night(obj)
	local htime = level.get_time_hours()
	if htime and obj and not blind_level() then

		local nid = obj:id()
		if laststate[nid] == nil then
			laststate[nid] = false
		end
		local npc = level.object_by_id(obj:id())
		if npc and IsStalker(npc) then
		
		if npc:character_community() == "zombied"  
		or npc:character_community() == "monolith" then
			return
		end

		if npc:character_community() == "military" and not has_alife_info("agr_first") and npc.level_name == "lvl1_escape" then
			npc:set_range(10)
			npc:set_fov(10)
			--log1("mil low fow")
		end			
		
		local npc_rank = ranks.get_obj_rank_name(npc)
			if (not npc:best_danger() and not npc:best_enemy()) then
			-- пока мы спокойны
				if htime <= 4 or htime >= 23 then
					-- ночь
					local range = npc:range()
					local fov = npc:fov()
					if range and range > 80 then
						if npc_rank == "novice" then 
							npc:set_range(30)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "experienced" then 
							npc:set_range(35)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "veteran" then
							npc:set_range(40)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "master" then
							npc:set_range(45)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						end				
					end
					if fov and fov > 120 then
						if npc_rank == "novice" then 
							npc:set_fov(90)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "experienced" then 
							npc:set_fov(95)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "veteran" then
							npc:set_fov(100)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "master" then
							npc:set_fov(110)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						end					
					end
					if laststate[nid] == true and not npc:best_danger() and not npc:best_enemy() then
						if npc then
							warn_check_timer[npc:id()] = time_global()
							if warn_check_timer[npc:id()] > warn_timer then  
								local snd_name = nothing_there[math.random(1,7)]
								if snd_name then
									local snd_obj = xr_sound.get_safe_sound_object(snd_name)
									if snd_obj and not snd_obj:playing() then
										snd_obj:play_no_feedback(npc, sound_object.s3d, 0, npc:position(), 1.0)
										--log1("snd nothing here")
									end
								end
								warn_timer = warn_check_timer[npc:id()] + math.random(15000, 25000) 
							end
						end
						laststate[nid] = false
					end
				elseif (htime <= 6 and htime > 4) or (htime >= 22 and htime < 23) then	
					-- сумерки
					local range = npc:range()
					local fov = npc:fov()
					if range and range > 80 then
						if npc_rank == "novice" then 
							npc:set_range(70)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "experienced" then 
							npc:set_range(75)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "veteran" then
							npc:set_range(77)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						elseif npc_rank == "master" then
							npc:set_range(80)
                                                        --log1(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
						end				
					end
				else
					-- день
					local range = npc:range()
					local fov = npc:fov()
					if range and range < 83 then
						npc:set_range(83)
					end
					if fov and fov < 125 then
						npc:set_fov(125)
					end
				end
			elseif (npc:best_danger() and not npc:best_enemy()) then
			-- если мы напуганы увеличим угол обзора
			-- имитиру€ опасливое осматривание по сторонам
			-- и повышенную внимательность
				local range = npc:range()
				local fov = npc:fov()
				if fov and fov < 135 then
					npc:set_fov(135)
					laststate[nid] = true
				end
			elseif npc:best_enemy() or (npc:best_enemy() and npc:best_danger()) then
			-- если мы заметили врага то увеличим и
			-- дальность обзора тоже, так как
			-- по сути нас уже заметили
				local range = npc:range()
				local fov = npc:fov()
				if range and range < 90 then
					npc:set_range(90)
                                        --logf(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
				end				
				if fov and fov < 138 then
					npc:set_fov(138)
                                        --logf(tostring(obj:name()).." fov "..tostring(fov).." range "..tostring(range))
				end
				laststate[nid] = false
			end
		end
	end
end


function npc_update(npc)
	if npc and npc:alive() then
		check_night(npc)
	end
end

local logf_console = nil

function logf( fmt, ... )
	logf_console = get_console()
	logf = logf_main
	logf_main( fmt, ... )
end

function logf_main( fmt, ... )
    local c = select( "#", ... )
    if c <= 0 then -- nothing to format
        logf_console:execute( ":" .. string.gsub( fmt, " ", "\160" ) )
    else
        logf_console:execute( ":" .. string.gsub( string.format( fmt, ... ), " ", "\160" ) )
    end
end


-- ухудшение зрени€ неписей ночью -- учитывает опыт непис€ - подразумева€ наличи ѕЌ¬ --
--------------------------- Copyright 2009 KamikaZze дл€ OGSE -------------------------