
class "verstak_start" (CUIScriptWnd)
function verstak_start:__init()super()
	self:InitControls()
	self:InitCallbacks()
end

function verstak_start:InitControls()
	local xml = CScriptXmlInit()
	self:Init(0,0,1024,768)
	if xml:is_16_9_mode() then
		xml:ParseFile("flyer\\ui_pult_dialog_16.xml")
	else
		xml:ParseFile("flyer\\ui_pult_dialog.xml")
	end

	self.background_main = xml:InitStatic("background_main", self)

	self.background_top = xml:InitStatic("background_main:background_top", self.background_main)
	self.background_bottom = xml:InitStatic("background_main:background_bottom", self.background_main)
	
	self.noise = xml:InitFrame("background_main:noise", self.background_main)

	self.textpan = xml:InitStatic("background_main:noise:textpan", self.noise)
	self.start = xml:Init3tButton("background_main:noise:start", self.noise)
	self:Register(self.start, "start")
	self.start2 = xml:Init3tButton("background_main:noise:start2", self.noise)
	self:Register(self.start2, "start2")
	self.start3 = xml:Init3tButton("background_main:noise:start3", self.noise)
	self:Register(self.start3, "start3")

	self.btn_exit = xml:Init3tButton("background_main:noise:btn_exit", self.noise)
	self:Register(self.btn_exit, "btn_exit")
end

function verstak_start:InitCallbacks()
	self:AddCallback("btn_exit",ui_events.BUTTON_DOWN,self.ExitBtn,self)
	self:AddCallback("start",ui_events.BUTTON_DOWN,self.Select_Bar,self)
	self:AddCallback("start2",ui_events.BUTTON_DOWN,self.Select_Yantar,self)
	self:AddCallback("start3",ui_events.BUTTON_DOWN,self.Select_Luch,self)
end
-----------------------------------------------------------------------------------------------------------------

function verstak_start:Select_Luch()
	olr.info("radbun_antena_mg")
	news_manager.send_tip(db.actor, game.translate_string("verstak_startSelect_Luch_0"))
	level.start_stop_menu(self, true)
end

function verstak_start:Select_Yantar()
	olr.info("radbun_antena_yan")
	news_manager.send_tip(db.actor, game.translate_string("verstak_startSelect_Yantar_0"))
	level.start_stop_menu(self, true)
end

function verstak_start:Select_Bar()
	olr.info("radbun_antena_bar")
	news_manager.send_tip(db.actor, game.translate_string("verstak_startSelect_Bar_0"))
	level.start_stop_menu(self, true)
end

function verstak_start:ExitBtn()
	level.start_stop_menu(self, true)
end












