----------------------------------------------------------------------------------
-- менеджер заданий для НПС (оффлайн)
-- hi_flyer 01.03.2019
-- olr_ai_tasks.script
----------------------------------------------------------------------------------

-- 1.	Добраться до Монолита, чтобы исполнилось желание
-- 2.	Найти причину возникновения Зоны и добиться ее исчезновения (поиск документов)
-- 3.	Месть другому сталкеру (старые счеты еще до Зоны)
-- 4.	Заработок (богатство, деньги на лечение)
-- 5.	В поисках приключений (адреналин, желание стать героем)
-- 6.	Попытки разобраться в себе
-- 7.	Побег в Зону (преступление, предательство, депрессия)

local global_task = {
    [1] = {name = "find_monolit", complete_target_walk = "aes_desant_wave2_look1"},
    [2] = {name = "reason_zone", complete_target_walk = "gen_find_exit_look"},
    [3] = {name = "revenge", complete_target_walk = "случайный путь смарта"},
    [4] = {name = "cash", complete_target_walk = "путь из зоны на кордоне"},
    [5] = {name = "tourism", complete_target_walk = "случайный путь "},
    [6] = {name = "find_himself", complete_target_walk = "случайный путь "},
    [7] = {name = "escape_in_zone", complete_target_walk = "случайный путь "}
}

local global_task_rnd_way = {
    [1] = {name = "esc_specnaz_way6"}, -- esc blokpost
    [2] = {name = "lvl1_escape_smart_terrain_0025_kamp_1"}, -- esc jaba
    [3] = {name = "komandir_esc_4_look"}, -- esc zavod
    [4] = {name = "lvl1_escape_smart_terrain_0014_home_1"}, -- esc right wood blokbost
    [5] = {name = "licker_look"}, -- esc derevnya
    [6] = {name = "lvl1_escape_smart_terrain_0023_kamp_1"}, -- esc wood
    [7] = {name = "way_dolg_gar_commander_look"}, -- gar dolg
    [8] = {name = "lvl2_garbage_smart_terrain_0034_kamp_1"}, -- gar angar
    [9] = {name = "lvl2_garbage_smart_terrain_0025_kamp_1"}, -- gar bandits
    [10] = {name = "kamp_center_svalka_nachalour"}, -- gar kran
    [11] = {name = "lvl3_agroprom_smart_terrain_0016_kamp_1"}, -- agr boloto
    [12] = {name = "lvl3_agroprom_smart_terrain_0024_kamp_1"}, -- arg nii
    [13] = {name = "lvl3_agroprom_smart_terrain_0005_home_1"}, -- agr voyaki
    [14] = {name = "lvl4_darkdolina_smart_terrain_0014_kamp_1"}, -- dol les
    [15] = {name = "x18_point_knock"}, -- dol stroika
    [16] = {name = "marlboro_men_camp"}, -- dol razvalini vint
    [17] = {name = "lvl5_bar_smart_terrain_united_dolg_stalkers_0001_kamp_1"}, -- bar	 bar
    [18] = {name = "lvl5_bar_smart_terrain_0029_home_1"}, -- bar rost vhod 1
    [19] = {name = "bar_mons_home_22"}, -- bar ozero mal
    [20] = {name = "agr_u_bandits_look6"}, -- bar ploshadka
    [21] = {name = "lvl5_bar_smart_terrain_0044_kamp_1"}, -- bar shkola
    [22] = {name = "ros_smart_stalker_bandits1_sleep_2"}, -- ros smart stalkers
    [23] = {name = "lvl6_rostok_smart_terrain_0002_kamp_1"}, -- ros stroika
    [24] = {name = "lvl7_yantar_smart_terrain_0020_home_1"}, -- yan scients monsters
    [25] = {name = "yan_zombies_home_bunker"}, -- yan dot
    [26] = {name = "lvl7_yantar_smart_terrain_0016_kamp_1"}, -- yan zomb derevnya
    [27] = {name = "lvl7_yantar_smart_terrain_0000_home_1"}, -- yan krovososovka
    [28] = {name = "suda_letit"}, -- yan fly bochki
    [29] = {name = "lvl9_military_smart_terrain_0003_home_1"}, -- mil pole
    [30] = {name = "lvl9_military_smart_terrain_home_1"}, -- mil krovososovka
    [31] = {name = "morak_way_walk"}, -- mil morak
    [32] = {name = "lvl9_military_smart_terrain_0004_home_1"}, -- mil vozle bazy
    [33] = {name = "lvl10_radar_smart_terrain_0000_1"}, -- rad lez
    [34] = {name = "lvl10_radar_smart_terrain_0003_home_1"}, -- rad anteny
    [35] = {name = "lvl11_deadcity_smart_terrain_0035_kamp_1"}, -- dead vozle bolota
    [36] = {name = "lvl11_deadcity_smart_terrain_0011_home_1"}, -- dead to swamp
    [37] = {name = "lvl11_deadcity_smart_terrain_0003_home_1"}, -- dead ludoed house
    [38] = {name = "lvl11_deadcity_smart_terrain_0019_home_1"}, -- dead home
    [39] = {name = "lvl11_deadcity_smart_terrain_0018_home_1"}, -- dead home 2
    [40] = {name = "pri_monolith_sniper_3_look"}, -- pri koop
    [41] = {name = "near_left_hand_kamp"}, -- pri magaz
    [42] = {name = "lvl13_prip_smart_terrain_0003_home_1"}, -- pri  skola
    [43] = {name = "lvl13_prip_smart_terrain_0000_home_1"}, -- pri kran
    [44] = {name = "aes_tourism_findtarget1"}, -- chaes geners
    [45] = {name = "aes_cash_findtarget1"}, -- chaes krai
    [46] = {name = "lvltwele_boness"}, -- lvl12 hata
    [47] = {name = "gar_lesok_esc_pere"},
     -- gar
    [48] = {name = "gar_kucha_dol"},
    [49] = {name = "gar_kucha_one"},
    [50] = {name = "gar_holm_left"},
    [51] = {name = "gar_agr_niz"},
    [52] = {name = "lvl2_garbage_smart_terrain_0032_home_1"},
    [53] = {name = "gar_nizina"},
    [54] = {name = "lvl2_garbage_smart_terrain_0003_home_1"},
    [55] = {name = "gar_left_angar"},
    [56] = {name = "gar_holm_left"},
    [57] = {name = "gar_sever_angar"},
    [58] = {name = "lvl2_garbage_smart_terrain_0004_home_1"},
    [59] = {name = "lvl2_garbage_smart_terrain_0008_home_1"},
    [60] = {name = "gar_smart_bandit_2_guard_3_walk"},
    [61] = {name = "gar_lesok_reka"},
    [62] = {name = "lvl2_garbage_smart_terrain_0002_home_1"},
    [63] = {name = "gar_tunel_right"},
    [64] = {name = "lvl2_garbage_smart_terrain_0025_kamp_1"},
    [65] = {name = "gar_tennel_left"},
    [66] = {name = "agr_left_holm"},
    [67] = {name = "agr_centr_holm"},
    [68] = {name = "agr_holm_right"},
    [69] = {name = "agr_holm_feft_mal"},
    [70] = {name = "agr_boar_nest_home_1"},
    [71] = {name = "agr_kazarma_one"},
    [72] = {name = "agr_rad_nizina"},
    [73] = {name = "agr_boloto"},
    [74] = {name = "agr_kolbat_place"},
    [75] = {name = "dol_razlavin_band"},
    [76] = {name = "dar_tunnel_midl"},
    [77] = {name = "kamp_center_slizni"},
    [78] = {name = "dar_garazh_midl"},
    [79] = {name = "dar_plen_house"},
    [80] = {name = "dar_garaz_razval"},
    [81] = {name = "dar_vint_house"},
    [82] = {name = "dar_holm_garb"},
    [83] = {name = "dar_pre_holm"},
    [84] = {name = "dar_ugol_holm"},
    [85] = {name = "dar_ugol_lab"},
    [86] = {name = "bar_dogs_holm"},
    [87] = {name = "bar_krilzo"},
    [88] = {name = "bar_zakol_house"},
    [89] = {name = "bar_house_anom"},
    [90] = {name = "bar_det_plos"},
    [91] = {name = "bar_actor_house"},
    [92] = {name = "lvl5_bar_smart_terrain_0049_kamp_1"},
    [93] = {name = "bar_dolg_holm"},
    [94] = {name = "bar_pole_one"},
    [95] = {name = "bar_pole_two"},
    [96] = {name = "bar_pole_tri"},
    [97] = {name = "bar_ros_pere"},
    [98] = {name = "lvl5_bar_smart_terrain_0034_home_1"},
    [99] = {name = "bar_boloro"},
    [100] = {name = "bar_boars_home_22"},
    [101] = {name = "lead_ohotik_pl_walk"},
    [102] = {name = "bar_magnit_grop"},
    [103] = {name = "bar_pamatnik"},
    [104] = {name = "ros_vorota"},
    [105] = {name = "ros_garaz"},
    [106] = {name = "ros_budka"},
    [107] = {name = "ros_kinoteatr"},
    [108] = {name = "ros_hidden"},
    [109] = {name = "ros_postancia"},
    [110] = {name = "ros_krisha"},
    [111] = {name = "ros_rad_konts"},
    [112] = {name = "ros_zagorodka"},
    [113] = {name = "ros_anom_lesok"},
    [114] = {name = "ros_stroika"},
    [115] = {name = "ros_kod_house"},
    [116] = {name = "ros_ugol"},
    [117] = {name = "ros_bukda"},
    [118] = {name = "ros_darazii"},
    [119] = {name = "ros_bukdara"},
    [120] = {name = "ros_mogoanom"},
    [121] = {name = "ros_komlpeks"},
    [122] = {name = "ros_ugolkompl"},
    [123] = {name = "ros_budkaugol"},
    [124] = {name = "yan_angar"},
    [125] = {name = "yan_vagon"},
    [126] = {name = "yan_psi_ugol"},
    [127] = {name = "yan_fuel_st"},
    [128] = {name = "yan_ribhouse"},
    [129] = {name = "yan_krovohouse"},
    [130] = {name = "yan_vodonap"},
    [131] = {name = "yan_stoyanka"},
    [132] = {name = "yan_himeraplace"},
    [133] = {name = "yan_olddead"},
    [134] = {name = "mil_torad"},
    [135] = {name = "mil_choppa"},
    [136] = {name = "mil_holm_vagon"},
    [137] = {name = "mil_barlook"},
    [138] = {name = "mil_neutrals"},
    [139] = {name = "mil_bazaugol"},
    [140] = {name = "mil_gzhde"},
    [141] = {name = "mil_seredina"},
    [142] = {name = "mil_hose"},
    [143] = {name = "mil_hoseee"},
    [144] = {name = "rad_ugoll"},
    [145] = {name = "rad_phtest"},
    [146] = {name = "rad_house"},
    [147] = {name = "ded_podezd"},
    [148] = {name = "ded_svoboda"},
    [149] = {name = "ded_anom_place"},
    [150] = {name = "ded_skola"},
    [151] = {name = "ded_nizina"},
    [152] = {name = "pri_sportzal"},
    [153] = {name = "pri_ploshad"},
    [154] = {name = "pri_visotka"},
    [155] = {name = "pri_hostel"},
    [156] = {name = "pri_shkola"},
    [157] = {name = "cha_plos"},
    [158] = {name = "cha_lenin"},
    [159] = {name = "cha_nil_sevendok"},
    [160] = {name = "cha_strelook"},
    [161] = {name = "cha_vorola"}
}

-- регистрация основной миссии при появлении в зоне (касается только тех сталкеров что спавнятся через респавн!)
function on_spawn_npc(obj)
    if obj and IsStalker(obj) and xvars.npcs_tasks then
        if obj:community() == "monolith" or obj:community() == "military" or obj:community() == "zombied" then
            return
        end
        if not xvars.npcs_tasks[obj:name()] then
            local s_name = game.translate_string(obj:name())
            if s_name then
                local rndpos = math.random(#global_task)
                local rnd_quest = global_task[rndpos].name

                xvars.npcs_tasks[obj:name()] = game.translate_string(rnd_quest)

                if xvars.npcs_tasks[obj:name()] then
                    --printf("REG NEW npc task ["..obj:name().."] - main task - ["..rnd_quest.."] on level - ["..obj.level_name.."]")
                    set_maintask_substates(obj, rnd_quest) -- установка подзадач для основного квеста
                end
            end
        end
    end
end

-------------smart_terrain-----
function has_task(obj)

	if not xvars or not xvars.npcs_tasks then return false end -- Так нужно так как se_stalker во время реги сталкера уже дёргаем ему первый апдейт который выбирает смарт куда тот пойдёт.
															   -- и это может происходить пока у нас нет xvars или xvars.npcs_tasks, поэтому проверяем на наличие онных
	
    if obj and IsStalker(obj) then
        --торговля бар
        if xvars.npc_ofl_trade[obj:name()] == true then
            return true
        end

        -- торговля янтарь
        if xvars.npc_ofl_trade_yan[obj:name()] == true then
            return true
        end

        -- глоб задачи
        -- добраться до монолита
        if xvars.npcs_tasks[obj:name()] == "find_monolit" then
            -- Найти причину возникновения Зоны и добиться ее исчезновения (поиск документов)
            if precondition_find_monolot(obj) then
                return true
            end
        elseif xvars.npcs_tasks[obj:name()] == "reason_zone" then
            -- Месть сталкеру
            if precondition_reason_zone(obj) then
                return true
            end
        elseif xvars.npcs_tasks[obj:name()] == "revenge" and xvars.npcs_tasks_rndway[obj:name()] ~= nil then
            -- Ппаднять бабла
            return true
        elseif xvars.npcs_tasks[obj:name()] == "cash" and xvars.npcs_tasks_rndway[obj:name()] ~= nil then
            -- Ткризм
            return true
        elseif xvars.npcs_tasks[obj:name()] == "tourism" and xvars.npcs_tasks_rndway[obj:name()] ~= nil then
            -- Поиск себя
            return true
        elseif xvars.npcs_tasks[obj:name()] == "find_himself" and xvars.npcs_tasks_rndway[obj:name()] ~= nil then
            return true
        end
    end

    return false
end

-- выполняется если есть has_task выше
function get_task_walk(obj)
    -- офл торговля бар
    if IsStalker(obj) and xvars.npc_ofl_trade[obj:name()] == true then
        --olr.add_spot_on_map( obj.id,"red_location"," идёт торговать в бар офлайн "..obj:name().."")
        --news_manager.send_tip(db.actor, "сталкер "..obj:name().." идёт торговать в бар в оффлайне", nil, "dolg", 15000)
        return "serogas_look"
    end
    -- офл торговля янтарь
    if IsStalker(obj) and xvars.npc_ofl_trade_yan[obj:name()] == true then
        --olr.add_spot_on_map( obj.id,"red_location"," идёт торговать в янтарь офлайн "..obj:name().."")
        --news_manager.send_tip(db.actor, "сталкер "..obj:name().." идёт торговать в янтарь в оффлайне", nil, "dolg", 15000)
        return "proff_prilavok_look"
    end

    -- глоб задачи
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "find_monolit" then
        return "sarkoy_cutscene_walk"
    end

    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "reason_zone" then
        return "gen_find_exit_look"
    end

    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "revenge" then
        if not precondition_revenge_is_dead(obj) then
            local waycash = xvars.npcs_tasks_rndway[obj:name()]
            if waycash then
                local waycashname = game.translate_string(waycash)
                if waycashname then
                    --printf("has tourism rnd way - "..waycashname.." ")
                    return waycashname
                end
            end
        else
            --printf("цель убита - тикаем из зоны")
            return "esc_garage_out_look" -- тикаем из зоны на кордоне
        end
    end

    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "cash" then
        local waycash = xvars.npcs_tasks_rndway[obj:name()]
        if waycash then
            local waycashname = game.translate_string(waycash)
            if waycashname then
                --printf("has cash rnd way - "..waycashname.." ")
                return waycashname
            end
        end
    end

    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "tourism" then
        local waycash = xvars.npcs_tasks_rndway[obj:name()]
        if waycash then
            local waycashname = game.translate_string(waycash)
            if waycashname then
                --printf("has tourism rnd way - "..waycashname.." ")
                return waycashname
            end
        end
    end

    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "find_himself" then
        if not precondition_find_himself(obj) then
            local waycash = xvars.npcs_tasks_rndway[obj:name()]
            if waycash then
                local waycashname = game.translate_string(waycash)
                if waycashname then
                    --printf("has find_himself rnd way - "..waycashname.." ")
                    return waycashname
                end
            end
        else
            return "esc_garage_out_look" -- тикаем из зоны на кордоне
        end
    end

    --printf(" !AHTUNG - go to [escccc_cutscene_walk]  "..obj:name().." set new ")
    --news_manager.send_tip(db.actor, " !AHTUNG - go to [escccc_cutscene_walk]  "..obj:name().."  идёт под смарт  "..obj.level_name.."  ", nil, "dolg", 15000)
    --olr.add_spot_on_map( obj.id,"green_location",obj:name() )
    --this.set_obj_rndway(obj)
    --return "escccc_cutscene_walk"  -- default Jaba's place
end

local flgmond = false
local flgmondr = false

-- проверка выполнения основного квеста. выполняется если есть has_task выше
function check_complete_main(obj)
    -- офл торговля бар
    if IsStalker(obj) and xvars.npc_ofl_trade[obj:name()] == true and obj.level_name == "l05_bar" then
        local bar_pos = vector():set(-107, -90, -231)
        if obj.position:distance_to(bar_pos) < 20 then
            --news_manager.send_tip(db.actor, "сталкер "..obj:name().." пришел в бар и торгует сейчас", nil, "dolg", 15000)
            olr_ofl_trade.on_point_bar(obj)
            amk_offline_alife.now_trade_ofl_bar(obj)
        end
    end
    -- офл торговля янтарь
    if IsStalker(obj) and xvars.npc_ofl_trade_yan[obj:name()] == true and obj.level_name == "l07_yantar" then
        local yan_pos = vector():set(-177, 6, 177)
        if obj.position:distance_to(yan_pos) < 10 then
            --news_manager.send_tip(db.actor, "сталкер "..obj:name().." пришел в янтарь и торгует сейчас", nil, "dolg", 15000)
            xvars.npc_ofl_trade_yan[obj:name()] = nil
            olr_ofl_trade.on_point_yan(obj)
        end
    end

    -- глоб задачи
    -- добраться до монолита и загадать желание (идем в саркофаг)
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "find_monolit" then
        local monolit_pos = vector():set(20, 51, 25)
        if obj.level_name == "l14u_sarcofag" and obj.position:distance_to(monolit_pos) < 20 then
            local rndm = math.random(1, 10)
            if rndm == 3 then
                local bos = level.object_by_id(obj.id)
                if bos then
                    bos:kill(bos)
                end
                local pk = get_netpk(obj, 1)
                if pk:isOk() then
                    local data = pk:get()
                    local name = data.character_name
                    data.health = 0
                    data.updhealth = 0
                    pk:set(data)
                    smart_terrain.on_death(obj.id)
                    if flgmond == false then
                        if level.name() == "l15_generators" then
                            return
                        end
                        news_manager.send_tip(db.actor,game.translate_string("st_olr_ai_tasks_monolith_searcher_1") .." " .. name .. " " .. game.translate_string("st_olr_ai_tasks_monolith_searcher_2"),1,"default",15000)
                        flgmond = true
                    end
                end
            end
        end
    end
    -- Найти причину возникновения Зоны и добиться ее исчезновения (добраться на генераторы)
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "reason_zone" then
        if obj.level_name == "l15_generators" then
            local rndstn = math.random(1, 4)
            if rndstn == 2 then
                local bos = level.object_by_id(obj.id)
                if bos then
                    bos:kill(bos)
                end
                local pk = get_netpk(obj, 1)
                if pk:isOk() then
                    local data = pk:get()
                    local name = data.character_name
                    data.health = 0
                    data.updhealth = 0
                    pk:set(data)
                    smart_terrain.on_death(obj.id)
                    if flgmondr == false then
                        if level.name() == "l15_generators" then
                            return
                        end
                        news_manager.send_tip(db.actor,game.translate_string("st_olr_ai_tasks_destruction_seeker_1") .." " .. name .. " " .. game.translate_string("st_olr_ai_tasks_destruction_seeker_2"),1,"news",15000)
                        flgmondr = true
                    end
                end
            end
        end
    end
    -- Месть сталкеру
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "revenge" then
        if this.precondition_revenge_is_dead(obj) then
            --olr.add_spot_on_map( obj.id,"green_location", " revenge go out "..obj:name().."" )
            --news_manager.send_tip(db.actor, "у сталкера "..obj:name().."  месть мертва - уходим из зоны сейчас на уровне - "..obj.level_name.."   "..obj.position.x.." - "..obj.position.y.." - "..obj.position.z.."  ", nil, "dolg", 15000)
            this.away_from_zone_revenge(obj)
        else
            -- ищем дальше - устанавливаем рнд путь гуляния
            this.set_rnd_way_walk(obj)
        end
    end
    -- Поднял бабла
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "cash" then
        if xvars.cash_need_summa_has[obj:name()] == true then
            -- собрали нужное колво денег - валим с зоны
            --news_manager.send_tip(db.actor, "у сталкера Поднял бабла "..obj:name().."  Поднял бабла- уходим из зоны сейчас на уровне - "..obj.level_name.." ", nil, "dolg", 15000)
            this.away_from_zone_cash(obj)
        else
            -- собираем бабки дальше - устанавливаем рнд путь гуляния
            this.set_rnd_way_walk(obj)
        end
    end
    -- Туризм
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "tourism" then
        if this.precondition_tourism(obj) then
            --news_manager.send_tip(db.actor, "у сталкера "..obj:name().."  натуристился - уходим из зоны сейчас на уровне - "..obj.level_name.." ", nil, "dolg", 15000)
            this.away_from_zone_tourism(obj)
        else
            -- туристим дальше - устанавливаем рнд путь гуляния
            this.set_rnd_way_walk(obj)
        end
    end
    -- Нашли себя
    if IsStalker(obj) and xvars.npcs_tasks[obj:name()] == "find_himself" then
        if this.precondition_find_himself(obj) then
            --news_manager.send_tip(db.actor, "у сталкера "..obj:name().."  нашёл себя - уходим из зоны сейчас на уровне - "..obj.level_name.." ", nil, "dolg", 15000)
            --olr.add_spot_on_map( obj.id,"green_location", obj:name() )
            this.away_from_zone(obj)
        else
            -- ищем себя дальше - устанавливаем рнд путь гуляния
            this.set_rnd_way_walk(obj)
        end
    end
end
-------------smart_terrain-----

function set_rnd_way_walk(obj)
    local xpath = xvars.npcs_tasks_rndway[obj:name()]
    if xpath then
        local rnd_path = patrol(xpath)
        local rnd_path_vert = rnd_path:level_vertex_id(0)
        if tostring(obj.m_level_vertex_id) == tostring(rnd_path_vert) then
            --olr.add_spot_on_map( obj.id,"green_location", obj:name() )
            --local itms = table.getn(amk_offline_alife.items[obj.id]) or 0  ставим новый итемов - "..itms.."
            --news_manager.send_tip(db.actor, " "..obj:name().." -- "..xvars.npcs_tasks[obj:name()].."  пришёл на свой путь - "..xpath.."  на "..obj.level_name.."  ", nil, "dolg", 15000)
            -- todo если можем (есть экипировка) то гуляем дальше, если нет идём в бар
            this.set_obj_rndway(obj)
            amk_offline_alife.process_trade(obj) -- переберем свой хабар
            amk_offline_alife.offline_alife(tostring(obj.level_name))
            local rndrank = math.random(10, 60)
            obj:set_rank(obj:rank() + rndrank)
        else
            --printf(" stalker идёт "..tostring(obj.m_level_vertex_id).."  на "..tostring(rnd_path_vert).." ")
        end
    end
end

function set_obj_rndway(obj)
    local rndway = math.random(#global_task_rnd_way)
    local rnd_task_way = global_task_rnd_way[rndway].name
    --printf(" set_obj_rndway "..obj:name().." set rndway - "..rnd_task_way.." ")
    xvars.npcs_tasks_rndway[obj:name()] = game.translate_string(rnd_task_way)
    --olr.add_spot_on_map( obj.id,"red_location"," идёт на новый путь  "..obj:name().." --- "..game.translate_string(rnd_task_way).." ")
end

function away_from_zone_cash(obj)
    if obj:alive() and obj.level_name == "l01_escape" then
        local rnd = math.random(1, 12)
        if rnd == 2 then
            xvars.cash_need_summa_has[obj:name()] = nil
            local wait_time = 0
            wait_time = time_global() + 500
            level.add_call(
                function()
                    return time_global() > wait_time
                end,
                function()
                    olr.to_offline(obj:name())
                end
            )
            local pk = get_netpk(obj, 1)
            if pk:isOk() then
                local data = pk:get()
                local name = data.character_name
                data.health = 0
                data.updhealth = 0
                pk:set(data)
                smart_terrain.on_death(obj.id)
                news_manager.send_tip(db.actor,game.translate_string("st_olr_ai_tasks_cashmoney") .." " .. name .. " " .. game.translate_string("st_olr_ai_tasks_cashmoney_2"),5,"default",15000)
            end
        --printf("away from zone cash kill - "..obj:name().." ")
        end
    end
end

function away_from_zone_tourism(obj)
    if obj:alive() and obj.level_name == "l14_stancia" then
        local rnd = math.random(1, 10)
        if rnd == 3 then
            local wait_time = 0
            wait_time = time_global() + 500
            level.add_call(
                function()
                    return time_global() > wait_time
                end,
                function()
                    olr.to_offline(obj:name())
                end
            )
            local pk = get_netpk(obj, 1)
            if pk:isOk() then
                local data = pk:get()
                local name = data.character_name
                data.health = 0
                data.updhealth = 0
                pk:set(data)
                smart_terrain.on_death(obj.id)
                news_manager.send_tip(db.actor,game.translate_string("st_olr_ai_tasks_tourism") .." " .. name .. " " .. game.translate_string("st_olr_ai_tasks_tourism_2"),5,"default",15000)
            end
        --printf("away from zone tourism kill - "..obj:name().." ")
        end
    end
end

function away_from_zone_revenge(obj)
    if obj and obj.level_name == "l01_escape" then
        local yan_pos = vector():set(147, 0, -13)
        if obj.position:distance_to(yan_pos) < 20 then
            local wait_time = 0
            wait_time = time_global() + 200
            level.add_call(
                function()
                    return time_global() > wait_time
                end,
                function()
                    olr.to_offline(obj:name())
                end
            )
            local pk = get_netpk(obj, 1)
            if pk:isOk() then
                local data = pk:get()
                local name = data.character_name
                data.health = 0
                data.updhealth = 0
                pk:set(data)
                smart_terrain.on_death(obj.id)
                news_manager.send_tip(db.actor,"" .. name .. " " .. game.translate_string("st_olr_ai_tasks_revenger"),nil,"unknown",39000)
                news_manager.send_tip(db.actor,game.translate_string("st_olr_ai_tasks_revenger_2") .." " .. name .. " " .. game.translate_string("st_olr_ai_tasks_revenger_3"),5,"default",15000)
            end
        end
    end
end

function away_from_zone(obj)
    if obj and obj.level_name == "l01_escape" then
        local yan_pos = vector():set(147, 0, -13)
        if obj.position:distance_to(yan_pos) < 20 then
            local wait_time = 0
            wait_time = time_global() + 200
            level.add_call(
                function()
                    return time_global() > wait_time
                end,
                function()
                    olr.to_offline(obj:name())
                end
            )
            local pk = get_netpk(obj, 1)
            if pk:isOk() then
                local data = pk:get()
                local name = data.character_name
                data.health = 0
                data.updhealth = 0
                pk:set(data)
                smart_terrain.on_death(obj.id)
                news_manager.send_tip(db.actor, game.translate_string("st_olr_ai_tasks_leave_zone_1").." "..name.." "..game.translate_string("st_olr_ai_tasks_leave_zone_2"),nil, "news", 15000)
                news_manager.send_tip(db.actor, game.translate_string("st_olr_ai_tasks_leave_zone_3").." "..name.." "..game.translate_string("st_olr_ai_tasks_leave_zone_4"), 5, "news", 15000)
            end
        end
    end
end

function set_maintask_substates(obj, rnd_quest)
	-- месть сталкеру
	if xvars.npcs_tasks[obj:name()] == "revenge" then
		local places = {}
		for _, kill in ipairs(olr_offline_walk.tabst) do
			if kill then
				if IsStalker(kill) then
					if kill.alive and kill:alive() and kill.level_name == "l01_escape" or kill.level_name == "l02_garbage" or kill.level_name == "l03_agroprom" or kill.level_name == "l04_darkvalley" then
						if not olr_protected.is_no_offline_alife_obj(kill:name()) then
							table.insert(places, kill)
						end
					end
				end
			end
		end
		if #places > 0 then
			local rand_kill = places[math.random(#places)]
			xvars.npcs_tasks_revenge_targets[obj:name()] = rand_kill:name()
		end
	--printf("revenge "..obj:name().." - set revenge target "..rand_kill:name().." ")
	end
end

--------------------------------------------------------------------------
-- !! в этих прекондишенах ещё добавить проверку например на колво денег (второстепенные квесты)
-- !! это проверка на то, можем ли мы идти по пути

function precondition_find_himself(obj)
    if obj:rank() >= 3150 then
        return true
    end
end

function precondition_tourism(obj)
    if obj:rank() >= 1650 and has_alife_info("bun_antenna_off") then
        return true
    end
end

function precondition_cash(obj)
    if xvars.cash_need_summa_has[obj:name()] == true then
        return true
    end
end

function precondition_find_monolot(obj)
    if obj:rank() >= 250 and has_alife_info("bun_antenna_off") then
        return true
    end
end

function precondition_reason_zone(obj)
    -- условие: если мы в симуляции нашли какой нибудь документ
    --if xvars.npcs_who_find_docs_id and xvars.npcs_who_find_docs_id[obj:name()] and xvars.npcs_who_find_docs_id[obj:name()] == obj.id then
    --printf("we find docs and can walk to generators "..obj:name().."")
    if IsStalker(obj) and obj:rank() >= 200 and has_alife_info("bun_antenna_off") then
        return true
    end
    --end
end

function precondition_revenge(obj)
    local targetkill = xvars.npcs_tasks_revenge_targets[obj:name()]
    if targetkill then
        local se_obj = alife():object(targetkill)
        if se_obj and se_obj:alive() then
            --printf("цель мести "..se_obj:name().." жива  - ищем её для "..obj:name().."  ")
            return true
        end
        return false
    end
end

function precondition_revenge_is_dead(obj)
    local targetkill = xvars.npcs_tasks_revenge_targets[obj:name()]
    if targetkill then
        local se_obj = alife():object(targetkill)
        if se_obj and not se_obj:alive() then
            return true
        end
        return false
    end
end

function set_walkers_rndways()
    local cnt = 0
    local sim = alife()
    for id = 1, 65534 do
        local kill = sim:object(id)
        if kill and IsStalker(kill) and kill:alive() then
            if xvars.npcs_tasks[kill:name()] == "cash" or xvars.npcs_tasks[kill:name()] == "tourism" or xvars.npcs_tasks[kill:name()] == "revenge" or xvars.npcs_tasks[kill:name()] == "find_himself" then
                cnt = cnt + 1
                --olr.add_spot_on_map( kill.id,"controller_spotmap",kill:name() )
                local rndway = math.random(#global_task_rnd_way)
                local rnd_task_way = global_task_rnd_way[rndway].name
                --printf(" "..kill:name().." set rndway - "..rnd_task_way.." ")
                xvars.npcs_tasks_rndway[kill:name()] = game.translate_string(rnd_task_way)
                local rnd = math.random(1, 2)
                if rnd == 1 then
                    --printf(" SET no RND WAY "..kill:name().." go to base ")
                    --olr.add_spot_on_map( kill.id,"red_location"," идёт в лагерь  "..kill:name().."")
                    xvars.npcs_tasks_rndway[kill:name()] = nil
                end
            end
        end
    end
    printf("olr_ai_tasks.set_walkers_rndways count = " .. tostring(cnt) .. "")
end