-- hi_flyer 03.17.19
-- удаляем тушки НПС, + гниение трупов (Проф что-то говорил про гниение...)

local level_name = level.name()
local nodelflag = false

function del_corpse(obj)
	local tostr = tostring
	if obj and not olr_protected.is_no_offline_alife_obj(obj:name()) then
		local dist = obj:position():distance_to(db.actor:position())

		if dist > 25 then
			-- жабы доска
			local esobj = game.translate_string(xvars.quest_two_target)
			if esobj then
				local eobj = alife():object(esobj)
				if eobj then
					if tostr(eobj:name()) == tostr(obj:name()) then
						return
					end
				end
			end

			-- бар доска
			local esobj = game.translate_string(xvars.quest_two_target_bar)
			if esobj then
				local eobj = alife():object(esobj)
				if eobj then
					if tostr(eobj:name()) == tostr(obj:name()) then
						return
					end
				end
			end

			-- если пустой труп
			if obj:ruck_count() == 0 then
				--log1("dead without habar "..obj:name().." DEL ")
				this.spawn_rotten(obj)
				this.del_now(obj)
				return
			end

			-- прошёл выброс - по флагу удаляем труп со всем хабаром кроме трупов с квестов итем
			if xvars.npc_del_afterblow[obj:name()] == true then
				obj:iterate_inventory(
					function(obj, item)
						if item then
							--log1("deadmen "..obj:name().." with habar - "..item:name().." ")
							if olr.bad_items[item:section()] == true then
								--news_manager.send_tip(db.actor, "АХТУНГ в трупе есть важный bad_items "..item:name().." ", nil, "hero", 9000)
								nodelflag = true
								return -- сразу заканчиваем, если итем есть нефиг дальше ковырять
							end
							if ini_sys:line_exist(item:section(), "quest_item") and ini_sys:r_bool(item:section(), "quest_item") == true then
								--news_manager.send_tip(db.actor, "АХТУНГ в трупе есть важный quest_item "..item:name().." ", nil, "dolg", 9000)
								nodelflag = true
								return -- сразу заканчиваем, если итем есть нефиг дальше ковырять
							end
						end
					end,
					obj
				)
				if nodelflag == false then
					this.spawn_rotten(obj)
					this.del_now(obj)
				end
			end
		end
	end
end

function del_now(obj)
	xvars.npc_actor_use[obj:name()] = nil

	if xvars.npc_seeing_news[obj:name()] ~= nil then
		xvars.npc_seeing_news[obj:name()] = nil
	end
	if xvars.npc_del_afterblow[obj:name()] ~= nil then
		xvars.npc_del_afterblow[obj:name()] = nil
	end
	if xvars.npc_jobs_foractor_status[obj:name()] ~= nil then
		xvars.npc_jobs_foractor_status[obj:name()] = nil
	end
	if xvars.npc_jobs_foractor_target[obj:name()] ~= nil then
		xvars.npc_jobs_foractor_target[obj:name()] = nil
	end
	
	local wait_time = 0
	wait_time = time_global() + 900
	level.add_call(
		function()
			return time_global() > wait_time
		end,
		function()
			olr.del(obj)
		end
	)
end

function spawn_rotten(obj)
	local mrandom = math.random
	if level_name == "lvl14_stancia" or level_name == "lvl5_bar" then
		return
	end
	local rnd = mrandom(1, 8)
	if rnd == 1 then
		local bobj2 = alife():create("dead_body_skelet", obj:position(), obj:level_vertex_id(), obj:game_vertex_id())
		level.client_spawn_manager():add(bobj2.id, 0,
			function(id, obj)
				if obj then
					local h = hit()
					h.draftsman = obj
					h.type = hit.strike
					h:bone("head")
					h.direction = vector():set(mrandom(1), 0.1, mrandom(1))
					h.power = 0.1
					h.impulse = mrandom(1, 3)
					obj:hit(h)
				end
			end
		)
	elseif rnd == 2 then
		local bobj2 = alife():create("dead_body_skelet2", obj:position(), obj:level_vertex_id(), obj:game_vertex_id())
		level.client_spawn_manager():add(bobj2.id, 0,
			function(id, obj)
				if obj then
					local h = hit()
					h.draftsman = obj
					h.type = hit.strike
					h:bone("head")
					h.direction = vector():set(mrandom(1), 0.1, mrandom(1))
					h.power = 0.2
					h.impulse = mrandom(1, 3)
					obj:hit(h)
				end
			end
		)
	end
end
