--[[
	-- Script name: olr_newnpc_eqp.script
	-- Description: Скрипт раздаёт оружие непесям (Только для респавновых, не для тех кто заранее заспавнен)
	-- Author: theysani
	-- Last edit: 12.02.26
--]]

--[[

Списки оружия по группировкам и рангу:

Бандит новичок - wpn_pm, wpn_pb, wpn_fort, wpn_bm16, wpn_toz34
Бандит опытный - wpn_pm, wpn_pb, wpn_fort, wpn_aps, wpn_bm16, wpn_toz34, wpn_mp5, wpn_akms
Бандит ветеран - wpn_fort, wpn_aps, wpn_hpsa, wpn_mp5, wpn_akms, wpn_ak74
Бандит мастер - wpn_aps, wpn_walther, wpn_colt1911, wpn_ak74, wpn_lr300

Слизень новичок - wpn_pm, wpn_pb, wpn_fort, wpn_bm16, wpn_toz34
Слизень опытный - wpn_pm, wpn_pb, wpn_fort, wpn_aps, wpn_bm16, wpn_toz34, wpn_mp5, wpn_akms
Слизень ветеран - wpn_fort, wpn_aps, wpn_hpsa, wpn_mp5, wpn_akms, wpn_ak74
Слизень мастер - wpn_aps, wpn_walther, wpn_colt1911, wpn_ak74, wpn_lr300

Сталкер новичок - wpn_pm, wpn_pb, wpn_fort, wpn_bm16, wpn_toz34
Сталкер опытный - wpn_pm, wpn_pb, wpn_fort, wpn_aps, wpn_hpsa, wpn_bm16, wpn_toz34, wpn_mp5, wpn_akms, wpn_ak74, wpn_lr300
Сталкер ветеран - wpn_aps, wpn_hpsa, wpn_colt1911, wpn_walther, wpn_ak74, wpn_lr300, wpn_wincheaster1300
Сталкер мастер - wpn_colt1911, wpn_sig220, wpn_usp, wpn_g36, wpn_val, wpn_vintorez, wpn_wincheaster1300

Долг новичок - wpn_pb, wpn_fort, wpn_aps, wpn_akms
Долг опытный - wpn_aps, wpn_hpsa, wpn_ak74
Долг ветеран - wpn_colt1911, wpn_walther, wpn_lr300, wpn_vintorez, wpn_val
Долг мастер - wpn_aps, wpn_usp, wpn_fn2000, wpn_groza, wpn_wincheaster1300, wpn_svu

Свобода новичок - wpn_pb, wpn_fort, wpn_akms, wpn_ak74
Свобода опытный - wpn_pb, wpn_fort, wpn_hpsa, wpn_ak74, wpn_lr300, wpn_vintorez
Свобода ветеран - wpn_colt1911, wpn_walther, wpn_g36, wpn_val
Свобода мастер - wpn_aps, wpn_colt1911, wpn_sig220, wpn_fn2000, wpn_groza, wpn_wincheaster1300, wpn_svd

Наемник новичок - wpn_aps, wpn_hpsa, wpn_ak74
Наемник опытный - wpn_aps, wpn_hpsa, wpn_ak74, wpn_lr300, wpn_wincheaster1300
Наемник ветеран - wpn_walther, wpn_colt1911, wpn_g36, wpn_vintorez
Наемник мастер - wpn_colt1911, wpn_usp, wpn_sig220, wpn_g36, wpn_val

Монолит новичок - wpn_aps, wpn_hpsa, wpn_akms, wpn_ak74
Монолит опытный - wpn_aps, wpn_walther, wpn_ak74, wpn_lr300, wpn_wincheaster1300
Монолит ветеран - wpn_colt1911, wpn_g36, wpn_val
Монолит мастер - wpn_usp, wpn_sig220, wpn_fn2000, wpn_groza, wpn_rg-6, wpn_svu

Ученый новичок: wpn_pm
Ученый опытный: wpn_fort
Ученый ветеран: wpn_aps, wpn_akms
Ученый мастер: wpn_hpsa, wpn_ak74

Небо новичок: wpn_pm, wpn_akms
Небо опытный: wpn_pm, wpn_fort, wpn_akms
Небо ветеран: wpn_pm, wpn_fort, wpn_aps, wpn_akms
Небо мастер: wpn_pm, wpn_fort, wpn_hpsa, wpn_ak74

Военный новичок: wpn_pm, wpn_akms
Военный опытный: wpn_pm, wpn_fort, wpn_akms
Военный ветеран: wpn_pm, wpn_hpsa wpn_fort, wpn_akms, wpn_ak74
Военный мастер: wpn_aps, wpn_hpsa, wpn_fort, wpn_ak74

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ссылка на тир-лист оружия - https://docs.google.com/spreadsheets/d/128LtOYGN1QQG-Monio_g4W48sRZ4i_8ffbc4tDLLjrc/edit?gid=0#gid=0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ранги по числам:
Новичок - от 0 до 300
Опытный - от 300 до 600
Ветеран - от 600 до 900
Мастер	- от 900

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Тир лист по секциями

S - prob = 0.1
A - prob = 0.3
B - prob = 0.5
C - prob = 0.7
D - prob = 0.9

Пистолеты
wpn_usp				- S
wpn_sig220			- S
wpn_colt1911		- A
wpn_walther			- A
wpn_hpsa			- B
wpn_aps				- B
wpn_fort			- C
wpn_pb				- C
wpn_pm				- D

ПП
wpn_mp5				- S

Дробовики
wpn_wincheaster1300	- S
wpn_toz34			- B
wpn_bm16			- C

Штурмовые винтовки
wpn_fn2000			- S
wpn_groza			- S
wpn_g36				- A 
wpn_val				- A
wpn_lr300			- B
wpn_ak74			- B
wpn_akms			- D

Снайперские винтовки
wpn_svu				- S
wpn_vintorez		- A
wpn_svd				- B

Остальное
wpn_rg-6			- S

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
В first не может быть любой секции кроме этих
wpn_usp - wpn_usp
wpn_sig220 - wpn_sig220
wpn_colt1911 - wpn_colt1911
wpn_walther - wpn_walther
wpn_hpsa - wpn_hpsa
wpn_aps - wpn_aps
wpn_fort - wpn_fort
wpn_pb - wpn_pb
wpn_pm - wpn_pm

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
В second могут быть все остальные секции кроме тех что есть в first
wpn_mp5 - wpn_mp5
wpn_wincheaster1300 - wpn_wincheaster1300
wpn_toz34 - wpn_toz34
wpn_bm16 - wpn_bm16
wpn_fn2000 - wpn_fn2000
wpn_groza - wpn_groza
wpn_g36 - wpn_g36
wpn_val - wpn_val
wpn_lr300 - wpn_lr300
wpn_ak74 - wpn_ak74
wpn_akms - wpn_akms
wpn_svu - wpn_svu
wpn_vintorez - wpn_vintorez
wpn_svd - wpn_svd
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--]]

local weapon_tables_blank = {
    bandit = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8},
            },
            second = {
                {section = "wpn_bm16", prob = 0.6},
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    sliznyaki = {
        novice = {
            first = {
            },
            second = {
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    stalker = {
        novice = {
            first = {
            },
            second = {
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    dolg = {
        novice = {
            first = {
            },
            second = {
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    freedom = {
        novice = {
            first = {
            },
            second = {
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    killer = {
        novice = {
            first = {
            },
            second = {
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    monolith = {
        novice = {
            first = {
            },
            second = {
            }
        },
        experienced = {
            first = {
            },
            second = {
            }
        },
        veteran = {
            first = {
            },
            second = {
            }
        },
        master = {
            first = {
            },
            second = {
            }
        }
    },
    ecologs = {
        novice = {
            first = {
            },
            second = {}
        },
        experienced = {
            first = {
            },
            second = {}
        },
        veteran = {
            first = {
            },
            second = {}
        },
        master = {
            first = {
            },
            second = {}
        }
    },
    sky = {
        novice = {
            first = {
            },
            second = {}
        },
        experienced = {
            first = {
            },
            second = {}
        },
        veteran = {
            first = {
            },
            second = {}
        },
        master = {
            first = {
            },
            second = {}
        }
    },
    military = {
        novice = {
            first = {
            },
            second = {}
        },
        experienced = {
            first = {
            },
            second = {}
        },
        veteran = {
            first = {
            },
            second = {}
        },
        master = {
            first = {
            },
            second = {}
        }
    }
}

local weapon_tables = {
    bandit = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.4}
            },
            second = {
                {section = "wpn_bm16", prob = 0.6},
                {section = "wpn_toz34", prob = 0.4}
            }
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.6},
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.6},
                {section = "wpn_aps", prob = 0.4}
            },
            second = {
                {section = "wpn_bm16", prob = 0.5},
                {section = "wpn_toz34", prob = 0.5},
                {section = "wpn_mp5", prob = 0.1},
                {section = "wpn_akms", prob = 0.6},
                {section = "wpn_aks74u", prob = 0.3}
            }
        },
        veteran = {
            first = {
                {section = "wpn_fort", prob = 0.3},
                {section = "wpn_aps", prob = 0.4},
                {section = "wpn_hpsa", prob = 0.4}
            },
            second = {
                {section = "wpn_mp5", prob = 0.4},
                {section = "wpn_akms", prob = 0.3},
                {section = "wpn_aks74u", prob = 0.5},
                {section = "wpn_ak74", prob = 0.4},
                {section = "wpn_l85", prob = 0.3},
                {section = "wpn_rpk", prob = 0.4},
                {section = "wpn_tiss", prob = 0.1}
            }
        },
        master = {
            first = {
                {section = "wpn_aps", prob = 0.4},
                {section = "wpn_walther", prob = 0.6},
                {section = "wpn_gsh", prob = 0.3}
            },
            second = {
                {section = "wpn_ak74", prob = 0.73},
                {section = "wpn_l85", prob = 0.59},
                {section = "wpn_lr300", prob = 0.52},
                {section = "wpn_spas12", prob = 0.32},
                {section = "wpn_wincheaster1300", prob = 0.24},
                {section = "wpn_rpk", prob = 0.22},
                {section = "wpn_rpk74", prob = 0.16},
                {section = "wpn_tiss", prob = 0.35}
            }
        }
    },
    sliznyaki = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.6}
            },
            second = {
                {section = "wpn_bm16", prob = 0.6},
                {section = "wpn_toz34", prob = 0.5}
            }
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.6},
                {section = "wpn_aps", prob = 0.5}
            },
            second = {
                {section = "wpn_bm16", prob = 0.6},
                {section = "wpn_toz34", prob = 0.5},
                {section = "wpn_mp5", prob = 0.1},
                {section = "wpn_akms", prob = 0.8}
            }
        },
        veteran = {
            first = {
                {section = "wpn_fort", prob = 0.6},
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5}
            },
            second = {
                {section = "wpn_mp5", prob = 0.1},
                {section = "wpn_akms", prob = 0.8},
                {section = "wpn_ak74", prob = 0.5}
            }
        },
        master = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_walther", prob = 0.3},
                {section = "wpn_colt1911", prob = 0.3}
            },
            second = {
                {section = "wpn_ak74", prob = 0.73},
                {section = "wpn_l85", prob = 0.59},
                {section = "wpn_lr300", prob = 0.52},
                {section = "wpn_spas12", prob = 0.32},
                {section = "wpn_wincheaster1300", prob = 0.24}
            }
        }
    },
    stalker = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.4}
            },
            second = {
                {section = "wpn_bm16", prob = 0.6},
                {section = "wpn_toz34", prob = 0.5}
            }
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.5},
                {section = "wpn_pb", prob = 0.5},
                {section = "wpn_fort", prob = 0.7},
                {section = "wpn_aps", prob = 0.4},
                {section = "wpn_hpsa", prob = 0.4}
            },
            second = {
                {section = "wpn_bm16", prob = 0.64},
                {section = "wpn_toz34", prob = 0.51},
                {section = "wpn_mp5", prob = 0.42},
                {section = "wpn_akms", prob = 0.68},
                {section = "wpn_aks74u", prob = 0.64},
                {section = "wpn_ak74", prob = 0.56},
                {section = "wpn_tiss", prob = 0.14},
                {section = "wpn_l85", prob = 0.45},
                {section = "wpn_rpk", prob = 0.31},
                {section = "wpn_lr300", prob = 0.52},
                {section = "wpn_svd", prob = 0.12},
                {section = "wpn_svu", prob = 0.06}
            }
        },
        veteran = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5},
                {section = "wpn_gsh", prob = 0.3},
                {section = "wpn_colt1911", prob = 0.3},
                {section = "wpn_walther", prob = 0.3}
            },
            second = {
                {section = "wpn_aks74u", prob = 0.34},
                {section = "wpn_ak74", prob = 0.52},
                {section = "wpn_lr300", prob = 0.50},
                {section = "wpn_l85", prob = 0.41},
                {section = "wpn_rpk", prob = 0.16},
                {section = "wpn_rpk74", prob = 0.24},
                {section = "wpn_vintorez", prob = 0.16},
                {section = "wpn_svd", prob = 0.16},
                {section = "wpn_svu", prob = 0.12},
                {section = "wpn_spas12", prob = 0.13},
                {section = "wpn_wincheaster1300", prob = 0.08}
            }
        },
        master = {
            first = {
                {section = "wpn_aps", prob = 0.25},
                {section = "wpn_colt1911", prob = 0.31},
                {section = "wpn_gsh", prob = 0.36},
                {section = "wpn_sig220", prob = 0.21},
                {section = "wpn_usp", prob = 0.16}
            },
            second = {
                {section = "wpn_ak74", prob = 0.16},
                {section = "wpn_g36", prob = 0.33},
                {section = "wpn_val", prob = 0.32},
                {section = "wpn_vintorez", prob = 0.34},
                {section = "wpn_rpk74", prob = 0.28},
                {section = "wpn_wincheaster1300", prob = 0.13}
            }
        }
    },
    dolg = {
        novice = {
            first = {
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.6},
                {section = "wpn_aps", prob = 0.5}
            },
            second = {
                {section = "wpn_akms", prob = 0.8}
            }
        },
        experienced = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5}
            },
            second = {
                {section = "wpn_ak74", prob = 0.73},
                {section = "wpn_aks74u", prob = 0.62},
                {section = "wpn_l85", prob = 0.55},
                {section = "wpn_akms", prob = 0.41},
                {section = "wpn_rpk", prob = 0.32},
                {section = "wpn_tiss", prob = 0.21},
                {section = "wpn_rpk74", prob = 0.15},
                {section = "wpn_svd", prob = 0.06}
            }
        },
        veteran = {
            first = {
                {section = "wpn_colt1911", prob = 0.3},
                {section = "wpn_walther", prob = 0.3}
            },
            second = {
                {section = "wpn_lr300", prob = 0.52},
                {section = "wpn_vintorez", prob = 0.38},
                {section = "wpn_val", prob = 0.36},
                {section = "wpn_spas12", prob = 0.21},
                {section = "wpn_svd", prob = 0.12},
                {section = "wpn_svu", prob = 0.08}
            }
        },
        master = {
            first = {
                {section = "wpn_gsh", prob = 0.3},
                {section = "wpn_usp", prob = 0.1}
            },
            second = {
                {section = "wpn_fn2000", prob = 0.24},
                {section = "wpn_groza", prob = 0.21},
                {section = "wpn_spas12", prob = 0.15},
                {section = "wpn_wincheaster1300", prob = 0.13},
                {section = "wpn_svu", prob = 0.11}
            }
        }
    },
    freedom = {
        novice = {
            first = {
                {section = "wpn_pb", prob = 0.6},
                {section = "wpn_fort", prob = 0.6}
            },
            second = {
                {section = "wpn_bm16", prob = 0.3},
                {section = "wpn_toz34", prob = 0.32},
                {section = "wpn_mp5", prob = 0.5},
                {section = "wpn_akms", prob = 0.74},
                {section = "wpn_aks74u", prob = 0.52},
                {section = "wpn_ak74", prob = 0.46},
                {section = "wpn_l85", prob = 0.24}
            }
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.43},
                {section = "wpn_pb", prob = 0.43},
                {section = "wpn_fort", prob = 0.45},
                {section = "wpn_aps", prob = 0.42},
                {section = "wpn_hpsa", prob = 0.46}
            },
            second = {
                {section = "wpn_bm16", prob = 0.21},
                {section = "wpn_toz34", prob = 0.22},
                {section = "wpn_mp5", prob = 0.30},
                {section = "wpn_aks74u", prob = 0.31},
                {section = "wpn_ak74", prob = 0.32},
                {section = "wpn_lr300", prob = 0.34},
                {section = "wpn_l85", prob = 0.38},
                {section = "wpn_akms", prob = 0.37},
                {section = "wpn_rpk", prob = 0.32},
                {section = "wpn_rpk74", prob = 0.31},
                {section = "wpn_tiss", prob = 0.35},
                {section = "wpn_vintorez", prob = 0.32},
                {section = "wpn_svd", prob = 0.12},
                {section = "wpn_svu", prob = 0.11},
                {section = "wpn_spas12", prob = 0.14},
                {section = "wpn_wincheaster1300", prob = 0.12}
            }
        },
        veteran = {
            first = {
                {section = "wpn_aps", prob = 0.31},
                {section = "wpn_colt1911", prob = 0.32},
                {section = "wpn_walther", prob = 0.37},
                {section = "wpn_gsh", prob = 0.35},
                {section = "wpn_sig220", prob = 0.33}
            },
            second = {
                {section = "wpn_aks74u", prob = 0.31},
                {section = "wpn_ak74", prob = 0.32},
                {section = "wpn_lr300", prob = 0.34},
                {section = "wpn_g36", prob = 0.35},
                {section = "wpn_rpk", prob = 0.24},
                {section = "wpn_rpk74", prob = 0.21},
                {section = "wpn_val", prob = 0.32},
                {section = "wpn_groza", prob = 0.3},
                {section = "wpn_vintorez", prob = 0.34},
                {section = "wpn_svd", prob = 0.14},
                {section = "wpn_svu", prob = 0.12},
                {section = "wpn_spas12", prob = 0.16},
                {section = "wpn_wincheaster1300", prob = 0.14}
            }
        },
        master = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_colt1911", prob = 0.3},
                {section = "wpn_sig220", prob = 0.1}
            },
            second = {
                {section = "wpn_fn2000", prob = 0.1},
                {section = "wpn_groza", prob = 0.1},
                {section = "wpn_vintorez", prob = 0.1},
                {section = "wpn_val", prob = 0.1},
                {section = "wpn_g36", prob = 0.1},
                {section = "wpn_wincheaster1300", prob = 0.1},
                {section = "wpn_svd", prob = 0.5}
            }
        }
    },
    killer = {
        novice = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5}
            },
            second = {
                {section = "wpn_l85", prob = 0.1},
                {section = "wpn_ak74", prob = 0.5}
            }
        },
        experienced = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5}
            },
            second = {
                {section = "wpn_aks74u", prob = 0.5},
                {section = "wpn_ak74", prob = 0.5},
                {section = "wpn_l85", prob = 0.5},
                {section = "wpn_lr300", prob = 0.5},
                {section = "wpn_spas12", prob = 0.1},
                {section = "wpn_wincheaster1300", prob = 0.1}
            }
        },
        veteran = {
            first = {
                {section = "wpn_walther", prob = 0.3},
                {section = "wpn_colt1911", prob = 0.3}
            },
            second = {
                {section = "wpn_rpk74", prob = 0.1},
                {section = "wpn_g36", prob = 0.3},
                {section = "wpn_vintorez", prob = 0.3}
            }
        },
        master = {
            first = {
                {section = "wpn_colt1911", prob = 0.3},
                {section = "wpn_usp", prob = 0.1},
                {section = "wpn_sig220", prob = 0.1}
            },
            second = {
                {section = "wpn_g36", prob = 0.3},
                {section = "wpn_val", prob = 0.3}
            }
        }
    },
    monolith = {
        novice = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5}
            },
            second = {
                {section = "wpn_akms", prob = 0.8},
                {section = "wpn_aks74u", prob = 0.5},
                {section = "wpn_ak74", prob = 0.5},
                {section = "wpn_l85", prob = 0.5}
            }
        },
        experienced = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_walther", prob = 0.3}
            },
            second = {
                {section = "wpn_aks74u", prob = 0.5},
                {section = "wpn_ak74", prob = 0.5},
                {section = "wpn_l85", prob = 0.5},
                {section = "wpn_lr300", prob = 0.5},
                {section = "wpn_spas12", prob = 0.1},
                {section = "wpn_wincheaster1300", prob = 0.1}
            }
        },
        veteran = {
            first = {
                {section = "wpn_colt1911", prob = 0.3}
            },
            second = {
                {section = "wpn_g36", prob = 0.3},
                {section = "wpn_val", prob = 0.3}
            }
        },
        master = {
            first = {
                {section = "wpn_usp", prob = 0.1},
                {section = "wpn_sig220", prob = 0.1}
            },
            second = {
                {section = "wpn_fn2000", prob = 0.1},
                {section = "wpn_groza", prob = 0.1},
                {section = "wpn_rg-6", prob = 0.1},
                {section = "wpn_svu", prob = 0.1}
            }
        }
    },
    ecologs = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8}
            },
            second = {}
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.6}
            },
            second = {}
        },
        veteran = {
            first = {
                {section = "wpn_fort", prob = 0.5}
            },
            second = {}
        },
        master = {
            first = {
                {section = "wpn_aps", prob = 0.5}
            },
            second = {}
        }
    },
    sky = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8}
            },
            second = {
                {section = "wpn_akms", prob = 0.8}
            }
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_fort", prob = 0.6}
            },
            second = {
                {section = "wpn_akms", prob = 0.8}
            }
        },
        veteran = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_fort", prob = 0.6},
                {section = "wpn_aps", prob = 0.5}
            },
            second = {
                {section = "wpn_akms", prob = 0.8}
            }
        },
        master = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_fort", prob = 0.6},
                {section = "wpn_hpsa", prob = 0.5}
            },
            second = {
                {section = "wpn_ak74", prob = 0.5}
            }
        }
    },
    military = {
        novice = {
            first = {
                {section = "wpn_pm", prob = 0.8}
            },
            second = {
                {section = "wpn_akms", prob = 0.8}
            }
        },
        experienced = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_fort", prob = 0.6}
            },
            second = {
                {section = "wpn_akms", prob = 0.8}
            }
        },
        veteran = {
            first = {
                {section = "wpn_pm", prob = 0.8},
                {section = "wpn_hpsa", prob = 0.5},
                {section = "wpn_fort", prob = 0.6}
            },
            second = {
                {section = "wpn_akms", prob = 0.8},
                {section = "wpn_aks74u", prob = 0.5},
                {section = "wpn_ak74", prob = 0.5}
            }
        },
        master = {
            first = {
                {section = "wpn_aps", prob = 0.5},
                {section = "wpn_hpsa", prob = 0.5},
                {section = "wpn_fort", prob = 0.6}
            },
            second = {
                {section = "wpn_aks74u", prob = 0.5},
                {section = "wpn_ak74", prob = 0.5}
            }
        }
    }
}

local skip_npc_names = {
    bar_barman = true,
	lvl1_escape_stalker_0030 = true,
}

-- функция для получения первого класса патронов
local function get_ammo_class(weapon_section)
	local weapon_ammo_class = utils.cfg_get_string(ini_sys, weapon_section, "ammo_class", weapon_section, false, "", "")
	if not weapon_ammo_class or weapon_ammo_class == "" then return nil end
	local ammo_section = amk.str_explode(",", weapon_ammo_class)
	return ammo_section[1]	
end

-- таблица соответствия группировок
local faction_groups = {
    deads = "bandit", 
	sin = "bandit", 
	lastday = "bandit",
    stranger = "stalker", 
	neutral = "stalker", 
	zombied = "stalker",
    sky = "ecologs", 
	iskateli = "ecologs", 
	voenstals = "military",
    bandit = "bandit", 
	stalker = "stalker", 
	ecolog = "ecologs", 
    military = "military", 
	sliznyaki = "sliznyaki", 
	dolg = "dolg",
    freedom = "freedom", 
	killer = "killer", 
	monolith = "monolith"
}

local function get_main_faction(community)
    return faction_groups[community] or "stalker"
end

local function get_rank_key(rank)
    if rank <= 300 then return "novice"
    elseif rank <= 600 then return "experienced"
    elseif rank <= 900 then return "veteran"
    else return "master" end
end

local function select_weapon(weapons)
    if not weapons or #weapons == 0 then return nil end
    if #weapons == 1 then return weapons[1].section end
    
    local rand = math.random()
    for i = 1, #weapons do
        if rand < weapons[i].prob then
            return weapons[i].section
        end
        rand = rand - weapons[i].prob
    end
    return weapons[1].section
end

-- Основная функция
function on_spawn(obj)
    if not obj then return end
	
	if skip_npc_names[obj:name()] then
		log1("### [INFO] olr_newnpc_eqp: skip npc - "..tostring(obj:name()).."")
		return
	end
	
	log1("### [INFO] olr_newnpc_eqp: Called euqip: name - "..tostring(obj:name())..", faction - "..tostring(obj:community())..", rank - "..tostring(get_rank_key(obj:rank())).."")
    
    local main_faction = get_main_faction(obj:community())
    local weapons = weapon_tables[main_faction] or weapon_tables.stalker
    weapons = weapons[get_rank_key(obj:rank())]
    if not weapons then return end
    
    -- Выдача оружия
    local function give_weapon(weapon_list)
        if not weapon_list or #weapon_list == 0 then return end
        local weapon_section = select_weapon(weapon_list)
        if not weapon_section then return end
        log1("### [INFO] olr_newnpc_eqp: Create weapon - "..tostring(weapon_section).."")
        alife():create(weapon_section, obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
        local ammo_class = get_ammo_class(weapon_section)
        if ammo_class then
			log1("### [INFO] olr_newnpc_eqp: Create ammo "..tostring(ammo_class).." for "..tostring(weapon_section).."")
            alife():create(ammo_class, obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
        end
    end
    
    give_weapon(weapons.first)
    give_weapon(weapons.second)
end