--Oblivion Lost Remake (2014-2015)
--(c) proger_Dencheek - базовая логика с игнором, скриптовое окно со своим интерфейсом
--Общение через КПК
-- Hrust: скрипт переписан и используется только для проверок доступности диалогов через движковое окно, скриптовое окно убрано (29.10.2025)

local ignore_ini = ini_file("pda_dialogs\\ignore_npc.ltx") --НПЦ, которые не участвуют в диалогах

--Коллбек на нажатие по элементу в списке контактов
function on_press(actor, npc)
	--news_manager.send_tip(db.actor, "on_press_check")

	if npc:character_community() == "zombied" then
		news_manager.send_tip(db.actor, game.translate_string("on_press_1"), nil, "signal_lost", 5000)
		return false
	end


	if npc:name() == "lvl4_darkdolina_staler_undead_olr_0001" then
		news_manager.send_tip(db.actor, game.translate_string("on_press_2"), nil, "signal_lost", 5000)
		return false
	end

	if db.actor:has_info("olr_blowout_phase_2") then
		news_manager.send_tip(db.actor, game.translate_string("on_press_7"), nil, "signal_lost")
		return false
	end

	if npc:name() == "bar_barman" and has_alife_info("olr_traders_night") then
		news_manager.send_tip(db.actor, game.translate_string("on_press_4"), nil, "barman", 5000, nil, nil, true, "st_barkeep_short")
		return false
	end
	
	if (npc:name() == "escape_trader_0000" or npc:name() == "lvl9_military_m_trader") and has_alife_info("olr_traders_night") then
		news_manager.send_tip(db.actor, game.translate_string("on_press_4"), nil, "trader", 5000, nil, nil, true, "escape_trader_name")
		return false
	end	

	if level.name() == "lvl16_generators" then
		news_manager.send_tip(db.actor, game.translate_string("on_press_5"), nil, "signal_lost")
		return false
	end
	
	for i=0, ignore_ini:line_count("main") - 1 do
		local _, val = ignore_ini:r_line("main", i, "", "")
		if npc:profile_name() == val then
			news_manager.send_tip(db.actor, game.translate_string("on_press_6"), nil, "signal_lost")
			return false
		end
	end
	
	if (npc:relation(db.actor) == game_object.enemy) then
		local rnd = math.random(1,4)
		if rnd == 1 then
			news_manager.send_tip(db.actor, game.translate_string("on_press_1"), nil, "signal_lost")
		elseif rnd == 2 then
			news_manager.send_tip(db.actor, game.translate_string("on_press_2"), nil, "signal_lost")
		elseif rnd == 3 then
			news_manager.send_tip(db.actor, game.translate_string("on_press_3"), nil, "signal_lost")
		end
		return false
	end

	--news_manager.send_tip(db.actor, "on_press_passed")
	return true
end

--Условия для диалогов
function is_pda_dialog()
return level.is_shown_pda()
end

function is_not_pda_dialog()
	return not level.is_shown_pda()
end
