--[[

-- Скрипт который отработает при получении инфопоршня start_olr_mod
-- author: theysani
-- last edit: 28.07.2025

--]]

function init()
	local mrandom = math.random
	local actor = db.actor -- тут движ по актору, нацепить костюм, дать фонарик и т.д
	if actor then
		local STbron = actor:object("stalker_outfit")
		if STbron then
			STbron:set_condition(mrandom(2,8)/100) -- состояние от 2 до 8%
		end
		actor.satiety = -mrandom(20, 75)/100 -- гг голод
		actor:change_actor_thirst(-mrandom(20, 75)/100) -- гг жажда
		local torch_item = alife():create("device_torch", actor:position(), actor:level_vertex_id(), actor:game_vertex_id(), actor:id())
		level.client_spawn_manager():add(torch_item.id, 0, function(id,obj) obj:set_condition((mrandom(15,45)/100)) end) -- портим сразу фонарик
	end

	-- далее вместо трёх или сколько там было проходов по 65к объектов
	-- делается один в котором сразу всё и происходит
	local sim = alife()
	local game_graph = game_graph()
	
	local art_sections = {
		af_transpsphere = true,
		af_gravi_heavy = true,
		af_gravi_med = true,
		af_electrosphere = true,
		af_gravi_weak = true
	}
	local excluded_levels = {
		[4] = true,
		[6] = true,
		[10] = true,
		[12] = true
	}
	
	local items_to_remove = {
		item_razradnik = true,
		bread = true,
		kolbasa = true,
		conserva = true,
		vodka = true,
		water = true,
		medkit = true,
		energy_drink = true,
		bandage = true,
		antirad = true,
		novice_outfit = true,
		killer_outfit = true,
		stalker_outfit = true,
		scientific_outfit = true,
		exo_outfit = true,
		ecolog_outfit = true,
		kanistra_benz = true,
		af_thorn = true,
		af_thorn_black = true,
		detector_simple = true,
		detector_advances = true,
		detector_elite = true,
		af_cotton = true,
		af_junk_debris = true,
		af_mercury_ball = true,
		af_sponge = true,
		af_deadhead = true,
		grenade_rgd5 = true,
		grenade_f1 = true,
		box_rukzak_treasure = true
	}
	
	local montabl = {
		[clsid.script_stalker] = true
	}

	for id = 1, 65534 do
		local obj = sim:object(id)
		if obj then
			local sect = obj:section_name()
			local clsid = obj:clsid()
			local processed = false	
			
			if not processed and art_sections[sect] then
				local gvid = obj.m_game_vertex_id
				local l_id = game_graph:vertex(gvid):level_id()
				if l_id < 14 and not excluded_levels[l_id] then
					if obj then
						sim:release(obj)
					end
					processed = true
				end
			end
			
			if not processed and montabl[clsid] and not obj.online and obj:alive() and obj:community() ~= "trader" then
				local tbl = amk.read_stalker_params(obj)
				local old_money = tbl.money or 0
				tbl.money = mrandom(30, 450)
				amk.write_stalker_params(tbl, obj)
			end
		end
	end
--	log1("Конец!")
end