-- hi_flyer 19/07/17

function look_item(obj)
    if obj and (obj:section() == "af_electrosphere" or obj:section() == "af_needle_heavy" or obj:section() == "af_transpsphere") then
        local iParent = obj:parent()
        if not iParent then
            local shelbone = obj:get_physics_shell():get_element_by_bone_id(0)
            shelbone:apply_force(math.random(140, 750), math.random(140, 750), math.random(100, 900))
        end
    end
end

function look_change(obj)
    local mrandom = math.random
    local level_name = level.name()
    if obj then
        if get_clsid(obj) == clsid.zombie or get_clsid(obj) == clsid.zombie_s then
            if obj:alive() == false and not has_alife_info("zombie_first_checkup") then
                db.actor:give_info_portion("zombie_first_checkup")
                olr.hud_tip("", game.translate_string("st_olr_on_look_tip_zombie"), 10)
            end
            if obj:alive() == false then
                if mrandom(1, 10) == 1 then
                    local shelbone = obj:get_physics_shell():get_element_by_bone_id(0)
                    shelbone:apply_force(mrandom(14, 75), mrandom(14, 75), mrandom(10, 90))
                    local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\zombie_mute_5]])
                    if not snd_obj:playing() then
                        snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
                    end
                end
            end
        end

        if get_clsid(obj) == clsid.controller or get_clsid(obj) == clsid.controller_s then
            if obj:alive() == false then
                if mrandom(1, 100) == 1 then
                    olr.rnd_camera_direction()
                end
            end
        end

        if obj:section() == "karlik" then
            if obj:alive() == false and not has_alife_info("karlik_first_checkup") then
                db.actor:give_info_portion("karlik_first_checkup")
                olr.hud_tip("", game.translate_string("st_olr_on_look_tip_child"), 10)
            end
        end

        if obj:section() == "m_pseudohuman_e" then
            if obj:alive() == false and not has_alife_info("pseudohuman_first_checkup") then
                db.actor:give_info_portion("pseudohuman_first_checkup")
                olr.hud_tip(game.translate_string("st_olr_on_look_tip_hmm"), game.translate_string("st_olr_on_look_tip_monster"), 20)
            end
        end

        if level_name == "l09_military" then
            nick.look_military(obj)
        end

        if level_name == "l02_garbage" then
            nick.look_garbage(obj)
        end

        if level_name == "l07_yantar" then
            nick.look_yantar(obj)
        end

        if level_name == "l05_bar" then
            this.look_bar(obj)
        end

        if level_name == "l03_agroprom" then
            if obj:name() == "lvl3_agroprom_physic_object_0381" then
                olr.hud_tip(game.translate_string("st_olr_on_look_tip_hmm"), game.translate_string("st_olr_on_look_tip_some_book"), 2)
            end
        end
    end
end

function look_bar(obj)
    if obj and obj:name() == "lvl5_bar_inventory_box" then
	
    end
end
