--[[-----------------------------------------------------------------------------------------------
 File         : olr_sleep.script
 Description  : Sleep menu based on this from build 1865
 Copyright    : OLR Team
 Author       : Stalker55, hi_flyer
 Date         : 04.05.2014
 Last edit    : 21.02.2026
--]]-----------------------------------------------------------------------------------------------

-- Вызывается из разных мест, считается что это сон в точно безопасной и комфортной зоне, 
-- поэтому тут всегда полное восстановление сонливости
-- тока часы (пока что)
function sleep_main(scale)
	bind_stalker.actor_sleep_full = true
	db.actor:actor_sleep(scale, 0)
end

------------------------------------------------------------------------------------------------------------------------ 

function blow_sleep_timer_low(scale)
	local tec = olr_blowout.get_blow_timer()
	if tec < 420 then
		return
	end
	local tmr = 50 + scale * 20
	olr_blowout.min_blow_timer(tmr)
end


function yan_dead_call()
	if level.name() == "lvl7_yantar" then
		if not xr_conditions.is_day() then
			if not has_alife_info("radar_de_done") then
				news_manager.send_tip(db.actor, game.translate_string("yan_dead_call_0"), nil, "unknown", 5000)
				news_manager.send_tip(db.actor, game.translate_string("yan_dead_call_1"), 5, "unknown", 5000)
				news_manager.send_tip(db.actor, game.translate_string("yan_dead_call_2"), 15, "unknown", 5000)
				news_manager.send_tip(db.actor, game.translate_string("yan_dead_call_3"), 25, "unknown", 5000)
				news_manager.send_tip(db.actor, game.translate_string("yan_dead_call_4"), 35, "unknown", 5000)
			end
		end
	end
end

function unic_arts()
	--[[
	local art = db.actor:object("af_art_kub")
	if art ~= nil then
		if has_alife_info("bolezn_zombied_info") then
			if olr_timers.has_timer("bolezn_zombied_timer") then
				olr_timers.del_timer("bolezn_zombied_timer")
			end
			if olr_timers.has_timer("bolezn_zombied_timer_m") then
				olr_timers.del_timer("bolezn_zombied_timer_m")
			end
			if olr_timers.has_timer("bolezn_zombied_timer_d") then
				olr_timers.del_timer("bolezn_zombied_timer_d")
			end
			get_hud():RemoveCustomStatic("actor_bolezn",true)
			db.actor:disable_info_portion("bolezn_zombied_info")
			olr.del(art)
		end
	end
	--]]
end
------------------------------------------------------------------------------------------------------------------------   

local no_izlom_levels = {
        ["lvl1_escape"] = true,
	["lvl2_garbage"] = true,
	["lvl5_bar"] = true,
	["lvl9_military"] = true,
	["lvl14_stancia"] = true,
	["lvl15_sarcofag"] = true,
	["lvl16_generators"] = true
}


function spawen_izlom_rand()
        if no_izlom_levels[level.name()] then
		return
	end
        if db.actor:is_actor_outdoors() == false then return end
    	local isl_var = math.random(1,2)
     	if isl_var == 1 then
    		alife():create("m_fracture_e", db.actor:position():add(db.actor:direction():add(15)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	end
end

function set_food_art_sleep()

local function TimeCondLost(obj)
	local skis = ini_sys:r_float(obj:section(), "cor_time") 
	if skis < 0 then
		return 0
	end
	return 100/skis/24/100/60 * 100 * 295
end	

local function TimeCondLostArts(obj)
	return 100/120/24/100/60 * 100 * 295
end


	local foods = {}
	local arts = {}
	for i= 1, 65534 do
		local obj = level.object_by_id(i)
		if obj ~= nil then
                                local section = obj:section()

                                 if section == "conserva" or section == "bread" or section == "kolbasa" 

				or section == "mutant_flesh_eye_coocked"
				or section == "mutant_boar_leg_coocked"
				or section == "mutant_dog_tail_coocked"
				or section == "mutant_psevdodog_tail"
				or section == "mutant_krovosos_jaw_coocked"
				or section == "mutant_burer_hand_coocked"
				or section == "mutant_zombie_hand_coocked" 

				or section == "rat_food_coocked"
				or section == "crow_food_coocked" 

				or section == "rat_food"
				or section == "crow_food" 

				or section == "mutant_flesh_eye"
				or section == "mutant_boar_leg"
				or section == "mutant_dog_tail"
				or section == "mutant_psevdodog_tail"
				or section == "mutant_krovosos_jaw"
				or section == "af_mercury_ball"
				or section == "mutant_burer_hand"
				or section == "mutant_zombie_hand" then

					table.insert(foods, obj)
				end
				if obj:is_artefact() and db.actor:is_on_belt(obj)-- and obj:section() ~= "exo_acum_ob"
				                                             then	
					--log1("adda")
					table.insert(arts, obj)
				end
                                if section == "detector_simple" or section == "detector_advances" or section == "detector_elite" then 
					if db.actor:is_on_belt(obj) then
						table.insert(arts, obj)
					end
				end
                  end
            end

	for i, obj in ipairs(foods) do
		local nowcond = obj:condition()
		local new_cond = nowcond - TimeCondLost(obj)
		--log1(" food - obj:name() --- cond old - "..nowcond.." set cond -  "..new_cond.." ")
		obj:set_condition(new_cond)
	end

	for i, obj in ipairs(arts) do
		local nowcond = obj:condition()
		local new_cond = nowcond - TimeCondLostArts(obj)
		--log1(" art - obj:name() --- cond old - "..nowcond.." set cond -  "..new_cond.." ")
		obj:set_condition(new_cond)
	end


end