--hi_flyer 10/05/16

local text_mess_fnc = ""
local text_mess_add = ""
local text_mess = ""
local last_info_in_table = "news_info_unicq_36"
local time_apdeyta_news = 0
local timerupnews = math.random(250000,2000000) -- частота апдейта	400000,750000
local text_phrases = {
	{game.translate_string("st_olr_network_courier"), "news_info_unicq_2", "", "" },
	{game.translate_string("st_olr_network_electrocluster"), "news_info_unicq_3", "", ""  },
	{game.translate_string("st_olr_network_milpatrol"), "news_info_unicq_4", game.translate_string("st_olr_network_milpatrol_2"), ""  },
	{game.translate_string("st_olr_network_dog_pack"), "news_info_unicq_6", "", "" },
	{game.translate_string("st_olr_network_need_magnet"), "news_info_unicq_7", "", ""  },
	{game.translate_string("st_olr_network_marked_one"), "news_info_unicq_8", game.translate_string("st_olr_network_marked_one_2"), ""	},
	{game.translate_string("st_olr_network_garage_fedka_bandosi"), "news_info_unicq_9", "", "nick.garage_fedka_bandosi()"  },
	{game.translate_string("st_olr_network_garage_dolg_from_doliana"), "news_info_unicq_11", "", "nick.garage_dolg_from_doliana()"	},
	{game.translate_string("st_olr_network_rusty_lake"), "news_info_unicq_12", "", ""  },
	{game.translate_string("st_olr_network_gunslinger_is_back"), "news_info_unicq_13", "", ""  },
	{game.translate_string("st_olr_network_dont_go_to_checkpoint"), "news_info_unicq_14", game.translate_string("st_olr_network_dont_go_to_checkpoint_2"), "", ""  },
	{game.translate_string("st_olr_network_dogs_from_center"), "news_info_unicq_15", "", ""	 },
	{game.translate_string("st_olr_network_military_snipers"), "news_info_unicq_16", "", ""	 },
	{game.translate_string("st_olr_network_military_hoarding"), "news_info_unicq_17", "", "" },
	{game.translate_string("st_olr_network_factory_walking_night"), "news_info_unicq_18", "", "" },
	{game.translate_string("st_olr_network_institute_scientist"), "news_info_unicq_19", "", "" },
	{game.translate_string("st_olr_network_toad_no_food"), "news_info_unicq_20", game.translate_string("st_olr_network_toad_no_food_2"), "", "" },
	{game.translate_string("st_olr_network_bar_rookies"), "news_info_unicq_21", game.translate_string("st_olr_network_bar_rookies_2"), "", "" },
	{game.translate_string("st_olr_network_blowout_gulp"), "news_info_unicq_22", "", "" },
	{game.translate_string("st_olr_network_zombie_explode"), "news_info_unicq_23", "", "" },
	{game.translate_string("st_olr_network_mil_quad"), "news_info_unicq_24", game.translate_string("st_olr_network_mil_quad_2"), "" },
	{game.translate_string("st_olr_network_bar_boarded_house"), "news_info_unicq_25", game.translate_string("st_olr_network_bar_boarded_house_2"), "", "" },
	{game.translate_string("st_olr_network_cant_reach"), "news_info_unicq_26", "", "" },
	{game.translate_string("st_olr_network_door_stuck"), "news_info_unicq_27", game.translate_string("st_olr_network_door_stuck_2"), "", "" },
	{game.translate_string("st_olr_network_valley_truck"), "news_info_unicq_28", game.translate_string("st_olr_network_valley_truck_2"), "", ""},										 
	{game.translate_string("st_olr_network_toad_rookie"), "news_info_unicq_29", game.translate_string("st_olr_network_toad_rookie_2"), "", "" },
	{game.translate_string("st_olr_network_city_flesh"), "news_info_unicq_30", "", ""},
	{game.translate_string("st_olr_network_collector_talk"), "news_info_unicq_31", game.translate_string("st_olr_network_collector_talk_2"), "", ""},
	{game.translate_string("st_olr_network_radio_rubble"), "news_info_unicq_32", game.translate_string("st_olr_network_radio_rubble_2"), "", ""},
	{game.translate_string("st_olr_network_bandits_vs_duty"), "news_info_unicq_33", game.translate_string("st_olr_network_bandits_vs_duty_2"), "", ""},
	{game.translate_string("st_olr_network_flat_tire"), "news_info_unicq_34", game.translate_string("st_olr_network_flat_tire_2"), "", ""},
	{game.translate_string("st_olr_network_barman_arsenal"), "news_info_unicq_35", game.translate_string("st_olr_network_barman_arsenal_2"), "", ""},
	{game.translate_string("st_olr_network_witches_jelly_cans"), "news_info_unicq_36", game.translate_string("st_olr_network_witches_jelly_cans_2"), "", ""}
}

function update()
	if db.actor then
		if time_global() > time_apdeyta_news then
			time_apdeyta_news = time_global() + timerupnews
			if device().precache_frame > 1 then
				return
			end
			if nick.is_pda_dead() then
				return
			end
			if has_alife_info(last_info_in_table) then
				--log1("VSE")
				return
			end			
			for key, val in ipairs(text_phrases) do
				if not has_alife_info(val[2]) then
					db.actor:give_info_portion(val[2])
					text_mess = (val[1])
					if val[3] ~= nil then
						text_mess_add = (val[3])
					end
					if val[4] ~= nil then
						text_mess_fnc = (val[4])
						break
					end
				end
			end

			if nick.is_pda_dead() then
				return
			end

			news_manager.send_tip_new(text_mess, "", "news", nil, math.random(1000, 3000), 15000)
			if text_mess_add ~= "" then
				local bol_var = math.random(1, 2)
				if bol_var == 1 then
					news_manager.send_tip_new(text_mess_add, "", "news", nil, math.random(1000, 3000), 15000)
				end
			end
			if text_mess_fnc ~= "" then
				local func = loadstring(text_mess_fnc)
				if func then
					pcall(func)
				end
			end
		end
	end
end