-- hi_flyer 07/05/15

function drop_item(obj)
	local mrandom = math.random
	if obj:section() == "zameritel_vibrosa" then
		if device().precache_frame > 1 then
			return
		end
		if db.actor:is_actor_outdoors() == false then
			news_manager.send_tip(db.actor, game.translate_string("drop_item_0"), nil, "info", 39000)
			return
		end
		if has_alife_info("olr_blowout_phase_0") then
			news_manager.send_tip(db.actor, game.translate_string("drop_item_1"), nil, "info", 39000)
			return
		end
		if has_alife_info("olr_blowout_phase_1") then
			news_manager.send_tip(db.actor, game.translate_string("drop_item_2"), nil, "info", 39000)
			return
		end
		if not has_alife_info("zameritel_vibrosa_has_result") and has_alife_info("olr_blowout_phase_2") then
			news_manager.send_tip(db.actor, game.translate_string("drop_item_3"), 5, "info", 39000)
			local song_start = xr_sound.get_safe_sound_object([[anomaly\burning_fuzz_hit]])
			song_start:play_at_pos(db.actor, db.actor:position(), sound_object.s3d + sound_object.looped)
			olr.info("zameritel_vibrosa_has_result")
		end
	end

	if obj:section() == "give_yashik_kvest_1_item" and utils.npc_in_zone(db.actor, db.zone_by_name["zone_kvest_1"]) then
		if has_alife_info("esc_olr_1_have_pre") and not has_alife_info("esc_olr_1_have") then
			obj:set_taking(false)
			olr.info("esc_olr_1_have")
		end
	end

	if obj:section() == "af_magnet_drop_q1" then
		for i = 1, 65534 do
			local anom = level.object_by_id(i)
			if anom ~= nil then
				local anom_sect = anom:section()
				local has_htype_str = ini_sys:line_exist(anom_sect, "hit_type") and anom_sect ~= "zone_rusty_hair"
				if anom:is_anomaly() and has_htype_str and ini_sys:r_string(anom_sect, "hit_type") == "shock" and anom:position():distance_to_sqr(db.actor:position()) < 15 then
					level.add_pp_effector("blink.ppe", 20131, false)
					olr.del(obj)
					alife():create("af_magnet_drop_q2", db.actor:position():add(db.actor:direction():mul(1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
					--alife():create("af_magnet_drop_q2", anom:position(), anom:level_vertex_id(), anom:game_vertex_id())
					break
				end
			elseif i == 65534 then
				return
			end
		end
	end

	if obj:section() == "pribor_primanka_mg" then
		if xr_conditions.actor_in_zone(nil, nil, {"lvl11_deadcity_space_restrictor_0025"}) then
			olr.info("mg_spawen_raz_boloto")
			level.add_pp_effector("blink.ppe", 2560131, false)
			nick.phantasms_zombies()
			nick.mg_ph_spawn_boloto()
			olr.del(obj)
		end
	end

	if obj:section() == "pribor_paras_spory" then
		local parasits = {
			["zombie_plague"] = true,
			["zombie_plague_strong"] = true
		}
		for i = 1, 65534 do
			local anom = level.object_by_id(i)
			if anom ~= nil and anom:is_monster() and parasits[anom:section()] and anom:position():distance_to_sqr(db.actor:position()) < 10 then
				news_manager.send_tip(db.actor, game.translate_string("drop_item_4"), nil, "info", 39000, nil, "pda_sos", true)
				olr_timers.st_timer("pribor_paras", mrandom(3, 6), "nick.pribor_paras_inf()")
				break
			elseif i == 65534 then
				return
			end
		end
	end

	if obj:section() == "pribor_paras_spory_mg" then
		if xr_conditions.actor_in_zone(nil, nil, {"lvl11_deadcity_space_restrictor_0038"}) then
			news_manager.send_tip(db.actor, game.translate_string("drop_item_5"), nil, "info", 39000, nil, "pda_sos", true)
			olr_timers.st_timer("pribor_paras2", mrandom(3, 6), "nick.pribor_paras_mg()")
		end
	end

	if obj:section() == "af_dezintegrator_m1" then
		for i = 1, 65534 do
			local anom = level.object_by_id(i)
			if anom ~= nil and anom:is_anomaly() and string.find(anom:section(), "zone_mincer_strong") and anom:position():distance_to_sqr(db.actor:position()) < 15 then
				olr.del(obj)
				alife():create("zone_witches_galantine_weak", anom:position(), anom:level_vertex_id(), anom:game_vertex_id())
				local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\teleport]])
				snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
				local snd_obj = xr_sound.get_safe_sound_object([[anomaly\witches_jelly_hit]])
				snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
				olr.hud_tip("", game.translate_string("drop_item_6"), 10, true)
				anom:disable_anomaly()
				olr_timers.st_timer("dezint_qt", mrandom(23, 36), "nick.dezint_qt_spawn()")
				break
			elseif i == 65534 then
				return
			end
		end
	end

	if obj:section() == "af_dezintegrator_m2" then
		if xr_conditions.actor_in_zone(nil, nil, {"lvl5_bar_space_restrictor_0122"}) then
			if has_alife_info("space_bar_zombied_dialog_info") then
				level.add_pp_effector("blink.ppe", 2560131, false)
				olr.del(obj)
				olr.del_by_name("lvl5_bar_staler_undead_olr_0005")
				olr.del_by_name("lvl5_bar_space_restrictor_0122")
				olr.del_by_name("lvl5_bar_physic_object_0126")
				olr.del_by_name("lvl5_bar_physic_object_0127")
				olr.del_by_name("lvl5_bar_physic_object_0122")
				olr.del_by_name("lvl5_bar_physic_object_0123")
				olr.del_by_name("lvl5_bar_physic_object_0120")
				olr.del_by_name("lvl5_bar_physic_object_0125")
				olr.disable_walk()
				olr_timers.st_timer("dezint_qt_two", mrandom(8, 12), "nick.dezint_qt_spawn_two()")
				local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\teleport]])
				snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
			end
		end
	end
end
