function init()
	core.ac("actor_update",update)
end

local att 				
local ptatt	

local repaintnow = false

function on_inventory_show()
    if not att then
        ptatt = ui.get_inventory_wnd()
        att = olr_ui_inv_acinfo.ui_trade()
        ptatt:AttachChild(att)
        att:SetAutoDelete(true)
        att:Show(true)
    end
end

function on_inventory_hide()
    if att and ptatt then
        att:Show(false)
        ptatt:DetachChild(att)
        att = nil
        ptatt = nil
    end
end

function update(delta)
    if att then
        att:UpdateVolume()
    end
end

function get_sleep(num)
	if num >= 0 and num <= 0.2 then
		return game.translate_string("st_ui_sleep_very_strong")
	elseif num > 0.2 and num <= 0.3 then
		return game.translate_string("st_ui_sleep_strong")
	elseif num > 0.3 and num <= 0.4 then
		return game.translate_string("st_ui_sleep_moderate")		
	elseif num > 0.4 and num <= 0.5 then
		return game.translate_string("st_ui_sleep_slight")
	elseif num > 0.5 then
		return game.translate_string("st_ui_sleep_none")
	end
end

class "ui_trade" (CUIScriptWnd)

function ui_trade:__init(owner) super()
	self.owner = owner
	self.comm = game.translate_string(db.actor:character_community())
	self.rank = game.translate_string(level.get_rank_as_text(db.actor:character_rank()))
	self.repa = game.translate_string(level.get_reputation_as_text(db.actor:character_reputation()))
	self.sleep = get_sleep(db.actor.sleep)
	self.blows = xvars.blow_count
	self.inv_vol = db.actor:get_used_volume()
	self.inv_vol_max = db.actor:get_max_volume()
	self:InitControls()
end

function ui_trade:__finalize() end

function ui_trade:InitControls()
	local sformat = string.format
	self:Init(0,0,1024,768)

	local xml = CScriptXmlInit()
	if xml:is_16_9_mode() then
		xml:ParseFile("flyer\\inv_acinfo_16.xml")
	else
		xml:ParseFile("flyer\\inv_acinfo.xml")
	end
    self.main = xml:InitScrollView("main", self)
    self.actor_name = xml:InitStatic("name_wnd", self)

	self.actor_name:SetTextST(xr_effects.get_real_actor_name())

	self.yess = xml:InitStatic("rank_wnd", self.main)
	self.yess:SetTextST(sformat("%s %s", game.translate_string("ui_st_pda_talk_rank"), ""..db.actor:character_rank().." : "..self.rank..""))

	self.no = xml:InitStatic("community_wnd", self.main)
	self.no:SetTextST(sformat("%s %s", game.translate_string("ui_st_pda_talk_community"), self.comm))

	self.rep = xml:InitStatic("reputation_wnd", self.main)
	self.rep:SetTextST(sformat("%s: %s", game.translate_string("pda_btn_reputation"), ""..db.actor:character_reputation().." ("..self.repa..")"))

	self.vo = xml:InitStatic("volume_wnd", self.main)

	self.so = xml:InitStatic("sleep_wnd", self.main)
	self.so:SetTextST(sformat("%s: %s", game.translate_string("ui_inv_sleeping"),  self.sleep))

	self.bw = xml:InitStatic("blowouts_wnd", self.main)
	self.bw:SetTextST(sformat("%s: %s", game.translate_string("ui_inv_survived_blowouts"),  self.blows))

	if self.inv_vol < 0 then
		self.inv_vol=0
	end
	
	local vol_cur
	local vol_cur_max
	
	if level.get_game_difficulty() < 2 then
		vol_cur = "--"
		vol_cur_max = "--"
	else
		vol_cur = sformat("%1.1f", self.inv_vol)
		vol_cur_max = sformat("%1.0f", self.inv_vol_max)
	end
	
	self.vo:SetTextST(sformat("%s: %s / "..vol_cur_max.."", game.translate_string("ui_inv_volume_script"),  vol_cur))
end

function ui_trade:UpdateVolume()

	if level.get_game_difficulty() < 2 then return end

	local sformat = string.format
	local cur_vol = db.actor:get_used_volume()
	if cur_vol < 0 then cur_vol = 0 end
	local max_vol = db.actor:get_max_volume()
	
	self.vo:SetTextST(sformat("%s: %1.1f / %1.0f", game.translate_string("ui_inv_volume_script"), cur_vol, max_vol))

end

function ui_trade:ActorInformation()
end