-- торговля нпс в баре и янтаре в оффлайне
-- hi_flyer 12.11.18

local jan_profesor = alife():object("lvl7_yantar_arts_box_profa")  -- ящик профессора 

local second_tab = {
	 
		 [1] = {name = "wpn_lr300",                ammo = "ammo_5.56x45_ap"},
		 [2] = {name = "wpn_mp5", 		   ammo = "ammo_5.56x45_ap"},

		 [3] = {name = "wpn_akms", 	   ammo = "ammo_5.45x39_ap"},

		 [4] = {name = "wpn_groza", 	   ammo = "ammo_9x39_ap"},

		 [5] = {name = "wpn_wincheaster1300", 	   ammo = "ammo_12x76_dart"},
		 [6] = {name = "wpn_toz34", 	   	ammo = "ammo_12x76_dart"},

		 [7] = {name = "wpn_svd", 	   	ammo = "ammo_7.62x54_7h14"},
		 [8] = {name = "wpn_svu", 	   	ammo = "ammo_7.62x54_7h14"},
		 [9] = {name = "wpn_val", 	   	ammo = "ammo_9x39_ap"},
		 [10] = {name = "wpn_vintorez", 	   	ammo = "ammo_9x39_ap"},

		 [11] = {name = "wpn_fn2000", 	   	ammo = "ammo_5.56x45_ap"},
		 [12] = {name = "wpn_g36", 	   	ammo = "ammo_5.56x45_ap"},
		 [13] = {name = "wpn_groza", 	   	ammo = "ammo_9x39_ap"}

		}

-- покупка хабара за 5к
function on_point_bar(obj)
	if has_alife_info("prp_first") then
		return
	end
	xvars.npc_ofl_trade[obj:name()] = nil
	local rndpos = math.random(#second_tab) or 1
	
	--news_manager.send_tip(db.actor, "сталкер купил в баре ствол "..second_tab[rndpos].name.."", nil, "artifact", 45000) 
	alife():create(tostring(second_tab[rndpos].name), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
	alife():create("medkit", obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
	se_respawn.create_ammo(tostring(second_tab[rndpos].ammo), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id, 10)

	if obj then
		local pk = get_netpk(obj)
        	if pk:isOk() then
         		local data = pk:get()
			boflsname = data.character_name
         		pk:set(data)
		end
	end
	local rnd = math.random(1,5)
	if rnd == 1 then
		news_manager.send_tip(db.actor, game.translate_string("olr_ofl_trade_buy_gun"), 2, "weapon", 25000, nil, nil, true, boflsname)
	end
	this.buy_new_armor(obj)
end

-- продажа артов у профа
function on_point_yan(obj)
	if has_alife_info("otpravlaet_spat_gg_done") then
		return
	end
	if obj then
		local old_m = 0
		local new_mon = 0
		local art_cnt = 0

		local sim = alife()
		for id=1, 65534 do
			local art = sim:object(id)
			if art then
				if isArtefact(art) then
					if art.parent_id == obj.id then
						art_cnt = art_cnt + 1
						if art then
							--log1("сталкер продаёт на янтаре арт "..art:name().."  телепорт  ")
							--news_manager.send_tip(db.actor, "сталкер продаёт на янтаре арт "..art:name().."  телепорт  ", nil, "artifact", 45000)
							if jan_profesor then
								alife():create(art:section_name(), jan_profesor.position, jan_profesor.m_level_vertex_id, jan_profesor.m_game_vertex_id, jan_profesor.id)
							end
							olr.del_by_name(art:name())
						end
					end
				end
			end
		end
		local pk = get_netpk(obj)
        	if pk:isOk() then
         		local data = pk:get()
			old_m = data.money
			new_mon = 1000 * art_cnt
			data.money = old_m + new_mon
			oflsname = data.character_name
         		pk:set(data)
		end
		--news_manager.send_tip(db.actor, "сталкер "..obj:name().." продал арты шт - "..art_cnt.." у профа было руб "..old_m.." рублей и продал на "..new_mon.." рублей", nil, "artifact", 45000)
		news_manager.send_tip(db.actor, game.translate_string("olr_ofl_trade_buy_art_1").." "..oflsname.." "..game.translate_string("olr_ofl_trade_buy_art_2"), nil, "professor", 25000)		
	end
	this.buy_new_armor(obj)
end


function buy_new_armor(obj)
	local num = obj:rank()
	if num > 0 and num < 300 then
		
	elseif num > 300 and num <= 600 then
		-- опытный
		this.set_opitn_vis(obj)
	elseif num > 600 and num <= 900 then
		-- ветеран		
		this.set_opitn_vis(obj)
	elseif num > 900 then
		--мастер
		this.set_master_vis(obj)
	end
end


local visuals_opitn = {
		[[actors\novice\novice_b_01]],
		[[actors\novice\novice_b_mask]],
		[[actors\novice\novice_w_mask]]
}


local visuals_neytral = {
		[[actors\neutral\stalker_exo]],
		[[actors\neutral\stalker_protected]],
		[[actors\neutral\stalker_hood_backpack_01]],
		[[actors\neutral\stalker_hood_balon_01]],
		[[actors\neutral\stalker_no_hood_backpack_01]],
		[[actors\neutral\stalker_hood_backpack_antigas]]
}

function set_opitn_vis(obj)
	--news_manager.send_tip(db.actor, game.translate_string("set_opitn_vis_0"), nil, "professor", 25000)
	local pk = get_netpk(obj,1)
  	if pk:isOk() then
    		local data = pk:get()
    		data.visual_name = visuals_opitn[math.random(#visuals_opitn)]
      		pk:set(data)
	end	
end

function set_master_vis(obj)
	--news_manager.send_tip(db.actor, game.translate_string("set_master_vis_0"), nil, "professor", 25000)
	local pk = get_netpk(obj,1)
  	if pk:isOk() then
    		local data = pk:get()
    		data.visual_name = visuals_neytral[math.random(#visuals_neytral)]
      		pk:set(data)
	end	
end





















