local day_sounds={
"ambient\\rnd_outdoor\\rnd_ak47_1",
"ambient\\rnd_outdoor\\rnd_ak47_2",
"ambient\\rnd_outdoor\\rnd_barking",
"ambient\\rnd_outdoor\\rnd_car",
"ambient\\rnd_outdoor\\rnd_chimes",
"ambient\\rnd_outdoor\\rnd_cooing",
"ambient\\rnd_outdoor\\rnd_crow_1",
"ambient\\rnd_outdoor\\rnd_crow_2",
"ambient\\rnd_outdoor\\rnd_crow_3",
"ambient\\rnd_outdoor\\rnd_darkwind",
"ambient\\rnd_outdoor\\rnd_deep_barking",
"ambient\\rnd_outdoor\\rnd_disgusting",
"ambient\\rnd_outdoor\\rnd_distantmortar",
"ambient\\rnd_outdoor\\rnd_doubler",
"ambient\\rnd_outdoor\\rnd_drone_1",
"ambient\\rnd_outdoor\\rnd_drone_2",
"ambient\\rnd_outdoor\\rnd_fallscream",
"ambient\\rnd_outdoor\\rnd_heart",
"ambient\\rnd_outdoor\\rnd_helicopter",
"ambient\\rnd_outdoor\\rnd_horror_1",
"ambient\\rnd_outdoor\\rnd_horror_2",
"ambient\\rnd_outdoor\\rnd_horror_3",
"ambient\\rnd_outdoor\\rnd_horror_4",
"ambient\\rnd_outdoor\\rnd_m-16_1",
"ambient\\rnd_outdoor\\rnd_m-16_2",
"ambient\\rnd_outdoor\\rnd_meow",
"ambient\\rnd_outdoor\\rnd_moan_1",
"ambient\\rnd_outdoor\\rnd_moan_2",
"ambient\\rnd_outdoor\\rnd_moan_3",
"ambient\\rnd_outdoor\\rnd_moan_4",
"ambient\\rnd_outdoor\\rnd_moan_5",
"ambient\\rnd_outdoor\\rnd_moan_6",
"ambient\\rnd_outdoor\\rnd_ratchant",
"ambient\\rnd_outdoor\\rnd_scr_1",
"ambient\\rnd_outdoor\\rnd_scr_2",
"ambient\\rnd_outdoor\\rnd_scr_3",
"ambient\\rnd_outdoor\\rnd_scr_4",
"ambient\\rnd_outdoor\\rnd_scr_5",
"ambient\\rnd_outdoor\\rnd_scr_6",
"ambient\\rnd_outdoor\\rnd_scr_7",
"ambient\\rnd_outdoor\\rnd_scr_8",
"ambient\\rnd_outdoor\\rnd_scr_9",
"ambient\\rnd_outdoor\\rnd_sickened_1",
"ambient\\rnd_outdoor\\rnd_sickened_2",
"ambient\\rnd_outdoor\\rnd_squeak",
"ambient\\rnd_outdoor\\rnd_thunder",
"ambient\\rnd_outdoor\\rnd_wolfhowl_1",
"ambient\\rnd_outdoor\\rnd_wolfhowl_2"
}

local night_sounds={
"ambient\\rnd_outdoor\\rnd_ak47_1",
"ambient\\rnd_outdoor\\rnd_ak47_2",
"ambient\\rnd_outdoor\\rnd_barking",
"ambient\\rnd_outdoor\\rnd_car",
"ambient\\rnd_outdoor\\rnd_chimes",
"ambient\\rnd_outdoor\\rnd_cooing",
"ambient\\rnd_outdoor\\rnd_crow_1",
"ambient\\rnd_outdoor\\rnd_crow_2",
"ambient\\rnd_outdoor\\rnd_crow_3",
"ambient\\rnd_outdoor\\rnd_darkwind",
"ambient\\rnd_outdoor\\rnd_deep_barking",
"ambient\\rnd_outdoor\\rnd_disgusting",
"ambient\\rnd_outdoor\\rnd_distantmortar",
"ambient\\rnd_outdoor\\rnd_doubler",
"ambient\\rnd_outdoor\\rnd_drone_1",
"ambient\\rnd_outdoor\\rnd_drone_2",
"ambient\\rnd_outdoor\\rnd_fallscream",
"ambient\\rnd_outdoor\\rnd_heart",
"ambient\\rnd_outdoor\\rnd_helicopter",
"ambient\\rnd_outdoor\\rnd_horror_1",
"ambient\\rnd_outdoor\\rnd_horror_2",
"ambient\\rnd_outdoor\\rnd_horror_3",
"ambient\\rnd_outdoor\\rnd_horror_4",
"ambient\\rnd_outdoor\\rnd_m-16_1",
"ambient\\rnd_outdoor\\rnd_m-16_2",
"ambient\\rnd_outdoor\\rnd_meow",
"ambient\\rnd_outdoor\\rnd_moan_1",
"ambient\\rnd_outdoor\\rnd_moan_2",
"ambient\\rnd_outdoor\\rnd_moan_3",
"ambient\\rnd_outdoor\\rnd_moan_4",
"ambient\\rnd_outdoor\\rnd_moan_5",
"ambient\\rnd_outdoor\\rnd_moan_6",
"ambient\\rnd_outdoor\\rnd_ratchant",
"ambient\\rnd_outdoor\\rnd_scr_1",
"ambient\\rnd_outdoor\\rnd_scr_2",
"ambient\\rnd_outdoor\\rnd_scr_3",
"ambient\\rnd_outdoor\\rnd_scr_4",
"ambient\\rnd_outdoor\\rnd_scr_5",
"ambient\\rnd_outdoor\\rnd_scr_6",
"ambient\\rnd_outdoor\\rnd_scr_7",
"ambient\\rnd_outdoor\\rnd_scr_8",
"ambient\\rnd_outdoor\\rnd_scr_9",
"ambient\\rnd_outdoor\\rnd_sickened_1",
"ambient\\rnd_outdoor\\rnd_sickened_2",
"ambient\\rnd_outdoor\\rnd_squeak",
"ambient\\rnd_outdoor\\rnd_thunder",
"ambient\\rnd_outdoor\\rnd_wolfhowl_1",
"ambient\\rnd_outdoor\\rnd_wolfhowl_2"
}

local default_sounds={
"ambient\\rnd_outdoor\\rnd_ak47_1",
"ambient\\rnd_outdoor\\rnd_ak47_2",
"ambient\\rnd_outdoor\\rnd_barking",
"ambient\\rnd_outdoor\\rnd_car",
"ambient\\rnd_outdoor\\rnd_chimes",
"ambient\\rnd_outdoor\\rnd_cooing",
"ambient\\rnd_outdoor\\rnd_crow_1",
"ambient\\rnd_outdoor\\rnd_crow_2",
"ambient\\rnd_outdoor\\rnd_crow_3",
"ambient\\rnd_outdoor\\rnd_darkwind",
"ambient\\rnd_outdoor\\rnd_deep_barking",
"ambient\\rnd_outdoor\\rnd_disgusting",
"ambient\\rnd_outdoor\\rnd_distantmortar",
"ambient\\rnd_outdoor\\rnd_doubler",
"ambient\\rnd_outdoor\\rnd_drone_1",
"ambient\\rnd_outdoor\\rnd_drone_2",
"ambient\\rnd_outdoor\\rnd_fallscream",
"ambient\\rnd_outdoor\\rnd_heart",
"ambient\\rnd_outdoor\\rnd_helicopter",
"ambient\\rnd_outdoor\\rnd_horror_1",
"ambient\\rnd_outdoor\\rnd_horror_2",
"ambient\\rnd_outdoor\\rnd_horror_3",
"ambient\\rnd_outdoor\\rnd_horror_4",
"ambient\\rnd_outdoor\\rnd_m-16_1",
"ambient\\rnd_outdoor\\rnd_m-16_2",
"ambient\\rnd_outdoor\\rnd_meow",
"ambient\\rnd_outdoor\\rnd_moan_1",
"ambient\\rnd_outdoor\\rnd_moan_2",
"ambient\\rnd_outdoor\\rnd_moan_3",
"ambient\\rnd_outdoor\\rnd_moan_4",
"ambient\\rnd_outdoor\\rnd_moan_5",
"ambient\\rnd_outdoor\\rnd_moan_6",
"ambient\\rnd_outdoor\\rnd_ratchant",
"ambient\\rnd_outdoor\\rnd_scr_1",
"ambient\\rnd_outdoor\\rnd_scr_2",
"ambient\\rnd_outdoor\\rnd_scr_3",
"ambient\\rnd_outdoor\\rnd_scr_4",
"ambient\\rnd_outdoor\\rnd_scr_5",
"ambient\\rnd_outdoor\\rnd_scr_6",
"ambient\\rnd_outdoor\\rnd_scr_7",
"ambient\\rnd_outdoor\\rnd_scr_8",
"ambient\\rnd_outdoor\\rnd_scr_9",
"ambient\\rnd_outdoor\\rnd_sickened_1",
"ambient\\rnd_outdoor\\rnd_sickened_2",
"ambient\\rnd_outdoor\\rnd_squeak",
"ambient\\rnd_outdoor\\rnd_thunder",
"ambient\\rnd_outdoor\\rnd_wolfhowl_1",
"ambient\\rnd_outdoor\\rnd_wolfhowl_2"
}

local indoor_lab_sounds = {
"ambient\\rnd_indoor\\rnd_breath_1",
"ambient\\rnd_indoor\\rnd_breath_2",
"ambient\\rnd_indoor\\rnd_dark_1",
"ambient\\rnd_indoor\\rnd_hit_1",
"ambient\\rnd_indoor\\rnd_hit_2",
"ambient\\rnd_indoor\\rnd_strange_noise_1",
"ambient\\rnd_indoor\\rnd_strange_noise_2",
"ambient\\rnd_indoor\\rnd_strange_noise_3"
}

local monolith_call = {
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_1",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_2",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_3",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_4",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_5",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_6",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_7"
}

local bsnd_obj = xr_sound.get_safe_sound_object([[music\mon_murderwrecker_l]])

function play_rnd_snd()

		if not level.present() then return end

      		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_bossfight_zone"})) then
			if has_alife_info("oso_killed") then return end

			local snd_obj = xr_sound.get_safe_sound_object(indoor_lab_sounds[math.random(table.getn(indoor_lab_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
			local randd = math.random(1,3)
			if randd == 1 then
				olr.spawen_phantoms()
				nick.clear_chaes_zom()
			elseif randd == 2 then
				nick.stancia_fake_anoms()
			else
				nick.phantasms_zombies()
			end

			if not bsnd_obj:playing() then 
				bsnd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
			end

		end

		if level.name() == "lvl16_generators" then return end 

		if has_alife_info("olr_traders_night") and not olr.actor_in_lab() then
			local snd_obj = xr_sound.get_safe_sound_object(night_sounds[math.random(table.getn(night_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		elseif has_alife_info("olr_traders_day") and not olr.actor_in_lab() and level.rain_factor() <= 0.1 then
			local snd_obj = xr_sound.get_safe_sound_object(day_sounds[math.random(table.getn(day_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		else
			local snd_obj = xr_sound.get_safe_sound_object(default_sounds[math.random(table.getn(default_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		end
		if olr.actor_in_lab() then
			local snd_obj = xr_sound.get_safe_sound_object(indoor_lab_sounds[math.random(table.getn(indoor_lab_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		end
		if actor_on_chaes() then
			local snd_obj = xr_sound.get_safe_sound_object(monolith_call[math.random(table.getn(monolith_call))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
			local rnd = math.random(1,5)
			if rnd == 1 then
				olr.spawen_phantoms()
				nick.clear_chaes_zom()
			else
				nick.stancia_fake_anoms()
			end
		end
end


-- db.actor:is_actor_outdoors() == false


function actor_on_chaes()
	local level_name = level.name()
	if level_name == "lvl14_stancia" and not has_alife_info("actor_ishet_sebbya_info") then
		return true
	end
end


