local enable = true
local tip = nil

function create()
  local sim = alife()
    if not sim then
        return
    end

    if enable == false then
        return
    end

    local gar = sim:object("lvl2_garbage_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl3_agroprom_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl4_darkdolina_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_small", tip)
    end

    local gar = sim:object("lvl5_bar_physic_fog_sity")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl7_yantar_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl8_swamp_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl9_military_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl10_radar_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl11_deadcity_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl13_prip_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl14_stancia_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl16_generators_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end

    local gar = sim:object("lvl_level12_physic_fog_center")
    if gar then
        olr.add_spot_on_map(gar.id, "fog_of_war_big", tip)
    end
end
