-- hi_flyer 18.06.16

function on_take(obj)
	local sim = alife()
	if level.name() == "l05_bar" then
		if device().precache_frame > 1 then
			return
		end
		if not has_alife_info("bar_robbing_sms") then
			local oname = obj:name()
			if oname == "lvl5_bar_kolbasa" or oname == "lvl5_bar_conserva" or oname == "lvl5_bar_physic_object_1079" or
					oname == "lvl5_bar_medkit_0011" or
					oname == "lvl5_bar_vodka_0013" or
					oname == "lvl5_bar_bread" or
					oname == "lvl5_bar_bread_0000" or
					oname == "lvl5_bar_antirad_0013" then
				db.actor:change_character_reputation(-5)
				news_manager.send_tip(db.actor, game.translate_string("bar_robber_actor_0"), 5, "unknown", 15000, nil, nil, false)
				olr.info("bar_robbing_sms")
				--news_manager.send_tip(db.actor, game.translate_string("on_take_0"), nil, "flash", 35000)
			end
		end
	end
	
	if obj:section() == "agro_case_01" then
		ui_hud_toolskit.Del_MapSpot(obj:id(), "treasure")
	end

	if obj:section() == "yad" then
		local sobj = sim:object(obj:id())
		if sobj then
			sim:release(sobj, true) -- Йадулин не должен быть у ГГ вообще
		end
	end -- !! ai_medic

	if obj:section() == "device_pda" then
		if device().precache_frame > 1 then
			return
		end
		if obj:original_owner_id() == db.actor:id() then
			return
		end
		olr.del(obj)
		local cond = obj:condition()
		local bobj3445 = sim:create("item_pda_dead_taken", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		level.client_spawn_manager():add(bobj3445.id, 0,
			function(id, obj)
				obj:set_condition(cond)
			end
		)
		--log1("item_pda_dead fix")
		local yaz_var = math.random(1, 15)
		if yaz_var == 1 then
			olr_treasure.create_treasure()
		else
			--log1("nope")
		end
	end

	if obj:section() == "psy_blocerator" and has_alife_info("esc_to_bar_start_go_dolina") and xvars.id_psyblock_garbage == -1 then
		news_manager.send_tip(db.actor, game.translate_string("on_take_1"), 5, "hero", 15000, nil, nil, true, xr_effects.get_real_actor_name())
		news_manager.send_tip(db.actor, game.translate_string("on_take_2"), 15, "lone_wolf", 35000, nil, nil, true, "st_sim_test_036_name")
		xvars.id_psyblock_garbage = obj:id()
	end

	if obj:section() == "agro_pda_pilot" and not has_alife_info("agr_pilot_take_pda") then
		news_manager.send_tip(db.actor, game.translate_string("on_take_3"), 1, "flash", 5000, nil, nil, true, "device-PDA")
		olr.info("agr_pilot_take_pda")
	end

	if obj:section() == "item_pda_dead" then
		local cond = obj:condition()
		olr.del(obj)
		local bobj3445 = sim:create("item_pda_dead_taken", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		level.client_spawn_manager():add(bobj3445.id, 0,
			function(id, obj)
				obj:set_condition(cond)
			end
		)
		--log1("item_pda_dead fix")
		local yaz_var = math.random(1, 11)
		if yaz_var == 1 then
			olr_treasure.create_treasure()
		else
			--log1("nope2")
		end
	end
end
