-- hi_flyer 25.03.16

local ini = system_ini()

function klick_item_inv(obj)

    if not obj then
        return
    end


    local has_geiger = db.actor:object("detector_simple")
    if has_geiger then
        local cnd = has_geiger:condition()
        if cnd > 0.01 then
            if xvars.foods[obj:name()] == true or xvars.weapons[obj:name()] == true then
                --log1("has rad obj")
                local snd_obj = xr_sound.get_safe_sound_object([[device\detectors\geiger_noise_loop]])
                if not snd_obj:playing() then
                    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
                end
                if not has_alife_info("radiation_inv_act_cliked") then
                    olr.info("radiation_inv_act_cliked")
                    news_manager.send_tip(db.actor, game.translate_string("st_olr_items_inv_click_radioactive_thing_1").." "..obj:get_name().." "..game.translate_string("st_olr_items_inv_click_radioactive_thing_2"), nil, "act", 59000)
                end
            end
            if ini:line_exist(obj:section(), "inventory_radiation") then
                local snd_obj = xr_sound.get_safe_sound_object([[device\detectors\geiger_noise_loop]])
                if not snd_obj:playing() then
                    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
                    --log1(" snd has inventory_radiation ")
                end
            end
        end
    end


    if obj:section() == "glaz_fila" and not has_alife_info("glaz_fila_checked") then
        db.actor:give_info_portion("glaz_fila_checked")
    end

    if obj:section() == "af_art_lampa" then
        db.actor.psy_health = -0.34
        local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\psy_noise]])
        if not snd_obj:playing() then
            snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
        end
    end


    if obj:section() == "af_cristall_flower" and not has_alife_info("encyclopedy_zone_artifact_af_cristall_flower") then
        af_unic()
    end
    if obj:section() == "af_night_star" and not has_alife_info("encyclopedy_zone_artifact_af_night_star") then
        af_unic()
    end
    if obj:section() == "af_vyvert" and not has_alife_info("encyclopedy_zone_artifact_af_vyvert") then
        af_grav()
    end
    if obj:section() == "af_gold_fish" and not has_alife_info("encyclopedy_zone_artifact_af_gold_fish") then
        af_grav()
    end
    if obj:section() == "af_drops" and not has_alife_info("encyclopedy_zone_artifact_af_drops") then
        af_unic()
    end
    if obj:section() == "af_fireball" and not has_alife_info("encyclopedy_zone_artifact_af_fireball") then
    --af_heat()
    end
    if obj:section() == "af_mincer_meat" and not has_alife_info("encyclopedy_zone_artifact_af_mincer_meat") then
        af_unic()
    end
    if obj:section() == "af_soul" and not has_alife_info("encyclopedy_zone_artifact_af_soul") then
        af_unic()
    end
    if obj:section() == "af_electra_flash" and not has_alife_info("encyclopedy_zone_artifact_af_electra_flash") then
        af_elec()
    end


end
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

function af_grav()
    local snd_obj = xr_sound.get_safe_sound_object([[anomaly\mosquito_bald_idle]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end


function af_elec()
    local snd_obj = xr_sound.get_safe_sound_object([[anomaly\electra_hit1]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

function af_heat()
--	local snd_obj = xr_sound.get_safe_sound_object([[anomaly\polter_fire_idle]])
--	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

function af_unic()
    local snd_obj = xr_sound.get_safe_sound_object([[anomaly\monolith_idle]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end
