-- hi_flyer 30.04.17

class "ui_quests_table" (CUIScriptWnd)

function ui_quests_table:__init() super()
	self:InitControls()
	self:InitCallBacks()
end

function ui_quests_table:__finalize()
end

function ui_quests_table:InitControls()
	local xml = CScriptXmlInit()
	self:Init(0,0,1024,768)
	xml:ParseFile("ui_quests_table.xml")
	self.background_main = xml:InitStatic("background_main", self)
	self.background_top = xml:InitStatic("background_main:background_top", self.background_main)
	self.background_bottom = xml:InitStatic("background_main:background_bottom", self.background_main)	
	self.background_table = xml:InitStatic("background_main:background_table", self.background_main)
	self.frame_desc_quest = xml:InitFrame("background_main:background_table:frame_desc_quest", self.background_table)
	self.static_desc_quest = xml:InitStatic("background_main:background_table:frame_desc_quest:static_desc_quest", self.frame_desc_quest)
	self.frame_list_quest = xml:InitFrame("background_main:background_table:frame_list_quest", self.background_table)
	self:Register(xml:Init3tButton("background_main:background_table:frame_list_quest:bt_find_item", self.frame_list_quest), "bt_find_item")
	self:Register(xml:Init3tButton("background_main:background_table:frame_list_quest:bt_kill_stalker", self.frame_list_quest), "bt_kill_stalker")
	self:Register(xml:Init3tButton("background_main:background_table:button_exit", self.background_table), "button_exit")
	self:Register(xml:Init3tButton("background_main:background_table:button_take_quest", self.background_table), "button_take_quest")
	self.Static3 = xml:InitStatic("background_main:background_table:Static3", self.background_table)
	local job_selected = false 
	local job_selected_kill = false
	local nm = "" 
end

function ui_quests_table:InitCallBacks()
	self:AddCallback("bt_find_item", ui_events.BUTTON_CLICKED, self.bt_find_item_button_clicked, self)
	self:AddCallback("bt_kill_stalker", ui_events.BUTTON_CLICKED, self.bt_kill_stalker_button_clicked, self)
	self:AddCallback("button_exit", ui_events.BUTTON_CLICKED, self.button_exit_button_clicked, self)
	self:AddCallback("button_take_quest", ui_events.BUTTON_CLICKED, self.button_take_quest_button_clicked, self)
end

function ui_quests_table:bt_find_item_button_clicked()
	job_selected_kill = false 
	local textdesc = game.translate_string(""..xvars.quest_one_text_yan.." — "..game.translate_string(xvars.quest_one_text_name_yan)..game.translate_string("st_olr_doska_payment")..xvars.quest_one_cost_yan.." ")
	if not has_alife_info("doska_one_taken_yan") then
		self.static_desc_quest:SetText(textdesc)
		job_selected = true
	elseif xvars.quest_one_target_yan == "" and has_alife_info("doska_one_taken_yan") then
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_no_work_available"))
	else
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_task_taken_retrieve_item")..game.translate_string(xvars.quest_one_text_name_yan)..game.translate_string("st_olr_doska_payment")..xvars.quest_one_cost_yan.." ")
	end
end

function ui_quests_table:bt_kill_stalker_button_clicked()
	job_selected = false
	local sobj = game.translate_string(xvars.quest_two_target_yan)
	local obj = alife():object(sobj)
	if not obj then
		olr_doska_yan.gen_kill_stalker()
 		nm = game.translate_string("st_olr_doska_yan_no_notes") 
		log1("sobj is nil")
		return
	end
	local pos = news_main.get_point_description(alife():level_name(game_graph():vertex(obj.m_game_vertex_id):level_id()), vector():set(obj.position.x,obj.position.y,obj.position.z))
	if xvars.quest_two_target_yan == "" then
		nm = "empty"
	end
	local textdesc = game.translate_string(game.translate_string("st_olr_doska_need_kill_strong_mutant").." "..pos..game.translate_string("st_olr_doska_payment").." "..xvars.quest_two_cost_yan)
	if not has_alife_info("doska_two_taken_yan") then
		self.static_desc_quest:SetText(textdesc)
		job_selected_kill = true
	elseif xvars.quest_two_target_yan == "" and has_alife_info("doska_two_taken_yan") then
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_no_work_available"))
	else
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_need_kill_strong_mutant_accepted").." "..xvars.quest_two_cost_yan)
	end  
end

function ui_quests_table:button_exit_button_clicked()
	job_selected = false
	job_selected_kill = false 
	self:GetHolder():start_stop_menu(self, true)
	bind_stalker.restore_weapon()
	level.remove_cam_effector(30)
end

function ui_quests_table:button_take_quest_button_clicked()
	if job_selected == true then
		job_selected_kill = false
		xvars.quests_all_ids = xvars.quests_all_ids + 1
		--log1("quest take now -  clear job one")
		job_selected = false
		self:GetHolder():start_stop_menu(self, true)
		bind_stalker.restore_weapon()
		level.remove_cam_effector(30)
		olr.info("doska_one_taken_yan")
		olr.info("doska_one_working_yan")
		news_manager.send_tip(db.actor, game.translate_string("st_olr_doska_find_item").." "..game.translate_string(xvars.quest_one_text_name_yan)..game.translate_string("st_olr_doska_yan_task_2"), 1, "item", 9000)
		olr_timers.st_timer("doska_one_gen_timer_fail_yan", 8500, "olr_doska_yan.doska_one_gen_timer_fail_yan()")
		db.actor:give_info_portion("yan_doska_quest_taken")
	else
		--log1("cannot take quest")
	end

	if job_selected_kill == true then
		--log1("take two")
		job_selected = false
		xvars.quests_all_ids = xvars.quests_all_ids + 1
		job_selected_kill = false
		self:GetHolder():start_stop_menu(self, true)
		bind_stalker.restore_weapon()
		level.remove_cam_effector(30)
		olr.info("doska_two_taken_yan")
		olr.info("doska_two_working_yan")
		news_manager.send_tip(db.actor, game.translate_string("ui_quests_tablebutton_take_quest_button_clicked_yantar"), 1, "mutants", 9000)
		local sobj = game.translate_string(xvars.quest_two_target_yan)
		local obj = alife():object(sobj)
		xvars.quest_two_cost_yan = 350
		
		olr.add_spot_on_map( obj.id,"monster_part_location", "Заказ от Профессора на Янтаре: убить мутанта" )
		olr_timers.st_timer("doska_two_gen_timer_fail_yan", 8500, "olr_doska_yan.doska_two_gen_timer_fail_yan()")
		db.actor:give_info_portion("yan_doska_quest_taken")
	else
		--log1("cannot take quest")
	end
end

function ui_quests_table:Hide()
	self:GetHolder():start_stop_menu(self, true)
	bind_stalker.restore_weapon()
	level.remove_cam_effector(30)
end

----------------------------------------------------------------------------------------------------------------------------
-- Поиск предметов

-- таймер на провал задания 
function doska_one_gen_timer_fail_yan()
	olr_doska_yan.clear_find_item()
	olr_timers.st_timer("doska_one_gen_yan", 33, "olr_doska_yan.gen_rnd_item_find()")
	db.actor:disable_info_portion("doska_one_working_yan")
	db.actor:disable_info_portion("yan_doska_quest_taken")
	db.actor:change_character_reputation(-20)
end 

-- преконд наличия итема
function precond_user_task_doska_item()
	if xvars.quest_one_target_yan == "" then
		return false
	end
	local obj_targ = tostring(xvars.quest_one_target_yan)
	--log1("need- "..obj_targ.." ")
	local art = db.actor:object(obj_targ)
	if art and art:is_artefact() then
		return false
	end
	return nik_dialog.item_much(obj_targ,1) ~= false 
end

function has_any_active_task_doska(first_speaker, second_speaker)
	if xvars.quest_one_target_yan ~= "" then
		return true
	end
	if xvars.quest_two_target_yan ~= "" then
		return true
	end
	return false
end

function precond_user_task_doska_item_art()
	if xvars.quest_one_target_yan == "" then
		return false
	end
	local obj_targ = game.translate_string(xvars.quest_one_target_yan)
	local art = db.actor:object(obj_targ)
	if art and not art:is_artefact() then
		return false
	end
	if art and art:is_artefact() then
		local known_inf = ini_sys:r_string(obj_targ, "known_info")
     	return nik_dialog.item_much(obj_targ,1) ~= false and has_alife_info(known_inf)
	end
end

-- сдаём квест на предмет
function one_complete_func_item()
	local mon = math.floor(xvars.quest_one_cost_yan) 
	db.actor:give_money(mon)
	game_stats.money_quest_update(mon)
	news_manager.relocate_money(db.actor, "in", mon)
	local obj_targ = tostring(xvars.quest_one_target_yan)
	nik_dialog.out_item_much(obj_targ,1)
	olr_doska_yan.clear_find_item()
	db.actor:disable_info_portion("doska_one_working_yan")
	db.actor:disable_info_portion("yan_doska_quest_taken")
	local time = math.random(96,466)
	olr_timers.st_timer("doska_one_genyan", time, "olr_doska_yan.gen_rnd_item_find()")
	olr_timers.del_timer("doska_one_gen_timer_fail_yan")

end


-- генерация предмета для поиска
function gen_rnd_item_find()
	--log1("gen one find jaba")
	db.actor:disable_info_portion("doska_one_taken_yan")
	local find_item_obj = {
	 
		 [1] = {name = "mutant_flesh_eye",            		cost = 120,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_flesh")},
		 [2] = {name = "mutant_boar_leg",       		cost = 140,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_boar")},
		 [3] = {name = "mutant_dog_tail",       		cost = 140,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_dog")},
		 [4] = {name = "mutant_psevdodog_tail",       			cost = 250,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_pseudodog")},
		 [5] = {name = "mutant_krovosos_jaw",       			cost = 350,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_bloodsucker")},
		 [6] = {name = "mutant_burer_hand",       			cost = 400,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_burer")},
		 [7] = {name = "mutant_zombie_hand",       			cost = 170,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_zombie")},
		 [8] = {name = "af_magnet",       			cost = 800,  text = game.translate_string("st_olr_doska_yan_find_item_magnet")},
		 [9] = {name = "af_zuda",       			cost = 300,  text = game.translate_string("st_olr_doska_yan_find_item_zuda")},
		 [10] = {name = "af_knot",       		cost = 300,  text = game.translate_string("st_olr_doska_bar_find_item_sparkler")},
		 [11] = {name = "af_mercury_ball",       			cost = 300,  text = game.translate_string("st_olr_doska_yan_find_item_mercury_ball")},
		 [12] = {name = "af_rusty_hair",       		cost = 200,  text = game.translate_string("st_olr_doska_yan_find_item_rusty_hair")},
		 [13] = {name = "af_bublik",       			cost = 200,  text = game.translate_string("st_olr_doska_yan_find_item_bagel")},
		 [14] = {name = "rat_food",       			cost = 135,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_rat")},
		 [15] = {name = "af_gravi_heavy",       			cost = 800,  text = game.translate_string("st_olr_doska_yan_find_item_strong_gravity_art")},
		 [16] = {name = "af_gravi_black",       			cost = 1500,  text = game.translate_string("st_olr_doska_yan_find_item_black_gravi")},
		 [17] = {name = "crow_food",       				cost = 150,  text = game.translate_string("st_olr_doska_yan_find_item_mutant_crow")}

		}

	local irnd = math.random(#find_item_obj) or 1
	local item = tostring(find_item_obj[irnd].name)
	local cost = tostring(find_item_obj[irnd].cost)
	local text = tostring(find_item_obj[irnd].text)

	xvars.quest_one_target_yan = item
	xvars.quest_one_cost_yan = cost
	xvars.quest_one_text_name_yan = text

	local text_phrase = {
		"st_olr_doska_find_item_preface_1", 
		"st_olr_doska_find_item_preface_2", 
		"st_olr_doska_yan_find_item_preface_1", 
		"st_olr_doska_yan_find_item_preface_2"
	}
	local text_find = game.translate_string(text_phrase[math.random(#text_phrase)])
	xvars.quest_one_text_yan = text_find

	--log1("jaba doska need find new - "..xvars.quest_one_target_yan.."  --- "..xvars.quest_one_cost_yan.."")
end

-- отчистка итема для поиска
function clear_find_item()
	xvars.quest_one_target_yan = ""
	xvars.quest_one_cost_yan = 0
	xvars.quest_one_text_yan = ""
	xvars.quest_one_text_name_yan = ""
end

-- завершаем квест
function one_complete_task_item()
	return not has_alife_info("doska_one_working_yan")
end

function one_complete_task_item_fail()
	return false
end


----------------------------------------------------------------------------------------------------------------------------
-- убить мутанта

-- таймер на провал задания 
function doska_two_gen_timer_fail_yan()
	local sobj = game.translate_string(xvars.quest_two_target_yan)
	local obj = alife():object(sobj)
	level.map_remove_object_spot(obj.id, "monster_part_location")
	olr_doska_yan.clear_find_kill()
	olr_timers.st_timer("gen_kill_monster", 26, "olr_doska_yan.gen_kill_stalker()")
	db.actor:disable_info_portion("doska_two_working_yan")
	db.actor:disable_info_portion("yan_doska_quest_taken")
	db.actor:change_character_reputation(-20)
end 

function gen_kill_stalker()
	db.actor:disable_info_portion("doska_two_taken_yan")
	local montabl = 
	{
       		[clsid.burer_s] = true,
       		[clsid.controller_s] = true,
       		[clsid.gigant_s] = true,
       		[clsid.fracture_s] = true,
       		[clsid.chimera_s] = true
	}
	local places = {}
	for _, kill in ipairs(olr_offline_walk.tabst) do
	--for id=1, 65534 do
		--local kill = sim:object(id)
		--local sim = alife()
		if kill then
				if montabl[kill:clsid()] then
					if kill.alive and kill:alive() and kill.level_name == "l03_agroprom" or kill.level_name == "l01_escape" or kill.level_name == "l02_garbage" or kill.level_name == "l04_darkvalley" or kill.level_name == "l06_rostok"
						or kill.level_name == "l07_yantar" or kill.level_name == "l09_military" or kill.level_name == "l11_deadcity" then
						if not olr_protected.is_no_offline_alife_obj(kill:name()) then
							table.insert(places, kill)
						end
					end
			end
		end
	end
	local rand_kill = places[math.random(#places)]
	xvars.quest_two_target_yan = rand_kill:name()
	xvars.quest_two_cost_yan = 350
	--olr.add_spot_on_map( rand_kill.id,"crlc_big", "килл" )
	--news_manager.send_tip(db.actor, "есть rand_kill "..rand_kill:name().." -- "..rand_kill.level_name.." ")
end


-- преконд убитого мутанта
function precond_user_task_doska_kill()
	if xvars.quest_two_target_yan == "" then
		return false
	end
     	local sobj = game.translate_string(xvars.quest_two_target_yan)
     	local obj = alife():object(sobj)
	if obj then
     		return not obj:alive() and has_alife_info("doska_two_taken_yan")
	end
end

-- сдаём квест на мутанта
function two_complete_func_kill()
     	local sobj = game.translate_string(xvars.quest_two_target_yan)
     	local obj = alife():object(sobj)
	level.map_remove_object_spot(obj.id, "monster_part_location")
	db.actor:give_money(xvars.quest_two_cost_yan)
	game_stats.money_quest_update(xvars.quest_two_cost_yan)
	news_manager.relocate_money(db.actor, "in", xvars.quest_two_cost_yan)
	db.actor:disable_info_portion("doska_two_working_yan")
	db.actor:disable_info_portion("yan_doska_quest_taken")
	local time = math.random(90,160)
	olr_timers.st_timer("gen_kill_stalker", time, "olr_doska_yan.gen_kill_stalker()")
	olr_doska_yan.clear_find_kill()
	olr_timers.del_timer("doska_two_gen_timer_fail_yan")
end

-- отчистка текущего убитого для поиска
function clear_find_kill()
	xvars.quest_two_target_yan = ""
	xvars.quest_two_cost_yan = 0
end






