-- Çàâèñèìîñòü ïîäâèæíîñòè ÃÃ îáùåãî ñîñòîÿíèÿ îğãàíèçìà
-- hi_flyer 05/03/15


local time_apd = 0
local timeru = 1236

function update()
	if db.actor == nil then
		return
	end
	if not alife() then
		return
	end
	if time_global() > time_apd then
		time_apd = time_global() + timeru

        if db.actor and db.actor:alive() and xvars then
        
			local iCurrSat = db.actor.satiety 
			local iCurrHea = db.actor.health
			local zazda = db.actor:get_actor_thirst()
			local iAllcond = math.max(iCurrSat * iCurrHea * zazda * 4, 0.1)

			if db.actor.max_power ~= iAllcond then
				db.actor.max_power = iAllcond        
			end

			if has_alife_info("actor_healing_medkit") then
				db.actor.health = db.actor.health + 0.015 - db.actor.health
			end

			if has_alife_info("actor_healing_antirad") then
				db.actor.radiation = - 0.05
				db.actor.alcohol = 0.01
				db.actor.power = 0.04
			end

			if has_alife_info("anti_glob_rad") then
				db.actor.radiation = - 0.4
				db.actor.alcohol = 0.001
			end

			-- if has_alife_info("deadzone_eff_now") then
				-- db.actor.psy_health = -0.02
				-- db.actor.alcohol = 0.0025
				-- level.add_pp_effector("brighten.ppe", 16771, true)
			-- end

			if db.actor.radiation > 0.45 then
				local radppe = db.actor.radiation
				level.add_pp_effector("radiation.ppe", 165236, true)
				level.set_pp_effector_factor(165236, radppe / 3)
			else
				level.remove_pp_effector(165236)
			end
		--log1(""..a.walk_accel.."")
		end
	end
end


function exo_check_jump()
	if db.actor then
		local has_out = db.actor:object("exo_outfit")
		if not has_out then
			return 0
		end
		if has_out and not db.actor:is_in_slot(has_out) then
			return 0
		end
		if has_out and db.actor:is_in_slot(has_out) then
			local exo_acum = db.actor:object("exo_acum_ob")
			if not exo_acum then
				local iCurrPow = db.actor.power * 6.5
				return iCurrPow
			end
		end

		if has_out and db.actor:is_in_slot(has_out) then
			local exo_acum = db.actor:object("exo_acum_ob")
			if exo_acum and not db.actor:is_on_belt(exo_acum) then
				local iCurrPow = db.actor.power * 6.5
				return iCurrPow
			end
		end

		if has_out and db.actor:is_in_slot(has_out) then
			local exo_acum = db.actor:object("exo_acum_ob")
			if exo_acum and db.actor:is_on_belt(exo_acum) then
				return 0
			end
		end
	end
end



function exo_check_walk()
	if db.actor then
		local has_out = db.actor:object("exo_outfit")
		if not has_out then
			return 0
		end
		if has_out and not db.actor:is_in_slot(has_out) then
			return 0
		end
		if has_out and db.actor:is_in_slot(has_out) then
			local exo_acum = db.actor:object("exo_acum_ob")
			if not exo_acum then
				local iCurrSat  = db.actor.satiety 
				local iCurrHea  = db.actor.health
				local ustalost  = db.actor:get_actor_sleep()
				local zazda 	= db.actor:get_actor_thirst()
				local iCurrPow5 = db.actor.power * 5
				local iAllcond = iCurrSat * iCurrHea * ustalost * zazda * 4
				local exwalk = 5 + iAllcond + iCurrPow5
				return exwalk
			end
		end


		if has_out and db.actor:is_in_slot(has_out) then
			local exo_acum = db.actor:object("exo_acum_ob")
			if exo_acum and not db.actor:is_on_belt(exo_acum) then
				local iCurrSat = db.actor.satiety 
				local iCurrHea = db.actor.health
				local zazda = db.actor:get_actor_thirst()
				local ustalost = db.actor:get_actor_sleep()
				local iCurrPow5 = db.actor.power * 5
				local iAllcond = iCurrSat * iCurrHea * ustalost * zazda * 4
				local exwalk = 5 + iAllcond + iCurrPow5
				return exwalk
			end
		end

		if has_out and db.actor:is_in_slot(has_out) then
			local exo_acum = db.actor:object("exo_acum_ob")
			if exo_acum and db.actor:is_on_belt(exo_acum) then
				return 0
			end
		end
	end
end



function walk_exo_prm()
	if db.actor then
		local has_out = db.actor:object("exo_outfit")
		if not has_out then
			return 0
		end
		if has_out and not db.actor:is_in_slot(has_out) then
			return 0
		end
		if has_out and db.actor:is_in_slot(has_out) then
			return 2.5
		end
	end
end



function jump_golmar_outfit()
	if db.actor then
		local has_out = db.actor:object("outfit_stalker_golmar")
		if not has_out then
			return 0
		end
		if has_out and not db.actor:is_in_slot(has_out) then
			return 0
		end
		if has_out and db.actor:is_in_slot(has_out) then
			return 2.5
		end
	end
end


function jump_exo_outfit()
	if db.actor then
		local has_out = db.actor:object("exo_outfit")
		if not has_out then
			return 0
		end
		if has_out and not db.actor:is_in_slot(has_out) then
			return 0
		end
		if has_out and db.actor:is_in_slot(has_out) then
			return 1.5
		end
	end
end

----------------------------------------------------------------------------------------------------

--Oblivion Lost Remake (2014)
--(c) proger_Dencheek
--Àğòåôàêòû, ïîäíèìàşùèå ìàêñèìàëüíûé âåñ â èíâåíòàğå

local ini = system_ini()
local last_obj = {}

local function take_item(state, obj)
	if state == true then
		if last_obj[tostring(obj:id())] == nil then
			last_obj[tostring(obj:id())] = true
		end
	elseif last_obj[tostring(obj:id())] == true then
		last_obj[tostring(obj:id())] = nil
	else
		return nil
	end
end


--Êîëëáåê íà ïîìåùåíèå ïğåäìåòà íà ñëîò
function take_item_on_slot(obj)
	take_item(true, obj)
end
--Êîëëáåê íà ïîìåùåíèå ïğåäìåòà íà ïîÿñ
function take_item_on_belt(obj)
	take_item(true, obj)
end
--Êîëëáåê íà ïîìåùåíèå ïğåäìåòà â ğşêçàê
function take_item_on_ruck(obj)
	take_item(false, obj)
end
--Êîëëáåê íà âûáğàñûâàíèå ïğåäìåòà èç èíâåíòàğÿ
function drop_item_on_inv(obj)
	take_item(false, obj)
end


----- ÒÅÌÏÅĞÀÒÓĞÀ ÃÃ
----------------------------------------------------------------------------------------------------
local min_porog_temp = 34
local max_porog_temp = 40

local min_temp = 32
local max_temp = 42

function act_temp()

	if not has_alife_info("esc_olr_kvest_3") then
		return 
	end

	--if level.name() == "lvl1_escape" or level.name() == "lvl2_garbage" then
		--return
	--end 

	if level.name() == "lvl16_generators" then
		return
	end
end

function has_norm_teploprot()
	local outfit = db.actor:get_current_outfit()
	if outfit and outfit:condition() > 0.51 then
		return true
	end
end

----------------------------------------------------------------------------------------------------
