-- hi_flyer 27/04/16
-- сюжетные функции

function on_netspawn()
	local level_name = level.name()
	local sim = alife()
	-- фикс
	if has_alife_info("karlik_gen_rush_goinfo") and sim:object("lvl16_generators_karlik") ~= nil and level_name == "lvl16_generators" then
		--log1("fix karlk")
		olr.del_by_name("lvl16_generators_karlik")
	--olr.info("karlik_gen_rush_goinfo_delkarlik")
	end

	--[[
	if has_alife_info("monolit_na_kordone") and not has_alife_info("start_freeplay_olr_start") then
		if level.name() ~= "lvl12_radar_bunker" or level.name() ~= "lvl16_generators" then
			--log1("gen wea")
			local wait_time = 0
			wait_time = time_global() + 100
			level.add_call(
				function() return time_global() > wait_time end,
				function() level.set_weather("gen",true) end
			)
		end
	end
--]]
	-- починка поврежденных данных
	if has_alife_info("monolit_na_kordone") and not has_alife_info("try_reload_pda_done_start") then
		if olr_timers.has_timer("first_killer_timer_sms") then
			olr_timers.del_timer("first_killer_timer_sms")
		end
		if olr_timers.has_timer("first_killer_timer") then
			olr_timers.del_timer("first_killer_timer")
		end
		olr_timers.st_timer("reload_pda2", 62, "nick.enemys_sms_pda_escape_mon()")
		db.actor:give_info_portion("try_reload_pda_done_start")
		if has_alife_info("try_reload_pda_done") then
			olr_timers.st_timer("try_reload_pda_done", 5, "nick.reload_pda_escape_mon()")
		end
	end

	if not has_alife_info("fin_rush_from_sarco_to_warlab_acess") and has_alife_info("fin_rush_from_sarco_to_warlab") and level_name == "lvl16_generators" then
		olr.info("fin_rush_from_sarco_to_warlab_acess")
		nick.from_sarco_to_cemetery()
	end

	-- старт фриплея
	if not has_alife_info("start_freeplay_olr_start") and has_alife_info("start_freeplay_olr") then
		olr_freeplay.start()
		db.actor:give_info_portion("start_freeplay_olr_start")
	end

	-- спавним группу биоисследований
	if not has_alife_info("bio_group_spawen") and has_alife_info("prof_sos_talk_saved_done") and level_name ~= "lvl7_yantar" then
		olr_timers.st_timer("yan_biogroup_online", 18, "nick.yan_biogroup_online()")
		db.actor:give_info_portion("bio_group_spawen")
	end

	if not has_alife_info("bar_killer_strt") and has_alife_info("open_bar_door_start_krisa") and level_name ~= "lvl5_bar" then
		olr_timers.st_timer("bar_killer_strts", 28, "nick.bar_killer_strts()")
		db.actor:give_info_portion("bar_killer_strt")
	end

	if not has_alife_info("dolina_scient_strt") and has_alife_info("yan_1_kvest_start") and level_name == "lvl4_darkdolina" then
		olr_timers.st_timer("dolina_scient_strt", 18, "nick.scient_strt()")
		db.actor:give_info_portion("dolina_scient_strt")
	end

	-- поиск экспедиции на холмах
	if has_alife_info("greh_leader_key_info") and not has_alife_info("holmy_expedition_start") and level_name == "lvl7_yantar" then
		db.actor:give_info_portion("holmy_expedition_start")
		olr_timers.st_timer("holmy_expedition_start", 250, "nick.holmy_expedition_start_now()")
	end

	if not has_alife_info("fin_rush_from_sarco_to_warlab") then
		if has_alife_info("gen_bunker_destr_alls_cutscene") and level_name == "lvl15_sarcofag" then
			olr_timers.st_timer("last_gens", 1, "nick.back_to_gens()")
			level.add_pp_effector("black.ppe", 203131, false)
			--db.actor:give_info_portion("fin_rush_from_sarco_to_warlab")
		end
	end

	-- удаляем группу космос
	if not has_alife_info("space_group_quest_delete") then
		if has_alife_info("space_bar_zombied_camback_talked") and level_name ~= "lvl2_garbage" then
			db.actor:give_info_portion("space_group_quest_delete")
		end
	end

	if not has_alife_info("dolina_killers_acess") and has_alife_info("kvest_bar_1_dialog_start") and level_name == "lvl4_darkdolina" then
		olr_timers.st_timer("dolina_killers_acess", 12, "nick.dolina_killers_acessss()")
		db.actor:give_info_portion("dolina_killers_acess")
	end
	
	if has_alife_info("dolina_killers_acess") and has_alife_info("kvest_bar_1_dialog_start") and level_name == "lvl4_darkdolina" then
		xr_gulag.setGulagRelation("val_x18_exit_base", game_object.friend, db.actor)
	end

	-- квест на гравимолот
	if has_alife_info("bar_1_done") and not has_alife_info("kvest_gravimolot_start") and level_name == "lvl3_agroprom" then
		olr_timers.st_timer("kvest_gravimolot_acess", 12, "nick.kvest_gravimolot_acessss()")
		db.actor:give_info_portion("kvest_gravimolot_start")
	end

	-- удаляем группу магнит
	if not has_alife_info("magnet_group_quest_delete") then
		if has_alife_info("magnet_group_quest_done") and level_name ~= "lvl5_bar" then
			db.actor:give_info_portion("magnet_group_quest_delete")
			olr_timers.st_timer("unic_rostor_vss", 850, "nick.rostok_spawn_unic_vss()")
		end
	end
	
	-- удаляем группу проффесора
	if not has_alife_info("proffecor_group_quest_delete") then
		if has_alife_info("laborant_otpravlaet_spat_gg_final_done") and level_name ~= "lvl7_yantar" then
			db.actor:give_info_portion("proffecor_group_quest_delete")
		end
	end

	--квест на зачистку паразитов в городе (выдача задания)
	if not has_alife_info("deadcity_paras_talk_to_dleader_pre") then
		if has_alife_info("dec_first") and level_name ~= "lvl11_deadcity" then
			db.actor:give_info_portion("deadcity_paras_talk_to_dleader_pre")
			olr_timers.st_timer("deadcity_paras_talk_to_dleader", 25, "nick.pre_deadcity_paras_talk_to_dleader()")
		end
	end

	-- проснулись у саркофага
	if not has_alife_info("find_journalist_restore_sarcofag") then
		if has_alife_info("find_journalist_restore_wep_done_info") and level_name == "lvl15_sarcofag" then
			db.actor:give_info_portion("find_journalist_restore_sarcofag")
		end
	end

	if level_name == "lvl16_generators" then
		--nick.clear_all_bolezns()
		db.actor:set_character_community("stalker", 0, 0)
		local db_actor_id = db.actor:id()
		relation_registry.set_community_goodwill("stalker", db_actor_id, 50)
		relation_registry.set_community_goodwill("ecolog", db_actor_id, 50)
		relation_registry.set_community_goodwill("neutral", db_actor_id, 50)
		relation_registry.set_community_goodwill("dolg", db_actor_id, 50)
		relation_registry.set_community_goodwill("freedom", db_actor_id, 50)
	end

	local actor = db.actor
	if not has_alife_info("gar_first") and level_name == "lvl2_garbage" then
		actor:give_info_portion("gar_first")
		olr.del_by_name("lvl2_garbage_physic_fog_center")
		olr.spawn_crows(20, 90)
		olr.to_offline("lvl2_garbage_af_compas")
		olr.del_by_name("lvl1_escape_zone_mosquito_bald_weak_0009")
	end

	if not has_alife_info("agr_first") and level_name == "lvl3_agroprom" then
		actor:give_info_portion("agr_first")
		olr.del_by_name("lvl3_agroprom_physic_fog_center")
		if not has_alife_info("s_kalashomvse") then
			olr.del_by_name("lvl1_escape_stalker_0030")
			olr.del_by_name("lvl1_escape_physic_object_0193")
		end
		olr.spawn_crows(15, 50)
		olr_timers.st_timer("infa_voenstals", 1100, "nick.infa_voenstals()")
		olr_timers.st_timer("create_agro_case_del", 21, "nick.create_agro_case_del()")
	end

	if not has_alife_info("dol_first") and level_name == "lvl4_darkdolina" then
		actor:give_info_portion("dol_first")
		olr_timers.st_timer("goaway_from_dolina()", 100, "nick.goaway_from_dolina()")
		olr.del_by_name("lvl4_darkdolina_physic_fog_center")
		nick.rnd_vis_killers()
		news_manager.send_tip(db.actor, game.translate_string("on_netspawn_1"), 26, "trader", 25000, nil, nil, true, "escape_trader_name")
	end

	if not has_alife_info("bar_first") and level_name == "lvl5_bar" then
		actor:give_info_portion("bar_first")
		olr_timers.st_timer("omsbar_first", 4500, "nick.bar_first_del_bar_alcoholics()")
		nick.del_jabas_art_navodki()
		olr.del_by_name("lvl5_bar_physic_fog_sity")
		olr_timers.st_timer("bar_first_ivancov", 15, "nick.bar_first_ivancov()")
		olr.to_offline("lvl5_bar_physic_object_1454")
		olr.to_offline("lvl5_bar_physic_object_1455")
		olr.to_offline("lvl5_bar_inventory_box_dopseif")
		olr.to_offline("lvl5_bar_physic_object_1466")
		olr_doska_bar.gen_rnd_item_find()
		olr_timers.st_timer("gen_kill_stalker", 10, "olr_doska_bar.gen_kill_stalker()")
		olr.spawn_crows(20, 90)
	end

	if not has_alife_info("ros_first") and level_name == "lvl6_rostok" then
		actor:give_info_portion("ros_first")
		olr.to_offline("ros_box_rukzak")
		olr.spawn_crows(15, 40)
	end

	if not has_alife_info("yan_first") and level_name == "lvl7_yantar" then
		actor:give_info_portion("yan_first")
		olr.del_by_name("lvl7_yantar_physic_fog_center")
		olr.del_by_name("lvl5_bar_physic_object_1452")
		news_manager.send_tip(db.actor, "on_netspawn_2", 15, "trader", 49000, nil, nil, true, "escape_trader_name")
		olr_doska_yan.gen_rnd_item_find()
		olr_timers.st_timer("gen_kill_m", 10, "olr_doska_yan.gen_kill_stalker()")
		olr.to_offline("lvl7_yantar_physic_object_0598")
		olr.info("bar_first_del_bar_alcoholics_done") -- дубль на всякий случай
		olr.to_offline("lvl7_yantar_physic_object_0055")
		olr.to_offline("lvl7_yantar_m_car_0000")
		olr.del_by_name("lvl5_bar_physic_object_1094")
		olr.del_by_name("lvl5_bar_physic_object_1095")
		olr.del_by_name("lvl5_bar_physic_object_0654")
		olr.del_by_name("lvl5_bar_physic_object_1065")
		olr.del_by_name("lvl5_bar_physic_object_1066")
	end

	if not has_alife_info("swp_first") and level_name == "lvl8_swamp" then
		actor:give_info_portion("swp_first")
		olr.del_by_name("lvl8_swamp_physic_fog_center")
		olr.del_by_name("lvl4_darkdolina_physic_object_0362")
		olr.to_offline("lvl8_swamp_physic_object_0314")
		olr.to_offline("lvl8_swamp_physic_object_0315")
		olr.to_offline("lvl8_swamp_physic_object_0252")
		olr.del_by_name("lvl5_bar_stalker_0001")
	end

	if not has_alife_info("mil_first") and level_name == "lvl9_military" then
		actor:give_info_portion("mil_first")
		actor:give_info_portion("bar_baout_special_med_shit")
		olr.del_by_name("lvl9_military_physic_fog_center")
		olr.to_offline("lvl9_military_doki_dla_ch")
		olr.spawn_crows(20, 60)
		olr_timers.st_timer("gen_kill_stalker", 50, "olr_doska_escape.gen_kill_stalker()")
		olr.to_offline("mil_naparnik_niva_ph")
	end

	if not has_alife_info("rad_first") and level_name == "lvl10_radar" then
		actor:give_info_portion("rad_first")
		olr.del_by_name("lvl10_radar_physic_fog_center")
		olr.blow_add(500)
	end

	if not has_alife_info("radlab_first") and level_name == "lvl12_radar_bunker" then
		actor:give_info_portion("radlab_first")
		olr.to_offline("l10u_radar_bunker_physic_object_0008")
		olr.to_offline("l10u_radar_bunker_physic_object_0007")
		local wait_time = 0
		wait_time = time_global() + 8000
		level.add_call(
			function()
				return time_global() > wait_time
			end,
			function()
				olr.kill_mon_in_radius(db.actor:position(), 150)
			end
		)
		local wait_time = 0
		wait_time = time_global() + 5000
		level.add_call(
			function()
				return time_global() > wait_time
			end,
			function()
				nick.kill_bandits()
			end
		)
		olr_teleport.rad_bun_first_hello()
	end

	if not has_alife_info("dec_first") and level_name == "lvl11_deadcity" then
		actor:give_info_portion("dec_first")
		olr_timers.st_timer("deadcity_jaba_about", 12, "nick.deadcity_jaba_about()")
		olr.del_by_name("lvl11_deadcity_physic_fog_center")
		olr.del_by_name("lvl5_bar_physic_object_1116")
		olr.spawn_crows(20, 60)
		nick.spawn_random_rats_on_level()
		olr_timers.st_timer("deadcity_izlom_about", 33, "nick.deadcity_izlom_about()")
	end

	if not has_alife_info("prp_first") and level_name == "lvl13_prip" then
		actor:give_info_portion("prp_first")
		olr.del_by_name("lvl13_prip_physic_fog_center")
		olr.spawn_crows(20, 90)
	end

	if not has_alife_info("lvl12_first") and level_name == "lvl_level12" then
		actor:give_info_portion("lvl12_first")
		olr.del_by_name("lvl_level12_physic_fog_center")
		olr.spawn_on_obj("conserva", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("conserva", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("conserva", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("conserva", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("wpn_rpg7", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("wpn_svd", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("antirad", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("antirad", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("water", "lvl_level12_stalker_0002")
		olr.spawn_on_obj("battery_change", "lvl_level12_stalker_0002")
		olr.spawn_crows(20, 90)
	end

	if not has_alife_info("sarco_first") and level_name == "lvl15_sarcofag" then
		actor:give_info_portion("sarco_first")
		olr_timers.st_timer("sarcosms", 12, "nick.sarcosms()")
		olr.to_offline("lvl15_sarcofag_physic_object_0038")
		olr.to_offline("lvl15_sarcofag_physic_object_0042")
		olr.to_offline("lvl15_sarcofag_physic_object_0040")
		olr.to_offline("lvl15_sarcofag_physic_object_0039")
		olr.to_offline("lvl15_sarcofag_physic_object_0041")
		olr.del_by_name("lvl10_radar_physic_object_0141")
	end
	
	if not has_alife_info("stan_first") and level_name == "lvl14_stancia" then
		actor:give_info_portion("stan_first")
		olr.del_by_name("lvl14_stancia_physic_fog_center")
		olr.spawn_on_obj("chaes_deadscient_doc", "lvl14_stancia_stalker_0075")
		olr_timers.st_timer("blowout_additional_timer", 53, "olr_blowout.blowout_additional_timer()")
		olr.spawn_crows(20, 190)
	end

	if not has_alife_info("gen_first") and level_name == "lvl16_generators" then
		actor:give_info_portion("gen_first")
		olr.del_by_name("lvl16_generators_physic_fog_center")
		olr.info("military_radio_go_done")
		olr.info("military_radio_go")
		olr.to_offline("lvl16_generators_physic_object_0199")
		olr.to_offline("lvl16_generators_physic_object_0200")
		olr.to_offline("lvl16_generators_physic_object_0231")
		olr.to_offline("lvl16_generators_physic_object_0230")
		olr.to_offline("lvl16_generators_physic_object_0249")
		db.actor.radiation = 0
		sim:create("m_poltergeist_e", db.actor:position():add(db.actor:direction():mul(69)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		sim:create("m_poltergeist_e", db.actor:position():add(db.actor:direction():mul(69)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		sim:create("m_poltergeist_e", db.actor:position():add(db.actor:direction():mul(69)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		sim:create("m_poltergeist_e", db.actor:position():add(db.actor:direction():mul(69)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		local wait_time = 0
		wait_time = time_global() + 1500
		level.add_call(
			function()
				return time_global() > wait_time
			end,
			function()
				olr.kill_mon_in_radius(db.actor:position(), 30)
			end
		)
	end
end
