-- hi_flyer 19.04.17
-- капсула R1


local reg_ids = {}
local cap_reg_ids = {}
local oButtons = {}
local oButtonsCap = {}
local curent_open_id = -1
local curent_inv_box_id = -1



function use(obj)
end

class "ui_capsule" (CUIScriptWnd)
function ui_capsule:__init(owner) super()
 	self.owner = owner
	self:InitControls()
	self:InitCallBacks()
end

function ui_capsule:InitControls()
	self:Init(335,5,675,266)

	-- фон
	self.back = CUIStatic()
	self.back:Init(0,0,675,266)
	self.back:InitTexture("ui\\flyer\\ui_dg_inventory_arc")
	self.back:SetOriginalRect(0,0,675,768)
	self:AttachChild(self.back)
	
    -- Кнопка выхода
    self.exit_btn = CUI3tButton()
    self.exit_btn:Init(600, 5, 70, 25)
    self.exit_btn:SetText(game.translate_string("st_olr_capsule_exit"))
    self.exit_btn:SetFont(GetFontGraffiti22())
    self.exit_btn:SetTextColor(255,255,255,255)
    self:Register(self.exit_btn, "exit_button")
    self.back:AttachChild(self.exit_btn)	
		
	self.inventory = CUIStatic()
	self.inventory:Init(5,5,200,10)
	self.inventory:SetText(game.translate_string("st_olr_capsule_rucksack"))
	self.inventory:SetFont(GetFontGraffiti22())
	self.inventory:SetTextAlign(CGameFont.alCenter)
	self.inventory:SetTextColor(255,255,255,255)
	self.back:AttachChild(self.inventory)


	self.capsule = CUIStatic()
	self.capsule:Init(5,5,500,150)
	self.capsule:SetText(game.translate_string("st_olr_capsule_capsule"))
	self.capsule:SetFont(GetFontGraffiti22())
	self.capsule:SetTextAlign(CGameFont.alCenter)
	self.capsule:SetTextColor(255,255,255,255)
	self.back:AttachChild(self.capsule)

	self:try_add_inv_arts()
	self:try_add_cap_arts()
end

function ui_capsule:InitCallBacks()
    self:AddCallback("exit_button", ui_events.BUTTON_CLICKED, self.OnButton_exit_button, self)
end

function ui_capsule:try_add_inv_arts()
	local wait_time = 0
  	wait_time = time_global() + 1000
  	level.add_call(
    		function() return time_global() > wait_time end,
    		function() self:add_inv_arts() end
  	)
end

function ui_capsule:try_add_cap_arts()
	local wait_time = 0
  	wait_time = time_global() + 1000
  	level.add_call(
    		function() return time_global() > wait_time end,
    		function() self:add_cap_arts() end
  	)
end


function ui_capsule:add_cap_arts()
	local wth = 28
	local st_id = 0
	local addItm = 35
	local box = level.object_by_id(curent_open_id)

	if box then
		for i = 0, box:inv_box_count() - 1 do
			local obj = box:object_from_inv_box(i)
			if obj and isArtefact(obj) then
				--log1("box - "..box:name().." has item - "..obj:name().."")
		
				local fName = ""..obj:get_name()..""
		
				local reg_id = ""
				if type(obj) == "number" then
					reg_id = ("af_%d"):format(obj)
				elseif type(obj) == "string" then
					reg_id = ("af_%s"):format(obj)
				else
					reg_id = ("af_%d"):format(obj:id())
				end

				self[reg_id] = CUIButton()
				self[reg_id]:SetAutoDelete(true)
				self[reg_id]:Init(175,wth,133,25)
				self[reg_id]:InitTexture("ui\\flyer\\ui_verst_list2")
				self[reg_id]:SetOriginalRect(46,296,133,25)
				self[reg_id]:SetStretchTexture(true)
				self[reg_id]:SetText(string.format(fName))
				self[reg_id]:SetFont(GetFontGraffiti22())
				self[reg_id]:SetTextColor(255,255,255,255)
				self:Register(self[reg_id], reg_id)
				self:AttachChild(self[reg_id])

				local button = CButtonDataCap(self, obj, self[reg_id])
				self:AddCallback(reg_id,ui_events.BUTTON_CLICKED,button.OnPressCap,button)
				self:AddCallback(reg_id,ui_events.WINDOW_LBUTTON_DB_CLICK,button.OnDoublePressCap,button)

				cap_reg_ids[#cap_reg_ids+1] = reg_id
				printf("%s", reg_id)
				st_id = st_id + 1
				wth = wth + 25
			end
		end
	end
end


function ui_capsule:add_inv_arts()
	local wth = 28
	local st_id = 0
	local addItm = 35

	-- перебор и заполнение инвентори
	local calc = function(npc, obj)
		if obj ~= nil and isArtefact(obj) and db.actor:is_in_ruck(obj) then
			local obj_sec = obj:section()
			if obj_sec == "af_galantine" or obj_sec == "af_junk_bolt" or obj_sec == "af_junk_debris" or obj_sec == "af_knot" or obj_sec == "af_cotton" then
				--local cond = obj:condition() * 100 
				--local condname = ""..string.format("%1.0f", cond).."%"

				local fName = ""..obj:get_name()..""

				local reg_id = ""
				if type(obj) == "number" then
					reg_id = ("af_%d"):format(obj)
				elseif type(obj) == "string" then
					reg_id = ("af_%s"):format(obj)
				else
					reg_id = ("af_%d"):format(obj:id())
				end

				self[reg_id] = CUIButton()
				self[reg_id]:SetAutoDelete(true)
				self[reg_id]:Init(32,wth,133,25)
				self[reg_id]:InitTexture("ui\\flyer\\ui_verst_list2")
				self[reg_id]:SetOriginalRect(46,296,133,25)
				self[reg_id]:SetStretchTexture(true)
				self[reg_id]:SetText(string.format(fName))
				self[reg_id]:SetFont(GetFontGraffiti22())
				self[reg_id]:SetTextColor(255,255,255,255)
				self:Register(self[reg_id], reg_id)
				self:AttachChild(self[reg_id])

				local button = CButtonData(self, obj, self[reg_id])
				self:AddCallback(reg_id,ui_events.BUTTON_CLICKED,button.OnPress,button)
				self:AddCallback(reg_id,ui_events.WINDOW_LBUTTON_DB_CLICK,button.OnDoublePress,button)

				reg_ids[#reg_ids+1] = reg_id

				st_id = st_id + 1
				wth = wth + 25
			end
		end
	end
	db.actor:iterate_inventory(calc, db.actor)   
end

function ui_capsule:Hide()
	self:GetHolder():start_stop_menu(self, true)
end

function ui_capsule:OnButton_exit_button()
	local inv_window = level.main_input_receiver()
	if inv_window and inv_window:IsShown() then
		level.start_stop_menu(inv_window,true)
	end
	hide_curent_capsule()
end

function ui_capsule:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	local bind = dik_to_bind(dik)
	
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then
			hide_curent_capsule()
		end
	end
end

function ui_capsule:hide_btn(section, button)
	button.button:Show(false)
end


-- в инвентарь
-----------------------------------
class "CButtonDataCap"
-----------------------------------
-- Construct
function CButtonDataCap:__init(wind, obj, button)
	self.obj = obj
	self.wind = wind
	self.button = button
	oButtons[#oButtons+1] = self
end

-- Destruct
function CButtonDataCap:__finalize()
end

function CButtonDataCap:hide_art(section, button)
	button:Show(false)
end

function CButtonDataCap:OnPressCap()
	--log1(" OnPresssss  "..self.obj:name().."")
	local section = self.obj:section()
	local x, y = GetInvPos(section)
	self.back = CUIStatic()
	self.wind:AttachChild(self.back)
	self.back:Init(145,395,50,50)
	self.back:InitTexture("ui\\icons\\icons_equipment")
	self.back:SetOriginalRect(x, y, 50, 50)
	self.back:SetStretchTexture(true)
	local wait_time = 0
  	wait_time = time_global() + 1000
  	level.add_call(
    		function() return time_global() > wait_time end,
    		function() self:hide_art(self.obj, self.back) end
  	)	
end

function CButtonDataCap:OnDoublePressCap()
	if self.obj then
		local box = level.object_by_id(curent_open_id)  -- мировой ящик
		if box then
			box:transfer_item(self.obj, db.actor)
			self.wind:hide_btn(self.obj, self)
			--self.wind:try_add_inv_arts()  -- вроде пашет
			local box_inv = level.object_by_id(curent_inv_box_id) -- инв. ящик
			if box_inv then
				local val_weight = box_inv:weight() - self.obj:weight()
				box_inv:set_weight(val_weight)
				xvars.inv_capsules[box_inv:name()] = val_weight
				on_move_art()
			end
		end
	end
end


-- в капсулу 
-----------------------------------
class "CButtonData"
-----------------------------------
-- Construct
function CButtonData:__init(wind, obj, button)
	self.obj = obj
	self.wind = wind
	self.button = button
	oButtonsCap[#oButtonsCap+1] = self
end

-- Destruct
function CButtonData:__finalize()
end

function CButtonData:hide_art(section, button)
	button:Show(false)
end

function CButtonData:OnPress()
	--log1(" OnPresssss  "..self.obj:name().."")
	local section = self.obj:section()
	local x, y = GetInvPos(section)
	self.back = CUIStatic()
	self.wind:AttachChild(self.back)
	self.back:Init(145,395,50,50)
	self.back:InitTexture("ui\\icons\\icons_equipment")
	self.back:SetOriginalRect(x, y, 50, 50)
	self.back:SetStretchTexture(true)
	local wait_time = 0
  	wait_time = time_global() + 1000
  	level.add_call(
    		function() return time_global() > wait_time end,
    		function() self:hide_art(self.obj, self.back) end
  	)	
end

function CButtonData:OnDoublePress()
	if self.obj then
		local box = level.object_by_id(curent_open_id)  -- мировой ящик
		if box then
			local art_cnt = box:inv_box_count()
			if art_cnt >= 3 then
				news_manager.send_tip(db.actor, game.translate_string("CButtonDataOnDoublePress_0"), nil, "artifact", 5000)
				return
			end
			db.actor:transfer_item(self.obj, box)
			self.wind:hide_btn(self.obj, self)
			local box_inv = level.object_by_id(curent_inv_box_id) -- инв. ящик
			if box_inv then
				local val_weight = box_inv:weight() + self.obj:weight()
				box_inv:set_weight(val_weight)
				xvars.inv_capsules[box_inv:name()] = val_weight
				on_move_art()
			end
		end
	end
end

-------------------------------

function hide_curent_capsule()
	if curent_open_id ~= -1 then
		alife():teleport_object(curent_open_id, db.actor:game_vertex_id(), db.actor:level_vertex_id(), db.actor:position():add(db.actor:direction():mul(2500)))
		curent_open_id = -1
		curent_inv_box_id = -1
		bind_stalker.restore_weapon()
	end
end


function snd_open_capsule()
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\open_capsule]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end


function on_move_art()
	local snd_obj = xr_sound.get_safe_sound_object([[sounds\device\detectors\geiger_6]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	local inv_window = level.main_input_receiver()
	if inv_window and inv_window:IsShown() then
		level.start_stop_menu(inv_window,true)
	end
	hide_curent_capsule()
end

function GetInvPos(section)
	local x = ini_sys:r_s32(section, "inv_grid_x")*50
	local y = ini_sys:r_s32(section, "inv_grid_y")*50
	return x, y
end