--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
-- name: olr_soundtrack.script
-- desc: Задаёт тему главного меню
-- author: theysani
-- date: 07.01.26
-- last edit: 07.01.26
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

-- трек 1 - в начале игры (при запуске игры, после смерти)
-- трек 2 - после того, как дождались бармена в баре по тому таймеру
-- трек 3 - с момента получения задания идти на янтарь
-- трек 4 - с момента получения задания идти на радар вырубать установку
-- трек 5 - с момента, когда для нас все врагами стали и идет пиздиловка

function menu_music_set_theme_one()
	xvars.current_music_theme = "music\\menu_01"
end

function menu_music_set_theme_two()
	xvars.current_music_theme = "music\\menu_02"
end

function menu_music_set_theme_three()
	xvars.current_music_theme = "music\\menu_03"
end

function menu_music_set_theme_four()
	xvars.current_music_theme = "music\\menu_04"
end

function menu_music_set_theme_five()
	xvars.current_music_theme = "music\\menu_05"
end