--Oblivion Lost Remake (2014-2015)
--(c) proger_Dencheek - базовая логика с игнором, скриптовое окно со своим интерфейсом
--Общение через КПК
-- Hrust: скрипт переписан и используется только для проверок доступности диалогов через движковое окно, скриптовое окно убрано (29.10.2025)

local ignore_ini = ini_file("pda_dialogs\\ignore_npc.ltx") --НПЦ, которые не участвуют в диалогах

local zombies_names = {
["lvl4u_darklab_stalker_0023"] = true,
["lvl4u_darklab_stalker_0026"] = true
}

--Коллбек на нажатие по элементу в списке контактов
function on_press(actor, npc)
	--news_manager.send_tip(db.actor, "on_press_check")

	if zombies_names[npc:name()] or npc:character_community() == "zombied" then
		news_manager.send_tip(db.actor, game.translate_string("on_press_1"), nil, "zombied", 5000)
		return false
	end


	if npc:name() == "lvl4_darkdolina_staler_undead_olr_0001" then
		news_manager.send_tip(db.actor, game.translate_string("on_press_2"), nil, "default", 5000)
		return false
	end

	if db.actor:has_info("olr_blowout_phase_2") then
		news_manager.send_tip(db.actor, game.translate_string("on_press_3"))
		return false
	end

	if npc:name() == "bar_barman" and has_alife_info("olr_traders_night") then
		news_manager.send_tip(db.actor, game.translate_string("on_press_4"), nil, "barman", 5000)
		return false
	end
	
	if (npc:name() == "escape_trader_0000" or npc:name() == "lvl9_military_m_trader") and has_alife_info("olr_traders_night") then
		news_manager.send_tip(db.actor, game.translate_string("on_press_4"), nil, "jaba", 5000)
		return false
	end	

	if level.name() == "lvl16_generators" then
		news_manager.send_tip(db.actor, game.translate_string("on_press_5"))
		return false
	end
	
	for i=0, ignore_ini:line_count("main") - 1 do
		local _, val = ignore_ini:r_line("main", i, "", "")
		if npc:profile_name() == val then
			news_manager.send_tip(db.actor, game.translate_string("on_press_6"))
			return false
		end
	end
	--news_manager.send_tip(db.actor, "on_press_passed")
	return true
end

--Условия для диалогов
function is_pda_dialog()
return level.is_shown_pda()
end

function is_not_pda_dialog()
	return not level.is_shown_pda()
end
