-- hi_flyer 25.03.16

local geiger_simple_snd = xr_sound.get_safe_sound_object([[device\detectors\da-2_noise1_loop]])
local geiger_advances_snd = xr_sound.get_safe_sound_object([[device\detectors\uda-14a_noise_loop]])
local geiger_elite_snd = xr_sound.get_safe_sound_object([[device\detectors\geiger_noise_loop]])

function klick_item_inv(obj)

    if not obj then
        return
    end


    local has_geiger = db.actor:object("detector_simple") or db.actor:object("detector_advances") or db.actor:object("detector_elite")
    if has_geiger then
        local cnd = has_geiger:condition()
        if cnd > 0.01 then
            local id_str = tostring(obj:id())
            local e_food = xvars.foods[id_str]
            local e_wpn = xvars.weapons[id_str]
            if (e_food and e_food.sec == obj:section() and e_food.rad) or (e_wpn and e_wpn.sec == obj:section() and e_wpn.rad) or (ini_sys:line_exist(obj:section(), "radiation_restore_speed") and ini_sys:r_float(obj:section(), "radiation_restore_speed") > 0) then
                if not geiger_elite_snd:playing() then
                    geiger_elite_snd:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
					--local icon_x, icon_y, icon_width, icon_height = ui_spawn_menu.GetIconRect(obj:section())
					if not obj:is_radioactive_flag() then
						obj:set_rad_mark("ui_icons_equipment_radiation_big")
						obj:set_radioactive_flag(true)
					end
					--if icon_width <= 2 and icon_height == 1 then
					--else
					--end
                end
                if not has_alife_info("radiation_inv_act_cliked") then
                    olr.info("radiation_inv_act_cliked")
                    news_manager.send_tip(db.actor, game.translate_string("st_olr_items_inv_click_radioactive_thing_1").." "..obj:get_name().." "..game.translate_string("st_olr_items_inv_click_radioactive_thing_2"), nil, "hero", 59000)
                end
            end
        end
    end


    if obj:section() == "glaz_fila" and not has_alife_info("glaz_fila_checked") then
        db.actor:give_info_portion("glaz_fila_checked")
    end

    if obj:section() == "af_lamp" then
        db.actor.psy_health = -0.34
        local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\psy_noise]])
        if not snd_obj:playing() then
            snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
        end
    end


    if obj:section() == "af_bublik_glass" and not has_alife_info("encyclopedy_zone_artifact_af-bublik-glass") then
        af_unic()
    end
    if obj:section() == "af_magnet" and not has_alife_info("encyclopedy_zone_artifact_af-magnet") then
        af_unic()
    end
    if obj:section() == "af_gravi_weak" and not has_alife_info("encyclopedy_zone_artifact_af-gravi-weak") then
        af_grav()
    end
    if obj:section() == "af_gravi_heavy" and not has_alife_info("encyclopedy_zone_artifact_af-gravi-heavy") then
        af_grav()
    end
    if obj:section() == "af_zuda" and not has_alife_info("encyclopedy_zone_artifact_af-zuda") then
        af_unic()
    end
    if obj:section() == "af_transpsphere" and not has_alife_info("encyclopedy_zone_artifact_af-transpsphere") then
		--af_heat()
    end
    if obj:section() == "af_rusty_hair" and not has_alife_info("encyclopedy_zone_artifact_af-rusty-hair") then
        af_unic()
    end
    if obj:section() == "af_black_drops" and not has_alife_info("encyclopedy_zone_artifact_af-black-drops") then
        af_unic()
    end
    if obj:section() == "af_cotton" and not has_alife_info("encyclopedy_zone_artifact_af-cotton") then
        af_elec()
    end


end
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

function af_grav()
    local snd_obj = xr_sound.get_safe_sound_object([[anomaly\mosquito_bald_idle]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end


function af_elec()
    local snd_obj = xr_sound.get_safe_sound_object([[anomaly\electra_hit]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

function af_heat()
	--	local snd_obj = xr_sound.get_safe_sound_object([[anomaly\polter_fire_idle]])
	--	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

function af_unic()
    local snd_obj = xr_sound.get_safe_sound_object([[anomaly\monolith_idle]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end
