function init()
	core.ac("actor_update",update)
end

local att 				
local ptatt	

local repaintnow = false

function get_vater(num)
	if num >= 0 and num <= 0.1 then
		return game.translate_string("st_very_strong")
	elseif num > 0.1 and num <= 0.3 then
		return game.translate_string("st_strong")
	elseif num > 0.3 and num <= 0.4 then
		return game.translate_string("st_middle")
	elseif num > 0.4 then
		return game.translate_string("st_none")
	end
end

function get_sleep(num)
	if num >= 0 and num <= 0.2 then
		return game.translate_string("st_ui_sleep_very_strong")
	elseif num > 0.2 and num <= 0.3 then
		return game.translate_string("st_ui_sleep_strong")
	elseif num > 0.3 and num <= 0.4 then
		return game.translate_string("st_ui_sleep_moderate")		
	elseif num > 0.4 and num <= 0.5 then
		return game.translate_string("st_ui_sleep_slight")
	elseif num > 0.5 then
		return game.translate_string("st_ui_sleep_none")
	end
end

vol_obem = 0

function repaint()
	repaintnow = true
	local wait_time = 0
  	wait_time = time_global() + 5
  	level.add_call(
    	function() return time_global() > wait_time end,
    	function() repaintnow = false end
  	)
end

-- db.actor:has_info("ui_inventory")
function update(delta)
		if ui.get_inventory_wnd():IsShown() and repaintnow == false then
			vol_obem = olr_ruck_limit.cur_amount
			vol_obem_max = olr_ruck_limit.max_item_amount
			if ui.get_inventory_wnd() and not att then
				ptatt = ui.get_inventory_wnd()
				att = olr_ui_inv_acinfo.ui_trade()
				ptatt:AttachChild(att)
				att:SetAutoDelete(true)
				att:Show(true)
				--ui.reinit_shown_ui()
			end	
		else
			if att and ptatt then
				att:Show(false)
				ptatt:DetachChild(att)
				att = nil
				ptatt = nil
			end
		end
end

class "ui_trade" (CUIScriptWnd)

function ui_trade:__init(owner) super()
	self.owner = owner
	self.comm = game.translate_string(db.actor:character_community())
	self.rank = game.translate_string(level.get_rank_as_text(db.actor:character_rank()))
	self.repa = game.translate_string(level.get_reputation_as_text(db.actor:character_reputation()))
	--self.vater = get_vater(db.actor:get_actor_thirst())
	self.sleep = get_sleep(db.actor.sleep)
	self.blows = xvars.blow_count
	self.inv_vol = vol_obem
	self.inv_vol_max = vol_obem_max
	self:InitControls()
end

function ui_trade:__finalize() end

function ui_trade:InitControls()
	local sformat = string.format
	self:Init(0,0,1024,768)

	local xml = CScriptXmlInit()
	if xml:is_16_9_mode() then
		xml:ParseFile("flyer\\inv_acinfo_16.xml")
	else
		xml:ParseFile("flyer\\inv_acinfo.xml")
	end
    self.main = xml:InitScrollView("main", self)
    self.actor_name = xml:InitStatic("name_wnd", self)

	self.actor_name:SetTextST(xr_effects.get_real_actor_name())

	self.yess = xml:InitStatic("rank_wnd", self.main)
	self.yess:SetTextST(sformat("%s %s", game.translate_string("ui_st_pda_talk_rank"), ""..db.actor:character_rank().." : "..self.rank..""))

	self.no = xml:InitStatic("community_wnd", self.main)
	self.no:SetTextST(sformat("%s %s", game.translate_string("ui_st_pda_talk_community"), self.comm))

	self.rep = xml:InitStatic("reputation_wnd", self.main)
	self.rep:SetTextST(sformat("%s: %s", game.translate_string("pda_btn_reputation"), ""..db.actor:character_reputation().." ("..self.repa..")"))

	self.vo = xml:InitStatic("volume_wnd", self.main)

	--self.vt = xml:InitStatic("water_wnd", self.main)
	--self.vt:SetTextST(string.format("%s: %s", game.translate_string("ui_inv_water_script"), self.vater))

	self.so = xml:InitStatic("sleep_wnd", self.main)
	self.so:SetTextST(sformat("%s: %s", game.translate_string("ui_inv_sleeping"),  self.sleep))

	-- 
	self.bw = xml:InitStatic("blowouts_wnd", self.main)
	self.bw:SetTextST(sformat("%s: %s", game.translate_string("ui_inv_survived_blowouts"),  self.blows))

	if self.inv_vol < 0 then
		self.inv_vol=0
	end
	
	local vol_cur
	local vol_cur_max
	
	if level.get_game_difficulty() < 2 then
		vol_cur = "--"
		vol_cur_max = "--"
	else
		vol_cur = sformat("%1.1f", self.inv_vol)
		vol_cur_max = sformat("%1.0f", self.inv_vol_max)
	end
	
	self.vo:SetTextST(sformat("%s: %s / "..vol_cur_max.."", game.translate_string("ui_inv_volume_script"),  vol_cur))
end


function ui_trade:ActorInformation()
end
