-- hi_flyer 07/05/15

function use(obj)
	local mrandom = math.random
	local sim = alife()

	local section = obj:section()
	
	--log1("olr_items_use - section = "..section.."")

	-- Мед инжектор и всё с ним связанное
	if section == "med_injector" then
		--level.start_stop_menu(olr_items_use.injector_info(),true) -- неиспользуемое на данный момент гуи длЯ инжектора
		sim:create("med_injector_empty", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	end
	if section == "med_injector_capsule" then
		if db.actor:object("med_injector_empty") == nil then
			news_manager.send_tip(db.actor, game.translate_string("use_2")) -- Переписать
			return
		end
		olr.del(db.actor:object("med_injector_empty"))
		olr.del(obj)
		sim:create("med_injector", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		return
	end
	if section == "med_injector_empty" then
		if db.actor:object("med_injector_capsule") == nil then
			news_manager.send_tip(db.actor, game.translate_string("use_2"))
			return
		end
		olr.del(db.actor:object("med_injector_capsule"))
		olr.del(obj)
		sim:create("med_injector", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		return
	end	
	
	-- Батарейки
	if section == "battery_change_headlamp" then
		local has_torch = db.actor:item_in_slot(9)
		if has_torch == nil then
			sim:create("battery_change_headlamp", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			news_manager.send_tip(db.actor, game.translate_string("torch_check_0"), nil, "info", 3000)
		else
			if has_torch:condition() < 1 then
				db.actor:item_in_slot(9):get_torch():enable(false)
				has_torch:set_condition(1)
				local message = game.translate_string("st_olr_item_efs_charge").." ["..has_torch:get_name().."] - 100%"
				news_manager.send_tip(db.actor, message, nil, "info", 3000)				
			else
				sim:create("battery_change_headlamp", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
				local message = game.translate_string("st_olr_item_efs_charge").." ["..has_torch:get_name().."] - 100%"
				news_manager.send_tip(db.actor, message, nil, "info", 3000)
			end
		end
		return
	end
	
	if section == "battery_change" then
		local pdaitm = db.actor:object("device_pda")
		if pdaitm:condition() == 1 then
			sim:create("battery_change", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			local message = game.translate_string("st_olr_item_efs_charge").." ["..pdaitm:get_name().."] - 100%"
			news_manager.send_tip(db.actor, message, nil, "info", 3000)
		else
			local message = game.translate_string("st_olr_item_efs_charge").." ["..pdaitm:get_name().."] - 100%"
			news_manager.send_tip(db.actor, message, nil, "info", 3000)
			nick.enable_senf()
			olr.show_minimap(true)
		end
		return
	end	

	-- Рюкзак тайник
	if section == "custom_treasure_rukzak" then
		local obj = sim:create("box_rukzak_treasure", db.actor:position():add(db.actor:direction():mul(0.2)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		clear_useful_for_ai(obj)
		return
	end

	-- Бутыль для воды с агропрома
	if section == "empty_butilka_arg_zam" then
		if not xr_conditions.actor_in_zone(nil,nil,{"lvl3_agroprom_space_restrictor_0019"})	 then
			news_manager.send_tip(db.actor, game.translate_string("use_3"))
			sim:create("empty_butilka_arg_zam", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			return
		end
		olr.give_item("arg_jaba_voda_boloto")
		news_manager.send_tip(db.actor, game.translate_string("use_4"), nil, "info")
		return
	end

	-- Бутыль для холодца
	if section == "empty_butilka" then
		for i=1,65534 do
			local anom = level.object_by_id(i)
			if anom then
				local anom_sec = anom:section()
				if anom_sec == "zone_witches_galantine" or anom_sec == "zone_witches_galantine_weak" or anom_sec == "zone_witches_galantine_strong" or anom_sec == "zone_witches_galantine_average" then
					if anom:position():distance_to(db.actor:position()) < anom:get_shape_radius() + 1 then
						olr.give_item("af_galantine_pot")
						local rnd = mrandom(1,5)
						if rnd == 1 then
							anom:disable_anomaly()
						end
						break
					end
				end
			elseif i == 65534 then
				news_manager.send_tip(db.actor, game.translate_string("use_5"))
				sim:create("empty_butilka", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			end
		end
		return
	end
	
	-- theysani
	-- Переносим всё из худовых функций в обычные юзы

	if section == "water" then
		local bobj2 = sim:create("ph_food_vater_drop", db.actor:position():add(db.actor:direction():add(0.1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		level.client_spawn_manager():add(bobj2.id, 0,
			function(id,obj)
				if obj then
					local h = hit()
					h.draftsman = obj
					h.type = hit.strike
					h.direction = vector():set(mrandom(1),0.1,mrandom(1))
					h.power = 1
					h.impulse = 2
					obj:hit(h)
				end
			end)
		--log1("eat voda")
	end

	if section == "antirad" then
		db.actor:give_info_portion("actor_healing_antirad")
		olr_timers.st_timer("eat_radiation_tmr_timer", 20, "olr_items_use.eat_radiation_tmr_timer()")
	end

	if section == "vodka" then
		if has_alife_info("actor_healing_antirad") or has_alife_info("eat_medkit_tmr") then
			db.actor:change_actor_sleep(-1)
		end
		db.actor:give_info_portion("actor_healing_antirad")
		olr_timers.st_timer("eat_radiation_tmr_timer", 10, "olr_items_use.eat_radiation_tmr_timer()")
		db.actor.psy_health = db.actor.psy_health + 0.3
		local bobj2 = sim:create("vodka_used_empty_drop", db.actor:position():add(db.actor:direction():add(0.1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		level.client_spawn_manager():add(bobj2.id, 0,
			function(id,obj)
				if obj then
					local h = hit()
					h.draftsman = obj
					h.type = hit.strike
					h.direction = vector():set(mrandom(1),0.1,mrandom(1))
					h.power = 1
					h.impulse = 2
					obj:hit(h)
				end
			end)
		--log1("eat vodka")
		xvars.drinked_vodkas = xvars.drinked_vodkas + 1
		if xvars.drinked_vodkas > 2 then
			if db.actor.health > 0.31 then
				db.actor.health = - 0.3
			end
			olr.hud_tip("", game.translate_string("st_olr_item_efs_too_much_drink"), 7)
			db.actor:change_actor_sleep(-0.6)
			--news_manager.send_tip(db.actor, game.translate_string("use_hud_item_4"), nil, "default", 6000)
		end
		if xr_conditions.actor_in_zone(nil,nil,{"lvl12_radar_bunker_space_restrictor_fake_lab_waro"}) then
			if has_alife_info("radbun_mosk_start") then
				olr_teleport.rad_back_bun_nacalo()
			end
		end
	end

	if section == "medkit" then
		db.actor:give_info_portion("eat_medkit_tmr")
		db.actor:give_info_portion("actor_healing_medkit")
		olr_timers.st_timer("eat_medkit_tmr_timer", 20, "olr_items_use.eat_medkit_tmr_timer()")
		--log1("eat medkit")
		local par_var = mrandom(1,3)
		if par_var == 1 then
			sim:create("energy_drink", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		end
	end
	
	if section == "conserva" then
		local bobj2 = sim:create("ph_food_conserv1_drop", db.actor:position():add(db.actor:direction():add(0.1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		level.client_spawn_manager():add(bobj2.id, 0,
			function(id,obj)
				if obj then
					local h = hit()
					h.draftsman = obj
					h.type = hit.strike
					h.direction = vector():set(mrandom(1),0.1,mrandom(1))
					h.power = 1
					h.impulse = 2
					obj:hit(h)
				end
			end)
		--log1(" lost - "..s_cond.." --- add satiety - "..curr_sat.."")
	end

	local cond = obj:condition()
	
	if g_food_table[section] then
		local e_food = xvars.foods[tostring(obj:id())]
		if e_food and e_food.sec == section and e_food.rad then
			db.actor.radiation = 0.1525 -- Поедание заражённой радиацией еды черевато
		end		
		xvars.foods[tostring(obj:id())] = nil -- Очищаем вообще в любом случае
	end

	if section == "snotvornoe" then
		db.actor.alcohol = 1
		db.actor:change_actor_sleep(-1)
	end

	if section == "psy_stabilizator" then
		db.actor.alcohol = -1
		db.actor.psy_health = 1
		if xr_conditions.actor_in_zone(nil,nil,{"lvl12_radar_bunker_space_restrictor_fake_lab_waro"}) then
			if has_alife_info("radbun_mosk_start") then
				olr_teleport.rad_back_bun_nacalo()
				nick.radbun_restore_stuffmosk()
			end
		end
	end

	if section == "anti_beshenstvo_dog_caps" then
		--db.actor:give_info_portion("bolezn_beshenstvo_info_lech")
		db.actor.alcohol = db.actor.alcohol + 0.3
	end

	if section == "antirad_medpribor" then
		db.actor:give_info_portion("anti_glob_rad")
		olr_timers.st_timer("anti_glob_rad_timer", 250, "olr_items_use.anti_glob_rad_timer()")
		olr_timers.st_timer("anti_glob_rad_timer", 265, "olr_items_use.anti_glob_rad_timer()")
	end
end

-- TODO: разбить хрень выше на свои мелкие функции(подобно on_use_sigaret), если есть копипаст,
-- то использовать у предметов одну и ту же функцию, но проверять по секции для
-- отличающегося функционала
function on_use_sigaret(itm, eater) -- eater всегда актор(entity alive), у других сущностей эта функция не вызывается
	db.actor.psy_health = db.actor.psy_health + 0.1
	db.actor.alcohol = db.actor.alcohol + 0.01
	db.actor.power = 0.05
	local head_pos = eater:bone_position("bip01_head")
	local smoke_particle = particles_object("weapons\\generic_sigarets")

	smoke_particle:set_direction(eater:direction())
	smoke_particle:play_at_pos(vector():set(head_pos.x, head_pos.y, head_pos.z))
	-- можно повесить на таймеры, чтобы дым отыгрывался после звука(сейчас одновременно), также вызывать постпроцесс
	return true
end

function on_use_raw_meat(itm, eater)
	local section = itm:section()
	--if section == "mutant_zombie_hand" or section == "mutant_boar_leg" or section == "mutant_flesh_eye"
	--   or section == "mutant_burer_hand"
	--   or section == "mutant_krovosos_jaw"
	--   or section == "mutant_dog_tail"
	--   or section == "mutant_psevdodog_tail" then
		--if section == "mutant_zombie_hand" then
			for k,v in pairs(db.storage) do
				local stalker = level.object_by_id(k)
				if stalker and (get_clsid(stalker)==clsid.script_stalker) and stalker:alive() then
					if stalker:position():distance_to(db.actor:position()) < 20 and stalker:see(db.actor) and not olr_protected.is_no_offline_alife_obj(stalker:name()) then
						local seer_name = news_main.get_npc_name(stalker)
						news_manager.send_tip(db.actor, game.translate_string("st_olr_items_efs_saw_disgusting_meat"), 15, "unknown", 39000, nil, nil, true, seer_name)
						db.actor:change_character_reputation(-10)
						break
					end
				end
			end
		--end
	--end
	return true
end

function eat_radiation_tmr_timer()
	db.actor:disable_info_portion("actor_healing_antirad")
end

function eat_medkit_tmr_timer()
	db.actor:disable_info_portion("eat_medkit_tmr")
	db.actor:disable_info_portion("actor_healing_medkit")
end

function anti_glob_rad_timer()
	db.actor:disable_info_portion("anti_glob_rad")
	db.actor.health = -0.1
end


class "injector_info" (CUIScriptWnd)

function injector_info:__init() super()
	self:InitControls()
	self:InitCallBacks()
end

function injector_info:InitControls()
	local sformat = string.format
	local xml = CScriptXmlInit()
	self:Init(0,0,1024,768)
	xml:ParseFile("injector_info.xml")
	self.frame3 = xml:InitFrame("frame3", self)
	self:Register(xml:Init3tButton("frame3:button2", self.frame3), "button2")
	self.Static5 = xml:InitStatic("frame3:Static5", self.frame3)
	self.frame4 = xml:InitFrame("frame3:frame4", self.frame3)
	self.Static7 = xml:InitStatic("frame3:frame4:Static7", self.frame4)
	self.Static8 = xml:InitStatic("frame3:frame4:Static8", self.frame4)
	self.Static9 = xml:InitStatic("frame3:frame4:Static9", self.frame4)
	self.Static10 = xml:InitStatic("frame3:frame4:Static10", self.frame4)
	self.Static11 = xml:InitStatic("frame3:frame4:Static11", self.frame4)
	self.Static15 = xml:InitStatic("frame3:frame4:Static15", self.frame4)
	self.Static17 = xml:InitStatic("frame3:frame4:Static17", self.frame4)

	self.temperatura = xvars.temperatura_actor
	self.paras = get_paras()
	self.beshenstv = get_besh()
	self.ratbezum = get_ratbezum()
	self.sibyazva = get_sibyazva()
	self.zombied = get_zombied()

	self.Static11:SetTextST(sformat(game.translate_string("st_olr_item_efs_status_temp"), self.temperatura))
	self.Static7:SetTextST(sformat(game.translate_string("st_olr_item_efs_status_parasite"), self.paras))
	self.Static9:SetTextST(sformat(game.translate_string("st_olr_item_efs_status_rabies"), self.beshenstv))
	self.Static10:SetTextST(sformat(game.translate_string("st_olr_item_efs_status_rat_rabies"), self.ratbezum))
	self.Static15:SetTextST(sformat(game.translate_string("st_olr_item_efs_status_anthrax"), self.sibyazva))
	self.Static17:SetTextST(sformat(game.translate_string("st_olr_item_efs_status_zombification"), self.sibyazva))
	self.Static8:SetTextST(game.translate_string("st_olr_item_efs_status_organism"))

	local snd_obj = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)

end

function injector_info:__finalize()
end

function injector_info:InitCallBacks()
	self:AddCallback("button2", ui_events.BUTTON_CLICKED, self.button2_button_clicked, self)
end

function injector_info:button2_button_clicked()
	self:GetHolder():start_stop_menu(self, true)
end

function injector_info:Hide()
	self:GetHolder():start_stop_menu(self, true)
	collectgarbage("collect")
end

function get_paras()
	if has_alife_info("bolezn_parazity_info") then
		return game.translate_string(game.translate_string("st_olr_item_efs_positive"))
	else
		return game.translate_string(game.translate_string("st_olr_item_efs_negative"))
	end
end

function get_besh()
	if has_alife_info("bolezn_beshenstvo_info") then
		return game.translate_string(game.translate_string("st_olr_item_efs_positive"))
	else
		return game.translate_string(game.translate_string("st_olr_item_efs_negative"))
	end
end

function get_ratbezum()
	if has_alife_info("bolezn_ratcrazy_info") then
		return game.translate_string(game.translate_string("st_olr_item_efs_positive"))
	else
		return game.translate_string(game.translate_string("st_olr_item_efs_negative"))
	end
end

function get_sibyazva()
	if has_alife_info("bolezn_sibyazva_info") then
		return game.translate_string(game.translate_string("st_olr_item_efs_positive"))
	else
		return game.translate_string(game.translate_string("st_olr_item_efs_negative"))
	end
end

function get_zombied()
	if olr_timers.has_timer("bolezn_zombied_timer_m") or olr_timers.has_timer("bolezn_zombied_timer_d") then
		return game.translate_string(game.translate_string("st_olr_item_efs_positive"))
	else
		return game.translate_string(game.translate_string("st_olr_item_efs_negative"))
	end
end