-- hi_flyer 30.04.17

class "ui_quests_table" (CUIScriptWnd)

function ui_quests_table:__init() super()
	self:InitControls()
	self:InitCallBacks()
end

function ui_quests_table:__finalize()
end

function ui_quests_table:InitControls()
	local xml = CScriptXmlInit()
	self:Init(0,0,1024,768)
	xml:ParseFile("ui_quests_table.xml")
	self.background_main = xml:InitStatic("background_main", self)
	self.background_top = xml:InitStatic("background_main:background_top", self.background_main)
	self.background_bottom = xml:InitStatic("background_main:background_bottom", self.background_main)	
	self.background_table = xml:InitStatic("background_main:background_table", self.background_main)
	self.frame_desc_quest = xml:InitFrame("background_main:background_table:frame_desc_quest", self.background_table)
	self.static_desc_quest = xml:InitStatic("background_main:background_table:frame_desc_quest:static_desc_quest", self.frame_desc_quest)
	self.frame_list_quest = xml:InitFrame("background_main:background_table:frame_list_quest", self.background_table)
	self:Register(xml:Init3tButton("background_main:background_table:frame_list_quest:bt_find_item", self.frame_list_quest), "bt_find_item")
	self:Register(xml:Init3tButton("background_main:background_table:frame_list_quest:bt_kill_stalker", self.frame_list_quest), "bt_kill_stalker")
	self:Register(xml:Init3tButton("background_main:background_table:button_exit", self.background_table), "button_exit")
	self:Register(xml:Init3tButton("background_main:background_table:button_take_quest", self.background_table), "button_take_quest")
	self.Static3 = xml:InitStatic("background_main:background_table:Static3", self.background_table)
	local job_selected = false 
	local job_selected_kill = false
	local nm = "" 
end

function ui_quests_table:InitCallBacks()
	self:AddCallback("bt_find_item", ui_events.BUTTON_CLICKED, self.bt_find_item_button_clicked, self)
	self:AddCallback("bt_kill_stalker", ui_events.BUTTON_CLICKED, self.bt_kill_stalker_button_clicked, self)
	self:AddCallback("button_exit", ui_events.BUTTON_CLICKED, self.button_exit_button_clicked, self)
	self:AddCallback("button_take_quest", ui_events.BUTTON_CLICKED, self.button_take_quest_button_clicked, self)
end

function ui_quests_table:bt_find_item_button_clicked()
	job_selected_kill = false 
	local textdesc = game.translate_string(""..xvars.quest_one_text.." — "..game.translate_string(xvars.quest_one_text_name)..game.translate_string("st_olr_doska_payment")..xvars.quest_one_cost.." ")
	if not has_alife_info("doska_one_taken") then
		self.static_desc_quest:SetText(textdesc)
		job_selected = true
	elseif xvars.quest_one_target == "" and has_alife_info("doska_one_taken") then
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_no_work_available"))
	else
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_task_taken_retrieve_item").." "..game.translate_string(xvars.quest_one_text_name)..game.translate_string("st_olr_doska_payment").." "..xvars.quest_one_cost.." ")
	end  
end

function ui_quests_table:bt_kill_stalker_button_clicked()
	job_selected = false
	local sobj = game.translate_string(xvars.quest_two_target)
	local obj = alife():object(sobj)
	if not obj then
		olr_doska_escape.gen_kill_stalker()
		log1("sobj is nil")
		return
	end
	local pk = get_netpk(obj,1)
	local pos = news_main.get_point_description(alife():level_name(game_graph():vertex(obj.m_game_vertex_id):level_id()), vector():set(obj.position.x,obj.position.y,obj.position.z))
  	if pk:isOk() then
    		local data = pk:get()
          	local name = data.character_name
		--log1(""..name.." isss")
		nm = name
	end
	if xvars.quest_two_target == "" then
		nm = "empty"
	end
	local textdesc = game.translate_string(game.translate_string("st_olr_doska_kill_stalker_preface").." "..nm..game.translate_string("st_olr_doska_kill_stalker_last_location").." "..pos..game.translate_string("st_olr_doska_payment").." "..xvars.quest_two_cost)
	if not has_alife_info("doska_two_taken") then
	
		self.static_desc_quest:SetText(textdesc)
		job_selected_kill = true
	elseif xvars.quest_two_target == "" and has_alife_info("doska_two_taken") then
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_no_work_available"))
		if not olr_timers.has_timer("gen_kill_stalker") then
			olr_timers.st_timer("gen_kill_stalker", 52, "olr_doska_escape.gen_kill_stalker()")
		end
	else
		self.static_desc_quest:SetText(game.translate_string("st_olr_doska_task_taken_kill_stalker").." "..nm..xvars.quest_two_cost)
		db.actor:give_info_portion("escape_doska_quest_taken")
	end  
end

function ui_quests_table:button_exit_button_clicked()
	job_selected = false
	job_selected_kill = false 
	self:GetHolder():start_stop_menu(self, true)
	bind_stalker.restore_weapon()
	level.remove_cam_effector(30)
end

function ui_quests_table:button_take_quest_button_clicked()
	if job_selected == true then
		job_selected_kill = false
		xvars.quests_all_ids = xvars.quests_all_ids + 1
		--log1("quest take now -  clear job one")
		--olr_doska_escape.give_quest_item_find()
		job_selected = false
		self:GetHolder():start_stop_menu(self, true)
		bind_stalker.restore_weapon()
		level.remove_cam_effector(30)
		olr.info("doska_one_taken")
		olr.info("doska_one_working")
		news_manager.send_tip(db.actor, game.translate_string("st_olr_doska_find_item").." "..xvars.quest_one_text_name.." "..game.translate_string("st_olr_doska_escape_task_2"), 1, "item", 9000)
		olr_timers.st_timer("doska_one_gen_timer_fail", 6500, "olr_doska_escape.doska_one_gen_timer_fail()")
		db.actor:give_info_portion("escape_doska_quest_taken")
	else
		--log1("cannot take quest")
	end

	if job_selected_kill == true then
		--log1("take two")
		job_selected = false
		xvars.quests_all_ids = xvars.quests_all_ids + 1
		job_selected_kill = false
		self:GetHolder():start_stop_menu(self, true)
		bind_stalker.restore_weapon()
		level.remove_cam_effector(30)
		olr.info("doska_two_taken")
		olr.info("doska_two_working")
		news_manager.send_tip(db.actor, game.translate_string("st_olr_doska_kill_stalker").." "..nm, 1, "kill_stalker", 9000)
		local sobj = game.translate_string(xvars.quest_two_target)
		local obj = alife():object(sobj)
		olr.add_spot_on_map( obj.id,"kill_stalker_location", game.translate_string("st_olr_doska_escape_task_4")..nm)
		olr_timers.st_timer("doska_two_gen_timer_fail", 6500, "olr_doska_escape.doska_two_gen_timer_fail()")
		if not has_alife_info("assasin_jaba_about") then
			olr.info("assasin_jaba_about")
			news_manager.send_tip(db.actor, game.translate_string("ui_quests_tablebutton_take_quest_button_clicked_0"), 3, "trader", 39000, nil, nil, true, "escape_trader_name")
			db.actor:give_info_portion("escape_doska_quest_taken")
		end
	else
		--log1("cannot take quest")
	end
end

function ui_quests_table:Hide()
	self:GetHolder():start_stop_menu(self, true)
	bind_stalker.restore_weapon()
	level.remove_cam_effector(30)
end

----------------------------------------------------------------------------------------------------------------------------
-- Поиск предметов

-- таймер на провал задания 
function doska_one_gen_timer_fail()
	olr_doska_escape.clear_find_item()
	olr_timers.st_timer("doska_one_gen", 33, "olr_doska_escape.gen_rnd_item_find()")
	db.actor:disable_info_portion("doska_one_working")
	db.actor:change_character_reputation(-20)
end 

-- преконд наличия итема
function precond_user_task_doska_item()
	if xvars.quest_one_target == "" then
		return false
	end
	local obj_targ = game.translate_string(xvars.quest_one_target)
	local art = db.actor:object(obj_targ)
	if art and art:is_artefact() then
		return false
	end
	return nik_dialog.item_much(obj_targ,1) ~= false 
end

function has_any_active_task_doska(first_speaker, second_speaker)
	if xvars.quest_one_target ~= "" then
		return true
	end
	if xvars.quest_two_target ~= "" then
		return true
	end
	return false
end

function precond_user_task_doska_item_art()
	if xvars.quest_one_target == "" then
		return false
	end
	local obj_targ = game.translate_string(xvars.quest_one_target)
	local art = db.actor:object(obj_targ)
	if art and not art:is_artefact() then
		return false
	end
	if art and art:is_artefact() then
		local known_inf = ini_sys:r_string(obj_targ, "known_info")
     	return nik_dialog.item_much(obj_targ,1) ~= false and has_alife_info(known_inf)
	end
end

-- сдаём квест на предмет
function one_complete_func_item()
	local mon = math.floor(xvars.quest_one_cost) 
	db.actor:give_money(mon)
	game_stats.money_quest_update(mon)
	news_manager.relocate_money(db.actor, "in", mon)
	local obj_targ = game.translate_string(xvars.quest_one_target)
	nik_dialog.out_item_much(obj_targ,1)
	olr_doska_escape.clear_find_item()
	db.actor:disable_info_portion("doska_one_working")
	db.actor:disable_info_portion("escape_doska_quest_taken")
	local time = math.random(96,466)
	olr_timers.st_timer("doska_one_gen", time, "olr_doska_escape.gen_rnd_item_find()")
	olr_timers.del_timer("doska_one_gen_timer_fail")
end



function gen_rnd_item_find()
	--log1("gen one find jaba")
	db.actor:disable_info_portion("doska_one_taken")

	if level.name() == "lvl1_escape" then
	--log1("init esc doska")
	zfind_item_obj = {
	 
		 [1] = {name = "wpn_pb",            		cost = 300,  text = game.translate_string("st_olr_doska_esc_find_item_pb")},
		 [2] = {name = "wpn_walther",       		cost = 400,  text = game.translate_string("st_olr_doska_esc_find_item_walther")},
		 [3] = {name = "wpn_bm16",       		cost = 450,  text = game.translate_string("st_olr_doska_esc_find_item_bm16")},
		 [4] = {name = "killer_outfit",       		cost = 1150,  text = game.translate_string("st_olr_doska_esc_find_item_killer_outfit")},
		 [5] = {name = "scientific_outfit",       	cost = 1250,  text = game.translate_string("st_olr_doska_esc_find_item_protective_outfit")},
		 [6] = {name = "wpn_svd",       		cost = 1100,  text = game.translate_string("st_olr_doska_esc_find_item_svd")},
		 [7] = {name = "af_magnet",       		cost = 400,  text = game.translate_string("st_olr_doska_esc_find_item_magnet")},
		 [8] = {name = "af_zuda",       		cost = 300,  text = game.translate_string("st_olr_doska_esc_find_item_zuda")},
		 [9] = {name = "af_knot",       		cost = 300,  text = game.translate_string("st_olr_doska_bar_find_item_sparkler")},
		 [10] = {name = "af_mercury_ball",       			cost = 300,  text = game.translate_string("st_olr_doska_esc_find_item_mercury_ball")},
		 [11] = {name = "af_thorn",       		cost = 100,  text = game.translate_string("st_olr_doska_esc_find_item_thorns")},
		 [12] = {name = "af_bublik",       			cost = 200,  text = game.translate_string("st_olr_doska_esc_find_item_bagel")},

		}
	else
	--log1("init mil doska")
	zfind_item_obj = {
	 
		 [1] = {name = "wpn_usp",       		cost = 680,  text = game.translate_string("st_olr_doska_esc_find_item_usp")},
		 [2] = {name = "killer_outfit",       		cost = 1550,  text = game.translate_string("st_olr_doska_esc_find_item_killer_outfit")},
		 [3] = {name = "scientific_outfit",       	cost = 2250,  text = game.translate_string("st_olr_doska_esc_find_item_protective_outfit")},
		 [4] = {name = "wpn_svd",       		cost = 1700,  text = game.translate_string("st_olr_doska_esc_find_item_svd")},
		 [5] = {name = "af_magnet",       		cost = 770,  game.translate_string("st_olr_doska_esc_find_item_magnet")},
		 [6] = {name = "af_zuda",       		cost = 380,  text = game.translate_string("st_olr_doska_esc_find_item_zuda")},
		 [7] = {name = "af_knot",       		cost = 360,  text = game.translate_string("st_olr_doska_bar_find_item_sparkler")},
		 [8] = {name = "af_mercury_ball",       			cost = 370,  text = game.translate_string("st_olr_doska_esc_find_item_mercury_ball")},
		 [9] = {name = "af_thorn",       		cost = 160,  text = game.translate_string("st_olr_doska_esc_find_item_thorns")},
		 [10] = {name = "af_bublik",       			cost = 270,  text = game.translate_string("st_olr_doska_esc_find_item_bagel")},

		 [11] = {name = "af_lamp",       		cost = 10000,  text = game.translate_string("st_olr_doska_esc_find_item_death_lamp")},

		 [12] = {name = "outfit_stalker_golmar",       		cost = 7350,  text = game.translate_string("st_olr_doska_esc_find_item_golmars_outfit")},
		 [13] = {name = "wpn_vintorez_gravi",       		cost = 2000,  text = game.translate_string("st_olr_doska_esc_find_item_gravity_vss")},
		 [14] = {name = "wpn_binoc",       			cost = 400,  text = game.translate_string("st_olr_doska_esc_find_item_binocs")},
		 [15] = {name = "hand_torch",       			cost = 450,  text = game.translate_string("st_olr_doska_esc_find_item_hand_torch")}

		}
	end

	local irnd = math.random(#zfind_item_obj) or 1
	local item = tostring(zfind_item_obj[irnd].name)
	local cost = tostring(zfind_item_obj[irnd].cost)
	local text = tostring(zfind_item_obj[irnd].text)

	xvars.quest_one_target = item
	xvars.quest_one_cost = cost
	xvars.quest_one_text_name = text

	local text_phrase = {
		"st_olr_doska_find_item_preface_1", 
		"st_olr_doska_find_item_preface_2", 
		"st_olr_doska_find_item_preface_3", 
		"st_olr_doska_find_item_preface_4"
	}
	local text_find = game.translate_string(text_phrase[math.random(#text_phrase)])
	xvars.quest_one_text = text_find

	--log1("jaba doska need find new - "..xvars.quest_one_target.."  --- "..xvars.quest_one_cost.."")
end

-- отчистка итема для поиска
function clear_find_item()
	xvars.quest_one_target = ""
	xvars.quest_one_cost = 0
	xvars.quest_one_text = ""
	xvars.quest_one_text_name = ""
end


-- выдача квеста на поиск предмета
function give_quest_item_find()
	local new_task = CGameTask()
	new_task:load("user_task_doska_item")
	new_task:set_title(game.translate_string("st_olr_doska_esc_find_item_for_toad"))
	local idr = xvars.quests_all_ids
	--new_task:set_id(idr)

	local SubTask = SGameTaskObjective (new_task, 1)
	local target = game.translate_string(xvars.quest_one_text_name)
	SubTask:set_description(game.translate_string("st_olr_doska_esc_find_target")..target.."")
	SubTask:add_complete_func("olr_doska_escape.precond_user_task_doska_item")
	new_task:add_objective(SubTask)

	local SubTask2 = SGameTaskObjective (new_task, 2)
	SubTask2:set_description(game.translate_string("st_olr_doska_esc_talk_to_client"))
	new_task:add_objective(SubTask2)
	local time = math.random(19600,46600)
	db.actor:give_task(new_task, time*1000, true)
end

-- завершаем квест
function one_complete_task_item()
	return not has_alife_info("doska_one_working")
end

function one_complete_task_item_fail()
	return false
end


----------------------------------------------------------------------------------------------------------------------------
-- убить сталкера

-- таймер на провал задания 
function doska_two_gen_timer_fail()
	local sobj = game.translate_string(xvars.quest_two_target)
	local obj = alife():object(sobj)
	level.map_remove_object_spot(obj.id, "kill_stalker_location")
	olr_doska_escape.clear_find_kill()
	olr_timers.st_timer("gen_kill_stalker", 26, "olr_doska_escape.gen_kill_stalker()")
	db.actor:disable_info_portion("doska_two_working")
	db.actor:change_character_reputation(-20)
	db.actor:disable_info_portion("escape_doska_quest_taken")
end 

function gen_kill_stalker()
	db.actor:disable_info_portion("doska_two_taken")
	local places = {}
	for _, kill in ipairs(olr_offline_walk.tabst) do
	--for id=1, 65534 do
		--local kill = alife():object(id)
		if kill then
			if IsStalker(kill) then
				if kill:alive() and kill.level_name == "lvl2_garbage" or kill.level_name == "lvl3_agroprom" or kill.level_name == "lvl4_darkdolina" then
					if kill:community()=="bandit" or kill:community()=="killer" or kill:community()=="zombied" or kill:community()=="monolith" or kill:community()=="voenstals" then
						if not olr_protected.is_no_offline_alife_obj(kill:name()) then
							table.insert(places, kill)
						end
					end
				end
			end
		end
	end
	local rand_kill = places[math.random(#places)]
	xvars.quest_two_target = rand_kill:name()
	local mon = 150
	if rand_kill:community()=="zombied" then
		mon = 200
	elseif rand_kill:community()=="bandit" then
		mon = 400
	else
		mon = 500
	end
	xvars.quest_two_cost = mon
	--olr.add_spot_on_map( rand_kill.id,"crlc_big", "килл" )
	--news_manager.send_tip(db.actor, "есть rand_kill "..rand_kill:name().." -- "..rand_kill.level_name.." ")
end


-- преконд убитого сталкера
function precond_user_task_doska_kill()
	if xvars.quest_two_target == "" then
		return false
	end
     	local sobj = game.translate_string(xvars.quest_two_target)
     	local obj = alife():object(sobj)
	if obj then
     		return not obj:alive() and has_alife_info("doska_two_taken") and xvars.npc_kileed_by_actor[obj:name()] ~= nil
	else
		return false
	end
end

-- сдаём квест на убийство
function two_complete_func_kill()
     	local sobj = game.translate_string(xvars.quest_two_target)
     	local obj = alife():object(sobj)
	if not obj then return end
	level.map_remove_object_spot(obj.id, "kill_stalker_location")
	if obj:community()=="zombied" then
		db.actor:change_character_reputation(10)
	elseif obj:community()=="bandit" then
		db.actor:change_character_reputation(20)
	else
		db.actor:change_character_reputation(30)
	end
	db.actor:give_money(xvars.quest_two_cost)
	game_stats.money_quest_update(xvars.quest_two_cost)
	news_manager.relocate_money(db.actor, "in", xvars.quest_two_cost)
	db.actor:disable_info_portion("doska_two_working")
	db.actor:disable_info_portion("escape_doska_quest_taken")
	local time = math.random(90,160)
	olr_timers.st_timer("gen_kill_stalker", time, "olr_doska_escape.gen_kill_stalker()")
	olr_doska_escape.clear_find_kill()
	olr_timers.del_timer("doska_two_gen_timer_fail")
end

-- отчистка текущего убитого для поиска
function clear_find_kill()
	xvars.quest_two_target = ""
	xvars.quest_two_cost = 0
end






