local monolith_call = {
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_1",
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_2",
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_3",
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_4",
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_5",
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_6",
	"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_7"
}

function play_rnd_snd()
	if not level.present() then
		return
	end
	
	if xr_conditions.actor_in_zone(nil, nil, {"lvl16_generators_bossfight_zone"}) then
	
		if has_alife_info("oso_killed") then
			return
		end
		
		local randd = math.random(1, 3)
		if randd == 1 then
			olr.spawen_phantoms()
			nick.clear_chaes_zom()
		elseif randd == 2 then
			nick.stancia_fake_anoms()
		else
			nick.phantasms_zombies()
		end
	end

	if level.name() == "l15_generators" then
		return
	end
	
	if actor_on_chaes() then
		local rnd = math.random(1, 5)
		if rnd == 1 then
			olr.spawen_phantoms()
			nick.clear_chaes_zom()
		else
			nick.stancia_fake_anoms()
		end
	end
end

-- db.actor:is_actor_outdoors() == false

function actor_on_chaes()
	local level_name = level.name()
	if level_name == "l14_stancia" and not has_alife_info("actor_ishet_sebbya_info") then
		return true
	end
end
