
-- TODO переделать
function sim_location_traveling()
	--local pt = profile_timer()
	--pt:start()

	if db.actor then
		local montabl = {
			[clsid.respawn] = true,
			[clsid.smart_terrain] = true
		}

		local sectionsa = {
			{"lvl5_bar_stalker_0008", "start_olr_mod"}, -- искатель бар
			{"lvl4_darkdolina_stalker_0017", "start_olr_mod"}, -- искатель долина
			{"lvl7_yantar_stalker_0013", "otdal_kulon_open_door"}, -- психованый мужик охранник янтарь
			{"lvl8_swamp_stalker_0005", "start_olr_mod"}, -- искатель болото
			--{"lvl8_swamp_stalker_0022", "fil_boloto_dialog_done"}, -- фил болото
			{"lvl2_garbage_stalker_0040", "start_zagon_bandosa_dead"}, -- спрут
			{"bar_bar_visitor_hunter", "bar_rosomaha_about_darkstaker_skazal"}, -- росомаха бар
			{"lvl1_escape_stalker_0008", "esc_lechenie_sos_gravart_info"}, -- рыхлый кордон после лечения
			--{"bar_bar_lisiy", "raboy_zdoh_nahui"}, -- лысый как здохнет рябой
			{"lvl9_military_staler_undead_olr", "morak_talk_two_done_talked"}, -- моряк
			--{"lvl1_escape_stalker_0054", "dolg_road_nin_donk_now_spaven_go_done"}, -- черт
			--{"lvl1_escape_stalker_0055", "dolg_road_nin_donk_now_spaven_go_done"}, -- сивый
			{"lvl5_bar_stalker_0039", "den_dialog_bar_done"} -- ден бар
		}

		local sim = alife()
		for id = 1, 65534 do
			local kill = sim:object(id)
			if kill then
				if montabl[kill:clsid()] then
					for _, val in ipairs(sectionsa) do
						if val then
							local sec = sim:object(val[1])
							if sec and sec:alive() and has_alife_info(val[2]) then
								local gvid = sec.m_game_vertex_id
								if game_graph():valid_vertex_id(gvid) then
									if sim:level_name(game_graph():vertex(gvid):level_id()) ~= level.name() then
										local bol_var = math.random(1, 200)
										if bol_var == 1 then
											--log1(""..sec:name().." - "..kill:name().." - "..alife():level_name(game_graph():vertex(sec.m_game_vertex_id):level_id()).."")
											sim:teleport_object(sec.id, kill.m_game_vertex_id, kill.m_level_vertex_id, kill.position)
											--log1("telep stlkrs")
											--log1(sobj:name())
											olr.clear_restrictors(sec)
											--olr.add_spot_on_map( sec.id,"jaba_spotmap", sec:name() )
										end
									end
								end
							end
						end
					end
				end
			end
		end
	end

	--pt:stop()
	--printf("работало (sim_location_traveling) "..pt:time().." ms")
end
