--------------------------------------------------------------------------------------------------------------------------------

function blowout_ending_set()
	if not no_blow_levels[level.name()] then
		olr.spawn_crows(20, 90)
	end

	local bc = xvars.blow_count
	bc = bc + 1
	xvars.blow_count = bc
	--news_manager.send_tip(db.actor, "Пережито "..bc.." выбросов...", nil, "dolg", 6000)

	all_blowend_funcs()

	db.actor:disable_info_portion("spawn_anoms_esc")
	db.actor:disable_info_portion("spawn_anoms_gar")
	db.actor:disable_info_portion("spawn_anoms_agr")
	db.actor:disable_info_portion("spawn_anoms_dol")
	db.actor:disable_info_portion("spawn_anoms_bar")
	db.actor:disable_info_portion("spawn_anoms_yan")
	db.actor:disable_info_portion("spawn_anoms_mil")
	db.actor:disable_info_portion("spawn_anoms_rad")
	db.actor:disable_info_portion("spawn_anoms_ded")
end

function all_blowend_funcs()
	-- на вс¤кий случай

	del_vidrosovie_arts() -- удаляет "af_mercury_ball" "af_junk_bolt" "af_magnet" "af_junk_debris" с локаций с шансом у каждого артефакта 1 к 35
	blow_info_count() -- выдаёт поршень про выбросы по условиям что мы на кордоне и притащили какой то ящик поршень medyasik_2_done, сам поршень что выдаётся высылает мессагу от жабы который спрашивает мессера мол ты живой
	set_arts_cond_after_blowout() -- проходится по онлайновым артефактам, список в функции, с шансом 50 на 50 меняет состояние артефакта на матч.рандом чёто там, если состояние ниже 0.01 удаляет артефакт
	spawen_arts_random() -- тупой спавен тупово гавна, ой артефактов в аномалиях, тупа рандомная хуйня, вырезать удалить написать нормальный, надо Рому
						 -- работает так, есть пачка аномалий, и пачка артефактов, списки в функции, идём по всем объектам, находим аномалию, далее с шансом 1 к 180 на позиции данной аномалии заспавнится рандомный артефакт из таблицы
	spawen_pseudohuman() -- лежало внутри функции выше, если пережили более 7 выбросов, то в радиоактивных зонах с шансом 1 к 580 спавнит мутанта там (кроме локации бар), список мутантов внутри функции
	spawn_esc_mil_group() -- спавн военных научных групп, спавнятся если пережили не менее 5 и не более 8 выбросов, потом не менее 12 и не более 16, потом уже не менее 25 выбросов надо пережить и спавн будет после каждого выброса
	remove_onl_anoms() -- проходится по нескольким clsid аномалий и включает их принудительно, список клсид в функции. Но это касается только онлайновых объектов, лол.

	olr_timers.st_timer("clear_dead_monsters", 12, "olr_blowout.clear_dead_monsters()") -- удаляет трупы монстров по условиям, если монстр не живой и не под защитой olr_protected и если не умерший в оффлайне и не на том же уровне на котором мы
	olr_timers.st_timer("xrs_trade_trading", 13, "xrs_trade.on_item_drop()") -- предложение поторговать, принудительно дёргает
	olr_timers.st_timer("spawen_radhlam_random", 16, "olr_blowout.spawen_radhlam_random()") -- обход по всем объектам, ищет радиоактивные зоны, с шансом 1 к 60 спавнит мусорные артефакты, список в функции
	olr_timers.st_timer("spawen_rtut_shars_random", 18, "olr_blowout.spawen_rtut_shars_random()") -- обход по всем объектам, ищет zone_mincer, с шансом 1 к 65 спавнит ртутный шар
	olr_timers.st_timer("spawen_rtut_shars", 20, "olr_blowout.spawen_rtut_shars()") -- пиздец... шанс 3 к 22, спавн ртутного шара на определенных координатах на кордоне и на свалке, 
																					-- точнее так, делаем два рандома, 1-22, если уровень кордон и выпал 1 то первые координаты, если 2 то вторые, если 3 то третьи, на свалке аналогично. главное находится там актору...
	olr_timers.st_timer("bar_alcos", 33, "olr_blowout.bar_alcos()") -- срабатывает только если актора нет в баре. Выводит в оффлайн и выводит из онлайна пьяниц фейковых что сидят в баре
																	-- сначала всех в оффлайн, потом с шансом 50 на 50 выгоняет в онлайн, всё работает по конкретному списку
																	-- потом еще добавляет бабок бармену и петренке от 1000 до 4500
	olr_timers.st_timer("clear_bolts", 44, "olr_blowout.clear_bolts()") -- с шансом 50 на 50 вызов удаления всего оружия без парента, потом если пережили более 6 выбросов
																		-- вызывает del_rnd_anoms, clear_deadinoffline_wars, потом проход по всем объектам, удаляет физ мусор, скелеты, m_pseudohuman_e мёртвых, zone_witches_galantine_banka, дезинтеграторную аномалию
																		-- (кстати надо это убрать и удалять по иному, это может вызвать проблемы), 
																		-- функция clear_deadinoffline_wars чистит всех кто помечен был мёртвым в оффлайне
																		-- функция del_rnd_anoms удаляет радиоактивные зоны, колючки, с шансом 50 на 50 но не на том уровне где мы находимся
	olr_timers.st_timer("fix_escape_restrs", 4, "olr_blowout.fix_escape_restrs()") -- если более 2 выбросов пережили, проходит по всем объектам, если это сталкер или мутант очищает у них dynamic_in_restrictions в нет-пакетах
	olr_timers.st_timer("clear_trash_wars", 59, "olr_blowout.clear_trash_wars()") -- чистит xvars foods, weapons, arts
	olr_timers.st_timer("clear_afterblow_deadnpc", 79, "olr_blowout.clear_afterblow_deadnpc()") -- если пережито более 6 выбросов проход по всем объектам, если это сталкер, не живой и не под защитой olr_protected то записываем в xvars.npc_del_afterblow
																								-- потом уборщик трупов осмотрит их инвентари и если там ничего важного нет то удалит, хуйня кароче очередная
	olr_timers.st_timer("set_walkers_rndways", 74, "olr_ai_tasks.set_walkers_rndways()") -- вызывает принудительную перетасовку смартов куда отправляются сталкеры которым выдан глобальный квест
																						 -- с шансом 50% снимает с них квест (вроде как, ну нилит npcs_tasks_rndway), я так понял потом smart_terrain если ему из квеста пришёл false тот уже сам выберет куда ему идти

	if has_alife_info("rad_first") and not has_alife_info("gen_first") then -- если были на радаре, но еще не были на генераторах, то после каждого выброса
																			-- вызываем 4 нахуй раза spawen_endgame_zombies
																			-- которая работает так
																			-- обход по всем объектам, ищет clsid.respawn везде кроме бара, там спавнит мутантов по таблице см. функцию, и вписывает их в свои охуительные костыли
		olr_blowout.spawen_endgame_zombies()
		olr_timers.st_timer("spawen_endgame_zombies1", 19, "olr_blowout.spawen_endgame_zombies()")
		olr_timers.st_timer("spawen_endgame_zombies2", 29, "olr_blowout.spawen_endgame_zombies()")
		olr_timers.st_timer("spawen_endgame_zombies3", 39, "olr_blowout.spawen_endgame_zombies()")
	end

	if xvars.blow_count > 6 and not has_alife_info("gen_first") then -- если пережили более 6 выбросов и не были на генераторах
																	 -- то проверяем что мы уже были в баре по поршню bar_dolg_propusk_done
																	 -- обходим все объекты и всех живых сталкеров, если у них есть свой смарт (т.е это не свободногуляющие где смарт ноне) strn_id ~= 65535 то записываем
																	 -- если их более 50 то не вызываем принудительный респавн, а если менее то вызываем принудительный респавн по всем респавнерам
																	 -- но я там еще добавил что шанс срабатывания принудительного респавна 1 к 15 будет у каждого респавнера
		olr_timers.st_timer("respawn_now", 79, "olr_blowout.respawn_now()")
	end

	if has_alife_info("monolit_na_kordone") then -- если мы получили поршень monolit_na_kordone то начинаем вызывать еще и эту хуету
		olr_timers.st_timer("spawen_endgame_posthuman", 39, "olr_blowout.spawen_endgame_posthuman()") -- спавнит мутантов по таблице в зонах респавна, химеры да постхуманы, проверяем валидность вертекс айди
																									  -- есть еще рандом 1 к 15 на каждый респавн что бы не слишком дохуя наспавнило
	end

	if has_alife_info("docent_zamer_vibros_done_pogo") then -- это квест с замером выброса от учёных в говне мочёных
		if not has_alife_info("docent_zamer_vibros_daem") then
			olr.info("docent_zamer_vibros_daem")
			news_manager.send_tip(db.actor, game.translate_string("all_blowend_funcs_0"), 15, "ecolog", 39000, nil, nil, true, "st_sim_test_033_name")
		end
	end
end

---------------------------------------------

function spawen_endgame_posthuman()
	local montabl = {
		[clsid.respawn] = true
	}

	local sectionsa = {
		"m_posthuman_e",
		"chimera_strong",
		"chimera_weak",
		"chimera_midl"
	}

	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if montabl[kill:clsid()] then
				local section = sectionsa[math.random(table.getn(sectionsa))]
				if game_graph():valid_vertex_id(kill.m_game_vertex_id) and math.random(1, 15) == 1 then
					local sobj = alife():create(section, kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id)
					--olr.add_spot_on_map( sobj.id,"alife_presentation_smart_on",sobj:name() )
					count = count + 1
					--news_manager.send_tip(db.actor, "m_posthuman_e заспавнилось "..count.." нау ииии", nil, "freedom", 9000)
				end
			end
		end
	end
end

-------------------------------------------------

function clear_trash_wars()

	for key, value in pairs(xvars.foods(true)) do
		if type(value) ~= "table" then
			--log1(" Invalid food entry for id " .. key .. ", type " .. type(value) .. ", removing")
			xvars.foods[key] = nil
		else
			--log1(" Key from tbl - "..tostring(key).."")
			local food_object = alife():object(tonumber(key))
			if not food_object then
				--log1(" DELETED food " .. key .. " id")
				xvars.foods[key] = nil
			else
				if value.sec and value.sec ~= food_object:section_name() then
					xvars.foods[key] = nil
				end
			end
		end
	end

	for key, value in pairs(xvars.weapons(true)) do
		if type(value) ~= "table" then
			--log1(" Invalid weapon entry for id " .. key .. ", type " .. type(value) .. ", removing")
			xvars.weapons[key] = nil
		else
			local wpn_object = alife():object(tonumber(key))
			if not wpn_object then
				--log1(" DELETED WPN " .. key .. " id")
				xvars.weapons[key] = nil
			else
				if value.sec and value.sec ~= wpn_object:section_name() then
					xvars.weapons[key] = nil
				end
			end
		end
	end

	-- Артефакты без изменений
	for key, value in pairs(xvars.arts()) do
		local art_object = alife():object(key)
		if not art_object then
			if xvars.arts[key .. game.translate_string("weight")] ~= nil then
				xvars.arts[key .. game.translate_string("weight")] = nil
			end
			if xvars.arts[key .. game.translate_string("cost")] ~= nil then
				xvars.arts[key .. game.translate_string("cost")] = nil
			end
		end
	end
end

function clear_bolts()
	local rndb = math.random(1, 2)
	if rndb == 1 then
		olr.del_noparent_weapons()
	end
	if xvars.blow_count < 6 then
		return
	end

	olr_timers.st_timer("del_rnd_anoms", 5, "olr_blowout.del_rnd_anoms()")
	olr_timers.st_timer("clear_deadinoffline_wars", 15, "olr_blowout.clear_deadinoffline_wars()")

	tab_hlam = {}

	local sim = alife()
	for id = 1, 65534 do
		local trs = sim:object(id)
		if trs then
			if trs:section_name() == "ph_food_conserv1" or trs:section_name() == "ph_food_conserv2" or trs:section_name() == "ph_food_vater" or trs:section_name() == "vodka_used_empty"
			 then
				table.insert(tab_hlam, trs)
				--log1("delhlam - add ph foods")
				--alife():release(trs, true)
			end
			if trs:section_name() == "shooting_bolts_objiect" then
				table.insert(tab_hlam, trs)
				--log1("delhlam - add bolts")
				--alife():release(trs, true)
			end
			if trs:section_name() == "dead_body_skelet" then
				table.insert(tab_hlam, trs)
				--log1("delhlam - add skelets")
				--alife():release(trs, true)
			end
			if trs:section_name() == "dead_body_skelet2" then
				table.insert(tab_hlam, trs)
				--log1("delhlam - add skelets 2")
				--alife():release(trs, true)
			end
			if trs:section_name() == "zone_witches_galantine_banka" or trs:section_name() == "zone_witches_galantine_dezint" then
				table.insert(tab_hlam, trs)
				--log1("delhlam - add banka buzz")
				--alife():release(trs, true)
			end
			if IsMonster(trs) and trs:section_name() == "m_pseudohuman_e" and not trs:alive() then
				--log1("delhlam - add dead pshum")
				--alife():release(trs, true)
				table.insert(tab_hlam, trs)
			end
			if trs:section_name() == "item_pda_dead_taken" then
				local pobj = sim:object(trs.parent_id)
				if not pobj then
					--log1("delhlam - taken pdas")
					--alife():release(trs, true)
					table.insert(tab_hlam, trs)
				end
			end
			if trs:section_name() == "device_torch" then
				--log1("delhlam - add torch HAS ")
				local pobj = sim:object(trs.parent_id)
				if not pobj then
				--log1("delhlam - add torch HAS without parent")
				--if trs.item_condition < 0.3 then
				--	--alife():release(trs, true)
				--	table.insert(tab_hlam, trs)
				--	--log1("delhlam - add torch without parent and low battery")
				--end
				end
			--if pobj and not pobj:alive() then
			--	--alife():release(trs, true)
			--	table.insert(tab_hlam, trs)
			--	log1("delhlam - add torch of dead parent")
			--end
			end
		end
	end

	--log1("lupa22")

	--log1(" tab_hlam count - "..#tab_hlam.." ")
	for _, o in ipairs(tab_hlam) do
		if o then
			--log1("clear trash IN TABLE items now "..o:name().." ")
			alife():release(o)
		end
	end
end

function clear_deadinoffline_wars()
	for key, value in pairs(xvars.dead_in_offline()) do
		local wpn = alife():object(key)
		if not wpn then
			--log1(" DELDETED food "..key.." = "..tostring(value).."")
			xvars.dead_in_offline[key] = nil
		--olr.add_spot_on_map( wpn.id,"crlc_mdl", "Место где проводили замеры учёные." )
		end
	end
end

function clear_dead_monsters()
	--local cnt = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if IsMonster(kill) and not kill:alive() and not olr_protected.is_no_offline_alife_obj(kill:name()) then
				if not xvars.dead_in_offline[kill:name()] == true then
					if kill.level_name ~= level.name() then
						--cnt = cnt + 1
						--log1("dell - "..kill:name().."   "..kill.level_name.."   ")
						if kill then
							alife():release(kill, true)
						end
					end
				end
			end
		end
	end
	--log1(cnt)
end

function respawn_now()
	if not has_alife_info("bar_dolg_propusk_done") then
		return
	end

	local cnt = 0
	local sim = alife()
	for id = 1, 65534 do
		local obj = sim:object(id)
		if IsStalker(obj) and obj:alive() then
			local strn_id = obj:smart_terrain_id()
			if strn_id ~= 65535 then
				cnt = cnt + 1
			end
		end
	end
	--log1(cnt)

	if cnt > 50 then
		--news_manager.send_tip(db.actor, " DBG respawn_now TOO MUCH ALIVE STALKERS - RESPAWN FALSE ["..cnt.."] сейчас.", nil, "freedom", 9000)
		return
	end

	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if kill:clsid() == clsid.respawn and math.random(15) == 1 then	-- добавлен рандом 1 из 15
				--log1("DBG respawn_now - "..kill:name().."	  "..kill.level_name.."	  ")
				kill:spawn(100)
			end
		end
	end
end

function del_rnd_anoms()
	local montabl = {
		["zone_radioactive"] = true,
		["zone_radioactive_weak"] = true,
		["zone_black_needle"] = true
	}

	local cnta = 0
	for i = 0, 65534 do
		local sobj = alife():object(i)
		if sobj then
			if IsAnomaly(sobj) and sobj.level_name ~= level.name() then
				local rndan = math.random(1, 2)
				if montabl[sobj:section_name()] and rndan == 1 then
					cnta = cnta + 1
					xvars.rnd_anoms_count = xvars.rnd_anoms_count - 1
					--log1("удаляем аномалию "..sobj:name().."	"..cnta.."	"..sobj.level_name.." ")
					if sobj then
						alife():release(sobj, true)
					end
				end
			end
		end
	end
end

---------------------------------------------

function fix_escape_restrs()
	if xvars.blow_count < 2 then
		return
	end
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if IsStalker(kill) or IsMonster(kill) then
				local pk = get_netpk(kill, 1)
				if pk:isOk() then
					local data = pk:get()
					if #data.dynamic_in_restrictions > 0 then
						--log1("clear restrictor "..kill:name().." ")
						data.dynamic_in_restrictions = {}
						pk:set(data)
					end
				end
			end
		end
	end
end

---------------------------------------------

function remove_onl_anoms()
	local anomaly_tbl = {
		[clsid.zone_mosquito_bald] = true,
		[clsid.zone_acid_fog] = true,
		[clsid.zone_bfuzz] = true,
		--[clsid.zone_bfuzz_s] = true,
		--[clsid.zone_electra_s] = true,
		[clsid.zone_galant_s] = true,
		[clsid.zone_galantine] = true,
		[clsid.zone_mbald_s] = true,
		[clsid.zone_mincer] = true,
		[clsid.zone_mincer_s] = true
		--[clsid.zone_zharka_s] = true,
	}

	for i = 1, 65534 do
		local obj = level.object_by_id(i)
		local sobj = alife():object(i)
		if obj then
			if anomaly_tbl[obj:clsid()] then
				obj:enable_anomaly()
			end
		end
	end
end

----------------------------------------------

function del_vidrosovie_arts()
	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local obj = sim:object(id)
		if obj then
			local sect = obj:section_name()
			if sect == "af_mercury_ball" or sect == "af_junk_bolt" or sect == "af_magnet" or sect == "af_junk_debris" then
				local bol_var = math.random(1, 35)
				if bol_var == 1 then
					if obj then
						sim:release(obj)
					end
					count = count + 1
				end
			end
		end
	end
	--news_manager.send_tip(db.actor,"выброс удалено " .. count .. " выбросовых артов",nil,"freedom",9000)
end

----------------------------------------------
function blow_info_count()
	local level_1name = level.name()
	if level_1name == "l01_escape" then
		if not has_alife_info("olr_blowout_first") and has_alife_info("medyasik_2_done") then
			db.actor:give_info_portion("olr_blowout_first")
		end
	end
end
----------------------------------------------------

function lomka_pda()
	local slom_var = math.random(1, 3)
	if slom_var == 1 then
		local STbron = db.actor:object("device_pda")
		if STbron then
			STbron:set_condition(0.02)
		end
	end
end

function golod_gg()
	if db.actor:alive() then
		db.actor.satiety = -db.actor.satiety / math.random(1, 5)
	end
end

function psy_gg()
	if db.actor:alive() then
		if db.actor:is_actor_outdoors() == false then
			return
		end
		db.actor.psy_health = -db.actor.psy_health / math.random(1, 5)
	end
end

-----------------------------------------------------
function Kill_Monsters(gulag1) -- вызывается из биндера смарт террейна, убивает онлайновых мутантов
	if gulag1 ~= nil then
		for k, v in pairs(gulag1.Object) do
			if level.object_by_id(k) ~= nil then
				obj = level.object_by_id(k)
				if obj:is_monster() then
					obj:kill(obj)
				end
			end
		end
	end
end

-----------------------------------------------
function set_arts_cond_after_blowout()
	local valid_sections = {
		af_bublik = true,
		af_electrosphere = true,
		af_knot = true,
		af_black_drops = true,
		af_rusty_hair = true,
		af_toadeye = true,
		af_dummy_double = true,
		af_bublik_glass = true,
		af_magnet = true,
		af_transpsphere = true,
		af_zuda = true,
		af_gravi_heavy = true,
		af_gravi_weak = true,
		af_gravi_med = true
	}
	
	for i = 1, 65534 do
		local obj = level.object_by_id(i)
		if obj ~= nil and valid_sections[obj:section()] then
			local par_var = math.random(1, 2)
			if par_var == 1 then
				obj:set_condition(obj:condition() - deletor())
				if obj:condition() <= 0.01 then
					olr.del(obj)
				end
			end
		end
	end
end

function deletor()
	return math.random(5, 85) / 100
end

---------------------------------------------
function spawen_rtut_shars()
	local sim = alife()
	local level_name = level.name()
	local noobposition = db.actor:position()
	local bol_var = math.random(1, 22)
	local bol_var2 = math.random(1, 22)
	if level_name == "l01_escape" then
		if bol_var == 1 then
			local bloodbridge = vector():set(-73.76, 2.13, 82.00)
			sim:create("af_mercury_ball", bloodbridge, db.actor:level_vertex_id(), db.actor:game_vertex_id())
			if bol_var == 2 then
				local bloodafterbridge = vector():set(137.47, 2.00, 66.03)
				sim:create("af_mercury_ball", bloodafterbridge, db.actor:level_vertex_id(), db.actor:game_vertex_id())
				if bol_var == 3 then
					local fracunderbridge = vector():set(25.91, 2.00, 316.13)
					sim:create("af_mercury_ball", fracunderbridge, db.actor:level_vertex_id(), db.actor:game_vertex_id())
				end
			end
		end
	end
	if level_name == "l02_garbage" then
		if bol_var2 == 1 then
			local bloodbridge1 = vector():set(15.54, 19.13, -321.68)
			sim:create("af_mercury_ball", bloodbridge1, db.actor:level_vertex_id(), db.actor:game_vertex_id())
			if bol_var2 == 2 then
				local bloodafterbridg1e = vector():set(8.55, 3.00, 368.84)
				sim:create("af_mercury_ball", bloodafterbridge1, db.actor:level_vertex_id(), db.actor:game_vertex_id())
			end
		end
	end
end
----------------------------------------------

function spawen_rtut_shars_random()
	local montabl = {
		[clsid.zone_mincer] = true,
		[clsid.zone_mincer_s] = true
	}
	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if montabl[kill:clsid()] then
				local bol_var = math.random(1, 65)
				if bol_var == 1 then
					alife():create("af_mercury_ball", kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id)
					count = count + 1
				end
			end
		end
	end
	--news_manager.send_tip(db.actor,"всего ртутных шаров " .. count .. " нау ииии",nil,"freedom",9000)
end

----------------------------------------------

function spawen_endgame_zombies()
	local montabl = {
		[clsid.respawn] = true
	}

	local sectionsa = {
		"zombie_weak",
		"zombie_normal",
		"zombie_strong",
		"fracture_strong",
		"fracture_midle",
		"zombie_immortal",
	}

	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill and kill.level_name ~= "l05_bar" then
			if montabl[kill:clsid()] then
				local section = sectionsa[math.random(table.getn(sectionsa))]
				local bol_var = math.random(1, 5)
				if bol_var == 1 then
					if game_graph():valid_vertex_id(kill.m_game_vertex_id) then
						local sobj = alife():create(section, kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id)
						amk.on_REspawn(sobj)
						olr.clear_restrictors(sobj)
						if sobj and IsStalker(sobj) then
							table.insert(olr_offline_walk.tabst, sobj)
						end
						count = count + 1
					end
				end
			end
		end
	end
	--news_manager.send_tip(db.actor,"всего новых spawen_endgame_zombies заспавнилось " .. count .. " ",nil,"freedom",9000)
end

----------------------------------------------

function spawen_radhlam_random()
	local montabl = {
		[clsid.zone_radioactive] = true
	}

	local sectionsa = {
		"af_junk_bolt",
		"af_junk_debris",
		"af_magnet"
	}

	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if montabl[kill:clsid()] then
				local section = sectionsa[math.random(table.getn(sectionsa))]
				local bol_var = math.random(1, 60)
				if bol_var == 1 then
					alife():create(section, kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id)
					count = count + 1
				end
			end
		end
	end
	--news_manager.send_tip(db.actor,"всего радиоактивных обломков " .. count .. " нау ииии",nil,"freedom",9000)
end

function spawen_pseudohuman()
	if xvars.blow_count < 7 then
		return
	end

	local montabl = {
		[clsid.zone_radioactive] = true
	}

	local sectionsa = {
		"m_flesh_e",
		"flesh_weak",
		"flesh_normal",
		"flesh_strong",
		"m_pseudohuman_e"
	}

	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill and kill.level_name ~= "l05_bar" then
			if montabl[kill:clsid()] then
				local section = sectionsa[math.random(table.getn(sectionsa))]
				local bol_var = math.random(1, 580)
				if bol_var == 1 then
					alife():create(section, kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id)
					count = count + 1
				end
			end
		end
	end
	--news_manager.send_tip(db.actor,"всего радиоактивных обломков " .. count .. " нау ииии",nil,"freedom",9000)
end

----------------------------------------------

function spawn_esc_mil_group()
	if xvars.blow_count > 5 and xvars.blow_count < 8 then
		olr.spawn_on_obj("esc_military_scienific", "esc_blokpost")
		--olr.spawn_on_obj("esc_military_scienific", "esc_blokpost")
	end
	if xvars.blow_count > 12 and xvars.blow_count < 16 then
		olr.spawn_on_obj("esc_military_scienific", "esc_blokpost")
		--olr.spawn_on_obj("esc_military_scienific", "esc_blokpost")
	end
	if xvars.blow_count > 25 then
		olr.spawn_on_obj("esc_military_scienific", "esc_blokpost")
		--olr.spawn_on_obj("esc_military_scienific", "esc_blokpost")
	end
end

function clear_afterblow_deadnpc()
	if xvars.blow_count > 3 then
		local cnt = 0
		local sim = alife()
		for id = 1, 65534 do
			local kill = sim:object(id)
			if kill and IsStalker(kill) then
				if not kill:alive() then
					if not olr_protected.is_no_offline_alife_obj(kill:name()) then -- удаляем впринципе всех не защищенных, даже если актор их не трогал
						cnt = cnt + 1
						--log1("deadmen "..kill:name().." for del - "..kill.level_name.." ")
						xvars.npc_del_afterblow[kill:name()] = true
					end
				end
			end
		end
	--log1(cnt)
	end
end

----------------------------------------------

function spawen_arts_random()

	local montabl = {
		[clsid.nogravity_zone] = true,
		[clsid.respawn] = true,
		[clsid.smart_terrain] = true,
		[clsid.zone_bfuzz] = true,
		[clsid.zone_bfuzz_s] = true,
		[clsid.zone_galant_s] = true,
		[clsid.zone_galantine] = true,
		[clsid.zone_mbald_s] = true,
		[clsid.zone_mincer] = true,
		[clsid.zone_mincer_s] = true,
		[clsid.zone_mosquito_bald] = true,
		[clsid.zone_rusty_hair] = true
	}

	local sectionsa = {
		"af_bublik",
		"af_bublik_glass",
		"af_gravi_med",
		"af_gravi_heavy",
		"af_zuda",
		"af_transpsphere",
		"af_dummy_double",
		"af_toadeye",
		"af_rusty_hair",
		"af_black_drops",
		"af_knot",
		"af_cotton",
		"af_electrosphere",
		"af_sponge",
		"af_dummy_simple",
		"af_chipper",
		"af_plasm",
		"af_deadhead",
		"af_thorn",
		"af_thorn_black",
		"af_needle",
		"af_needle_heavy",
		"af_junk_bolt",
		"af_junk_debris",
		"af_galantine"
	}

	local count = 0
	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if montabl[kill:clsid()] then
				local section = sectionsa[math.random(table.getn(sectionsa))]
				local bol_var = math.random(1, 180)
				if bol_var == 1 then
					alife():create(section, kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id)
					count = count + 1
				end
			end
		end
	end
	--news_manager.send_tip(db.actor,"всего РАНДОМНЫХ ПОСЛЕВЫБРОСНЫХ АРТОВ " .. count .. " нау ииии",nil,"freedom",9000)
end

----------------------------------------------

function bar_alcos()
	local sim = alife()
	if level.name() == "l05_bar" then
		return
	end

	local bars_alcos = {
		"lvl5_bar_physic_object_1382",
		"lvl5_bar_physic_object_1349",
		"lvl5_bar_physic_object_0446",
		"lvl5_bar_physic_object_1350",
		"lvl5_bar_physic_object_1348",
		"lvl5_bar_physic_object_1380",
		"lvl5_bar_physic_object_0376",
		"lvl5_bar_physic_object_1382",
		"lvl5_bar_physic_object_1381"
	}

	for _, val in ipairs(bars_alcos) do
		local sobj = sim:object(val)
		if sobj then
			local id = sobj.id
			sim:set_switch_offline(id, true)
			sim:set_switch_online(id, false)
			sim:set_interactive(id, false)
		--log1("ofl")
		end
	end

	for _, val in ipairs(bars_alcos) do
		local sobj = sim:object(val)
		if sobj then
			local id = sobj.id
			if math.random(1, 2) == 1 then
				sim:set_switch_offline(id, false)
				sim:set_switch_online(id, true)
				sim:set_interactive(id, true)
			--log1("onl")
			end
		end
	end

	local bars = {
		--"lvl9_military_m_trader",
		"bar_barman",
		"bar_dolg_petrenko"
	}

	for _, val in ipairs(bars) do
		local sobj = sim:object(val)
		if sobj then
			local pk = get_netpk(sobj)
			if pk:isOk() then
				local data = pk:get()
				local sd = data.money
				data.money = sd + math.random(1000, 4500)
				pk:set(data)
			--log1("barman money - "..sd.." --- "..data.money.."")
			end
		end
	end
end

----------------------------------------------
-- Эта залупа по сюжету где будет использоваться, накидывать всякие эффекты что бы ебало трясло нахуй
function blowout_additional_timer()
	--log1("blowout_additional_timer ADD CAM EFFECTOR 2004")
	level.add_cam_effector("camera_effects\\shell_shock.anm", 2004, false, "")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\weather\blowout_wave_1]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr_timers.st_timer("blowout_additional_timer", 10, "olr_blowout.blowout_additional_timer2()")
end

function blowout_additional_timer2()
	--log1("blowout_additional_timer2 ADD CAM EFFECTOR 22002")
	level.add_cam_effector("camera_effects\\earthquake.anm", 22002, true, "")
	--log1("blowout_additional_timer2 ADD PP EFFECTOR 2001")
	level.add_pp_effector("event\\deprecated\\vibros.ppe", 2001, true)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\weather\blowout_hit_2]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr_timers.st_timer("blowout_additional_timer2", 5, "olr_blowout.blowout_additional_timer3()")
end

function blowout_additional_timer3()
	--log1("blowout_additional_timer3 ADD CAM EFFECTOR 32002")
	level.add_cam_effector("camera_effects\\earthquake.anm", 32002, true, "")
	--log1("blowout_additional_timer3 ADD PP EFFECTOR 2001")
	level.add_pp_effector("camera_postprocess\\noise.ppe", 2001, true)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\weather\blowout_hit_3]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr_timers.st_timer("blowout_additional_timer3", 15, "olr_blowout.blowout_additional_timer4()")
end

function blowout_additional_timer4()
	--log1("blowout_additional_timer4 ADD CAM EFFECTOR 42002")
	level.add_cam_effector("camera_effects\\earthquake.anm", 42002, true, "")
	--log1("blowout_additional_timer4 ADD PP EFFECTOR 2001")
	level.add_pp_effector("camera_postprocess\\psy_antenna_indoor.ppe", 2001, true)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\weather\blowout_hit_1]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr_timers.st_timer("blowout_additional_timer4", 5, "olr_blowout.blowout_additional_timer5()")
end

function blowout_additional_timer5()
	--log1("blowout_additional_timer5 ADD CAM EFFECTOR 52002")
	level.add_cam_effector("camera_effects\\earthquake.anm", 52002, true, "")
	--log1("blowout_additional_timer5 ADD PP EFFECTOR 2001")
	level.add_pp_effector("camera_postprocess\\blink.ppe", 2001, true)
	--log1("blowout_additional_timer5 ADD PP EFFECTOR 2003")
	level.add_pp_effector("event\\deprecated\\monolith_off.ppe", 2003, false)
	--log1("blowout_additional_timer5 ADD PP EFFECTOR 2001")
	level.add_pp_effector("camera_postprocess\\psy_antenna_indoor.ppe", 2001, true)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\weather\blowout_wave_3]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr_timers.st_timer("blowout_additional_timer5", 10, "olr_blowout.blowout_additional_timer6()")
end

function blowout_additional_timer6()
	--log1("blowout_additional_timer6 REMOVE CAM EFFECTOR 12002")
	level.remove_cam_effector(12002)
	--log1("blowout_additional_timer6 REMOVE CAM EFFECTOR 22002")
	level.remove_cam_effector(22002)
	--log1("blowout_additional_timer6 REMOVE CAM EFFECTOR 32002")
	level.remove_cam_effector(32002)
	--log1("blowout_additional_timer6 REMOVE CAM EFFECTOR 42002")
	level.remove_cam_effector(42002)
	--log1("blowout_additional_timer6 REMOVE CAM EFFECTOR 52002")
	level.remove_cam_effector(52002)
	--log1("blowout_additional_timer6 REMOVE PP EFFECTOR 2001")
	level.remove_pp_effector(2001)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\weather\cold_wind]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end
----------------------------------------------
-- Надо тоже убрать это всё, у нас другой таймер и по другому надо добавлять время до выброса
function get_blow_timer()
	return xvars.blowout_timer
end

function set_blow_timer(val)
	xvars.blowout_timer = val
end

function add_blow_timer(a)
	xvars.blowout_timer = xvars.blowout_timer + a
end

function min_blow_timer(a)
	xvars.blowout_timer = xvars.blowout_timer - a
end