-- hi_flyer 21.01.16

local walk_on = true
local loadedsim = false
tabst = {}

local montabl = {
	[clsid.zombie_s] = true,
	[clsid.zombie] = true,
	[clsid.dog_s] = true,
	[clsid.boar_s] = true,
	[clsid.boar] = true,
	[clsid.burer_s] = true,
	[clsid.controller_s] = true,
	[clsid.bloodsucker_s] = true,
	[clsid.controller] = true,
	[clsid.controller_s] = true,
	[clsid.pseudodog_s] = true,
	[clsid.script_stalker] = true
}

function update(delta)
	if db.actor then
		if loadedsim == false and walk_on == true then
			if not has_alife_info("delll_maniken_gg") then return end
			--news_manager.send_tip(db.actor, game.translate_string("update_0"), nil, "freedom", 59000)
			local sim = alife()
			for id = 1, 65534 do
				local kill = sim:object(id)
				if kill then
					if montabl[kill:clsid()] then
						if kill and kill ~= nil and not kill.online and kill.m_game_vertex_id and game_graph():valid_vertex_id(kill.m_game_vertex_id) and kill.health and kill:alive() then
							local strn_id = kill:smart_terrain_id()
							if strn_id ~= 65535 then
								if sim:object(kill.id).level_name ~= level.name() then
									--olr.add_spot_on_map( kill.id,"green_location", kill:name() )
									table.insert(tabst, kill)
									loadedsim = true
								end
							end
						end
					end
				end
			end
			--log1("offline walkers - ["..#tabst.."]")
		end
	end
end