-- hi_flyer 28.04.18
-- рандомные военные сталкеры

local first_tab = {
	[1] = {name = "wpn_val", ammo = "ammo_9x39_ap"},
	[2] = {name = "wpn_vintorez", ammo = "ammo_9x39_ap"},
	[3] = {name = "wpn_fn2000", ammo = "ammo_5.56x45_ap"},
	[4] = {name = "wpn_g36", ammo = "ammo_5.56x45_ap"},
	[5] = {name = "wpn_groza", ammo = "ammo_9x39_ap"}
}

local name = {
	"st_olr_voenstals_name_1",
	"st_olr_voenstals_name_2",
	"st_olr_voenstals_name_3",
	"st_olr_voenstals_name_4",
	"st_olr_voenstals_name_5"
}

function create_mil_stk()
	if xvars.blow_count < 4 then
		return
	end

	local sim = alife()
	for id = 1, 65534 do
		local kill = sim:object(id)
		if kill then
			if kill:clsid() == clsid.respawn and kill.level_name ~= "lvl5_bar" then
				local bol_var = math.random(1, 55)
				if bol_var == 1 then
					if game_graph():valid_vertex_id(kill.m_game_vertex_id) then
						local sobj = alife():create("sim_voenstal_num", kill.position, kill.m_level_vertex_id, kill.m_game_vertex_id )
						--olr.add_spot_on_map( sobj.id,"red_location",sobj:name() )
						--log1("spawn voenstal")
						olr.clear_restrictors(sobj)
						if sobj and IsStalker(sobj) then
							olr_offline_walk.tabst[#olr_offline_walk.tabst + 1] = sobj
							--olr_ai_tasks.on_spawn_npc(obj)
							set_params(sobj)
						end
					end
				end
			end
		end
	end
end

function set_params(sobj)
	local mrandom = math.random
	local number = tostring(mrandom(1, 20))
	local pk = get_netpk(sobj, 1)
	if pk:isOk() then
		local data = pk:get()
		data.character_name = ""..game.translate_string(name[mrandom(#name)]).." "..number..""
		pk:set(data)
	end
	sobj:set_rank(sobj:rank() + mrandom(5, 500))
end