-- hi_flyer 09/02/16 

function proceed()
	local actor = db.actor


	if has_alife_info("jrets_dead_1") and has_alife_info("jrets_dead_2") and has_alife_info("jrets_dead_3") and not has_alife_info("jrets_dead_all") then
		actor:give_info_portion("jrets_dead_all")
		news_manager.send_tip(db.actor, game.translate_string("proceed_0"), 3, "hero", 30000)
		olr_timers.st_timer("osved_bar_band_kill", 14, "nick.osved_bar_band_kill()")		
	end


	if has_alife_info("kill_bar_portoshitely_dead_1") and has_alife_info("kill_bar_portoshitely_dead_2") and has_alife_info("kill_bar_portoshitely_dead_3") and not has_alife_info("kill_bar_portoshitely_dead_all") then
		actor:give_info_portion("kill_bar_portoshitely_dead_all")
		news_manager.send_tip(db.actor, game.translate_string("proceed_1"), 3, "hero", 30000, nil, nil, true, xr_effects.get_real_actor_name())
		news_manager.send_tip(db.actor, game.translate_string("proceed_2"), 7, "flash", 30000, nil, nil, true, "st_bar_bar_osvedomitel_name")
		olr_timers.st_timer("osved_bar_band_kill", 214, "nick.osved_dolina_band_kill()")		
	end


	if	not has_alife_info("bar_under_prison_doc_have") and
		actor:object("bar_under_prison_doc") ~= nil 
	then		
		actor:give_info_portion("bar_under_prison_doc_have")
	end 



	if	not has_alife_info("bar_1_have") and
		actor:object("olr_doc_lab_1") ~= nil 
	then		
		actor:give_info_portion("bar_1_have")
	end 


	if	not has_alife_info("dnevnik_strelka_have") and
		actor:object("dnevnik_strelka") ~= nil 
	then		
		actor:give_info_portion("dnevnik_strelka_have")
	end 


	if	not has_alife_info("ros_pda_hmir_finded") and
		actor:object("pda_hmir_rostok") ~= nil 
	then		
		actor:give_info_portion("ros_pda_hmir_finded")
		olr.hud_tip("", game.translate_string("proceed_3"), 15)
		news_manager.send_tip(db.actor, game.translate_string("proceed_4"), 1, "info", 30000)
		local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\scenario\rostok\agent\hmiry_pda_message]])
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end 

	if	not has_alife_info("has_all_mil_eqs") and
		has_alife_info("mil_eqsped_one") and has_alife_info("mil_eqsped_two") and has_alife_info("mil_eqsped_tri")
	then		
		actor:give_info_portion("has_all_mil_eqs")
		olr_timers.st_timer("has_all_mil", 4, "nick.has_all_mil_sms()")
	end 


	if has_alife_info("gen_bunker_destr_1") and has_alife_info("gen_bunker_destr_2") and has_alife_info("gen_bunker_destr_3") and has_alife_info("gen_bunker_destr_4") and not has_alife_info("gen_bunker_destr_alls") then
		actor:give_info_portion("gen_bunker_destr_alls")
		news_manager.send_tip(db.actor, game.translate_string("proceed_6"), 1, "hero", 30000)	
	end

	if	not has_alife_info("on_lab_swithc_dok_fin_done_del_door") and
		has_alife_info("on_lab_swithc_dok_1_done") and has_alife_info("on_lab_swithc_dok_2_done") and has_alife_info("on_lab_swithc_dok_3_done") and has_alife_info("on_lab_swithc_dok_4_done")
	then		
		actor:give_info_portion("on_lab_swithc_dok_fin_done_del_door")
	end 

	if	not has_alife_info("dedast_docs_brain_info") and
		actor:object("dedast_docs_brain") ~= nil 
	then		
		actor:give_info_portion("dedast_docs_brain_info")
		local obj = actor:object("dedast_docs_brain")
		olr.del(obj)
	end 

	if	not has_alife_info("greh_leader_key_taken_docs_vetri") and
		actor:object("vetri_bezumia_doki") ~= nil 
	then		
		actor:give_info_portion("greh_leader_key_taken_docs_vetri")
	end 

	if	not has_alife_info("greh_leader_key_info") and
		actor:object("greh_leader_key") ~= nil 
	then		
		actor:give_info_portion("greh_leader_key_info")
	end 

	if	not has_alife_info("goplit_pda_dolina_info") and
		actor:object("goplit_pda_dolina") ~= nil 
	then		
		actor:give_info_portion("goplit_pda_dolina_info")
	end 

	if	not has_alife_info("mg_zombie_dnevnik_dead_info") and
		actor:object("mg_zombie_dnevnik_dead") ~= nil 
	then		
		actor:give_info_portion("mg_zombie_dnevnik_dead_info")
	end 

	if	not has_alife_info("lithium_profff") and
		actor:object("device_pda_lab_one") ~= nil 
	then		
		actor:give_info_portion("lithium_profff")
	end 
	
	--if	not has_alife_info("nifa_7") and
	--	actor:object("olr_strelok_fleshka") ~= nil 
	--then		
	--	actor:give_info_portion("nifa_7")
	--end 

	if	not has_alife_info("garb_miliraty_docs_pors") and
		actor:object("garb_miliraty_docs") ~= nil 
	then		
		actor:give_info_portion("garb_miliraty_docs_pors")
	end 


	if	not has_alife_info("start_kill_gen_link") and
		actor:object("gen_dnev_doki") ~= nil 
	then		
		actor:give_info_portion("start_kill_gen_link")
	end 


	if	not has_alife_info("dolina_barman_house_doki_info") and
		actor:object("dolina_barman_house_doki") ~= nil and actor:object("dolina_barman_house_doki_additional") ~= nil
	then		
		actor:give_info_portion("dolina_barman_house_doki_info")
	end 

	if	not has_alife_info("find_journalist_final_done_info") and
		actor:object("jurn_doki_cely_osoznania") ~= nil and actor:object("jurn_doki_controlory") ~= nil and actor:object("jurn_doki_last_zapiska") ~= nil
	then		
		actor:give_info_portion("find_journalist_final_done_info")
	end 

	if	not has_alife_info("jornal_1_taken") and
		actor:object("jornal_1") ~= nil
	then		
		actor:give_info_portion("spawn_doks_gar")
		actor:give_info_portion("jornal_1_taken")
	end 

	if	not has_alife_info("jornal_3_taken") and
		actor:object("jornal_3") ~= nil
	then
		actor:give_info_portion("jornal_3_taken")		
		actor:give_info_portion("spawn_doks_gar")
	end 

	if	not has_alife_info("spawn_doks_holmy") and
		actor:object("jornal_2") ~= nil 
	then		
		actor:give_info_portion("spawn_doks_holmy")
		actor:give_info_portion("jornal_2_taken")
	end 

	if	not has_alife_info("spawn_doks_yantar") and
		actor:object("jornal_4") ~= nil 
	then		
		actor:give_info_portion("spawn_doks_yantar")
	end 

	if	not has_alife_info("spawn_doks_radar") and
		actor:object("jornal_5") ~= nil 
	then		
		actor:give_info_portion("spawn_doks_radar")
	end 

	if	not has_alife_info("jornal_6_taken") and
		actor:object("jornal_6") ~= nil 
	then		
		actor:give_info_portion("jornal_6_taken")
		olr.del_by_name("lvl13_prip_physic_object_0006")
	end 

	if	not has_alife_info("spawn_jourlalist") and
		actor:object("jornal_7") ~= nil 
	then		
		actor:give_info_portion("spawn_jourlalist")
		olr.del_by_name("lvl13_prip_space_restrictor_0005")
	end
	-- Не сюжетные документы в память ПДА
	if	not has_alife_info("bar_journalist_dnevnik_taken") and
		actor:object("bar_journalist_dnevnik") ~= nil
	then		
		actor:give_info_portion("bar_journalist_dnevnik_taken")
	end 

	if	not has_alife_info("bar_barman_kamaz_doki_taken") and
		actor:object("bar_barman_kamaz_doki") ~= nil
	then		
		actor:give_info_portion("bar_barman_kamaz_doki_taken")
	end

	if	not has_alife_info("gazeta_otrivok_1_taken") and
		actor:object("gazeta_otrivok_1") ~= nil
	then		
		actor:give_info_portion("gazeta_otrivok_1_taken")
	end

	if not has_alife_info("doki_agro_dyatel_taken") and actor:object("doki_agro_dyatel") ~= nil then
    	actor:give_info_portion("doki_agro_dyatel_taken")
	end

	if not has_alife_info("gar_postroika_dnevnik_taken") and actor:object("gar_postroika_dnevnik") ~= nil then
		actor:give_info_portion("gar_postroika_dnevnik_taken")
	end

	if not has_alife_info("zombied_pda_dezintegr_taken") and actor:object("zombied_pda_dezintegr") ~= nil then
		actor:give_info_portion("zombied_pda_dezintegr_taken")
	end

	if not has_alife_info("zap_killera_jurn_zap_taken") and actor:object("zap_killera_jurn_zap") ~= nil then
		actor:give_info_portion("zap_killera_jurn_zap_taken")
	end

	if not has_alife_info("ros_seif_zap_1_taken") and actor:object("ros_seif_zap_1") ~= nil then
		actor:give_info_portion("ros_seif_zap_1_taken")
	end

	if not has_alife_info("ros_seif_zap_2_taken") and actor:object("ros_seif_zap_2") ~= nil then
		actor:give_info_portion("ros_seif_zap_2_taken")
	end

	if not has_alife_info("ros_korpus_pass_taken") and actor:object("ros_korpus_pass") ~= nil then
		actor:give_info_portion("ros_korpus_pass_taken")
	end

	if not has_alife_info("city_fake_dnevnik_taken") and actor:object("city_fake_dnevnik") ~= nil then
		actor:give_info_portion("city_fake_dnevnik_taken")
	end

	if not has_alife_info("jurn_plen_mesage_taken") and actor:object("jurn_plen_mesage") ~= nil then
		actor:give_info_portion("jurn_plen_mesage_taken")
	end

	if not has_alife_info("device_pda_last_day_taken") and actor:object("device_pda_last_day") ~= nil then
		actor:give_info_portion("device_pda_last_day_taken")
	end

	if not has_alife_info("killers_deadscient_doc_taken") and actor:object("killers_deadscient_doc") ~= nil then
		actor:give_info_portion("killers_deadscient_doc_taken")
	end

	if not has_alife_info("mg_monolitovec_doki_taken") and actor:object("mg_monolitovec_doki") ~= nil then
		actor:give_info_portion("mg_monolitovec_doki_taken")
	end

	if not has_alife_info("mg_zombie_dnevnik_dead_taken") and actor:object("mg_zombie_dnevnik_dead") ~= nil then
		actor:give_info_portion("mg_zombie_dnevnik_dead_taken")
	end

	if not has_alife_info("yantar_mozg_doki_taken") and actor:object("yantar_mozg_doki") ~= nil then
		actor:give_info_portion("yantar_mozg_doki_taken")
	end

	if not has_alife_info("dolina_prelaba_doki_taken") and actor:object("dolina_prelaba_doki") ~= nil then
		actor:give_info_portion("dolina_prelaba_doki_taken")
	end

	if not has_alife_info("radar_kompleks_doki_taken") and actor:object("radar_kompleks_doki") ~= nil then
		actor:give_info_portion("radar_kompleks_doki_taken")
	end

	if not has_alife_info("esc_vishka_dnevnik_taken") and actor:object("esc_vishka_dnevnik") ~= nil then
		actor:give_info_portion("esc_vishka_dnevnik_taken")
	end

	if not has_alife_info("pda_ecol_dolina_taken") and actor:object("pda_ecol_dolina") ~= nil then
		actor:give_info_portion("pda_ecol_dolina_taken")
	end

	if not has_alife_info("device_pda_jan_one_taken") and actor:object("device_pda_jan_one") ~= nil then
		actor:give_info_portion("device_pda_jan_one_taken")
	end

	if not has_alife_info("device_pda_jan_two_taken") and actor:object("device_pda_jan_two") ~= nil then
		actor:give_info_portion("device_pda_jan_two_taken")
	end

	if not has_alife_info("device_pda_jan_tri_taken") and actor:object("device_pda_jan_tri") ~= nil then
		actor:give_info_portion("device_pda_jan_tri_taken")
	end
	
	if	not has_alife_info("ln9_karta_pc_have") and
		actor:object("radbun_karta_pc") ~= nil 
	then		
		actor:give_info_portion("ln9_karta_pc_have")
	end 
	
	if	not has_alife_info("lab_code_have") and
		actor:object("device_pda_lab_two") ~= nil 
	then		
		actor:give_info_portion("lab_code_have")
	end 
end



function process_info_portion(info_id)
end
