-- hi_flyer	 28/05/15

count = xvars.kill_count

function del_count_kills()
	xvars.kill_count = 0
end

function kill_neutral(victim, who)
	if who:id() == db.actor:id() then
		if victim:name() == "lvl5_bar_stalker_0038" then
			return
		end
		if victim:name() == "lvl3_agroprom_stalker_0045" then
			return
		end
		if victim:name() == "lvl13_prip_stalker_0089" then
			return
		end
		if victim:name() == "lvl1_escape_stalker_0038" then
			return
		end
		if victim:name() == "lvl9_military_stalker_0012" then
			return
		end
		if victim:name() == "lvl9_military_stalker_0013" then
			return
		end
		if victim:name() == "lvl9_military_stalker_0014" then
			return
		end
		if victim:name() == "lvl11_deadcity_stalker_0048" then
			return
		end
		if victim:name() == "lvl9_military_stalker_0053" then
			return
		end
		if victim:name() == "lvl9_military_stalker_0054" then
			return
		end
		if victim:name() == "lvl9_military_stalker_0055" then
			return
		end
		if victim:name() == "lvl8_swamp_stalker_0020" then
			return
		end
		local sobj = game.translate_string(xvars.quest_two_target)
		if sobj and sobj == game.translate_string(victim:name()) then
			return
		end
		local sobj2 = game.translate_string(xvars.quest_two_target_bar)
		if sobj2 and sobj2 == game.translate_string(victim:name()) then
			return
		end

		if has_alife_info("prp_first") then
			return
		end
	end
	this.kill_neutral11(victim, who)
	this.kill_neutral22(victim, who)
end

function kill_neutral11(victim, who)
	if who:id() == db.actor:id() then
		if victim:name() == xvars.quest_two_target_bar or victim:name() == xvars.quest_two_target then
			--log1("наш клиент")
			return
		end
		if not has_alife_info("monolit_na_kordone") then
			local community = victim:character_community()
			if community == "stalker" or community == "dolg" or community == "freedom" and community ~= "sin" then
				if not has_alife_info("messer_killar_pre") then
					if not olr_timers.has_timer("first_killer_timer") then
						for k, v in pairs(db.storage) do
							local stalker = level.object_by_id(k)
							if stalker and stalker:is_stalker() and stalker:alive() then
								if stalker:see_right_now(db.actor) then
									--log1("see how kill 1")
									olr_timers.st_timer("first_killer_timer_sms", 900, "olr_killer.first_killer_timer_seen("..tostring(victim:id())..")")
									--log1(""..tostring(victim:character_name()).."")
									olr_timers.st_timer("first_killer_timer", 790, "olr_killer.first_killer_timer()")
									olr.info("just_kill_the_man")
									xvars.kill_count = 1000
								end
							end
						end
					end
				end
			end
		end
	end
end

function kill_neutral22(victim, who)
	if who:id() == db.actor:id() then
		if victim:name() == xvars.quest_two_target_bar or victim:name() == xvars.quest_two_target then
			--log1("наш клиент")
			return
		end
		local community = victim:character_community()
		if community == "stalker" or community == "dolg" or community == "freedom" and community ~= "sin" then
			if has_alife_info("messer_killar_washe") then
				count = count + math.random(550, 1000)
				xvars.kill_count = count
				db.actor:change_character_reputation(-500)
				--news_manager.send_tip(db.actor, " Ћ”Ќ“ "..count.." сейчас.", nil, "dolg", 6000)
			end
		end
	end
end

----------------------------------------------------------------------------------------------------------------------------------

function first_killer_timer()
	if not has_alife_info("messer_killar_pre") then
		db.actor:give_info_portion("messer_killar_pre")
		db.actor:change_character_reputation(-100)
	end 
end

function first_killer_timer_seen(id)
	olr.info("messer_killar_washe")
	db.actor:change_character_reputation(-400)
	local sobj = alife():object(id)
	if sobj then
		local pk = get_netpk(sobj,1)
		if pk:isOk() then
			local data = pk:get()
			local name = data.character_name
			local pos = news_main.get_point_description(alife():level_name(game_graph():vertex(sobj.m_game_vertex_id):level_id()), vector():set(sobj.position.x,sobj.position.y,sobj.position.z))
				news_manager.send_tip(db.actor, game.translate_string("first_killer_timer_seen_0") .." "..name.. game.translate_string("first_killer_timer_seen_1") ..pos.." ".. game.translate_string("first_killer_timer_seen_2"), nil, "unknown", 39000)
		end
	end	
end

----------------------------------------------------------------------------------------------------------------------------------

function trader_check_oplata(trader, actor)
	local k_oplate_cost = xvars.kill_count
	if k_oplate_cost > 0 and db.actor:money() >= k_oplate_cost then
		return true
	end
	return false
end

function trader_oplata_sama(trader, actor)
	local k_oplat = math.floor(count)
	dialogs.relocate_money(actor, k_oplat, "out")
	xvars.kill_count = 0
end

function rasplata_costs(first_speaker, second_speaker)
	local task_texture, task_rect = get_texture_info("ui_notification_kill_stalker")

	local rasplata_costs_price = ""
	local rasplata_costs_cost = 0
	if db.actor ~= nil then
		local rasplata_costsp = count
		if rasplata_costsp ~= nil then
			rasplata_costs_cost = count
			if rasplata_costs_cost > 0 then
				rasplata_costs_price = game.translate_string("babosy_platit").." %c[255,238,155,23]"..rasplata_costs_cost.."$%c[default]"
				db.actor:give_talk_message(rasplata_costs_price, task_texture, task_rect, "iconed_trade_info")
			end
		end
	end
end