-- hi_flyer 22.02.16
-- ранодомные стволы и визуалы для новых сталкеров в зоне

local first_tab = {
	 
		 [1] = {name = "wpn_pm",                ammo = "ammo_9x18_pmm", prb = 0.5},
		 [2] = {name = "wpn_fort",       	ammo = "ammo_9x18_pmm", prb = 0.5},
		 [3] = {name = "wpn_pb", 	   	ammo = "ammo_9x18_pmm", prb = 0.5},
		 [4] = {name = "wpn_sig220", 		   ammo = "ammo_11.43x23_hydro", prb = 0.4},
		 [5] = {name = "wpn_hpsa", 		   ammo = "ammo_9x19_pbp", prb = 0.4},
		 [6] = {name = "wpn_walther", 		   ammo = "ammo_9x19_pbp", prb = 0.5}

		}

local second_tab = {
	 
		 [1] = {name = "wpn_lr300",                ammo = "ammo_5.56x45_ap", prb = 0.5},
		 [2] = {name = "wpn_mp5", 		   ammo = "ammo_5.56x45_ap", prb = 0.5},
		 [3] = {name = "wpn_ak74", 	   ammo = "ammo_5.45x39_ap", prb = 0.5},
		 [4] = {name = "wpn_groza", 	   ammo = "ammo_9x39_ap", prb = 0.3},
		 [5] = {name = "wpn_wincheaster1300", 	   ammo = "ammo_12x76_dart", prb = 0.4},
		 [6] = {name = "wpn_toz34", 	   	ammo = "ammo_12x76_dart", prb = 0.5},
		 [7] = {name = "wpn_svd", 	   	ammo = "ammo_7.62x54_7h14", prb = 0.2},
		 [8] = {name = "wpn_svu", 	   	ammo = "ammo_7.62x54_7h14", prb = 0.2},
		 [9] = {name = "wpn_val", 	   	ammo = "ammo_9x39_ap", prb = 0.2},
		 [10] = {name = "wpn_vintorez", 	   	ammo = "ammo_9x39_ap", prb = 0.1},
		 [11] = {name = "wpn_fn2000", 	   	ammo = "ammo_5.56x45_ap", prb = 0.15},
		 [12] = {name = "wpn_g36", 	   	ammo = "ammo_5.56x45_ap", prb = 0.15},
		 [13] = {name = "wpn_groza", 	   	ammo = "ammo_9x39_ap", prb = 0.15}

		}

local mil_tab = {
	 
		 [1] = {name = "wpn_ak74", 	   	ammo = "ammo_5.45x39_ap"},
		 [2] = {name = "wpn_groza", 	   	ammo = "ammo_9x39_ap"},

}

local eco_tab = {
	 
		 [1] = {name = "wpn_fn2000", 	   	ammo = "ammo_5.56x45_ap"},
		 [2] = {name = "wpn_g36", 	   	ammo = "ammo_5.56x45_ap"},
		 [3] = {name = "wpn_groza", 	   	ammo = "ammo_9x39_ap"}
}


local visuals_bandits = {
		[[actors\bandit\bandit_antigas]],
		[[actors\bandit\bandit_coat_01]],
		[[actors\bandit\bandit_coat_02]],
		[[actors\bandit\bandit_hood_01]],
		[[actors\bandit\bandit_hood_02]],
		[[actors\bandit\bandit_hood_03]],
		[[actors\bandit\bandit_hood_04]],
		[[actors\bandit\bandit_hood_05]],
		[[actors\bandit\bandit_hood_06]]
}

local visuals_novice = {
		[[actors\novice\novice_b_01]],
		[[actors\novice\novice_b_02]],
		[[actors\novice\novice_b_03]],
		[[actors\novice\novice_b_04]],
		[[actors\novice\novice_b_mask]],
		[[actors\novice\novice_w_01]],
		[[actors\novice\novice_w_02]],
		[[actors\novice\novice_w_03]],
		[[actors\novice\novice_w_04]],
		[[actors\novice\novice_w_mask]]
}


local visuals_neytral = {
		[[actors\neutral\stalker_exo]],
		[[actors\neutral\stalker_hood_backpack_01]],
		[[actors\neutral\stalker_hood_backpack_02]],
		[[actors\neutral\stalker_hood_backpack_03]],
		[[actors\neutral\stalker_hood_backpack_04]],
		[[actors\neutral\stalker_hood_backpack_05]],
		[[actors\neutral\stalker_hood_backpack_06]],
		[[actors\neutral\stalker_hood_backpack_antigas]],
		[[actors\neutral\stalker_hood_backpack_mask]],
		[[actors\neutral\stalker_hood_balon_01]],
		[[actors\neutral\stalker_hood_balon_02]],
		[[actors\neutral\stalker_hood_balon_03]],
		[[actors\neutral\stalker_hood_balon_04]],
		[[actors\neutral\stalker_hood_balon_05]],
		[[actors\neutral\stalker_hood_balon_06]],
		[[actors\neutral\stalker_hood_balon_07]],
		[[actors\neutral\stalker_hood_balon_antigas]],
		[[actors\neutral\stalker_no_hood_backpack_01]],
		[[actors\neutral\stalker_no_hood_backpack_02]],
		[[actors\neutral\stalker_no_hood_backpack_03]],
		[[actors\neutral\stalker_no_hood_backpack_04]],
		[[actors\neutral\stalker_no_hood_balon_01]],
		[[actors\neutral\stalker_no_hood_balon_02]],
		[[actors\neutral\stalker_no_hood_balon_03]],
		[[actors\neutral\stalker_no_hood_balon_04]],
		[[actors\neutral\stalker_no_hood_backpack_mask]],
		[[actors\neutral\stalker_protected]]
}


function on_spawn(obj)

	if not obj then return end

	if obj:community()=="military" then
		--news_manager.send_tip(db.actor, " se_respawn MILITARY ["..obj:name().."] on level ["..obj.level_name.."] ", nil, "zombied", 5000)
		--olr.add_spot_on_map( obj.id,"red_location",obj:name() )
		local frndpos = math.random(#mil_tab) or 1
		alife():create(tostring(mil_tab[frndpos].name), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
		se_respawn.create_ammo(tostring(mil_tab[frndpos].ammo), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id, 10)
		return
	end

	if obj:community()=="ecolog" then
		--news_manager.send_tip(db.actor, " se_respawn ecolog ["..obj:name().."] on level ["..obj.level_name.."] ", nil, "zombied", 5000)
		--olr.add_spot_on_map( obj.id,"red_location",obj:name() )
		local frndpos = math.random(#eco_tab) or 1
		alife():create(tostring(eco_tab[frndpos].name), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
		se_respawn.create_ammo(tostring(eco_tab[frndpos].ammo), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id, 10)
		return
	end

	local frndpos = math.random(#first_tab) or 1
	local rndpos = math.random(#second_tab) or 1
	
	if math.random() < second_tab[rndpos].prb then
		--log1("по рандому заспавнился ствол "..second_tab[rndpos].name.."") 
		alife():create(tostring(second_tab[rndpos].name), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
		se_respawn.create_ammo(tostring(second_tab[rndpos].ammo), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id, 10)
	end

	if math.random() < first_tab[frndpos].prb then
		--log1("по рандому заспавнился ствол "..first_tab[frndpos].name.."") 
		alife():create(tostring(first_tab[frndpos].name), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
		se_respawn.create_ammo(tostring(first_tab[frndpos].ammo), obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id, 10)
	end

	if obj:community()=="bandit" then
		--news_manager.send_tip(db.actor, " se_respawn BANDIT ["..obj:name().."] on level ["..obj.level_name.."] wpn - ["..first_tab[frndpos].name.."] wpn2 - ["..second_tab[rndpos].name.."] ", nil, "zombied", 5000)
		--olr.add_spot_on_map( obj.id,"red_location",obj:name() )
		local pk = get_netpk(obj,1)
  		if pk and pk:isOk() then
    			local data = pk:get()
    			data.visual_name = visuals_bandits[math.random(#visuals_bandits)]
          		data.character_name = game.translate_string("neizvestnyy_bandits")
      			pk:set(data)
		end
	end

	if obj:community()=="stalker" then
		--news_manager.send_tip(db.actor, " se_respawn stalker ["..obj:name().."] on level ["..obj.level_name.."] wpn - ["..first_tab[frndpos].name.."] wpn2 - ["..second_tab[rndpos].name.."] ", nil, "zombied", 5000)
		--olr.add_spot_on_map( obj.id,"red_location",obj:name() )
		local num = obj:rank()
		if num >= 0 and num <= 300 then
			--log1("stalker rank NOVICE "..obj:rank().."")
			set_novice_vis(obj)
		elseif num > 300 and num <= 600 then
			--log1("stalker rank OPYTNIY "..obj:rank().."")
			set_novice_vis(obj)
		elseif num > 600 and num <= 900 then
			--log1("stalker rank VETERAN "..obj:rank().."")
			set_veteran_vis(obj)
		elseif num > 900 then
			--log1("stalker rank MASTER "..obj:rank().."")
			set_veteran_vis(obj)
		end
	end

end


function set_novice_vis(obj)
	local pk = get_netpk(obj,1)
  	if pk and pk:isOk() then
    		local data = pk:get()
		local rndmoney = math.random(205,743)
		data.money = rndmoney
    		data.visual_name = visuals_novice[math.random(#visuals_novice)]
      		pk:set(data)
	end	
end

function set_veteran_vis(obj)
	local pk = get_netpk(obj,1)
  	if pk:isOk() then
    		local data = pk:get()
		local rndmoney = math.random(905,2743)
		data.money = rndmoney
    		data.visual_name = visuals_neytral[math.random(#visuals_neytral)]
      		pk:set(data)
	end	
end


















