function plus_reputation(stalker, player) 
db.actor:change_character_reputation(10) 
end

function mh_drunk()
vodka_spawn()
mh_drink_vodka()
end

function vodka_spawn(first_speaker, second_speaker)
dialogs.relocate_item_section(second_speaker, "vodka", "in")
end

function mh_drink_vodka() 
local item = db.actor:object("vodka") 
if item then 
db.actor:eat(item) 
end 
end 

function reward_for_dyatel_off(first_speaker, second_speaker)
    dialogs.relocate_money(first_speaker, 1000, "in") 
    	local bol_var = math.random(1,3)
	if bol_var == 1 then
    		dialogs.relocate_item_section(second_speaker, "wpn_g36","in")
	end
end

function actor_has_100_money(first_speaker, second_speaker) 
   return first_speaker:money() >= 100 
end

--function sto_money_from_gg_to_npc(actor, npc)
--   dialogs.relocate_money(npc, 100, "out")
--end


function sto_money_from_gg_to_npc(t1,t2)
local npc=t1
if npc:id()==db.actor:id() then
npc=t2
end
dialogs.relocate_money(npc,100,"out")
end


function actor_has_bred(first_speaker, second_speaker) 
   return nik_dialog.item_much("bread",1) ~= false 
end
function actor_has_kolbasa(first_speaker, second_speaker) 
   return nik_dialog.item_much("kolbasa",1) ~= false 
end 
function actor_has_conserva(first_speaker, second_speaker) 
   return nik_dialog.item_much("conserva",1) ~= false 
end


function give_bred_to_npc(first_speaker, second_speaker) 
   nik_dialog.out_item_much("bread",1) 
end 
function give_kolbasa_to_npc(first_speaker, second_speaker) 
   nik_dialog.out_item_much("kolbasa",1)
end 
function give_conserva_to_npc(first_speaker, second_speaker) 
   nik_dialog.out_item_much("conserva",1) 
end 

function medic_help()
  if db.actor then
     db.actor.health = db.actor.health + 1
  end
end

function actor_isnt_health()
 if db.actor.health <= 0.95 then
 return true
 end
return false
end

function actor_is_health()
 if db.actor.health > 0.95 then
 return true
end
return false
end

function mh_has_capsule(first_speaker, second_speaker) 
	return first_speaker:object("energy_drink") ~= nil 
end

function has_any_af_for_professor(first_speaker, second_speaker)
	return has_101(first_speaker, second_speaker) or has_102(first_speaker, second_speaker)
	or has_103(first_speaker, second_speaker) or has_104(first_speaker, second_speaker)
	or has_105(first_speaker, second_speaker) or has_106(first_speaker, second_speaker)
	or has_107(first_speaker, second_speaker) or has_108(first_speaker, second_speaker)
	or has_109(first_speaker, second_speaker) or has_110(first_speaker, second_speaker)
	or has_111(first_speaker, second_speaker)
end

function has_101(first_speaker, second_speaker)
	return first_speaker:object("af_magnet") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-magnet")
end 
function has_102(first_speaker, second_speaker) 
	return first_speaker:object("af_gravi_heavy") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-gravi-heavy")
end 
function has_103(first_speaker, second_speaker) 
	return first_speaker:object("af_dummy_double") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-dummy-double")
end 
function has_104(first_speaker, second_speaker) 
	return first_speaker:object("af_black_drops") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-black-drops") 
end 
function has_105(first_speaker, second_speaker) 
	return first_speaker:object("af_electrosphere") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-electrosphere")
end 
function has_106(first_speaker, second_speaker) 
	return first_speaker:object("af_mercury_ball") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-mercury-ball")
end 
function has_107(first_speaker, second_speaker) 
	return first_speaker:object("af_sponge") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-sponge")
end 
function has_108(first_speaker, second_speaker) 
	return first_speaker:object("af_dummy_simple") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-dummy-simple")
end 
function has_109(first_speaker, second_speaker) 
	return first_speaker:object("af_deadhead") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-deadhead")
end 
function has_110(first_speaker, second_speaker) 
	return first_speaker:object("af_needle") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-needle")
end 
function has_111(first_speaker, second_speaker) 
	return first_speaker:object("af_needle_heavy") ~= nil and has_alife_info("encyclopedy_zone_artifact_af-needle-heavy")
end 

function give_101()
nik_dialog.out_item_much("af_magnet",1)
end

function give_102()
nik_dialog.out_item_much("af_gravi_heavy",1)
end

function give_103()
nik_dialog.out_item_much("af_dummy_double",1)
end

function give_104()
nik_dialog.out_item_much("af_black_drops",1)
end

function give_105()
nik_dialog.out_item_much("af_electrosphere",1)
end

function give_106()
nik_dialog.out_item_much("af_mercury_ball",1)
end

function give_107()
nik_dialog.out_item_much("af_sponge",1)
end

function give_108()
nik_dialog.out_item_much("af_dummy_simple",1)
end

function give_109()
nik_dialog.out_item_much("af_deadhead",1)
end

function give_110()
nik_dialog.out_item_much("af_needle",1)
end

function give_111()
nik_dialog.out_item_much("af_needle_heavy",1)
end



function arts_reward (first_speaker, second_speaker) 
 dialogs.relocate_money(first_speaker, 300, "in") 
end

