------Copyright DEXXX-------soundtrack

snd_obj = {}
snd_obj = xr_sound.get_safe_sound_object([[monsters\biting\def_0]])

function s_stop()
	if snd_obj:playing()==true then snd_obj:stop() end
end

function s_play(path)
	s_stop()
	snd_obj = xr_sound.get_safe_sound_object(path)
	if snd_obj then
		snd_obj:play_at_pos(db.actor, vector ():set (0, 0, 0), 0, sound_object.s2d)
	end
end

--------------------------------------------

function occusion()
	s_play([[actor\heartbeat]])
end

function esc_prizrak_agressive()
	s_play([[ambient\rnd_outdoor\rnd_horror_3]])
end

function darklab_start_bassz()
	s_play([[ambient\special\darklab_ambient]])
end

function gar_zom_woo()
	s_play([[monsters\zombie\threaten_0]])
end

function ros_shoot_max()
	s_play([[weapons\svd\shoot]])
end

function svd_shoot_max()
	s_play([[weapons\svd\shoot]])
end

function gen_last_sch()
	s_play([[ambient\special\rostok_bloodsucker_call]])
end

function gen_last_schs()
	news_manager.send_tip(db.actor, game.translate_string("gen_last_schs_0"), 1, "item", 25000, nil, nil, true, "st_sec_system_name")
	news_manager.send_tip(db.actor, game.translate_string("gen_last_schs_1"), 5, "ecolog", 25000, nil, nil, true, "scene_scientist")
	olr.del_by_name("lvl16_generators_physic_object_0210")
	olr.kill_mon_in_radius(db.actor:position(), 150)
	s_play([[ambient\special\siren_gen]])
end

function ros_veter_plen_snd()
	s_play([[ambient\special\bloodsucker_sucking]])
end

function ros_sosichi_roscall_snd()
	s_play([[ambient\special\rostok_bloodsucker_call]])
end

function samaya_hata_prip()
	s_play([[ambient\special\fear_hata]])
end

function pridi_gar_mon()
	s_play([[characters_voice\scenario\sarcofag\monolith\monolith_call_1]])
end

function ghouls_orut_out()
	s_play([[ambient\special\sob]])
end

function vkl_pitanie()
	s_play([[ambient\special\power_on]])
end

function vkl_pitanie2()
	s_play([[ambient\special\power_switch]])
end

function vkl_pitanie3()
	s_play([[ambient\special\use_canister]])
end

function sosaka_cut_ros()
	s_play([[monsters\bloodsucker\take_damage_0]])
end

function achit1()
	s_play([[actor\hurt_1]])
end

function achit2()
	s_play([[actor\hurt_3]])
end

function flaer_2()
	olr_timers.st_timer("flaer_3", 2, "soundtrack.flaer_3()")
	olr_timers.st_timer("flaer_3", 285, "nick.fraer_yeag_3()")
end

function flaer_3()
	olr.del_by_name("lvl4_darkdolina_stalker_0071")
end

function rc_svd_shot()
	s_play([[weapons\svd\shoot]])
end

function x18_laugh()
	s_play([[ambient\special\tun_noise]])
end
