---------------------------------------------------------------------------------------------------------------------
--	Схема озвучки
--	автор:  Диденко Руслан  (Stohe)
--	update: Чугай Александр (Chugai)
----------------------------------------------------------------------------------------------------------------------
nstl = 64

snd_ini = ini_file("misc\\script_sound.ltx")

theme = {}
ph_snd_themes = {}

ph_snd_themes["humor"] = {  "characters_voice\\scenario\\escape\\megaphone\\commander_megaphone_1",
							"characters_voice\\scenario\\escape\\megaphone\\commander_megaphone_2",
							"characters_voice\\scenario\\escape\\megaphone\\commander_megaphone_3",
							"characters_voice\\scenario\\escape\\megaphone\\commander_megaphone_4",
							"characters_voice\\scenario\\escape\\megaphone\\commander_megaphone_5",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_1",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_2",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_3",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_4",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_5",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_6",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_7",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_8",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_9",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_10",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_11",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_12",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_13",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_14",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_music_15"

	                        }					
ph_snd_themes["epic"] = {	"characters_voice\\scenario\\escape\\megaphone\\megaphone_1",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_2",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_3",
							"characters_voice\\scenario\\escape\\megaphone\\megaphone_4"
							}

---------------------------OLR 3---------------------------------------------------------

ph_snd_themes["none_idle"] = {"monsters\\biting\\def_0"}

ph_snd_themes["generator_idle"]			= {[[ambient\special\generator_idle_work]]}

ph_snd_themes["military_radio_peredacha"]	= {[[characters_voice\scenario\military\radio\military_radio_broadcast]]}

ph_snd_themes["rat_lounge_music"]	= {[[monsters\biting\def_0]]}

ph_snd_themes["grob_music"]	= {[[ambient\special\grob_music]]}

ph_snd_themes["el_humm"]	= {[[ambient\special\bar_antenna_hum]]}

---------------------------OLR 3---------------------------------------------------------



ph_snd_themes["radio_music_off"]	= {
	                        "device\\radio\\radio_noise_1",
				"device\\radio\\radio_noise_2"
	                        }

ph_snd_themes["radio_noise_ph"]	= {
	                        "device\\radio\\radio_noise_1",
				"device\\radio\\radio_noise_2"
	                        }


ph_snd_themes["bar_music"]	= {
	                        "characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_1",
				"characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_2",
				"characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_3",
				"characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_4"
	                        }



ph_snd_themes["bar_drink_vet_ph"]	= {
	                        "characters_voice\\scenario\\bar\\bar_veteran\\bar_veteran_1",
				"characters_voice\\scenario\\bar\\bar_veteran\\bar_veteran_2",
				"characters_voice\\scenario\\bar\\bar_veteran\\bar_veteran_3",
				"characters_voice\\scenario\\bar\\bar_veteran\\bar_veteran_4"
	                        }



ph_snd_themes["bar_night_radio"]	= {
	                        "characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_1",
				"characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_2",
				"characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_3",
				"characters_voice\\scenario\\bar\\bar_radio_music\\bar_radio_music_4"
	                        }




ph_snd_themes["bar_drinkers_ph"]	= {
	                        "characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_1",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_2",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_3",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_4",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_5",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_6",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_7",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_8",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_9",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_10",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_11",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_12",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_13",
				"characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_14",
	            "characters_voice\\scenario\\bar\\bar_visitor\\bar_visitor_15"
		
	                        }




ph_snd_themes["zombie_bred"] = {"monsters\\zombie\\die_0",
				"monsters\\zombie\\idle_0",
				"monsters\\zombie\\idle_1",
				"monsters\\zombie\\idle_2",
				"monsters\\zombie\\hurt_0",
				"monsters\\zombie\\hurt_1"
	                        }


ph_snd_themes["bar_bar_drunk_standing"]	= {"characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_1",
	                        "characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_2",
	                        "characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_3",
	                        "characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_4"
	                        }

ph_snd_themes["bar_bar_drunk_sitting"]	= {"characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_1",
	                        "characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_2",
	                        "characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_3",
	                        "characters_voice\\scenario\\bar\\bar_drunker\\drunker_hiccup_4",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_1",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_2",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_3",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_4",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_5",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_6",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_7",
	                        "characters_voice\\human_01\\stalker\\states\\sleep\\sleep_8"
	                        }


-----------------------------------------------------------------------------------------------------------------------


                     
ph_snd_themes["alarm1"] = { "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_1",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_2",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_3",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_4",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_5",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_6",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_7",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_8",
                            "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_9",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_10",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_11",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_12",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_13"
	                        }


-----------------------------------------------------------------------------------------------------------------------


ph_snd_themes["alarm2"] = { "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_2",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_3",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_4",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_5",
	                        "characters_voice\\scenario\\escape\\megaphone\\megaphone_alarm_6"
	                      }
ph_snd_themes["siren"] 		= { "ambient\\special\\siren" }
ph_snd_themes["siren_gen"] 	= { "ambient\\special\\siren_gen" }
-- ph_snd_themes["bomb"] 		= {"detectors\\bomb_timer"}
ph_snd_themes["detector"] 	= {"device\\detectors\\da-2_beep1"}

ph_snd_themes["sin_megafon"] = {

                                "characters_voice\\scenario\\military\\sin_megaphone\\sin_megaphone_1",
                                "characters_voice\\scenario\\military\\sin_megaphone\\sin_megaphone_2",
                                "characters_voice\\scenario\\military\\sin_megaphone\\sin_megaphone_3",
								"characters_voice\\scenario\\military\\sin_megaphone\\sin_megaphone_4"
	                        }


ph_snd_themes["radio_music"] = {	"characters_voice\\scenario\\escape\\radio\\radio_music_1",
									"characters_voice\\scenario\\escape\\radio\\radio_music_2",
									"characters_voice\\scenario\\escape\\radio\\radio_music_3",
									"characters_voice\\scenario\\escape\\radio\\radio_music_4",
									"characters_voice\\scenario\\escape\\radio\\radio_music_5"
	                        }

ph_snd_themes["dolg_speech"]		= {[[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
									   [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_3]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_4]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_5]],
									   [[characters_voice\scenario\megafon\megafon_music_1]],
									   [[characters_voice\scenario\megafon\megafon_music_2]],
									   [[characters_voice\scenario\megafon\megafon_music_3]]
}

ph_snd_themes["dolg_alarm"]			= {[[characters_voice\scenario\bar\dolg_megafon\megaphone_duty_alarm]]}
ph_snd_themes["dolg_megafon_1_hit"] 		= {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_1]]}
ph_snd_themes["dolg_megafon_2_hit"] 		= {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_2]]}
ph_snd_themes["dolg_megafon_kill"]		= {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_3]]}



ph_snd_themes["bar_start_megafon"]		= {[[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
									   [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]]}

ph_snd_themes["mon_monolith_damaged"]			= {[[characters_voice\scenario\sarcofag\monolith_damaged]]}
ph_snd_themes["mon_monolith_heavy_damaged"]		= {[[characters_voice\scenario\sarcofag\monolith_heavy_damaged]]}
ph_snd_themes["mon_monolith_alarm"]				= {[[characters_voice\scenario\sarcofag\monolith_alarm]]}
ph_snd_themes["mon_monolith_recharged"]			= {[[characters_voice\scenario\sarcofag\monolith_recharged]]}

ph_snd_themes["sar_monolith_call"]			= {[[characters_voice\scenario\sarcofag\monolith_call_1]],
												[[characters_voice\scenario\sarcofag\monolith_call_2]],
												[[characters_voice\scenario\sarcofag\monolith_call_3]],
												[[characters_voice\scenario\sarcofag\monolith_call_4]],
												[[characters_voice\scenario\sarcofag\monolith_call_5]],
												[[characters_voice\scenario\sarcofag\monolith_call_6]],
												[[characters_voice\scenario\sarcofag\monolith_call_7]]}

ph_snd_themes["aes_battle1"] =        {"ambient\\battle_1"}
ph_snd_themes["aes_battle2"] =        {"ambient\\battle_2"}
ph_snd_themes["gar_bandits_seryi"] =   {[[characters_voice\scenario\garbage\grey_bandit_1]],      
										[[characters_voice\scenario\garbage\grey_bandit_2]],
										[[characters_voice\scenario\garbage\grey_bandit_3]],
										[[characters_voice\scenario\garbage\grey_bandit_4]],
										[[characters_voice\scenario\garbage\grey_bandit_5]]}
ph_snd_themes["radar_drone"] = {"ambient\\radar_1"}
ph_snd_themes["radar_thunder"] = {"ambient\\radar_2"}
ph_snd_themes["radar_sparks"] = {"ambient\\radarsparks_1"}
--ph_snd_themes["aes_teleport"] = {"anomaly\\teleport_incoming"}

ph_snd_themes["yan_antenna"] = {{"ambient\\special\\psy_voices"}} -- Стерео

ph_snd_themes["radar_meh_on"] = {"ambient\\cooling_run"}
ph_snd_themes["radar_meh_off"] = {"ambient\\cooling_stop"}                               






ph_snd_themes["psy_voices"] = {{[[ambient\special\psy_voices]]}} -- Стерео

ph_snd_themes["heli_explosion"] = {[[device\vehicle\explosion]]}

ph_snd_themes["trader_door_open_start"]		= {[[device\door\door_start]]}
ph_snd_themes["trader_door_close_start"]	= {[[device\door\door_closing]]}
ph_snd_themes["trader_door_close_stop"]		= {[[device\door\door_stop]]}
ph_snd_themes["trader_door_locked"]			= {[[device\door\door_locked]]}
ph_snd_themes["trader_door_unlock"]			= {[[device\door\door_servomotor]]}
ph_snd_themes["wood_small_open"]			= {[[device\door\wood_small_open]]}
ph_snd_themes["wood_small_close_start"]		= {[[device\door\wood_small_close_start]]}
ph_snd_themes["wood_small_close_stop"]		= {[[device\door\wood_small_close_stop]]}
ph_snd_themes["wood_large_open"]			= {[[device\door\wood_large_open]]}
ph_snd_themes["wood_large_close_start"]		= {[[device\door\wood_large_close_start]]}
ph_snd_themes["wood_large_close_stop"]		= {[[device\door\wood_large_close_stop]]}
ph_snd_themes["metal_small_open"]			= {[[device\door\metal_small_open]]}
ph_snd_themes["metal_small_close_start"]	= {[[device\door\metal_small_close_start]]}
ph_snd_themes["metal_small_close_stop"]		= {[[device\door\metal_small_close_stop]]}


-----------------------------------------------------------------------------------------------------------------------------------
--	Theme  functions
-----------------------------------------------------------------------------------------------------------------------------------
function weather_class(avail_types, npc)
	local type = "weather_good"
	if level.rain_factor() < 0.07 then
		type = "weather_good"
	else
		type = "weather_bad"
	end
	return type
end

function combat_class(avail_types, npc)
	if npc:best_enemy() ~= nil or
	   npc:best_danger() ~= nil
	then
		return ""
	end
	return "state"
end

-------------------------------------------------------------------------
-- ЗВУКИ СТАЛКЕРОВ
-------------------------------------------------------------------------
local sounds_base = stalker_ids.sound_script + 10000
function id()
	sounds_base = sounds_base + 1
	return sounds_base - 1
end

theme = {



	-- olr

	newbie_phrase_artifact_1              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_phrase_artifact_2              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_phrase_artifact_3              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_phrase_artifact_4              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_phrase_artifact_5              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_phrase_artifact_6              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	newbie_replic_1              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_replic_2              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_replic_3              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_replic_4              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	newbie_replic_5              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	prof_da_skudnovato              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	prof_fu_nu_i_gadost              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	prof_habara_naberu              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	prof_jizn_nalajivaetsya              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	prof_nemnogo_habara              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},


	prof_sluhal_pro_zomby_stalkerov              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rainbow_net_a_chto_s_nimi              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	prof_rasskaz_o_zomby              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rainbow_ni_hrena_sebe              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	prof_dobrogo_mochi_ne_sprashivay              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	prof_che_nado              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},




	olr_loshara			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},


	-- olr



	
	-- погода
	weather = {	exec = sound_theme.weather_class, 
				types = {weather_bad	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
						 weather_good	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}} }},

	-- состояния тела
	state = {	exec = sound_theme.combat_class, 
				types = {state	= {min_snd = 60, max_snd = 90, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}} },
	

	sleep				= {min_snd = 10, max_snd = 15, rnd = 75, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- просьба о помощи
	help				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_see			= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_heavy			= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_thanx			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy_shoot	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- окрик
	hail				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- ожидание
	wait				= {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    
	-- угрозы
	threat_weap			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_back			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_stop			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- реакции
--	reac_hear				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_see				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_monstr		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_enemy			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_neutral		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_friend		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_nothing			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	reac_box				= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_music				= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_joke				= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- болтовня
	talk_hello				= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_hello_friend			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_bye				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_accept				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_reject				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_abuse				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- реакции на юзание
	use_yes_fight			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_sleep			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_kamp			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_default			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_fight			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_sleep			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_weapon			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_default			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_abuse				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- бой
	fight_attack			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	zombied_fight_attack	= {min_snd = 5, max_snd = 10,rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_search			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},




	
	-- торговля
	trade_yes				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	trade_no				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- игра на губной гармошке
	intro_music				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	harmonica				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- игра на гитаре
	guitar					= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- шутки, прибаутки
	intro_joke				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	joke					= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

        -- new_hello				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Истории
	story_01				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[2] = {theme = "story_reac_cool_info", min = 1, max = 1},
								[3] = {theme = "story_reac_continue", min = 2, max = 3},
								[5] = {theme = "story_reac_laughter", type = "all"}}},
	story_02				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[2] = {theme = "story_reac_yes", min = 1, max = 2},
								[3] = {theme = "story_reac_continue", min = 1, max = 1},
								[4] = {theme = "story_reac_action_right", min = 1, max = 1},
								[5] = {theme = "story_reac_cool_teller", min = 1, max = 1},
								[6] = {theme = "story_reac_continue", min = 1, max = 1},
								[7] = {theme = "story_reac_belief_story, story_reac_final_happy, story_reac_yes", min = 2, max = 4}}},											
	story_03				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[1] = {theme = "story_reac_continue", min = 1, max = 1},
								[2] = {theme = "story_reac_final_tragic", min = 1, max = 1},
								[3] = {theme = "story_reac_belief_story", min = 2, max = 3}}},
	story_04				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[1] = {theme = "story_reac_continue", min = 1, max = 1},
								[2] = {theme = "story_reac_final_tragic", min = 1, max = 1},
								[3] = {theme = "story_reac_belief_story", min = 2, max = 3}}},
	story_05				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[1] = {theme = "story_reac_advice_sceptic, story_reac_advice_support", min = 1, max = 1}}},
	story_06				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[2] = {theme = "story_reac_continue", min = 1, max = 1},
								[3] = {theme = "story_reac_cool_teller", min = 1, max = 1},
								[4] = {theme = "story_reac_action_right", min = 1, max = 1},
								[5] = {theme = "story_reac_yes", min = 1, max = 1},
								[6] = {theme = "story_reac_disbelief_teller, story_reac_belief_story", min = 2, max = 3},
								[7] = {theme = "story_reac_cool_teller", min = 1, max = 1},
								[8] = {theme = "story_reac_wonder", min = 1, max = 1},
								[9] = {theme = "story_reac_disbelief_story, story_reac_belief_story, story_reac_yes", min = 2, max = 4}}},

	legend_01				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_doubt", min = 1, max = 1},
								[2] = {theme = "story_reac_wonder, story_reac_disbelief_story", min = 1, max = 1},
								[3] = {theme = "story_reac_yes", min = 2, max = 3},
								[4] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_02				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_doubt", min = 1, max = 1},
								[2] = {theme = "story_reac_disbelief_story", min = 1, max = 1},
								[3] = {theme = "story_reac_wonder", min = 1, max = 1},
								[4] = {theme = "story_reac_laughter", min = 1, max = 1},
								[5] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_03				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_cool_info", min = 1, max = 1},
								[2] = {theme = "story_reac_yes, story_reac_doubt", min = 2, max = 4}}},								
	legend_04				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_fear", min = 1, max = 1},
								[2] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
								
	legend_05				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_yes", min = 2, max = 3},
								[2] = {theme = "story_reac_doubt", min = 1, max = 1},
								[3] = {theme = "story_reac_disbelief_story, story_reac_belief_story", min = 2, max = 4}}},

	story_reac_action_right		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_action_wrong		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_advice_sceptic	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_advice_support	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_belief_story		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_continue			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_cool_info		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_cool_teller		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief_story	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief_teller	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_doubt			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_fear				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_final_happy		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_final_tragic		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_laughter			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_old_story		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_uncertain		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_wonder			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_yes				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	

	-- УНИКАЛЬНЫЕ ТЕМЫ
	-- Bar
	bar_bar_osvedomitel_hello		= {min_snd = 15, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello			= {min_snd = 2, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello_room		= {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_leader_hello			= {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_leader_idle			= {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Bar dolg guard
	bar_dolg_guard_stop				= {min_snd = 15, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_guard_prohodi				= {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_guard_busy				= {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	bar_guard_enter					= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      
	bar_guard_stop					= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      

	-- Bar dolg Petrenko
	bar_dolg_petrenko_hello				= {min_snd = 3, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}
}
   
-- В темах для игрока интервал задается в миллисекундах!!!
actor_theme = {
	level_border_detector = {min_snd = 10, max_snd = 100,
							 sounds = {xr_sound.get_safe_sound_object([[device\detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_2]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_2]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_4]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_5]]),
									   xr_sound.get_safe_sound_object([[device\detectors\geiger_6]]) }}
}
   										
function select_sound_from_ltx(obj, section, ltx)
--	1. проверка по story_id
	local c = obj:story_id()
	if ltx:line_exist(section, utils.to_str(c)) then
		return ltx:r_string(section, utils.to_str(c))
	end

--	2. проверка по npc_profile
	c = obj:profile_name()
	if ltx:line_exist(section, c) then
		return ltx:r_string(section, c)
	end

--	3. проверка по character_community
	c = obj:character_community()
	if ltx:line_exist(section, c) then
		return ltx:r_string(section, c)
	end
	
--	4. загрузка дефолта
	if ltx:line_exist(section, "stalker") then
		return ltx:r_string(section, "stalker")
	else
		return nil
	end
end

-----------------------------------------------------------------------------------------------------------------------------------
local character_prefix = ""
local default_prefix = "characters_voice\\"
function check_prefix(s)
	local flag = string.sub(s, 1, 1)
	return flag, string.sub(s, 3)
end

function load_sound(obj)
	local k,v = 0,0
	
	-- загрузка звуков на основе данных ltx
	function load_sound_from_ltx(obj, name, tbl)		
		tbl.max_ids[obj:id()] = {}
		if snd_ini:section_exist(name.."_rnd") then		
			local s = select_sound_from_ltx(obj, name.."_rnd", snd_ini)			
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end
					
				--printf("NPC[%s] flag[%s] prefix[%s] path[%s]", obj:name(), flag, obj:sound_prefix(), path)
				tbl.max_ids[obj:id()].rnd_max = obj:add_sound(path, nstl, snd_type.talk, 2, 1, tbl.rnd_id)

				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
		if snd_ini:section_exist(name.."_seq") then
			local s = select_sound_from_ltx(obj, name.."_seq", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end

				--printf("NPC[%s] flag[%s] prefix[%s] path[%s]", obj:name(), flag, obj:sound_prefix(), path)
				tbl.max_ids[obj:id()].into_max = obj:add_sound(path, nstl, snd_type.talk, 2, 1, tbl.into_id)
				tbl.max_ids[obj:id()].into_cycled = true

				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
		if snd_ini:section_exist(name.."_single") then
			local s = select_sound_from_ltx(obj, name.."_single", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end

				--printf("NPC[%s] flag[%s] prefix[%s] path[%s]", obj:name(), flag, obj:sound_prefix(), path)
				tbl.max_ids[obj:id()].into_max = obj:add_sound(path, nstl, snd_type.talk, 2, 1, tbl.into_id)
				tbl.max_ids[obj:id()].into_cycled = false

				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end			
			end
		end
	end
	
	function load_theme_sound(npc, tbl)
		for k,v in pairs(tbl) do
			if v.types == nil then
				load_sound_from_ltx(npc, k, v)
			else
				load_theme_sound(npc, v.types)
			end
		end
	end

	load_theme_sound(obj, theme)

	-- делаем заготовку в db.sound
	db.sound[obj:id()] = {}
	
----	printf("All sounds loaded for %s, section %s", obj:name(), obj:section())
---	print_table(theme)
end