--[[-----------------------------------------------------------------------------------------------
 File         : sr_deadnight.script
 Description  : Модуль включения indoor погоды
 Copyright    : Oblivion Lost Remake 3.0
 Author       : hi_flyer
 Date         : 17.05.15
 Last Edit    : 17.05.15
--]]----------------------------------------------------------------------------------------------- 

class "action_deadnight"

function action_deadnight:__init( obj, storage )
	self.object = obj
	self.st = storage
end

function action_deadnight:reset_scheme()

end

function action_deadnight:update( delta )
	local actor = db.actor

	if xr_logic.try_switch_to_another_section( self.object, self.st, actor ) then
		return
	end	

end
---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: scheme='%s', section='%s'", scheme, section)

	local new_action = action_deadnight(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end
---------------------------------------------------------------------------------------------------------------------