----------------------------------------------------------------------------------------------------
-- Do nothing
----------------------------------------------------------------------------------------------------

class "action_subtitle"

function action_subtitle:__init(obj, storage)
	self.object = obj
	self.st = storage
end

function action_subtitle:reset_scheme()
	--printf("_bp: sr_idle: action_subtitle:reset_scheme: self.object:name()='%s'", self.object:name())
	self.st.tips_sended = false
	self.st.signals = {}
end

function action_subtitle:update(delta)
	--printf("_br: sr_idle: action_subtitle:update()")

	--if not xr_logic.is_active(self.object, self.st) then
	--	return
	--end

	local actor = db.actor
	if not actor then
		return
	end

	if self.object:inside(actor:position()) then
		--print_table(self.st.conditions)	
		--printf("condlist %s", utils.to_str(xr_logic.pick_section_from_condlist(actor, nil, self.st.conditions.condlist)))
		if self.st.conditions == nil or
		xr_logic.pick_section_from_condlist(actor, nil, self.st.conditions.condlist) ~= nil
		then
			if self.st.tips_sended == false then
				olr.hud_tip("", game.translate_string(self.st.info), self.st.showtime, self.st.from_actor)
				if self.st.single == true then
					self.st.signals["tip_sended"] = true
					self.st.tips_sended = true
				end     
			end   
		end
	end

	if xr_logic.try_switch_to_another_section(self.object, self.st, actor) then
		return
	end	
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: scheme='%s', section='%s'", scheme, section)

	local new_action = action_subtitle(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

function set_scheme(obj, ini, scheme, section, gulag_name)
	local st		= xr_logic.assign_storage_and_bind(obj, ini, scheme, section)
	st.logic		= xr_logic.cfg_get_switch_conditions(ini, section, obj)

	st.info			= utils.cfg_get_string( ini, section, "name",     obj, true,  "", "" )
	st.showtime		= utils.cfg_get_number( ini, section, "showtime", obj, false,     3 )
	st.from_actor	= utils.cfg_get_bool  ( ini, section, "from_actor", obj, false, true )

	st.conditions	= xr_logic.cfg_get_condlist( ini, section, "cond", obj )
end
