--[[-----------------------------------------------------------------------------------------------
 File		  : sr_zone_dead.script
 Description  : Модуль "аномалии" мёртвая зона
 Copyright	  : Oblivion Lost Remake 3.0
 Author		  : hi_flyer, theysani
 Date		  : 15.11.15
 Last Edit	  : 15.11.25
--]]----------------------------------------------------------------------------------------------- 

local state_nowhere = 0 -- схема только что включилась
local state_inside = 1 -- актер внутри
local state_outside = 2 -- актер снаружи

class "action_zonedead"

function action_zonedead:__init( obj, storage )
	self.object = obj
	self.st = storage
	self.pp_effector_active = false
end

function action_zonedead:reset_scheme()
	self.state = state_nowhere -- еще неясно, в зоне он, или нет
	self:switch_state(db.actor)
end

function action_zonedead:update( delta )
	local actor = db.actor

	if xr_logic.try_switch_to_another_section( self.object, self.st, actor ) then
		return
	end	   
	
	self:switch_state( actor )
	
	if self.state == state_inside then
		-- Внутри зоны, действия на апдейте
	end
end

function action_zonedead:switch_state( actor )
	local state = self.state
	
	if state == state_outside or state == state_nowhere then
		if self.object:inside( actor:center() ) then
			self:zone_enter()
			return
		end
	end
	
	if state == state_inside or state == state_nowhere then
		if not self.object:inside( actor:center() ) then
			self:zone_leave()
			return
		end
	end
end

function action_zonedead:zone_enter()
	self.state = state_inside
	
	-- Действия при входе в зону (однократное выполнение при переходе из стейта nowhere или outside)
	
end

function action_zonedead:zone_leave()
	self.state = state_outside
	
	-- Действия при выходе из зоны (однократное выполнение при переходе из стейта nowhere или inside)
	
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: scheme='%s', section='%s'", scheme, section)

	local new_action = action_zonedead(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end