----------------------------------------------------------------------------------------------------------------------
--  Библиотека состояний тела
--  автор: Диденко Руслан (Stohe)
--  TODO: 
----------------------------------------------------------------------------------------------------------------------

states = {






 scient_bar_resercher = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "scient_bar_resercher" }, 



 scient_bar_resercher2 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "scient_bar_resercher2" }, 



 ohrana_stopper = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "ohrana_stopper" }, 




 actor_noway = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "actor_noway" }, 



 actor_sumka = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "actor_sumka" }, 


 actor_sumka2 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "actor_sumka2" }, 



  walk_fwd_crawl_0 = {  weapon = "unstrapped",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "walk_poisk_0"
      },








 lejit = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "lejit" }, 


 stalker_1 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "stalker_1" }, 


 stalker_2 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "stalker_2" }, 


 stalker_3 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "stalker_3" }, 




 lejit_idle = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "lejit_idle" }, 



  wounded_heavy_monster = { weapon = "drop",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        direction = look.cur_dir,
        animstate = "stand",
        animation = "wounded_heavy_monster"
      },


 new_medic = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "new_medic" }, 


 smert = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "smert" }, 


 proverka_dver = {weapon = "unstrapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "proverka_dver" }, 



  pprisluh = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "pprisluh",
        reset = true
      },




  mashina_full = {  weapon = "strapped",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
 	animation = "mashina_full" }, 




 mashina_idle = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "mashina_idle" }, 


 mil_sit_chair_3 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "mil_sit_chair_3" }, 


 norm_2_dazzle_light_0 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "norm_2_dazzle_light_0" }, 


 norm_2_dazzle_light_1 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "norm_2_dazzle_light_1" }, 


 norm_2_dazzle_light_2 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "norm_2_dazzle_light_2" }, 


 norm_death_0 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "norm_death_0" }, 

 norm_hello_0 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "norm_hello_0" }, 



  -- Дефолтовый
  idle = {  weapon = nil,
        movement = nil,
        mental = nil,
        bodystate = nil,
        animstate = "stand",
        animation = nil
      },

  -- Ходячие состояния
  walk = {  weapon = "strapped",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  run = {   weapon = "strapped",
        movement = move.run,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  sprint = {  weapon = "unstrapped",
        movement = move.run,
        mental = anim.panic,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  patrol = {  weapon = "unstrapped",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  patrol_fire = { weapon = "fire",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  raid = {  weapon = "unstrapped",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  raid_fire = {weapon = "fire",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  sneak = { weapon = "unstrapped",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },      
  sneak_run = { weapon = "unstrapped",
        movement = move.run,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },      
  sneak_no_wpn = {  weapon = "strapped",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },      
  sneak_fire = {  weapon = "fire",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },      
  assault = { weapon = "unstrapped",
        movement = move.run,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  assault_fire = {  weapon = "fire",
        movement = move.run,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  rush = {  weapon = "unstrapped",
        movement = move.run,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },

  -- Стоячие состояния
  wait = {  weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "idle"
      },
  wait_trade = {  weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "idle"
      },
  wait_na = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  guard = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "idle"
      },
  guard_na = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  guard_fire = {  weapon = "fire",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  threat = {  weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  threat_heli = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  threat_na = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  threat_fire = { weapon = "fire",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  threat_sniper_fire = {  weapon = "sniper_fire",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
-- Сидит целится вперед
  hide = {  weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "hide"
      },
-- Сидит целится вперед
  count = {  weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "hide"
      },
  hide_na = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },
-- Стоит целится вперед
  hide_fire = { weapon = "fire",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },
-- Стоит целится вперед
  hide_sniper_fire = {  weapon = "sniper_fire",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = nil
      },
-- Стоит всматривается вперед
  caution = { weapon = nil,
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "caution"
      },
-- Читает на стене
  choose   = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "choosing"
      },
-- Жмёт кнопку
  press  = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "press"
      },
-- Стоит руки за спиной
  ward   = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "warding"
      },
-- поиск чего-либо перед ногами
  search  = {weapon = nil,
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "poisk"
      },
-- Воинское приветствие 
  salut  = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "salut"
      },
  salut_free = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "salut_free"
      },
-- Пленный
  prisoner = {weapon = "strapped",
        movement = nil,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "prisoner"
      },
-- Сидя на корточках смотрит вперёд
  hide_no_wpn = { weapon = "strapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "hide"
      },

 

  -- Сидячие состояния
  sit = {   weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit",
        animation = "sit"
      },
  sit_knee = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_knee",
        animation = "sit_knee"
      },
  sit_stul = { weapon = "unstrapped",
       movement = move.stand,
       mental = anim.free,
       bodystate = move.standing,
       animstate = "stand",
       animation = "sit_stul"
      },
  sit_stul_stul = { weapon = "none",
       movement = move.stand,
       mental = anim.free,
       bodystate = move.standing,
       animstate = "stand",
       animation = "sit_stul_stul"
      },
  sit_ass = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_ass",
        animation = "sit_ass"
      },
  sleep = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sleep",
        animation = "sleeping"
      },
  sleep_sit = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_ass",
        animation = "sleep_sit"
      },
  eat_bread = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_knee",
        animation = "eat_bread"
      },
  eat_vodka = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_ass",
        animation = "eat_vodka"
      },
  eat_energy  = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_ass",
        animation = "eat_energy"
      },
  eat_kolbasa = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_ass",
        animation = "eat_kolbasa"
      },

  guitar  = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_knee",
        animation = "guitar"
      },
  harmonica = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "sit_ass",
        animation = "harmonica"
      },

  hello = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "hello",
        reset = true
      },
  hello_wpn = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "hello",
        reset = true
      },
-- Да у меня нет нечего      
  refuse = {  weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "refuse",
        reset = true
      },
-- Целится и подзывает к себе
  claim = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "claim",
        reset = true
      },
  backoff = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "backoff",
        reset = true
      },
  backoff2 = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "backoff",
        reset = true
      },
-- Суицид
  suicide = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "suicide",
        reset = true
      },
-- Удар прекладом
  punch = { weapon = nil,
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "punch",
        reset = true
      },
-- Присел с разваротом влево
  hide_s_left = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "hide_s_left",
        reset = true
      },
-- Присел с разваротом вправо
  hide_s_right = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "hide_s_right",
        reset = true
      },
  dynamite = {weapon = "strapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "dynamite"
      },

  binocular = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "binocular"
      },
-- Сидя говорит по рации
  hide_rac = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand",
        animation = "cr_raciya"
      },
-- Стоя говорит по рации
  wait_rac = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "raciya"
      },
-- Стоя говорит по рации с оружием на плече
  guard_rac = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "raciya"
      },
  probe = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "probe"
      },
  probe_1 = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "probe_1"
      },
  probe_2 = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "probe_2"
      },
  probe_3 = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "probe_3"
      },
  mode_shlem  = {weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "mode_shlem"
      },
-- Руки вверх
  hands_up  = {weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "hands_up"
      },
      
      

  -- Раненый
  wounded = { weapon = "strapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        direction = look.cur_dir,
        animstate = "stand",
        animation = "wounded"
      },
  wounded_heavy = { weapon = "drop",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        direction = look.cur_dir,
        animstate = "stand",
        animation = "wounded_heavy_1"
      },
  wounded_heavy_2 = { weapon = "drop",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        direction = look.cur_dir,
        animstate = "stand",
        animation = "wounded_heavy_2"
      },
  wounded_heavy_3 = { weapon = "drop",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        direction = look.cur_dir,
        animstate = "stand",
        animation = "wounded_heavy_3"
      },
  wounded_zombie = {  weapon = "unstrapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        direction = look.cur_dir,
        animstate = "stand",
        animation = "wounded_zombie"
      },
  help_me = { weapon = "strapped",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "wounded",
        animation = "help_me"
      },
  trans_0 = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "trans_0"
      },
  trans_1 = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "trans_1"
      },
  trans_zombied = {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "trans_zombied"
      },

  -- Пси раненый
  psy_pain = {weapon = "drop",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "psy_armed"
      },
  psy_armed = {weapon = "unstrapped",
        weapon_slot = 1,
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "psy_armed"
      },
  psy_shoot = {weapon = "fire",
        weapon_slot = 1,
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "psy_shoot"
      },
  -- Псих в баре падает на колени идержится за голову
  psycho_pain = {weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "psycho_pain"
      },
  psycho_shoot = {weapon = "fire",
        weapon_slot = 1,
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "psycho_shoot"
        },
  -- Бармен
  bar_fas = { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "bar_fas"
      },
  bar_left= { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "bar_left"
      },
  bar_head= { weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "bar_head"
      },
  bar_sleep= {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "bar_sleep"
      },
  bar_right= {weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "bar_right"
      },


  barman_talk_free = {  weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "barman_free_anims"
      },
  
  barman_walk_free = {  weapon = "none",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },

  barman_tv = { weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "barman_tv"
      },

  barman_wait_free = {  weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "barman_wait"
      },

  barman_walk_danger = {  weapon = "none",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },

  barman_shock = {  weapon = "none",
        movement = move.walk,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "barman_shock"
      },

  barman_wait_danger = {  weapon = "none",
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.standing,
        animstate = "stand",
        animation = "barman_talk"
      },

  --  Доктор в мертвом городе
  doctor_wakeup = {weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "doctor_wakeup"
      },
  --  Профессор на Янтаре
  yan_professor_walk = {  weapon = "none",
        movement = move.walk,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = nil
      },
  yan_professor_wait = {  weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "idle"
      },
  help_agr = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "help_agr"
      },
  oso_flying = {  weapon = "none",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "oso_flying"
      },
  preblow = { weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "preblow"
      },


  -- Восстановленные состояния

-- стоит курит   
  olr_kurit_stoya = {  weapon = "strapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "olr_kurit_stoya"
      },

-- Пьяный идёт olr
  drunk_walk_olr = {  weapon = "none",
        movement = nil,
        mental = nil,
        bodystate = nil,
        animstate = nil,
        animation = "drunk_walk_olr"
      },
-- Пьяный идёт
  drunk_walk = {  weapon = "none",
        movement = nil,
        mental = nil,
        bodystate = nil,
        animstate = nil,
        animation = "drunk_walk"
      },
-- Пьяный стоит
  drunk_stoya   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "drunk_stoya" 
      },
-- Пьяный спит
  drink_sleep   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "drink_sleep" 
      },
-- Пьяный держится за стену
 drink_wall   = {weapon = "unstrapped", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "drink_wall" 
      },
-- Смеётся
   smeh   = {weapon = "none", 
        movement = move.stand,
        mental = anim.danger,
        bodystate = move.crouch,
        animstate = "stand", 
        animation = "smeh" 
      },
-- Курит сидя
 kurit_sidya  = {weapon = "unstrapped", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "kurit_sidya" 
      },
-- Раненый идёт   
 wounded_walk   = {weapon = "strapped", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "wounded_walk" 
      },
-- Раненый стоит   
 wounded_stoya   = {weapon = "strapped", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "wounded_stoya" 
      },
-- Преслонился к стене
 k_stene   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "k_stene" 
      },
-- Испуг
 ispug   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "ispug" 
      },
-- Сидит на стуле
 sit_stul_a   = {weapon = "none", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "sit_stul_a" 
      },
-- Сидит на стуле засыпает
 sit_stul_sleep   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "sit_stul_sleep" 
      },
-- Сидит на стуле ремонтирует
 sit_stul_mechanic   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "sit_stul_mechanic" 
      },
-- Сидит за столом
 sit_stol   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "sit_stol" 
      },
-- Сидит за столом и пишет
 sit_stol_pen   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "sit_stol_pen" 
      },
-- пинает мяч
 myach_1   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "myach_1" 
      },
 myach_2   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "myach_2" 
      },
-- возмущение
 refuse_1   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "refuse" 
      },

-- Подвешенное состояние
 monolith_0   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "monolith_0" 
      }, 
 monolith_1   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "monolith_1" 
      }, 
 monolith_2   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "monolith_2" 
      }, 
 monolith_3   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "monolith_3" 
      }, 
 monolith_4   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "monolith_4" 
      }, 
 monolith_5   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "monolith_5" 
      }, 

------------------------------------------------------------------------------
kurit_stoya	= {weapon = "strapped",
		movement = move.stand,
		mental = anim.free,
		bodystate = move.standing,
		animstate = "stand",
		animation = "kurit_stoya"
      },


 sit_chair1 = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "sit_chair1" }, 


 konvulsii = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "konvulsii" }, 


 drunk_idle_0 = {weapon = "strapped", 
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
	animation = "drunk_idle_0" }, 


 lezanie_idle_1 = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "lezanie_idle_1" }, 


 lezanie_idle_2 = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "lezanie_idle_1" }, 


 mil_sit_chair_7 = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "mil_sit_chair_7" }, 


 trans_stoya = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "trans_stoya" }, 


 umiraet_dramatic = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "umiraet_dramatic" }, 



 umiraet_kashel = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "umiraet_kashel" },


 idle_ranen = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "idle_ranen" },



 lavochka_sit = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "lavochka_sit" },


 read_sit_stul = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "read_sit_stul" },



 read_sit_stul_2 = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "read_sit_stul_2" },



 sit_idle_norm = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "sit_idle_norm" },


 sit_idle_sleepy = {weapon = "strapped", 
	movement = nil,
	mental = nil,
	bodystate = nil,
	animstate = nil,
	animation = "sit_idle_sleepy" },



  ragdol_anomaly_electra = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "ragdol_anomaly_electra",
        reset = true
      },



  ragdol_anomaly_jarka = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "ragdol_anomaly_jarka",
        reset = true
      },



  ragdol_anomaly_puh = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "ragdol_anomaly_puh",
        reset = true
      },


  ragdol_burst_front = {weapon = "unstrapped",
        movement = move.stand,
        mental = anim.free,
        bodystate = move.standing,
        animstate = "stand",
        animation = "ragdol_burst_front",
        reset = true
      },



	limping_run = {	weapon = "drop",
				movement = move.run,
				mental = anim.free,
				bodystate = move.standing,
				animstate = "stand",
				animation = "damaged_run"
			},
	limping_walk = {weapon = "unstrapped",
				movement = move.walk,
				mental = anim.free,
				bodystate = move.standing,
				animstate = "stand",
				animation = "damaged_walk"
			},


   
  test   = {weapon = "none", 
        movement = nil, 
        mental = nil, 
        bodystate = nil, 
        animstate = nil, 
        animation = "test" 
      }
}
