-- рейтинг сталкеров
-- hi_flyer 17.07.17

class "ui_best_stalkers" (CUIScriptWnd)

function ui_best_stalkers:__init(owner) super()
 	self.owner = owner
	self:InitControls()
end


function ui_best_stalkers:InitControls()
 self:Init(335,5,1024,768)
	local xml = CScriptXmlInit()
	if xml:is_16_9_mode() then
		xml:ParseFile("flyer\\best_stalkers_16.xml")
	else
		xml:ParseFile("flyer\\best_stalkers.xml")
	end

    self.back = xml:InitStatic("background", self)
		
	self.help_vopros = xml:InitStatic("help_vopros", self.back)
    self.main = xml:InitScrollView("list_wnd", self)

	local st_id = 0

	local addItm = 35
	local maxItems = 0
	local rnkFrst = {}
	local sim = alife()

	local montabl = 
	{
       		[clsid.script_stalker] = true,

	}

	for id=1, 65534 do
		local sobj = sim:object(id)
		if sobj then
            		if montabl[sobj:clsid()]  then
                		if sobj:alive() then
					if not olr_protected.is_no_offline_alife_obj(sobj:name()) then
						local rnk = sobj:rank()
						table.insert(rnkFrst, {rnk,sobj.id})
					end
				end
			end
		end
	end
	
	table.sort(rnkFrst, function(a,b) return a[1] > b[1] end) 

	for k,v in pairs(rnkFrst) do
		local sobj = sim:object(v[2])
		if sobj then
			if maxItems < addItm then
				maxItems = maxItems + 1
				local pk = get_netpk(sobj,1)
				if pk:isOk() then
					local data = pk:get()
					local name = data.character_name
					local rank = data.rank

    				self.no = xml:InitStatic("static_number", self.main)
					self.no:SetText(string.format("%s  (%d)",name, rank))
    				self:Register(self.no,"no")
    				self:AddCallback("no",ui_events.BUTTON_DOWN,self.n,self)

					st_id = st_id + 1


				end
			end
		end
	end

end

function ui_best_stalkers:Hide()
	self:GetHolder():start_stop_menu(self, true)
end




























