-- file:		UI_MM_OPT_MAIN.script
-- created:		01.07.2005
-- description:	options dialog
-- author:		Serge Vynnychenko
--

class "options_dialog" (CUIScriptWnd)

function options_dialog:__init() super()
   self:SetFont(GetFontMicron12()) --set base font for dialog.

	self.m_preconditions			= {}
	self.m_preconditions_retromode	= {}

	self:InitControls		()
	self:InitCallBacks		()
	self:NeedCenterCursor	(false)
	self.tab:SetActiveTab	("video")
end

function options_dialog:__finalize()

end

function options_dialog:InitControls()
	self:Init(0,0,1024,768)
	self:Enable(true)

	local xml = CScriptXmlInit()
	xml:ParseFile("ui_mm_opt.xml")


	xml:InitStatic("back_video", self)
	xml:InitStatic("background", self)
	xml:InitStatic("rug_video", self)
	if xml:NavigateToNode("back_left", 0) then
		xml:InitStatic("back_left", self)
	end
	if xml:NavigateToNode("back_right", 0) then
		xml:InitStatic("back_right", self)
	end
	self.dialog = xml:InitStatic("main_dialog:dialog", self)

	xml:InitStatic("main_dialog:cap_options", self.dialog)

	self.dlg_video = ui_mm_opt_video.opt_video()
	self.dlg_video:InitControls(55,74, xml, self)
	self.dialog:AttachChild(self.dlg_video)

	self.dlg_sound = ui_mm_opt_sound.opt_sound()
	self.dlg_sound:InitControls(55,74, xml, self)
	self.dlg_sound:Show(false)
	self.dialog:AttachChild(self.dlg_sound)

	self.dlg_gameplay = ui_mm_opt_gameplay.opt_gameplay()
	self.dlg_gameplay:InitControls(55,74, xml, self)
	self.dlg_gameplay:Show(false)
	self.dialog:AttachChild(self.dlg_gameplay)

	self.dlg_controls = ui_mm_opt_controls.opt_controls()
	self.dlg_controls:InitControls(55,74, xml, self)
	self.dlg_controls:Show(false)
	self.dialog:AttachChild(self.dlg_controls)

	self.dlg_video_adv = ui_mm_opt_video_adv.opt_video_adv()
	self.dlg_video_adv:InitControls(55,74, xml, self)
	self.dlg_video_adv:Show(false)
	self.dialog:AttachChild(self.dlg_video_adv)

	self.dlg_video_retromode = ui_mm_opt_retromode.opt_retromode()
	self.dlg_video_retromode:InitControls(55,74, xml, self)
	self.dlg_video_retromode:Show(false)
	self.dialog:AttachChild(self.dlg_video_retromode)

	local btn
	btn = xml:Init3tButton("main_dialog:btn_accept", self)
	self:Register(btn, "btn_accept")
	btn = xml:Init3tButton("main_dialog:btn_cancel", self)
	self:Register(btn, "btn_cancel")

	self.tab = xml:InitTab("main_dialog:tab", self.dialog)
	self:Register(self.tab, "tab")

	self.message_box			= CUIMessageBoxEx()
	self:Register				(self.message_box, "mb")

	self.b_restart_system_shown	= false
	self.timer					= nil

end

function options_dialog:SetCurrentValues()
	local opt = COptionsManager()

	opt:SetCurrentValues("mm_opt_video_preset")
	opt:SaveBackupValues("mm_opt_video_preset")

	opt:SetCurrentValues("mm_opt_video")
	opt:SaveBackupValues("mm_opt_video")

	opt:SetCurrentValues("mm_opt_video_adv")
	opt:SaveBackupValues("mm_opt_video_adv")

	opt:SetCurrentValues("mm_opt_video_retromode")
	opt:SaveBackupValues("mm_opt_video_retromode")

	opt:SetCurrentValues("mm_opt_gameplay")
	opt:SaveBackupValues("mm_opt_gameplay")

	opt:SetCurrentValues("mm_opt_sound")
	opt:SaveBackupValues("mm_opt_sound")

	opt:SetCurrentValues("mm_opt_controls")
	opt:SaveBackupValues("mm_opt_controls")

	opt:SetCurrentValues("key_binding")
	opt:SaveBackupValues("key_binding")


	self:UpdateDependControls()

	if self.btn_retromode then
		self.btn_retromode:Enable(self.check_retromode:GetCheck())
	end
end

function options_dialog:UpdateDependControls()
	self.scroll_v:Clear()
	local _current_id = self.combo_renderer:CurrentID()

	for i,j in pairs(self.m_preconditions) do
		if(j.func(_current_id)) then
			self.scroll_v:AddWindow(j.control, true)
			j.control:SetAutoDelete(false)
		end
	end

	--local max_texture_lod = 4
	--local min_texture_lod = 0

	--if _current_id ~= 0 then
	--	if not is_enough_address_space_available()	then
	--		min_texture_lod = 1
	--	end
	--end

	--self.texture_lod_track:SetOptIBounds(min_texture_lod, max_texture_lod)
end

function options_dialog:InitCallBacks()
	self:AddCallback("tab",					ui_events.TAB_CHANGED,		self.OnTabChange,			self)
	self:AddCallback("btn_advanced_graphic",ui_events.BUTTON_CLICKED,	self.OnBtnAdvGraphic,		self)
	self:AddCallback("btn_accept",			ui_events.BUTTON_CLICKED,	self.OnBtnAccept,			self)
	self:AddCallback("btn_cancel",			ui_events.BUTTON_CLICKED,	self.OnBtnCancel,			self)
	self:AddCallback("btn_default_graphic",	ui_events.BUTTON_CLICKED,	self.OnBtnDefGraph,			self)
	self:AddCallback("btn_default_sound",	ui_events.BUTTON_CLICKED,	self.OnBtnDefSound,			self)
	self:AddCallback("combo_renderer",		ui_events.LIST_ITEM_SELECT,	self.UpdateDependControls,	self)
	self:AddCallback("combo_preset",		ui_events.LIST_ITEM_SELECT,	self.OnPresetChanged,		self)
	self:AddCallback("check_retromode",		ui_events.BUTTON_CLICKED,	self.OnRetromodeChanged,	self)
	self:AddCallback("btn_retromode_graphic",ui_events.BUTTON_CLICKED,	self.OnBtnRetromodeGraphic,	self)
	self:AddCallback("btn_retromode_simply",ui_events.BUTTON_CLICKED,	self.OnSimplyRetromode,		self)
	self:AddCallback("btn_simply_graphic",	ui_events.BUTTON_CLICKED,	self.OnSimplyGraphic,		self)
	self:AddCallback("btn_keyb_default",	ui_events.BUTTON_CLICKED,	self.OnBtnKeyDefault,		self)
	self:AddCallback("check_crosshair",		ui_events.BUTTON_CLICKED,	self.OnCheckCrossChanged,	self)

	self:AddCallback("btn_cancel_download",	ui_events.BUTTON_CLICKED,	self.OnBtn_CancelDownload,	self)

	self:AddCallback("mb",					ui_events.MESSAGE_BOX_YES_CLICKED, self.OnApplyChanges, self)
	self:AddCallback("mb",					ui_events.MESSAGE_BOX_NO_CLICKED, self.OnDiscardChanges,self)
end

function options_dialog:OnBtnKeyDefault()
	local console			= get_console()
	console:execute			("default_bindings")

	local opt				= COptionsManager()
	opt:SetCurrentValues	("mm_opt_controls")
	opt:SetCurrentValues	("key_binding")
end

function options_dialog:OnPresetChanged()
	local opt					= COptionsManager()
	opt:SetCurrentValues		("mm_opt_video")
	opt:SetCurrentValues		("mm_opt_video_adv")
end

function options_dialog:OnCheckCrossChanged()
	self.check_crosshair_cross:Enable(self.check_crosshair:GetCheck())
	self.check_dyn_crosshair:Enable(self.check_crosshair:GetCheck())
	self.check_hud_info:Enable(self.check_crosshair:GetCheck())
end


function options_dialog:OnRetromodeChanged()
	self:UpdateDependControls()
	local get_check = self.check_retromode:GetCheck()
	self.btn_retromode:Enable(get_check)
end

function options_dialog:OnBtnDefGraph()
	local opt = COptionsManager()
	opt:SendMessage2Group("mm_opt_video","set_default_value")
	opt:SendMessage2Group("mm_opt_video_retromode","set_default_value")
end

function options_dialog:OnBtnDefSound()
	local opt = COptionsManager()
	opt:SendMessage2Group("mm_opt_sound","set_default_value")
end

function options_dialog:OnBtnAccept()

	local opt = COptionsManager()
	local console = get_console()

	console:execute("cfg_save tmp")

	opt:SaveValues("mm_opt_video_preset")
	opt:SaveValues("mm_opt_controls")
	opt:SaveValues("key_binding")
	opt:SaveValues("mm_opt_video")
	opt:SaveValues("mm_opt_video_adv")
	opt:SaveValues("mm_opt_video_retromode")
	opt:SaveValues("mm_opt_gameplay")
	opt:SaveValues("mm_opt_sound")
	opt:SaveValues("mm_opt_controls")

	if opt:NeedVidRestart() then
		_G.b_discard_settings_shown = true
		self.message_box:Init("message_box_accept_vid_restart")
		self.message_box:SetText(string.format("%s %d% s", game.translate_string("ui_mm_confirm_changes"), 15, game.translate_string("mp_si_sec")))
		self:GetHolder():start_stop_menu(self.message_box,true)
	else
		self:OnApplyChanges()
		opt:OptionsPostAccept()
		console:execute("cfg_save")
	end
end

function options_dialog:OnBtnCancel()
	local opt = COptionsManager()
	opt:UndoGroup("mm_opt_video_preset")
	opt:UndoGroup("mm_opt_video")
	opt:UndoGroup("mm_opt_video_adv")
	opt:UndoGroup("mm_opt_video_retromode")
	opt:UndoGroup("mm_opt_sound")
	opt:OptionsPostAccept()

	self:GetHolder():start_stop_menu	(self.owner, true) --new(show main window)
	self:GetHolder():start_stop_menu	(self,true)
	self.owner:Show						(true)
end

function options_dialog:OnTabChange()
	self.dlg_video:Show		(false)
	self.dlg_sound:Show		(false)
	self.dlg_gameplay:Show	(false)
	self.dlg_controls:Show	(false)
	self.dlg_video_adv:Show	(false)
	self.dlg_video_retromode:Show(false)

	local ids = self.tab:GetActiveId()
	if ids == "video" then
		self.dlg_video:Show(true)
	elseif ids == "sound" then
		self.dlg_sound:Show(true)
	elseif ids == "gameplay" then
		self.dlg_gameplay:Show(true)
		self.check_crosshair_cross:Enable(self.check_crosshair:GetCheck())
		self.check_dyn_crosshair:Enable(self.check_crosshair:GetCheck())
		self.check_hud_info:Enable(self.check_crosshair:GetCheck())
	elseif ids == "controls" then
		self.dlg_controls:Show(true)
	end
end

function options_dialog:OnBtnAdvGraphic()
	self.dlg_video:Show		(false)
	self.dlg_video_adv:Show	(true)
end

function options_dialog:OnSimplyGraphic()
	self.dlg_video:Show		(true)
	self.dlg_video_adv:Show	(false)
end

function options_dialog:OnBtnRetromodeGraphic()
	self.dlg_video:Show(false)
	self.dlg_video_retromode:Show(true)
	self:UpdateDependRetromodeControls()
end

function options_dialog:OnSimplyRetromode()
	self.dlg_video:Show(true)
	self.dlg_video_retromode:Show(false)
end

function options_dialog:UpdateDependRetromodeControls()
	self.scroll_v_retromode:Clear()
	for i,j in pairs(self.m_preconditions_retromode) do
		self.scroll_v_retromode:AddWindow(j.control, true)
		j.control:SetAutoDelete(false)
	end
end

function options_dialog:OnKeyboard(dik, keyboard_action)
	local res = CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)

	if res==false then

		local bind = dik_to_bind(dik)

		if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
			if dik == DIK_keys.DIK_ESCAPE then
				if self.dlg_video_retromode:IsShown() then
					self.dlg_video_retromode:Show(false)
					self.dlg_video:Show(true)
				elseif self.dlg_video_adv:IsShown() then
					self.dlg_video_adv:Show	(false)
					self.dlg_video:Show		(true)
				else
					self:GetHolder():start_stop_menu	(self.owner, true) --new(show main window)
					self:GetHolder():start_stop_menu	(self,true)
					self.owner:Show						(true)
				end
			end

		end
	end
	   
	return res
end

function options_dialog:Update()
	CUIScriptWnd.Update(self)

	if(_G.b_discard_settings_shown) then
		local tg = math.floor(time_global_async()/1000)
		if(self.timer==nil) then
			self.timer = tg
		end
		self.message_box:SetText(string.format("%s %d %s", game.translate_string("ui_mm_confirm_changes"), 15-(tg-self.timer), game.translate_string("ui_st_secs")))
		if(tg-self.timer>=15) then
			self.owner:GetHolder():start_stop_menu	(self.message_box,true)
			self:OnDiscardChanges()
		end
	end
end

function options_dialog:OnApplyChanges()
	self.timer = nil
	_G.b_discard_settings_shown = false

	self:GetHolder():start_stop_menu	(self.owner, true)
	self:GetHolder():start_stop_menu	(self,true)
	self.owner:Show(true)
	
	local opt = COptionsManager()
	opt:OptionsPostAccept()
	get_console():execute("cfg_save")

	if false==self.b_restart_system_shown then
		local opt = COptionsManager()
		if opt:NeedSystemRestart() then
			self.b_restart_system_shown = true
			self.message_box:Init("message_box_restart_game")
			self.owner:GetHolder():start_stop_menu(self.message_box,true)
		end
	end
end

function options_dialog:OnDiscardChanges()
	self.timer = nil
	_G.b_discard_settings_shown = false

	local c = get_console()
	c:execute("cfg_load tmp")

	self:SetCurrentValues()

	c:execute("vid_restart")
	c:execute("cfg_save")
end

function options_dialog:OnMenuReloaded()
	if(_G.b_discard_settings_shown) then
		self.message_box:Init("message_box_accept_vid_restart")
		self.message_box:SetText(string.format("%s %d% s", game.translate_string("ui_mm_confirm_changes"), 15, game.translate_string("ui_st_secs")))
		self:GetHolder():start_stop_menu(self.message_box,true)
	end
end
