-- File:        UI_MAIN_MENU.SCRIPT
-- Description: Load Dialog for STALKER
-- Created:     28.10.2004
-- Lasd edit:	18.01.2006
-- Copyright:   2004 GSC Game World
-- Author:      Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
-- Version:     0.9

_G.xvars = get_stored_vars()

class "main_menu" (CUIScriptWnd)

function main_menu:__init() super()
	self.mbox_mode = 0
   	self:InitControls()
   	self:InitCallBacks()
end

function main_menu:__finalize()

end

function main_menu:InitControls()
	self:Init(0,0,1024,768)
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_mm_main.xml")

	xml:InitStatic("back_video", self)
	xml:InitStatic("background", self) 
	xml:InitStatic("fire_ugli_new", self)
	xml:InitStatic("fire_movie", self)
	xml:InitStatic("back_shniaga", self)
	if xml:NavigateToNode("back_left", 0) then
		xml:InitStatic("back_left", self)
	end
	if xml:NavigateToNode("back_right", 0) then
		xml:InitStatic("back_right", self)
	end
	self.main_frame = 	xml:InitStatic("shniaga_wnd", self)

	self.btn_new_game 		= xml:Init3tButton("shniaga_wnd:btn_new_game",			self.main_frame)
	self.btn_load			= xml:Init3tButton("shniaga_wnd:btn_load",				self.main_frame)
	self.btn_lastsave		= xml:Init3tButton("shniaga_wnd:btn_lastsave",			self.main_frame)
	self.btn_save			= xml:Init3tButton("shniaga_wnd:btn_save",				self.main_frame)
	self.btn_options		= xml:Init3tButton("shniaga_wnd:btn_options",			self.main_frame)
	self.btn_quit			= xml:Init3tButton("shniaga_wnd:btn_quit",				self.main_frame)
	self.btn_quit_to_mm		= xml:Init3tButton("shniaga_wnd:btn_quit_to_mm",		self.main_frame)
	self.btn_offset_y		= xml:ReadAttribFlt("shniaga_wnd", 0, "btn_offset_y", 22)
	self.btn_offset2_y		= xml:ReadAttribFlt("shniaga_wnd", 0, "btn_offset2_y", 22)
	
	self.btn_new_game:SetWindowName("btn_new_game")
	self.btn_load:SetWindowName("btn_load")
	self.btn_lastsave:SetWindowName("btn_lastsave")
	self.btn_save:SetWindowName("btn_save")
	self.btn_options:SetWindowName("btn_options")
	self.btn_quit_to_mm:SetWindowName("btn_quit_to_mm")
	self.btn_quit:SetWindowName("btn_quit")

	-- регистрация обработчика (как раньше)
	self:Register(self.btn_new_game)
	self:Register(self.btn_load)
	self:Register(self.btn_lastsave)
	self:Register(self.btn_save)
	self:Register(self.btn_options)
	self:Register(self.btn_quit_to_mm)
	self:Register(self.btn_quit)

	self.btn_novice 	= xml:Init3tButton("shniaga_wnd:btn_novice",	self.main_frame)
	self.btn_stalker	= xml:Init3tButton("shniaga_wnd:btn_stalker",	self.main_frame)
	self.btn_veteran	= xml:Init3tButton("shniaga_wnd:btn_veteran",	self.main_frame)
	self.btn_master		= xml:Init3tButton("shniaga_wnd:btn_master",	self.main_frame)
	self.btn_back		= xml:Init3tButton("shniaga_wnd:btn_back",		self.main_frame)
	self.btn_ret		= xml:Init3tButton("shniaga_wnd:btn_ret",		self.main_frame)
	
	self.btn_novice:SetWindowName("btn_novice")
	self.btn_stalker:SetWindowName("btn_stalker")
	self.btn_veteran:SetWindowName("btn_veteran")
	self.btn_master:SetWindowName("btn_master")
	self.btn_back:SetWindowName("btn_back")
	self.btn_ret:SetWindowName("btn_ret")

	self:Register(self.btn_novice)
	self:Register(self.btn_stalker)
	self:Register(self.btn_veteran)
	self:Register(self.btn_master)
	self:Register(self.btn_back)
	self:Register(self.btn_ret)
	self.shniaga = xml:InitMMShniaga("shniaga_wnd",self)
	if level.present() then
		if db.actor ~= nil and db.actor:alive() then
			self:ShowTabs("main_loaded")
		else
			self:ShowTabs("main_dead")
		end
	else
		self:ShowTabs("main")
	end
	self.btn_save:Enable(level.present())


	self.message_box = CUIMessageBoxEx()
	self:Register(self.message_box, "msg_box")
	
	local _ver = xml:InitStatic		("static_version",self)
	local mm						= _G.main_menu.get_main_menu()
	_ver:SetText					(olr.modver)
	self:NeedCenterCursor			(true)
end

function main_menu:Show(f)
end

function main_menu:ShowTabs(menu_type)
	if menu_type == "main" or menu_type == "main_loaded" or menu_type == "main_dead" then
		self.btn_novice:Show(false)
		self.btn_stalker:Show(false)
		self.btn_veteran:Show(false)
		self.btn_master:Show(false)
		self.btn_back:Show(false)

		self.btn_novice:Enable(false)
		self.btn_stalker:Enable(false)
		self.btn_veteran:Enable(false)
		self.btn_master:Enable(false)
		self.btn_back:Enable(false)

		self.btn_new_game:Show(menu_type == "main")
		self.btn_quit_to_mm:Show(menu_type == "main_loaded" or menu_type == "main_dead")
		self.btn_ret:Show(menu_type == "main_loaded")

		self.btn_new_game:Enable(menu_type == "main")
		self.btn_quit_to_mm:Enable(menu_type == "main_loaded" or menu_type == "main_dead")
		self.btn_ret:Enable(menu_type == "main_loaded")
		
		if menu_type == "main_dead" then
			local x_pos, y_pos = self.btn_load:GetWndPosX(), self.btn_load:GetWndPosY()
			y_pos = y_pos + self.btn_offset_y
			self.btn_load:SetWndPos(x_pos, y_pos)

			x_pos, y_pos = self.btn_lastsave:GetWndPosX(), self.btn_lastsave:GetWndPosY()
			y_pos = y_pos + self.btn_offset_y
			self.btn_lastsave:SetWndPos(x_pos, y_pos)

			x_pos, y_pos = self.btn_options:GetWndPosX(), self.btn_options:GetWndPosY()
			y_pos = y_pos + self.btn_offset_y * 2
			self.btn_options:SetWndPos(x_pos, y_pos)
			self.btn_save:Show(false)
			self.btn_save:Enable(false)
		else
			self.btn_save:Show(menu_type == "main_loaded")
			self.btn_save:Enable(menu_type == "main_loaded")
			if menu_type == "main" then
				local x_pos, y_pos = self.btn_load:GetWndPosX(), self.btn_options:GetWndPosY()
				y_pos = y_pos + self.btn_offset2_y
				self.btn_options:SetWndPos(x_pos, y_pos)
			end
		end
		self.btn_load:Show(true)
		self.btn_lastsave:Show(true)
		self.btn_options:Show(true)
		self.btn_quit:Show(true)

		self.btn_load:Enable(true)
		self.btn_lastsave:Enable(self.shniaga:HasLastSave())
		self.btn_options:Enable(true)
		self.btn_quit:Enable(true)
	else
		self.btn_novice:Show(true)
		self.btn_stalker:Show(true)
		self.btn_veteran:Show(true)
		self.btn_master:Show(true)
		self.btn_back:Show(true)
		self.btn_options:Show(false)
		self.btn_quit_to_mm:Show(false)
		self.btn_ret:Show(false)
		self.btn_quit:Show(false)

		self.btn_novice:Enable(true)
		self.btn_stalker:Enable(true)
		self.btn_veteran:Enable(true)
		self.btn_master:Enable(true)
		self.btn_back:Enable(true)
		self.btn_options:Enable(false)
		self.btn_quit_to_mm:Enable(false)
		self.btn_ret:Enable(false)
		self.btn_quit:Enable(false)

		self.btn_load:Enable(false)
		self.btn_lastsave:Enable(false)
		self.btn_save:Enable(false)
	end
end


function main_menu:InitCallBacks()
	-- new game
	self:AddCallback("btn_new_game",	ui_events.BUTTON_CLICKED,				self.OnButton_new_game_clicked,		self)
	self:AddCallback("btn_novice",		ui_events.BUTTON_CLICKED,				self.OnButton_new_novice_game,		self)
	self:AddCallback("btn_stalker",		ui_events.BUTTON_CLICKED,				self.OnButton_new_stalker_game,		self)
	self:AddCallback("btn_veteran",		ui_events.BUTTON_CLICKED,				self.OnButton_new_veteran_game,		self)
	self:AddCallback("btn_master",		ui_events.BUTTON_CLICKED,				self.OnButton_new_master_game,		self)
	self:AddCallback("btn_back",		ui_events.BUTTON_CLICKED,				self.OnButton_new_btn_back,			self)
	self:AddCallback("btn_spawn",		ui_events.BUTTON_CLICKED,				self.OnButton_load_spawn,			self)
	-- options																											
	self:AddCallback("btn_options",     ui_events.BUTTON_CLICKED,				self.OnButton_options_clicked,		self)
	-- load																												
	self:AddCallback("btn_load",        ui_events.BUTTON_CLICKED,				self.OnButton_load_clicked,			self)
	-- save																												
	self:AddCallback("btn_save",		ui_events.BUTTON_CLICKED,				self.OnButton_save_clicked,			self)
	-- quit																												
	self:AddCallback("btn_quit",		ui_events.BUTTON_CLICKED,				self.OnButton_quit_clicked,			self)
	self:AddCallback("btn_quit_to_mm",	ui_events.BUTTON_CLICKED,				self.OnButton_disconnect_clicked,	self)
	self:AddCallback("btn_ret",			ui_events.BUTTON_CLICKED,				self.OnButton_return_game,			self)
	self:AddCallback("btn_lastsave",	ui_events.BUTTON_CLICKED,				self.OnButton_last_save,			self)
	self:AddCallback("btn_credits",		ui_events.BUTTON_CLICKED,				self.OnButton_credits_clicked,		self)
	-- message box
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_OK_CLICKED,		self.OnMsgOk,						self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_CANCEL_CLICKED,	self.OnMsgCancel,					self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_YES_CLICKED,		self.OnMsgYes,						self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_NO_CLICKED,		self.OnMsgNo,						self)
	self:AddCallback("msg_box",			ui_events.MESSAGE_BOX_QUIT_GAME_CLICKED,self.OnMessageQuitGame,				self)
	self:AddCallback("msg_box",			ui_events.MESSAGE_BOX_QUIT_WIN_CLICKED,	self.OnMessageQuitWin,				self)
end
function main_menu:OnMsgOk()
	self.mbox_mode = 0
end

function main_menu:OnMsgCancel()
	self.mbox_mode = 0
end

function main_menu:OnMsgYes()
	
	if 	self.mbox_mode == 1 then
		self:LoadLastSave()	
	end

	self.mbox_mode = 0
end

function main_menu:OnMsgNo()
	self.mbox_mode = 0
end

function main_menu:LoadLastSave()
	local					console = get_console()
	console:execute			("main_menu off")
	console:execute			("load_last_save")
end

function main_menu:OnButton_new_game_clicked()
	self:ShowTabs("new_game")
end

function main_menu:OnButton_new_btn_back()
	if level.present() then
		if db.actor and db.actor:alive() then
			self:ShowTabs("main_loaded")
		else
			self:ShowTabs("main_dead")
		end
	else
		self:ShowTabs("main")
	end
end

function main_menu:OnButton_last_save()
	if (alife() == nil) then
		self:LoadLastSave	()
		return
	end
	
	self.mbox_mode			= 1
	self.message_box:Init	("message_box_confirm_load_save")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnButton_credits_clicked()
	game.start_tutorial("credits_seq")
end

function main_menu:OnButton_quit_clicked()
	self.message_box:Init("message_box_quit_windows")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnButton_disconnect_clicked()
	self.message_box:Init("message_box_quit_game")
	
	if (level.game_id() ~= 1) then		
		self.message_box:SetText("ui_mm_disconnect_message")	-- MultiPlayer
	else
		self.message_box:SetText("ui_mm_quit_game_message")		-- SinglePlayer
	end
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnMessageQuitGame()
	local console = get_console()
	console:execute("disconnect")
end

function main_menu:OnMessageQuitWin()
	local console = get_console()
	console:execute("quit")
end

function main_menu:OnButton_return_game()
	local console = get_console()
	console:execute("main_menu off")
end

function main_menu:OnButton_new_novice_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_novice")
	self:StartGame()	
end

function main_menu:OnButton_new_stalker_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_stalker")
	self:StartGame()
end

function main_menu:OnButton_new_veteran_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_veteran")
	self:StartGame()
end

function main_menu:OnButton_new_master_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_master")
	self:StartGame()
end

function main_menu:StartGame()
	local console = get_console()
	
	if (alife() ~= nil) then
		console:execute	("ehit")
	end
	
	console:execute("start server(olr/single/alife/new) client(localhost)")
	console:execute("main_menu off")
end

function main_menu:DisplayWnd(child, stop_self)
	if self.child_wnd ~= nil and self.child_wnd:IsShown() then
		self:StopWnd(self.child_wnd)
	end

	self:GetHolder():start_stop_menu(child, true)
	child.owner = self
	self.child_wnd = child
	
	if stop_self then
		self:GetHolder():start_stop_menu(self, true)
		self:Show(false)
	end
end

function main_menu:StopWnd(child)
	-- always return self visibility
	
	if not self:IsShown() then
		child:GetHolder():start_stop_menu(self, true)
		self:Show(true)
	end
	
	child:GetHolder():start_stop_menu(child, true)
	child:Show(false)
	self.child_wnd = nil
end

function main_menu:OnButton_load_spawn()
	if self.spawn_dlg == nil then
		self.spawn_dlg = ui_spawn_dialog.spawn_dialog()
		self.spawn_dlg.owner = self
	end
	
	self:GetHolder():start_stop_menu(self.spawn_dlg, true)
	self:GetHolder():start_stop_menu(self, true) --new
	self:Show(false)
	self:NeedCenterCursor(false)
end

function main_menu:OnButton_save_clicked()
	if self.save_dlg == nil then
		self.save_dlg = ui_save_dialog.save_dialog()
		self.save_dlg.owner = self
	end
	
	self:GetHolder():start_stop_menu(self.save_dlg, true)
	self:GetHolder():start_stop_menu(self, true) --new
	self:Show(false)
	self:NeedCenterCursor(false)
end

function main_menu:OnButton_options_clicked()
	if self.opt_dlg == nil then
		self.opt_dlg = ui_mm_opt_main.options_dialog()
		self.opt_dlg.owner = self
	end
	
	self.opt_dlg:UpdateControls()
	self:GetHolder():start_stop_menu(self.opt_dlg, true)
	self:GetHolder():start_stop_menu(self, true) --new
	self:Show(false)
	self:NeedCenterCursor(false)
end

function main_menu:OnButton_load_clicked()
	if self.load_dlg ==nil then
		self.load_dlg = ui_load_dialog.load_dialog()
		self.load_dlg.owner = self
	end
	
	self:GetHolder():start_stop_menu(self.load_dlg, true)
	self:GetHolder():start_stop_menu(self, true) --new
	self:Show(false)
	self:NeedCenterCursor(false)
end

function main_menu:OnButton_show_toolskit_menu() --/#+# (debug tools)
	if (ui_hud_toolskit) then --/ and self:check_game()
		if not self.toolskit_dlg then
			self.toolskit_dlg = ui_hud_toolskit.get_ui_menu()
			self.toolskit_dlg.owner = self
		end
		self:GetHolder():start_stop_menu(self.toolskit_dlg, true)
	end
	self:NeedCenterCursor(false)
end

function main_menu:OnButton_show_spawn_menu() --/#+# (debug spawn)
	if (ui_spawn_menu) then --/ and self:check_game()
		if not self.spaw_dlg then
			self.spawn_dlg = ui_spawn_menu.get_ui_menu()
			self.spawn_dlg.owner = self
		end
		self:DisplayWnd(self.spawn_dlg, true)
	end
	self:NeedCenterCursor(false)
end

function main_menu:OnKeyboard(dik, keyboard_action) --virtual function
    CUIScriptWnd.OnKeyboard(self, dik, keyboard_action)
    local bind = dik_to_bind(dik)
    local console = get_console()

    if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if not level.present() and dik == DIK_keys.DIK_ESCAPE then
			self:ShowTabs("main")
		end
	end
    if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
        if level.present() and (db.actor ~= nil) and db.actor:alive() then
            if dik == DIK_keys.DIK_ESCAPE then
                self:OnButton_return_game()
            elseif dik == DIK_keys.DIK_F2 then
                self:OnButton_show_toolskit_menu()
            elseif dik == DIK_keys.DIK_F3 then
                self:OnButton_show_spawn_menu()
            end
        end

        if dik == DIK_keys.DIK_Q then
            self:OnMessageQuitWin()
        end

        if olr.olrdbg == true then
            if dik == DIK_keys.DIK_F then
                get_console():execute("demo_record 1")
                get_console():execute("main_menu off")
            end

            if dik == DIK_keys.DIK_S and alife() == nil then
                self:OnButton_load_spawn()
            end

            if dik == DIK_keys.DIK_D then
                if olr_timers.has_timer("zombies_task_select_timer") then
                    log1(" zombies_task_select_timer HAS")
                end
                if olr_timers.has_timer("dogs_task_select_timer") then
                    log1(" dogs_task_select_timer HAS")
                end
                if olr_timers.has_timer("artefact_merger_timer") then
                    log1(" artefact_merger_timer HAS")
                end
                if olr_timers.has_timer("oms3") then
                    log1(" oms3 HAS")
                end
                olr_timers.dump_timers()
                get_console():execute("main_menu off")
            end

            if dik == DIK_keys.DIK_S then
                for key, value in pairs(xvars()) do
                    log1(" " .. key .. " = " .. tostring(value) .. "")
                    get_console():execute("main_menu off")
                end
            --for key, value in pairs(xvars.dead_in_offline()) do
            --	log1(" dead_in_offline table -  "..key.." = "..tostring(value).."")
            --	get_console():execute("main_menu off")
            --end
            end

            if dik == DIK_keys.DIK_R then
                _G.nnnn = nil
                get_console():execute("main_menu off")
                log1("nnnn script reloaded")
            end

            if dik == DIK_keys.DIK_T then
                smart_terrain.stat()
                get_console():execute("main_menu off")
            end

            if dik == DIK_keys.DIK_NUMPAD1 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl1_escape")
            end

            if dik == DIK_keys.DIK_NUMPAD5 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl5_bar")
            end

            if dik == DIK_keys.DIK_NUMPAD2 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl2_garbage")
            end

            if dik == DIK_keys.DIK_NUMPAD3 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl3_agroprom")
            end

            if dik == DIK_keys.DIK_NUMPAD4 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl4_darkdolina")
            end

            if dik == DIK_keys.DIK_NUMPAD5 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl5_bar")
            end

            if dik == DIK_keys.DIK_NUMPAD6 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl6_rostok")
            end

            if dik == DIK_keys.DIK_NUMPAD7 then
                get_console():execute("main_menu off")
                get_console():execute("jump_to_level lvl7_yantar")
            end

            if dik == DIK_keys.DIK_NUMPAD8 then
                game.start_tutorial("credits_seq")
            end
        end
    end

    return true
end