class "opt_gameplay" (CUIWindow)

function opt_gameplay:__init() super()
end

function opt_gameplay:__finalize()

end

function opt_gameplay:InitControls(x, y, xml, handler)

	self:Init(x,y, 738, 416)
	self:SetAutoDelete(true)
	
	self.bk = xml:InitFrame("frame_gameplay", self)
	
	xml:InitStatic("tab_gameplay:cap_hud_type",			self)
	xml:InitStatic("tab_gameplay:cap_pda_type",			self)
	xml:InitStatic("tab_gameplay:cap_language",			self)
	xml:InitStatic("tab_gameplay:cap_difficulty",		self)
	
	--xml:InitCheck("tab_gameplay:check_tips",			self)
	xml:InitCheck("tab_gameplay:check_crosshair",		self)
	xml:InitCheck("tab_gameplay:check_dyn_crosshair", 	self)
	xml:InitCheck("tab_gameplay:check_show_weapon", 	self)
	xml:InitCheck("tab_gameplay:check_dist", 			self)
	xml:InitCheck("tab_gameplay:check_hud_info", 		self)
	xml:InitCheck("tab_gameplay:check_buildobobbing", 	self)
	xml:InitCheck("tab_gameplay:check_debug_info", 		self)
	xml:InitCheck("tab_gameplay:check_inv_sorting", 	self)
	xml:InitComboBox("tab_gameplay:list_pda_type",		self)
	xml:InitComboBox("tab_gameplay:list_hud_type",		self)
	xml:InitComboBox("tab_gameplay:list_language",		self)
	xml:InitComboBox("tab_gameplay:list_difficulty",	self)
end
