-- File:        UI_SAVE_DIALOG.SCRIPT
-- Description: Save Dialog for STALKER
-- Created:     27.9.2004
-- Author:      Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
-- Copyright:   2004 GSC Game World
-- Version:     0.8

class "save_item" (CUIListItemEx)
local xml_init

function save_item:__init() super()
	self:SetWndRect		(0,0,430,22)

	local ca = 255
	local cr = 216
	local cg = 186
	local cb = 140

	local fn_size_x 				= xml_init:ReadAttribFlt("filename", 0, "size_x", 230)
	local fn_size_y 				= xml_init:ReadAttribFlt("filename", 0, "size_y", 22)
	self.fn							= CUIStatic	()
	self.fn:SetAutoDelete			(true)
	self:AttachChild				(self.fn)
	self.fn:SetWndRect				(0,0,fn_size_x,fn_size_y)
	self.fn:SetTextColoringMode		(false)
	self.fn:SetText					("filename")
	self.fn:SetFont					(GetFontLetterica18())
	self.fn:SetTextColor			(cr,cg,cb,ca)
	self.fn:SetCutWordsMode			(true)

	local fileage_size_x 			= xml_init:ReadAttribFlt("fileage", 0, "size_x", 230)
	local fileage_size_y 			= xml_init:ReadAttribFlt("fileage", 0, "size_y", 22)
	local fileage_pos_x 			= xml_init:ReadAttribFlt("fileage", 0, "pos_x", 250)
	self.fage						= CUIStatic	()
	self.fage:SetAutoDelete			(true)
	self:AttachChild				(self.fage)
	self.fage:SetWndRect			(fileage_pos_x,0,fileage_size_x,fileage_size_y)
	self.fage:SetTextColoringMode	(false)
	self.fage:SetText				("fileage")
	self.fage:SetFont				(GetFontLetterica18())
	self.fage:SetTextColor			(cr,cg,cb,ca)
	self.fage:SetTextAlign(CGameFont.alRight)
end


class "save_dialog" (CUIScriptWnd)

function save_dialog:__init() super()
	self:InitControls()
	self:InitCallBacks()
	self:FillList()
end

function save_dialog:__finalize()

end

function save_dialog:FillList()
	local flist = getFS():file_list_open_ex("$game_saves$",FS.FS_ListFiles,"*.sav")
	local f_cnt = flist:Size()

	flist:Sort(FS.FS_sort_by_modif_down)

	for	it=0, f_cnt-1 	do
		local file		=	flist:GetAt(it)
		local file_name = string.sub(file:NameFull(), 0, (string.len(file:NameFull()) - 4))
		local date_time = "[" .. file:ModifDigitOnly() .. "]"
		--menu_item =  .. 
		self:AddItemToList(file_name, date_time)
	end
end

function save_dialog:InitControls()
	self:Init(0,0,1024,768)

	self.list_file_font = GetFontMicron12()
	self.list_date_font = GetFontMicron12()

	xml_init = CScriptXmlInit()
	xml_init:ParseFile("ui_mm_save_dlg.xml")

	local ctrl

	xml_init:InitStatic("back_video", self)

	xml_init:InitStatic("background",				self)

	if xml_init:NavigateToNode("back_left", 0) then
		xml_init:InitStatic("back_left", self)
	end
	if xml_init:NavigateToNode("back_right", 0) then
		xml_init:InitStatic("back_right", self)
	end
	xml_init:InitStatic("newspaper_video",			self)
	self.form = xml_init:InitStatic("form",			self)

	xml_init:InitStatic("form:caption",				self.form)

	ctrl = xml_init:InitEditBox("form:edit", 		self.form, true)
	self:Register(ctrl, "edit_filename")

	xml_init:InitFrame("form:list_frame",			self.form)

	ctrl = xml_init:InitList("form:list", 			self.form)
	ctrl:ShowSelectedItem(true)
	self:Register(ctrl, "list_window")

	ctrl = xml_init:Init3tButton("form:btn_save",	self)
	self:Register(ctrl, "button_ok")

	ctrl = xml_init:Init3tButton("form:btn_delete",	self)
	self:Register(ctrl, "button_del")

	ctrl = xml_init:Init3tButton("form:btn_cancel",	self)
	self:Register(ctrl, "button_cancel")

	self.message_box = CUIMessageBoxEx()
	self:Register(self.message_box,"message_box")

	self.mbox_mode	= 0
end

function save_dialog:InitCallBacks()
    -- main frame buttons
	self:AddCallback("button_ok",     ui_events.BUTTON_CLICKED, 			self.OnButton_ok_clicked,		self)
	self:AddCallback("button_cancel", ui_events.BUTTON_CLICKED, 			self.OnButton_cancel_clicked,	self)
	self:AddCallback("button_del",	  ui_events.BUTTON_CLICKED,             self.OnButton_del_clicked,	self)

	self:AddCallback("message_box", ui_events.MESSAGE_BOX_YES_CLICKED,		self.OnMsgYes,					self)
	self:AddCallback("list_window", ui_events.LIST_ITEM_CLICKED, 			self.OnListItemClicked,			self)
end

function save_dialog:OnListItemClicked()
	local list_box		= self:GetListWnd("list_window")
	if list_box:GetSize()==0 then return end

	local edit_box		= self:GetEditBox("edit_filename")
	local item_id		= list_box:GetFocusedItem()
	local item			= list_box:GetItem(item_id)

	if item==nil then return end

	local item_text		= item.fn:GetText()
	edit_box:SetText	(item_text)
end

function save_dialog:OnMsgYes()
	if self.mbox_mode == 1 then
		self:SaveFile(self.new_save)

		self:GetHolder():start_stop_menu	(self.owner, true) --new
		self:GetHolder():start_stop_menu	(self,true)
		self.owner:Show						(true)

	elseif self.mbox_mode == 2 then
		self:delete_selected_file()
	end
end

function save_dialog:OnButton_del_clicked()

	local list		= self:GetListWnd		("list_window")
	if list:GetSize()==0 then return end

	local index		= list:GetSelectedItem	()

	if index == -1 then return end

	self.mbox_mode = 2
	self.message_box:Init("message_box_delete_file_name")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function save_dialog:delete_selected_file()
	local list		= self:GetListWnd		("list_window")
	if list:GetSize()==0 then return end
	local index		= list:GetSelectedItem	()

	if index == -1 then return end

	local item				= list:GetItem(index)
	local filename			= item.fn:GetText()

	ui_load_dialog.delete_save_game(filename)

	list:RemoveItem			(index)
	self:OnListItemClicked	()
end

function save_dialog:OnButton_ok_clicked()
	-- prepare message box
	local message_box	= self.message_box
	local main_frame	= self:GetFrameWindow("main_frame")

	-- Get file name
	local edit_box		= self:GetEditBox("edit_filename")
	self.new_save		= edit_box:GetText()

	-- check for empty name
	if string.len(self.new_save) == 0 then
		self.mbox_mode = 0
		self.message_box:Init("message_box_empty_file_name")
		self:GetHolder():start_stop_menu(self.message_box, true)
		return
	end

	-- check for match name
	local f = getFS()
	local flist = f:file_list_open("$game_saves$",FS.FS_ListFiles)
	local file_struct = f:exist("$game_saves$", self.new_save .. ".sav" )

	if file_struct ~= nil then
		self.mbox_mode = 1
		self.message_box:Init("message_box_file_already_exist")
		self:GetHolder():start_stop_menu(self.message_box, true)

		flist:Free()
		return
	end
	flist:Free()
	self:SaveFile(self.new_save)

	self:GetHolder():start_stop_menu	(self.owner, true) --new
	self:GetHolder():start_stop_menu	(self,true)
	self.owner:Show						(true)
end

function save_dialog:OnButton_cancel_clicked()
	self:GetHolder():start_stop_menu	(self.owner, true) --new
	self:GetHolder():start_stop_menu	(self,true)
	self.owner:Show						(true)
end

function save_dialog:OnKeyboard(dik, keyboard_action)  --virtual function
   ui_base_dialog.base_dialog.OnKeyboard(self,dik,keyboard_action)
     
   DIK_RETURN = 28
   WINDOW_KEY_PRESSED = 6

	if dik == DIK_RETURN and keyboard_action == WINDOW_KEY_PRESSED then
		self:OnButton_ok_clicked()
		self.owner:Show(true)
	end
   
	return true
end

function save_dialog:AddItemToList(file_name, date_time)

	local _itm			= save_item()
	_itm.fn:SetText	(file_name)
	_itm.fage:SetText	(date_time)
	local list_box		= self:GetListWnd("list_window")
	list_box:AddItem	(_itm, 0)

end

function save_dialog:SaveFile(fileName)
	if nil~= fileName then
		local console = get_console()
		console:execute("save " .. fileName)
	end
end

