----------------------------------------------------------------------------------------------------------------------
--	Схема кемпер. Чудак с бальшой пушкой ходит и отстреливает живность.
--	автор: Диденко Руслан (Stohe)
--	TODO: 
----------------------------------------------------------------------------------------------------------------------

local def_ignore_distance			= 150
local def_ignore_distance_grenade	= 15
local def_ignore_distance_corpse	= 10
local def_ignore_distance_hit		= 150
local def_ignore_distance_sound		= 50

local def_danger_inertion_time_grenade	= 20000
local def_danger_inertion_time_corpse	= 10000
local def_danger_inertion_time_hit		= 60000
local def_danger_inertion_time_sound	= 15000
local def_danger_inertion_time_ricochet	= 30000

local engage_after_update	= 5
local count_update			= {}

local always_ignore_danger_from = { m_car = "true" }

--костыль против дебилизма непися - реакция на взрыв гранаты из гренадера, возможно при наличии укрытий на карте будет адекватнее себя вести, хз
for k,v in pairs(xrs_grenade.gr_types) do
	always_ignore_danger_from[v.."_fake"] = "true"
end

----------------------------------------------------------------------------------------------------------------------
-- EVALUATORS
----------------------------------------------------------------------------------------------------------------------
-- true - есть danger, false - нет danger
class "evaluator_danger" (property_evaluator)
function evaluator_danger:__init(name, storage, npc) super (nil, name)
	self.a = storage

	self.is_zombied = npc:section() == "stalker_zombied"
end
function evaluator_danger:evaluate()

	if count_update[self.object:id()] and count_update[self.object:id()] <= engage_after_update then
		count_update[self.object:id()] = count_update[self.object:id()] + 1
		return false
	elseif not count_update[self.object:id()] then
		count_update[self.object:id()] = 0
		return false			
	end	
	
	if not self.object:alive() then
		return false			
	end	

	if self.mgr == nil then
		self.mgr = self.object:motivation_action_manager()
	end	

	local best_danger = self.object:best_danger()

	-- проверка на денжер.
	if best_danger == nil then
		self.danger_time = nil
		return false
	end

	local active_scheme = db.storage[self.object:id()].active_scheme
	local bd_type = best_danger:type()
	local best_danger_object = best_danger:object()

	if bd_type ~= danger_object.grenade and best_danger:dependent_object() ~= nil then
		best_danger_object = best_danger:dependent_object()
	end
	
	-- Проверяем наличие объекта денжера.
	if best_danger_object == nil then
		return false
	end

	local best_danger_name = best_danger_object:name()
	local best_danger_section_name = best_danger_object:section()
	local is_monster_obj = IsMonster(best_danger_object)
	local is_stalker_obj = IsStalker(best_danger_object)
	local is_still_alive = best_danger_object:alive()

	-- проверка не находится ли денжер в списке вечнозапрещенных.(БТР, Вертолеты и тд)
	if best_danger_section_name ~= nil then
		if always_ignore_danger_from[best_danger_section_name] == "true" then
			return false
		end
	end

	-- Не триггерится на мёртвых
	if is_monster_obj or is_stalker_obj then
		if is_still_alive == false and bd_type ~= danger_object.entity_corpse then
			return false
		end
	else
		if bd_type == danger_object.enemy_sound then
			return false
		end
	end

	-- отключённое отключение денжера если мутант или сталкер дальше энного кол-ва метров
	if is_monster_obj then
		--if not self.object:see(best_danger_object) and best_danger_object:position():distance_to(self.object:position()) > 40 then
		--	return false
		--end
	elseif is_stalker_obj then
		--if not self.object:see(best_danger_object) and is_still_alive and not best_danger_object:see(self.object) and best_danger_object:position():distance_to(self.object:position()) > 150 then
		--	return false
		--end
	end

	-- На самого себя не триггерится
	if is_stalker_obj and best_danger_object:id() == self.object:id() then
		-- три года на зоне, вся жопа в шрамах, сам себя боюсь
		return false
	end

	-- Проверка на запрещенный денжер от актера
	if best_danger_object ~= nil and
	   best_danger_object:id() == db.actor:id() and
	   (bd_type == danger_object.attack_sound or
	   bd_type == danger_object.bullet_ricochet)
	then
		if self.object:best_enemy() == nil and
		   self.object:relation(db.actor) ~= game_object.enemy
		then
			return false
		end
	end

	-- Игнорим денжеры от своих.
	if bd_type == danger_object.attack_sound or bd_type == danger_object.enemy_sound then
		if is_stalker_obj and (best_danger_object:character_community() == self.object:character_community()
		or ((self.object:relation(best_danger_object) ~= game_object.enemy) and (best_danger_object:relation(self.object) ~= game_object.enemy))) then
			if not best_danger_object:best_enemy() and not best_danger_object:best_danger() then
				return false
			end
		end
	end

	-- Проверка, не находится ли данжер в списке запрещенных.
	if bd_type == danger_object.grenade then
		if self.object:character_community() == "zombied" then
		--	printf("DANGER [%s] [FALSE] ignore grenade for community [zombied]", self.object:name())
			return false
		end	
		if self.a and self.a.ignore_types and self.a.ignore_types["grenade"] == true then
	--		printf("DANGER [%s] [FALSE] ignore grenade", self.object:name())
			return false		
		end
	elseif bd_type == danger_object.entity_corpse then
		if self.a.ignore_types["corpse"] == true then
			return false
		end
	elseif bd_type == danger_object.entity_attacked or
		   bd_type == danger_object.attacked then
		if self.a.ignore_types["hit"] == true then
			return false
		end
	elseif bd_type == danger_object.enemy_sound or
	       bd_type == danger_object.attack_sound or
	       bd_type == danger_object.entity_death then
		if self.a.ignore_types["sound"] == true then
			return false
		end
	end

	-- отсеиваем по настройке combat_ignore/danger
	db.storage[self.object:id()].enemy = best_danger:object()
	if db.storage[self.object:id()].enemy ~= nil then
	    local overrides = xr_logic.generic_scheme_overrides(self.object)
	    if overrides and
	    overrides.combat_ignore and
	    active_scheme ~= nil and
	    xr_logic.pick_section_from_condlist(db.actor, self.object, overrides.combat_ignore.condlist ) ~= nil
	    then
		    return false
	    end
    end

	-- Отсеиваем по дистанции
	if check_danger_distance(self.object, best_danger) == false then
		return false
	end

	-- Отсеиваем по зоне
	if sr_danger.check_danger_position(best_danger:position()) then
		return false
	end

	-- Отсеиваем по информационным рестрикторам
	if xr_gulag.is_info_restricted(self.object:id(), best_danger:position()) then
		return false
	end

	-- Отсеиваем тяжелораненых
	if xr_wounded.is_heavy_wounded_by_id(self.object:id()) then
		return false
	end

	-- Отсеиваем психораненых
	if xr_wounded.is_psy_wounded_by_id(self.object:id()) then
		return false
	end

	--[[
	-- Денжер для снайпера
	if active_scheme == "camper" then
		if best_danger:type() == danger_object.grenade then
			self.danger_time = best_danger:time()
			return true
		end
		return false
	else
		self.danger_time = best_danger:time()
		return true
	end
	
	-- инерция возврата. Только не для кемпера.
	if self.danger_time then
		self.danger_time = best_danger:time()
		local passed_time = time_global() - self.danger_time
		if check_danger_inertion_time(self.object, best_danger, passed_time) == true then
			return true
		else
			return false
		end
	end	
	--]]
	
	-- Денжер для снайпера
	if active_scheme == "camper" then
		if best_danger:type() == danger_object.grenade then
			self.danger_time = best_danger:time()
			return true
		end
		return false
	else
		self.danger_time = best_danger:time()
		-- инерция возврата. Только не для кемпера.
		if self.danger_time then
			-- self.danger_time = best_danger:time() <-- Дико непонятно нахуя тут вот это было. Убрал пока позырить
			local passed_time = time_global() - self.danger_time
			if check_danger_inertion_time(self.object, best_danger, passed_time) == true then
				return true
			else
				return false
			end
		end

	end	

	return false
end


----------------------------------------------------------------------------------------------------------------------
-- BINDER
----------------------------------------------------------------------------------------------------------------------
function add_to_binder(object, ini, scheme, section, storage)
  		local operators	= {}
	  	local properties  = {}
		
	   	local manager = object:motivation_action_manager()

--		if true then return end
		manager:remove_evaluator(stalker_ids.property_danger)
		manager:add_evaluator(stalker_ids.property_danger, this.evaluator_danger("danger", storage, object))
end
function set_danger(npc, ini, scheme, section)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
end

function reset_danger(npc, scheme, st, section)
	local mpow = math.pow
	local danger_section
	if scheme ~= nil and scheme ~= "nil" then
		danger_section = utils.cfg_get_string(st.ini, section, "danger", npc, false, "")
	end
	
	--printf("DANGER SECTION [%s]", utils.to_str(danger_section))
	st.danger.ignore_types = {}
	if danger_section then
		local t = parse_names(utils.cfg_get_string(st.ini, danger_section, "ignore_types", npc, false, "", ""))
		for k,v in pairs(t) do
			st.danger.ignore_types[v] = true
		end
	end
	st.danger.ignore_distance			=  mpow(utils.cfg_get_number(st.ini, danger_section, "ignore_distance", npc, false, def_ignore_distance), 2)
	st.danger.ignore_distance_grenade	=  mpow(utils.cfg_get_number(st.ini, danger_section, "ignore_distance_grenade", npc, false, def_ignore_distance_grenade), 2)
	st.danger.ignore_distance_corpse	=  mpow(utils.cfg_get_number(st.ini, danger_section, "ignore_distance_corpse", npc, false, def_ignore_distance_corpse), 2)
	st.danger.ignore_distance_hit		=  mpow(utils.cfg_get_number(st.ini, danger_section, "ignore_distance_hit", npc, false, def_ignore_distance_hit), 2)
	st.danger.ignore_distance_sound		=  mpow(utils.cfg_get_number(st.ini, danger_section, "ignore_distance_sound", npc, false, def_ignore_distance_sound), 2)

	st.danger.danger_inertion_time_grenade		=  utils.cfg_get_number(st.ini, danger_section, "danger_inertion_time_grenade", npc, false, def_danger_inertion_time_grenade)
	st.danger.danger_inertion_time_corpse		=  utils.cfg_get_number(st.ini, danger_section, "danger_inertion_time_corpse", npc, false, def_danger_inertion_time_corpse)
	st.danger.danger_inertion_time_hit			=  utils.cfg_get_number(st.ini, danger_section, "danger_inertion_time_hit", npc, false, def_danger_inertion_time_hit)	
	st.danger.danger_inertion_time_sound		=  utils.cfg_get_number(st.ini, danger_section, "danger_inertion_time_sound", npc, false, def_danger_inertion_time_sound)	
	st.danger.danger_inertion_time_ricochet		=  utils.cfg_get_number(st.ini, danger_section, "danger_inertion_time_ricochet", npc, false, def_danger_inertion_time_ricochet)
	-- Зомбированные сталкеры не убегают от гранаты, lvg_brest
	if npc then
		if npc:character_community()=="zombied" then
			st.danger.danger_inertion_time_grenade = utils.cfg_get_number(st.ini, danger_section, "danger_inertion_time_grenade", npc, false, 0)
		end
	end
end


function check_danger_inertion_time(npc, danger, passed_time)
	if not npc or not danger then return false end

	local danger_settings = db.storage[npc:id()].danger
	local bd_type = danger:type()
	if not bd_type then return false end

	if danger_settings ~= nil then
		if bd_type == danger_object.grenade then
			if danger_settings.danger_inertion_time_grenade and danger_settings.danger_inertion_time_grenade <= passed_time then
				return false
			end
		elseif bd_type == danger_object.entity_corpse then
			if danger_settings.danger_inertion_time_corpse and danger_settings.danger_inertion_time_corpse <= passed_time then
				return false
			end
		elseif bd_type == danger_object.entity_attacked or
			bd_type == danger_object.attacked then
			if danger_settings.danger_inertion_time_hit and danger_settings.danger_inertion_time_hit <= passed_time then
				return false
			end
		elseif bd_type == danger_object.enemy_sound or
			bd_type == danger_object.attack_sound or
	        bd_type == danger_object.entity_death then
			if danger_settings.danger_inertion_time_sound and danger_settings.danger_inertion_time_sound <= passed_time then
				return false
			end
		elseif bd_type == danger_object.bullet_ricochet then
			if danger_settings.danger_inertion_time_ricochet and danger_settings.danger_inertion_time_ricochet <= passed_time then
				return false
			end
		end
	else
		if bd_type == danger_object.grenade then
			if def_danger_inertion_time_grenade <= passed_time then
				return false
			end
		elseif bd_type == danger_object.entity_corpse then
			if def_danger_inertion_time_corpse <= passed_time then
				return false
			end
		elseif bd_type == danger_object.entity_attacked or
			bd_type == danger_object.attacked then
			if def_danger_inertion_time_hit <= passed_time then
				return false
			end
		elseif bd_type == danger_object.enemy_sound or
			bd_type == danger_object.attack_sound or
	        bd_type == danger_object.entity_death then
			if def_danger_inertion_time_sound <= passed_time then
				return false
			end
		elseif bd_type == danger_object.bullet_ricochet then
			if def_danger_inertion_time_ricochet <= passed_time then
				return false
			end
		end
	end
	return true
end

function check_danger_distance(npc, danger)
	if not npc or not danger then return false end

	local danger_settings = db.storage[npc:id()].danger
	local bd_type = danger:type()
	if not bd_type then return false end
	local danger_distance_sqr = danger:position():distance_to_sqr(npc:position())
	if not danger_distance_sqr or type(danger_distance_sqr) ~= "number" then return false end

	if danger_settings ~= nil then
		if danger_distance_sqr >= danger_settings.ignore_distance then
			return false
		end
		if bd_type == danger_object.grenade then
			if danger_distance_sqr >= danger_settings.ignore_distance_grenade then
				return false
			end
		elseif bd_type == danger_object.entity_corpse then
			if danger_distance_sqr >= danger_settings.ignore_distance_corpse then
				return false
			end
		elseif bd_type == danger_object.entity_attacked or
			   bd_type == danger_object.attacked then
			if danger_distance_sqr >= danger_settings.ignore_distance_hit then
				return false
			end
		elseif bd_type == danger_object.enemy_sound or
			   bd_type == danger_object.attack_sound or
			   bd_type == danger_object.entity_death then
			if danger_distance_sqr >= danger_settings.ignore_distance_sound then
				return false
			end
		end
	else
		if danger_distance_sqr >= def_ignore_distance then
			return false
		end
		if bd_type == danger_object.grenade then
			if danger_distance_sqr >= def_ignore_distance_grenade then
				return false
			end
		elseif bd_type == danger_object.entity_corpse then
			if danger_distance_sqr >= def_ignore_distance_corpse then
				return false
			end
		elseif bd_type == danger_object.entity_attacked or
			   bd_type == danger_object.attacked then
			if danger_distance_sqr >= def_ignore_distance_hit then
				return false
			end
		elseif bd_type == danger_object.enemy_sound or
			   bd_type == danger_object.attack_sound or
			   bd_type == danger_object.entity_death then
			if danger_distance_sqr >= def_ignore_distance_sound then
				return false
			end
		end
	end
	return true
end