-- ----------------------------------------------------------------------------------------------------
-- Общие функции
-- ----------------------------------------------------------------------------------------------------

function disable_ui_elements(actor, npc, p)
	local i, v = 0, 0
	for i, v in pairs(p) do
		if v == "all" then
			db.actor:hide_weapon()
			level.disable_input()
			level.hide_indicators()
			break
		elseif v == "weapon" then
			db.actor:hide_weapon()
		elseif v == "input" then
			level.disable_input()
		elseif v == "hud" then
			level.hide_indicators()
		end
	end
	--printf("xr_effects <disable_ui_elements>")
end

function enable_ui_elements(actor, npc, p)
	local i, v = 0, 0
	for i, v in pairs(p) do
		if v == "all" then
			level.show_indicators()
			level.enable_input()
			db.actor:restore_weapon()
			break
		elseif v == "hud" then
			level.show_indicators()
		elseif v == "input" then
			level.enable_input()
		elseif v == "weapon" then
			db.actor:restore_weapon()
		end
	end
end

function disable_ui(actor, npc)
	db.actor:hide_weapon()
	level.disable_input()
	level.hide_indicators()
	olr.disable_walk()
	--printf("xr_effects <disable_ui>")
end

function enable_ui(actor, npc)
	level.show_indicators()
	level.enable_input()
	db.actor:restore_weapon()
	olr.enable_walk()
	--printf("xr_effects <enable_ui>")
end

function run_cam_effector(actor, npc, p)
	if p[1] then
		local loop, num = false, (1000 + math.random(100))
		
		if p[2] and type(p[2]) == "number" and p[2] > 0 then
			num = p[2]
		end

		if p[3] and p[3] == "true" then
			loop = true
		end
		
		--level.add_pp_effector(p[1] .. ".ppe", num, loop)
		level.add_cam_effector("camera_effects\\" .. p[1] .. ".anm", num, loop, "")					  
	end
end

function stop_cam_effector(actor, npc, p)
	if p[1] and type(p[1]) == "number" and p[1] > 0 then
		level.remove_cam_effector(p[1])
	end
end

function run_postprocess(actor, npc, p)
	if p[1] then
		local loop, num = false, (2000 + math.random(100))
		
		if p[2] and type(p[2]) == "number" and p[2] > 0 then
			num = p[2]
		end

		if p[3] and p[3] == "true" then
			loop = true
		end
		
		level.add_pp_effector(p[1] .. ".ppe", num, loop)
	end
end

function stop_postprocess(actor, npc, p)
	if p[1] and type(p[1]) == "number" and p[1] > 0 then
		level.remove_pp_effector(p[1])
	end
end

function run_tutorial(actor, npc, p)
	game.start_tutorial(p[1])
end
function run_tutorial_if_newbie(actor, npc, p)
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial(p[1])
	end
end

function teleport_actor(actor, npc, p)
	local point = patrol(p[1])
	local look = patrol(p[2])
	
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())	
end


function teleport_npc(actor, npc, p)
	local patrol_point = p[1]
	local patrol_point_index = p[2] or 0
	if patrol_point == nil then
		abort("Wrong parameters in 'teleport_npc' function!!!")
	end
	local position = patrol(patrol_point):point(patrol_point_index)
	--reset_animation(npc)

	npc:set_npc_position(position)
end

function teleport_npc_by_story_id(actor, npc, p)
    local story_id = p[1]
    local patrol_point = p[2]
    local patrol_point_index = p[3] or 0
    if story_id == nil or patrol_point == nil then
        abort("Wrong parameters in 'teleport_npc_by_story_id' function!!!")
    end
    local position = patrol(tostring(patrol_point)):point(patrol_point_index)
    local npc_id = alife():story_object(story_id)
    if npc_id == nil then
        abort("There is no story object with id [%s]", story_id)
    end
    local cl_object = level.object_by_id(npc_id.id)
    if cl_object then
        --reset_animation(cl_object)
        cl_object:set_npc_position(position)
    else
        alife():object(npc_id).position = position
    end
end

-----------------------------------------------------------------------------
local drop_point, drop_object = 0, 0
local function drop_object_item(item)
	drop_object:drop_item_and_teleport(item, drop_point)
	--log1("drop to point")
end

function drop_actor_inventory(actor, npc, p)
	if p[1] then
		drop_point	= patrol(p[1]):point(0)
		drop_object = actor
		actor:inventory_for_each(drop_object_item)
	end
end

-- FIXME: drop_npc_inventory doesn't work
function drop_npc_inventory(actor, npc, p)
	if p[1] then
		drop_point	= patrol(p[1]):point(0)
		drop_object = npc
		npc:inventory_for_each(drop_object_item)
	end
end

function drop_npc_item(actor, npc, p)
	if p[1] then
		local item = npc:object(p[1])
		if item then
			npc:drop_item(item)
		end
	end
end

function drop_npc_items(actor, npc, p)
	local item = 0
	for i, v in pairs(p) do
		item = npc:object(v)
		if item then
			npc:drop_item(item)
		end
	end
end

function give_item(actor, npc, p)
	if p[1] then
		alife():create(p[1], npc:position(), npc:level_vertex_id(), npc:game_vertex_id(), npc:id())
	end
end

function give_items(actor, npc, p)
	local pos, lv_id, gv_id, npc_id = npc:position(), npc:level_vertex_id(), npc:game_vertex_id(), npc:id()
	for i, v in pairs(p) do
		alife():create(v, pos, lv_id, gv_id, npc_id)
	end
end

function respawner_spawn(actor, npc, p)
	if p[1] then
		se_respawn.spawn(p[1])
	end
end

function play_particle_on_path(actor, npc, p)
	local name = p[1]
	local path = p[2]
	local point_prob = p[3]
	if name == nil or path == nil then
		return
	end

	if point_prob == nil then
		point_prob = 100
	end
	
	local path = patrol(path)
	local count = path:count()
	for a = 0,count-1,1 do	 
		local particle = particles_object(name)
		if math.random(100) <= point_prob then
			particle:play_at_pos(path:point(a))
		end
	end	  
end

-----------------------------------------------------------------------------
function monster_berserk(actor, npc)
	npc:berserk()
end

function activate_bolt(actor, npc)
	db.actor:activate_slot(5)
end

--[[
send_tip(news_id:sender:sender_id)
	1. news_id
	2. sender*
	3. sender_id*
	* - not necessary
--]]
function send_tip(actor, npc, p)
	news_manager.send_tip(actor, p[1], nil, p[2], nil, p[3])
end

--[[
Дать сталкеру небольшой пинок. Например чтоб скинуть его с возвышения.
параметры: actor, npc, p[direction,bone,power,impulse,reverse=false]
	1. direction - если строка, то считается, что это имя пути и в сторону
		первой точки производится толчек. Если же это число, то оно
		рассматривается как story_id персонажа от которого должен поступить хит.
	2. bone - строка. Имя кости, по которой наносится удар.
	3. power - сила удара
	4. impulse - импульс
	5. reverse (true/false) - изменение направления удара. по умолчанию false
--]]
function hit_npc(actor, npc, p)
	local h = hit()
	local rev = p[5] and p[5] == 'true'
	h.draftsman = npc
	h.type = hit.wound
	if type(p[1]) == 'number' then
		local hitter = level_object_by_sid(p[1])
		if not hitter then return end
		if rev then
			h.draftsman = hitter
			h.direction = hitter:position():sub(npc:position())
		else
			h.direction = npc:position():sub(hitter:position())
		end
	else
		if rev then
			h.draftsman = nil
			h.direction = npc:position():sub(patrol(p[1]):point(0))
		else
			h.direction = patrol(p[1]):point(0):sub(npc:position())
		end
	end
	h:bone(p[2])
	h.power = p[3]
	h.impulse = p[4]
	--printf("HIT EFFECT: (%s, %s,%d,%d) health(%s)", npc:name(), p[2], h.power, h.impulse, npc.health)
	npc:hit(h)
end

--[[
Дать обьекту, заданному story_id, хит.
параметры: actor, npc, p[sid,bone,power,impulse,hit_src=npc:position()]
	1. sid - story_id обьекта, по которому наносится хит.
	2. bone - строка. Имя кости, по которой наносится удар.
	3. power - сила удара
	4. impulse - импульс
	5. hit_src - если число, то рассматривается как story_id обьекта, со стороны
		которого наносится хит (он же является и инициатором хита), иначе это
		точка (waypoint), из которой по объекту наносится хит.
		Если не задано, то берется позиция обьекта, из которого была вызвана
		данная функция.
--]]
function hit_obj(actor, npc, p)
	local h = hit()
	local obj = level_object_by_sid(p[1])
	local sid = nil

	if not obj then
--		abort("HIT_OBJ [%s]. Target object does not exist", npc:name())
		return
	end

	h:bone(p[2])
	h.power = p[3]
	h.impulse = p[4]

	if p[5] then
		sid = tonumber(p[5])
		if sid then
			sid = level_object_by_sid(sid)
			if sid then
				h.direction = vector():sub(sid:position(), obj:position())
			end
		end
		if not sid then
			h.direction = vector():sub(patrol(p[5]):point(0), obj:position())
		end
	else
		h.direction = vector():sub(npc:position(), obj:position())
	end

	h.draftsman = sid or npc
	h.type = hit.wound
	obj:hit(h)
end

--[[
Дать сталкеру небольшой пинок после смерти. Аналогично предыдущему, только направление хита теперь
вычисляется через убийцу. Поэтому параметра direction нет.
параметры: actor, npc, p[bone,power,impulse]
FIXME: killer:position() isn't working
--]]
function hit_by_killer(actor, npc, p)
	if not npc then return end
	local t = db.storage[npc:id()].death
	if t == nil or t.killer == -1 then return end
	local killer = db.storage[t.killer]
	if killer == nil then return end
	local p1, p2
	p1 = npc:position()
	p2 = killer:position()
	local h = hit()
	h.draftsman = npc
	h.type = hit.wound
	h.direction = utils.vector_copy_by_val(p1):sub(p2)
	h.bone = p[1]
	h.power = p[2]
	h.impulse = p[3]
	npc:hit(h)
end

function set_friends(actor, npc, p)
	local npc1
	for i, v in pairs(p) do
		npc1 = level_object_by_sid(v)
		if npc1 and npc1:alive() then
			--printf("_bp: %d:set_friends(%d)", npc:id(), npc1:id())
			npc:set_relation(game_object.friend, npc1)
			npc1:set_relation(game_object.friend, npc)
		end
	end
end

function set_enemies(actor, npc, p)
	local npc1
	for i, v in pairs(p) do
		--printf("_bp: set_enemies(%d)", v)
		npc1 = level_object_by_sid(v)
		if npc1 and npc1:alive() then
			npc:set_relation(game_object.enemy, npc1)
			npc1:set_relation(game_object.enemy, npc)
		end
	end
end

-- играть звук в голове актёра
function play_snd(actor, npc, p)
	if p[1] then
		local snd_obj = xr_sound.get_safe_sound_object(p[1])
		--snd_obj:play(actor, p[2] or 0, sound_object.s2d)
		snd_obj:play_no_feedback(actor, sound_object.s2d, p[2] or 0, vector(), 1.0)
	end
end

-- играть звук от указанного объекта
function play_snd_from_obj(actor, npc, p)
	if p[1] and p[2] then
		local snd_obj = xr_sound.get_safe_sound_object(p[2])
		local obj	  = level_object_by_sid(p[1])
		if obj ~= nil then
		   printf("can't find object with story id %s", tostring(p[1]))
		
--		snd_obj:play_at_pos(obj, obj:position(), sound_object.s3d)
		snd_obj:play_no_feedback(obj, sound_object.s3d, 0, obj:position(), 1.0)
		end
	end
end

-- играть звук от указанного объекта
function play_snd_now(actor, npc, p)
	xr_sound.set_sound_play(npc, p[1])
end

-- прибавить к указанному счётчику актёра 1
function inc_counter(actor, npc, p)
	if p[1] then
		printf( "inc_counter '%s'", p[1] )
		xr_logic.pstor_store(actor, p[1], xr_logic.pstor_retrieve(actor, p[1], 0) + 1)
	end
end

function dec_counter(actor, npc, p)
	if p[1] then
		printf( "dec_counter '%s'", p[1] )
		xr_logic.pstor_store(actor, p[1], xr_logic.pstor_retrieve(actor, p[1], 0) - 1)
	end
end

-- переключает камеру на монстра или на актёра
function alien_control( actor, npc, p )
	printf( "alien_control(%s)", p[1] )
	npc:set_alien_control( p[1] == "true" )
end

-- слелать актёра врагом персонажам, которые в онлайне под указанным смартом
function set_gulag_enemy_actor( actor, npc, p )
	if p[1] then
		xr_gulag.setGulagEnemy(p[1], actor)
	end
end

-- принудительное обновление смарта. Использовать только в КРАЙНИХ случаях!!!
-- каждое использование согласовывать со мной. Чугай.
function smart_terrain_force_update(actor, npc, p)
	printf( "xr_effects.smart_terrain_force_update called" )

	if p[1] then
		local gulag = xr_gulag.get_gulag(p[1])

		if gulag then
			gulag.smrttrn:update()
		end
	end
end

------------------------------------------------------------------------------------------------------------------------
-- постпроцесс и влияние удара в морду
function actor_punch(npc)
	if db.actor:position():distance_to_sqr(npc:position()) > 4 then
		return
	end

	local active_slot = db.actor:active_slot()
	if active_slot ~= 1 and
	   active_slot ~= 2
	then
		return 
	end

	local active_item = db.actor:active_item()
	if active_item then
		db.actor:drop_item(active_item)
	end
	
	set_inactivate_input_time(30)
	local snd_obj = xr_sound.get_safe_sound_object([[actor\hit_fist]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)

	level.add_cam_effector("camera_effects\\fusker.anm", 999, false, "")		
end

-- забывание обиды
function clearAbuse(npc)
	printf("CLEAR_ABUSE")
	xr_abuse.clear_abuse(npc)
end

---Выключение динамической лампочки (hanging_lamp)
function turn_off(actor, npc, p)
	local obj = level_object_by_sid(p[1])

	if not obj then
		abort("TURN_OFF [%s]. Target object does not exist", npc:name())
		return
	end
	obj:get_hanging_lamp():turn_off()
end
function turn_off_object(actor, npc)
	npc:get_hanging_lamp():turn_off()
end

---Включение динамической лампочки (hanging_lamp)
function turn_on(actor, npc, p)
	local obj = level_object_by_sid(p[1])

	if not obj then
		abort("TURN_ON [%s]. Target object does not exist", npc:name())
		return
	end
	obj:get_hanging_lamp():turn_on()
end
function turn_on_object(actor, npc)
	npc:get_hanging_lamp():turn_on()
end

function actor_friend(actor, npc)
	printf("_bp: xr_effects: actor_friend(): npc='%s': time=%d", npc:name(), time_global())
	npc:set_relation(game_object.friend, actor)
end

function actor_neutral(actor, npc)
	npc:set_relation(game_object.neutral, actor)
end

function actor_enemy(actor, npc)
	npc:set_relation(game_object.enemy, actor)
end

-- Вызов этой функции отключит обработчик [combat] боя для персонажа.
-- Используется в случаях, когда все необходимые действия, такие как переключение на другую секцию,
-- уже выполнены, и повторно выполнять их во время боя нельзя (а условия секции [combat] проверяются на каждом
-- апдейте, когда персонаж в бою, если, конечно, не отключены вызовом этой функции).
function disable_combat_handler(actor, npc)
	if db.storage[npc:id()].combat then
		db.storage[npc:id()].combat.enabled = false
	end
	
	if db.storage[npc:id()].mob_combat then
		db.storage[npc:id()].mob_combat.enabled = false
	end
end

-- Вызов этой функции отключит обработчик [combat_ignore] перехвата боя для персонажа.
function disable_combat_ignore_handler(actor, npc)
	if db.storage[npc:id()].combat_ignore then
		db.storage[npc:id()].combat_ignore.enabled = false
	end
end

function psi_hit_npc(actor, npc,p)

end

function search_gulag_job(actor, npc)
	xr_gulag.resetJob(npc)
end

function enable_level_changer(actor, npc, p)
	if(p[1]~=nil) then
		local obj = level_object_by_sid(tonumber(p[1]))
		if(obj) then
			local obj_id = obj:id()
			if db.storage[obj_id] and db.storage[obj_id].s_obj then
				db.storage[obj_id].s_obj.enabled = true
				db.storage[obj_id].s_obj.hint = "level_changer_invitation"
			else
				return
			end
			obj:enable_level_changer(true)
			level_tasks.add_lchanger_location()
			obj:set_level_changer_invitation("level_changer_invitation")
		end
	end
end

function disable_level_changer(actor, npc, p)
	if(p[1]~=nil) then
		local obj = level_object_by_sid(tonumber(p[1]))
		if(obj) then
			if not(db.storage[obj:id()] and db.storage[obj:id()].s_obj) then
				return
			end
			obj:enable_level_changer(false)
			level_tasks.del_lchanger_mapspot(tonumber(p[1]))
			db.storage[obj:id()].s_obj.enabled = false
			if(p[2]==nil) then
				obj:set_level_changer_invitation("level_changer_invitation_disabled")
				db.storage[obj:id()].s_obj.hint = "level_changer_invitation_disabled"
			else
				obj:set_level_changer_invitation(p[2])
				db.storage[obj:id()].s_obj.hint = p[2]
			end
		end
	end
end

-- Сюжетное сохранение в важных местах
function scenario_autosave(actor, npc, p)
	local save_name = p[1]
	if save_name == nil then
		abort("You are trying to use scenario_autosave without save name")
	end
	save_manager.create_named_save(save_name)
end

-- ----------------------------------------------------------------------------------------------------
-- kill
-- ----------------------------------------------------------------------------------------------------
function killactor (actor, npc)
	npc:set_relation (game_object.enemy, actor)
	--actor:give_info_portion ("mil_bodyguard_kill")
end

function kill(actor, npc)
	npc:kill( npc )
end

function kill_actor(actor, npc) 
	db.actor:kill(db.actor)
end

function kill_actor_psy()
	if db.actor:alive() then
		db.actor.health = -1
		level.add_pp_effector("black.ppe", 20131, false)
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\psy_noise]])
		if not snd_obj:playing() then 
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
		end	
	end
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для работы с вертолётами
-- ----------------------------------------------------------------------------------------------------
function heli_set_enemy_actor(actor, npc)
	local st = db.storage[npc:id()]
	if not st.combat.enemy_id and actor:alive() then
		st.combat.enemy_id = actor:id()

		--heli_snd.play_snd( st, heli_snd.snd_see_enemy, 1 )
	end 
end

function heli_set_enemy(actor, npc, p)
	local st  = db.storage[npc:id()]
	local obj = level_object_by_sid( p[1] )

	if not st.combat.enemy_id and obj:alive() then
		st.combat.enemy_id = obj:id()

		--heli_snd.play_snd( st, heli_snd.snd_see_enemy, 1 )
	end
end

function heli_clear_enemy(actor, npc)
	db.storage[npc:id()].combat:forget_enemy()
end

function heli_start_flame(actor, npc)
	bind_heli.heli_start_flame( npc )
end

function heli_die(actor, npc)
	bind_heli.heli_die( npc )
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для PDA
-- ----------------------------------------------------------------------------------------------------
--Согласие на торговлю
function def_trade_1_end(actor, npc)
	olr_ai_trade_agree.enable_scheme(actor, nil, "trade_agree", "trade_agree")
end

--Согласие прийти на помощь
function def_save_me_1_end(actor, npc)
	olr_ai_follower_agree.enable_scheme(actor, nil, "follower_agree")
end

--Согласие уйти
function def_out_you_1_end(actor, npc)

end

-- ----------------------------------------------------------------------------------------------------
-- Функции проигрывания видео и титров
-- ----------------------------------------------------------------------------------------------------
function game_credits(actor, npc)
	db.gameover_credits_started = true
	game.start_tutorial("credits_seq")
end

function game_over(actor, npc)
	if db.gameover_credits_started ~= true then
		return
	end
	local c = get_console()
--	c:execute("disconnect")
	printf("main_menu on console command is executed")
	c:execute("main_menu on")
end

function after_credits(actor, npc)
	if db.gameover_credits_started ~= true then
		-- Считаем что вызывалось из главного меню, так как там эта переменная не тру
		ui_main_menu.Proxy_InitMusic()
		return
	end
	local c = get_console()
	c:execute("disconnect")
end

function end_yantar_dream(actor, npc)
	db.actor:give_info_portion("tupoi_ded")
end

function end_startolr_dream(actor, npc)
	--db.actor:give_info_portion("storyline_actor_start")
	--get_console():execute("snd_volume_music 0")
	--get_console():execute("snd_volume_eff 0")
end

function end_x18_dream(actor, npc)
	db.actor:give_info_portion("dar_x18_dream")
	--nick.move_online_blokpost()
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для сна
-- ----------------------------------------------------------------------------------------------------
-- Основная функция для проверок, используется во всех местах сна
function sleep_check()
	-- проверка на выброс
	if has_alife_info("olr_blowout_phase_1") or has_alife_info("olr_blowout_phase_2") or has_alife_info("olr_blowout_phase_3") then
		news_manager.send_tip(db.actor, game.translate_string("st_sleep_blowout"), nil, "info")
		return false
	end

	-- фром кок, проверки на ранение и радиацию
	local bleeding = db.actor.bleeding > 0
	local radiation = db.actor.radiation > 0

	if (bleeding or radiation) then
		if (bleeding and radiation) then
			news_manager.send_tip(db.actor, game.translate_string("st_sleep_bleeding_radiation"), nil, "info")
		elseif (bleeding) then
			news_manager.send_tip(db.actor, game.translate_string("st_sleep_bleeding"), nil, "info")
		elseif (radiation) then
			news_manager.send_tip(db.actor, game.translate_string("st_sleep_radiation"), nil, "info")
		end
		return false
	end	
	
	-- проверка что на улице ночь
	if not has_alife_info("olr_traders_day") then
		return true
	end
	-- если день то проверяем нашу сониловость
	local sleep_level = db.actor.sleep
	-- при сонливости менее 0.5 идём спать, иначе не спать
	if sleep_level <= 0.5 then
		return true
	else
		news_manager.send_tip(db.actor, game.translate_string("st_sleep_not_tired"), nil, "info", 30000)
		return false
	end
	return false
end

-- Янтарь, бункер учёных
function use_spat_hata_yan()
	-- Оставлю пока старый код, ибо я запутался нах
	--[[
	if not has_alife_info("laborant_otpravlaet_spat_gg_finished") then
		news_manager.send_tip(db.actor, game.translate_string("use_spat_hata_yan_0"), nil, "info", 30000)
		return
	end
	if has_alife_info("otpravlaet_spat_gg_done") then
		return
	end
	olr_sleep.sleep_main(6)
	db.actor:change_actor_sleep(1)
	olr_timers.st_timer("dedsmert", 10, "nick.ded_pomeraet_yan()")
	--]]
	if has_alife_info("laborant_otpravlaet_spat_gg_finished") and not has_alife_info("otpravlaet_spat_gg_done") then -- Если у нас есть поршень что нас отправили поспать и нет поршня что поспали
		olr_sleep.sleep_main(1,0,true) -- Основная функция сна
		olr_timers.st_timer_game("dedsmert", 1, "nick.ded_pomeraet_yan()") -- Запускаем самоубийство деда через 1 игровую секунду, ну не сразу короче (пока оставим так)
		return -- уходим отсюда сразу, проверок не делаем
	end
	if sleep_check() then
		olr_sleep.sleep_main(0,0,true) -- Основная функция сна
	end	
end

-- Бар, в школе
function use_spat_hata()
    if has_alife_info("lonewolf_bar_spawn") and not has_alife_info("sleeped_in_shlkola_done") then -- проверяем на поршни спавна одинокого волка в баре и что мы не поспали в школе
        db.actor:give_info_portion("sleeped_in_shlkola_done")
		olr_sleep.sleep_main(0,0,true) -- Основная функция сна
		return -- уходим отсюда сразу, проверок не делаем
    end
	if sleep_check() then
		olr_sleep.sleep_main(0,0,true) -- Основная функция сна
	end
end

-- Кордон, подвал недалеко от Жабы
-- Бар дом Мессера
function use_spat_hata_esc()
	if sleep_check() then
		olr_sleep.sleep_main(0,0,true) -- Основная функция сна
	end
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Кордона
-- ----------------------------------------------------------------------------------------------------
function start_aah_shii(actor, npc)
	olr.hud_tip("", game.translate_string("start_aah_shii_0"), 3, true) -- мысль мессера
	soundtrack.achit2()
end

function start_aah_shii_mesto_znak(actor, npc)
	olr.hud_tip("", game.translate_string("start_aah_shii_mesto_znak_0"), 3, true) -- мысль мессера
end

function start_aah_shii_mesto_znak2(actor, npc)
	local case = db.actor:object("give_yashik_kvest_1_item")
	if case then
		if has_alife_info("kvest_esc_1_dialog_start") then
			olr.hud_tip("", game.translate_string("start_aah_shii_mesto_znak2_0"), 3, true) -- мысль мессера
		else
			news_manager.send_tip(db.actor, game.translate_string("start_aah_shii_mesto_znak2_1"), 5, "trader", 10000, nil, nil, true, "escape_trader_name")
		end
	else
		if has_alife_info("kvest_esc_1_dialog_start") then
			news_manager.send_tip(db.actor, game.translate_string("start_aah_shii_mesto_znak2_2"), nil, "trader", 10000, nil, nil, true, "escape_trader_name")
		end
	end
	if not has_alife_info("kvest_esc_1_dialog_start") then
		news_manager.send_tip(db.actor, game.translate_string("start_aah_shii_mesto_znak2_3"), 5, "trader", 10000, nil, nil, true, "escape_trader_name")
	end
end

function use_lestniza_esc()
	level.add_pp_effector("black.ppe", 20131, false)
	olr_teleport.tele_lestnica()
end

function mochalka_poezd_online()
	olr.to_online("lvl1_escape_af_dummy_dummy_q1")
	news_manager.send_tip(db.actor, game.translate_string("mochalka_poezd_online_0"), 22, "trader", 35000, nil, nil, true, "escape_trader_name")
end

function esc_prizrak_proverka(actor, npc)
	if has_alife_info("olr_traders_night") and has_alife_info("jaba_start_phanrom_start") and not has_alife_info("jaba_start_phanrom_spawen") then
		db.actor:give_info_portion("jaba_start_phanrom_spawen")
		olr.spawen_phantoms()
	end
end

function del_odvolk2(actor)
	local se_obj = alife():object("lvl1_escape_staler_undead_olr")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function esc_prizrak_hitted()
	local mrandom = math.random

	if not has_alife_info("jaba_start_phanrom_spawen_agressive") then
		xr_effects.kill_actor()
		db.actor.health = -11
	end
	
	db.actor.health = -0.03
	level.add_pp_effector("dead_zone.ppe", 971974, false)
	local song_start = xr_sound.get_safe_sound_object([[ambient\special\heartbeat_fast]])
	song_start:play_at_pos(db.actor, db.actor:position(), sound_object.s3d)
	db.actor.psy_health = -0.05

	-- Случайные эффекты
	local rnd = mrandom(1, 5)
	if rnd == 1 then
		olr.horror_snd()
	elseif rnd == 2 then
		olr.spawen_phantoms()
	elseif rnd == 3 or rnd == 4 then
		olr.spawn_crows(2, 22)
	elseif rnd == 5 then
		for id = 1, mrandom(1, 2) do
			local sectionsa = {
				"zombie_weak",
				"zombie_normal",
				"zombie_strong",
			}
			local section = sectionsa[math.random(#sectionsa)]
			alife():create(section, db.actor:position():add(db.actor:direction():mul(-24)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		end
	end

	nick.set_norm_relation_stalkers()

	local target = alife():object("lvl1_escape_stalker_0038")
	if target then
		local level_obj = level.object_by_id(target.id)
		if level_obj then
			-- Создаем партиклы
			local boss_particle = particles_object("anomaly2\\body_tear_00")
			boss_particle:play_at_pos(level_obj:position())

			-- Случайная телепортация
			local teleport_positions = {
				vector():set(46, 3, 145),	-- позиция 1
				vector():set(64, 3, 169),	-- позиция 2
				vector():set(71, 11, 164),	-- позиция 3
				vector():set(66, 3, 150),	-- позиция 4
				vector():set(56, -0.36, 157) -- позиция 5
			}
			
			local new_pos = teleport_positions[mrandom(1, 5)]
			level_obj:set_position(new_pos)
		end
	end
end

function del_horok_esc()
	level.add_pp_effector("black.ppe", 201831, false)
	local se_obj = alife():object("lvl1_escape_stalker")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function kvest_esc_5_kill_voyaka()
	-- Отправка сообщения остается без изменений
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_ferret_greeting"), math.random(1000, 3000), "neutral", 15000, nil, nil, true, "esc_fox_name")

	-- Прямое обращение к объекту по имени
	local target = alife():object("lvl1_escape_stalker_0003")
	if target then
		local npc = level.object_by_id(target.id)
		if npc then
			local h = hit()
			h.power = 100
			h.direction = vector():set(0, -1, 0)
			h.impulse = 0
			h.draftsman = npc
			h.type = hit.strike
			npc:hit(h)
		end
	end
end

function first_doska_use_start_1()
	olr.hud_tip(game.translate_string("st_xr_effects_message_from_toad"), game.translate_string("st_xr_effects_message_toad_board_1"), 4)
end

function first_doska_use_start_2()
	olr.hud_tip(game.translate_string("st_xr_effects_message_from_toad"), game.translate_string("st_xr_effects_message_toad_board_2"), 10)
end

function first_doska_use_start_3()
	olr.hud_tip(game.translate_string("st_xr_effects_message_from_toad"), game.translate_string("st_xr_effects_message_toad_board_3"), 17)
end

function first_doska_use_start_4()
	bind_stalker.restore_weapon()
	level.enable_input()
	level.remove_cam_effector(30)
	olr.del_by_name("lvl1_escape_space_restrictor_0106")
end

function borziy_esc_dead()
	if xr_conditions.actor_in_zone(nil,nil,{"lvl1_escape_space_restrictor_0108"}) then
		--log1("fail")
		news_manager.send_tip(db.actor, game.translate_string("borziy_esc_dead_0"), nil, "heli", 49000)
		olr_timers.st_timer("expl_actor", 5, "nick.expl_actor_away()")
	else
		--log1("ok")
		db.actor:give_info_portion("esc_kill_okay_mil")
	end
end

function now_iremember()
	olr.hud_tip("", game.translate_string("now_iremember_0"), 15)
	db.actor:give_info_portion("now_iremember_demand")
end

function journalist_timer_sms()
	olr_timers.st_timer("dfds", math.random(135,190), "nick.the_god_is_seven()")
end

function del_na_kordone_komandira()
	local se_obj = alife():object("lvl1_escape_stalker_0039")
	if se_obj then
		alife():release(se_obj, true)
	end
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Свалки
-- ----------------------------------------------------------------------------------------------------
function use_take_art_gar()
	olr.del_by_name("lvl2_garbage_physic_object_0111")
	db.actor:give_info_portion("gar_vhod_art_taken_info")
	olr.give_item("af_thorn_black")
end

function del_artvhod_done()
	olr.del_by_name("lvl2_garbage_stalker_0051")
end

function del_fist_gar_vorony_glaz(actor)
	local se_obj = alife():object("lvl2_garbage_staler_undead_olr_0001")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_storoz_pes(actor)
	local se_obj = alife():object("lvl2_garbage_staler_undead_olr_0000")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_glazovoron(actor)
	local se_obj = alife():object("lvl2_garbage_staler_undead_olr")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_obossanetz(actor)
	local sobj = alife():object("lvl2_garbage_stalker_0031")
	if sobj then
		local pk = get_netpk(sobj,1)
		local data = pk:get()
		data.custom_data:setString("[smart_terrains]\n".."lvl3_agroprom_smart_terrain_0020 = true\n")
		pk:set(data)
		table.insert(olr_offline_walk.tabst, sobj)
	end
end

function del_fil_done_glaz()
	local se_obj = alife():object("lvl2_garbage_stalker_0030")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function use_tip_press_button_gar()
	if not has_alife_info("now_use_tip_press_button_gar") then
		db.actor:give_info_portion("now_use_tip_press_button_gar")
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\garbage_open_door]])
		if not snd_obj:playing() then 
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
		local bloodbridge = vector():set(-46.5, 6.4, 261.37)
		alife():create("kanistra_benz", bloodbridge,db.actor:level_vertex_id(),	db.actor:game_vertex_id())
		olr.spawn_on_obj("kanistra_benz", "lvl2_garbage_physic_object_0017")
		olr.del_by_name("lvl2_garbage_physic_object_0110")
	end
end

function take_gar_deathlamp()
	if has_alife_info("garbage_can_take_lamp") then
		olr.del_by_name("lvl2_garbage_physic_object_0114")
		olr.give_item("af_lamp")
		olr.horror_snd()
  		level.add_call(
    		function() return time_global() > time_global() + 5000 end,
    		function() olr.hud_tip("", game.translate_string("take_gar_deathlamp_0"), 5, true) end
  		)
  		level.add_call(
    		function() return time_global() > time_global() + 10000 end,
    		function() olr.hud_tip("", game.translate_string("take_gar_deathlamp_1"), 5, true) end
  		)
  		level.add_call(
    		function() return time_global() > time_global() + 15000 end,
    		function() olr.hud_tip("", game.translate_string("take_gar_deathlamp_2"), 5, true) end
  		)					
	end
end

function kill_rats_garbage_killer_start_sms()
	olr.kill_mon_in_radius(db.actor:position(), 90)
	olr.del_by_name("lvl2_garbage_space_restrictor_0026")
	olr_timers.st_timer("kill_go_krisa", 30, "nick.kill_go_krisa()")
	news_manager.send_tip(db.actor, game.translate_string("kill_rats_garbage_killer_start_sms_0"), nil, "dolg", 15000)
end

function start_killing_kris_gar()
	olr.del_by_name("lvl2_garbage_space_restrictor_0029")
	olr.del_by_name("lvl2_garbage_space_restrictor_0027")
	news_manager.send_tip(db.actor, game.translate_string("start_killing_kris_gar_0"), 1, "dolg", 10000)
	news_manager.send_tip(db.actor, game.translate_string("start_killing_kris_gar_1"), 6, "unknown", 10000)
	olr_timers.st_timer("kill_go_krisa_st_kills", 10, "nick.kill_go_krisa_st_kills()")
end

function use_garage_door1()
	if not has_alife_info("medyasik_done") then
		olr.hud_tip("", game.translate_string("st_xr_effects_message_door_closed"), 5)
		return
	end

	level.add_pp_effector("black.ppe", 20131, false)
	local point = patrol("esc_garage_in_walk")
	local look = patrol("esc_garage_in_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function use_garage_door2()
	level.add_pp_effector("black.ppe", 20131, false)
	local point = patrol("esc_garage_out_walk")
	local look = patrol("esc_garage_out_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Агропрома
-- ----------------------------------------------------------------------------------------------------
function use_book_agr()
	if has_alife_info("olr_agro_2_start") and not has_alife_info("agr_perepat_tainik_start") then
		olr.hud_tip(game.translate_string("st_xr_effects_message_book_note"), game.translate_string("st_xr_effects_message_book_hidden_pc"), 15)
		olr.info("agr_perepat_tainik_start")
	end
end

function take_nii_gravmolot()
	if has_alife_info("kvest_gravimolot_go") then
		alife():create("grav_molot", db.actor:position(),db.actor:level_vertex_id(),  db.actor:game_vertex_id(),db.actor:id())
		nick.del_molot_agr()
	else
		olr.hud_tip("", game.translate_string("take_nii_gravmolot_0"), 5)
	end	
end

function use_agr_anihilator()
	if has_alife_info("agr_anihil_shooted") then
		news_manager.send_tip(db.actor, game.translate_string("use_agr_anihilator_0"), nil, "default", 5000)
		return
	end
	olr_timers.st_timer("anihil_shooted", 62, "nick.anihil_shooted()")
	db.actor.psy_health = -0.21
	db.actor:give_info_portion("agr_anihil_shooted")
	olr.kill_mon_in_radius(db.actor:position(), 25)
	level.add_cam_effector("camera_effects\\shell_shock.anm", 346, false, "")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\agroprom_anihilator]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function find_killer_agro()
	olr.info("spawn_killer_deader")
	news_manager.send_tip(db.actor, game.translate_string("find_killer_agro_0"), nil, "unknown", 5000)
	olr.del_by_name("lvl3_agroprom_space_restrictor_0021")	
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Тёмной долины
-- ----------------------------------------------------------------------------------------------------
function drop_actor_inventory_dolina_killers(actor, npc, p)
	--local has_art = act:object("olr_doc_lab_1")
	--if has_art then
	--	olr.del(has_art)
	--end
	level.add_pp_effector("black.ppe", 201831, false)
	local point = patrol("prison_killers_way")
	local look = patrol("prison_killers_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("snd_shock.ppe", 2031, false)
	local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\scenario\darkvalley\killers\actor_stunning_1]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	news_manager.send_tip(db.actor, game.translate_string("drop_actor_inventory_dolina_killers_0"), nil, "killer", 15000)
	local obox = alife():object("lvl4_darkdolina_big_safe_box")
	local box = level.object_by_id(obox.id)
	if box then
		db.actor:iterate_inventory( function(_, item)
			if item then
				if item:is_weapon() or item:is_grenade() then 
					actor:transfer_item(item, box)
					--log1("trrr has box")
				end
			end
		end )
	end 
	news_manager.send_tip(db.actor, game.translate_string("drop_actor_inventory_dolina_killers_1"), 15, "killer", 9000)
	news_manager.send_tip(db.actor, game.translate_string("drop_actor_inventory_dolina_killers_2"), 20, "killer", 9000)		
	olr.kill_mon_in_radius(db.actor:position(), 100)
	nik_dialog.out_item_much("olr_doc_lab_1",1)
	olr.blow_add(300)
	olr.del_by_name("lvl4_darkdolina_gigant_normal")
end

function killers_second_sleep()
	level.add_pp_effector("black.ppe", 201831, false)
	level.add_pp_effector("snd_shock.ppe", 2031, false)
	local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\scenario\darkvalley\killers\actor_stunning_2]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	olr.kill_mon_in_radius(db.actor:position(), 100)
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0002")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0003")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0004")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0005")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0006")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0007")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0008")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0009")
	olr.del_by_name("lvl4_darkdolina_staler_undead_olr_0010")
	news_manager.send_tip(db.actor, game.translate_string("killers_second_sleep_0"), 5, "dolg", 9000)
	olr_timers.st_timer("killers_specops_go", 22, "nick.killers_specops_go()")
end

function del_glazovoron_dolina(actor)
	local se_obj = alife():object("lvl4_darkdolina_stalker_0095")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_flyer_dolina()
	olr.del_by_name("lvl4_darkdolina_stalker_0071")
end

function dolina_pris_ecol()
	if not has_alife_info("dolina_pris_ecol") then
		news_manager.send_tip(db.actor, game.translate_string("dolina_pris_ecol_0"), nil, "ecolog", 5000)
		olr.spawn_on_obj("bloodsucker_strong", "lvl4u_darklab_space_restrictor_0008")
		olr.del_by_name("lvl4_darkdolina_physic_object_0362")
		olr_timers.st_timer("kill_ec_dolin", 10, "nick.kill_ec_dolin()")
		olr.info("dolina_pris_ecol")
	end
end

function kill_actor_killers()
	db.actor.health = -1
	local snd_obj = xr_sound.get_safe_sound_object([[weapons\svu\shoot]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Военной лаборатории
-- ----------------------------------------------------------------------------------------------------
function dol_kumiry_1(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)
	soundtrack.darklab_start_bassz()
	olr.kill_mon_in_radius(db.actor:position(), 65)
end

function dol_kumiry_2(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_2_0"), 3, "hero", 15000, nil, "pda_objective", true)	
end

function dol_kumiry_3(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry3"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)
end

function dol_kumiry_4(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_4_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_5(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry5"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_6(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_6_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_7(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry7"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_8(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_8_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_9(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry9"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_10(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_10_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_11(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry11"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_12(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_12_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_13(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry13"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_14(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_14_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_15(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry15"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_16(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_16_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_17(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry17"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_18(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_18_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_19(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry19"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)	
end

function dol_kumiry_20(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_20_0"), 3, "hero", 15000, nil, "pda_objective", true)		
end

function dol_kumiry_21(actor, npc)
	local sim = alife()
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_kumiry21"), math.random(3000, 4000), "unknown", 15000, nil, "pda_objective", false)
	local se_obj = sim:object("lvl4_darkdolina_staler_undead_olr_0000")
	if se_obj then
		sim:release(se_obj, true)
	end
	local se_obj = sim:object("lvl4_darkdolina_physic_object_0027_tomb")
	if se_obj then
		sim:release(se_obj, true)
	end
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_21_0"), 5, "signal_lost", 15000, nil, nil, true, "device-PDA")
	news_manager.send_tip(db.actor, game.translate_string("dol_kumiry_21_1"), 11, "hero", 15000, nil, nil, true, xr_effects.get_real_actor_name())
	olr.info("lab_find_switch")
end

function multicutscene_one(actor)
	xr_effects.disable_ui(db.actor, nil)
	level.add_pp_effector("blink.ppe", 20131, false) 
	level.add_cam_effector2("camera_effects\\dolina_cam_1.anm", 30, false, "xr_effects.multicutscene_two")
	--log1("1")
end

function multicutscene_two(actor)
	level.add_cam_effector2("camera_effects\\dolina_cam_2.anm", 30, false, "xr_effects.multicutscene_tri")
	--log1("2")
end

function multicutscene_tri(actor)
	level.add_cam_effector2("camera_effects\\dolina_cam_3.anm", 30, false, "xr_effects.enable_newui")
	--log1("3")
end

function enable_newui(actor)
	xr_effects.enable_ui(db.actor, nil)
	local se_obj = alife():object("lvl4_darkdolina_staler_undead_olr_0000")
	if se_obj then
		alife():release(se_obj, true)
	end
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Бара
-- ----------------------------------------------------------------------------------------------------
function bar_territory_logic(actor, npc)
	local level = level.name()
	if	level == "lvl5_bar" then
		if dialogs.actor_in_dolg(actor,npc) then
			if has_alife_info("bar_dolg_territory_kill") then
				--news_manager.send_tip(actor, "bar_territory_dolg_kill", nil, "dolg", nil, 507)
				--xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava_2", db.actor)
				--xr_gulag.setGulagEnemy("bar_visitors", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_3_hit") then
				--news_manager.send_tip(actor, "bar_territory_dolg_3_hit", nil, "dolg", nil, 507)
				--xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava_2", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_2_hit") then
				--news_manager.send_tip(actor, "bar_territory_dolg_2_hit", nil, "dolg", nil, 507)
				return
			end
			if has_alife_info("bar_dolg_territory_1_hit") then
				--news_manager.send_tip(actor, "bar_territory_dolg_1_hit", nil, "dolg", nil, 507)
				return
			end
		else
			if has_alife_info("bar_dolg_territory_kill") then
				db.actor:give_info_portion("bar_territory_nodolg_kill")
				--news_manager.send_tip(actor, "bar_territory_nodolg_kill", nil, "dolg", nil, 507)
				--xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava_2", db.actor)
				--xr_gulag.setGulagEnemy("bar_visitors", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_2_hit") then
				db.actor:give_info_portion("bar_territory_nodolg_2_hit")
				--news_manager.send_tip(actor, "bar_territory_nodolg_2_hit", nil, "dolg", nil, 507)
				--xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava", db.actor)
				--xr_gulag.setGulagEnemy("bar_dolg_zastava_2", db.actor)
				--xr_gulag.setGulagEnemy("bar_visitors", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_1_hit") then
				db.actor:give_info_portion("bar_territory_nodolg_1_hit")
				--news_manager.send_tip(actor, "bar_territory_nodolg_1_hit", nil, "dolg", nil, 507)
				return
			end	
		end
	end
	return
end

function bar_babah_start()
	if not has_alife_info("bar_babah_start") then
		olr.info("bar_babah_start")
		olr_timers.st_timer("barbah", 15, "xr_effects.barbah()")
		news_manager.send_tip(db.actor, game.translate_string("bar_babah_start_0"), nil, "hero", 5000, nil, nil, true, get_real_actor_name())
		news_manager.send_tip(db.actor, game.translate_string("bar_babah_start_1"), 5, "neutral", 15000, nil, nil, true, "st_stalker_general_default_name")
	end
end

function barbah()
	olr.info("start_bar_bah")
end

function bar_bbaah_explode()
	db.actor.health = - 0.1
	--news_manager.send_tip(db.actor, game.translate_string("bar_bbaah_explode_0"), 5, "hero", 5000, nil, nil, false, get_real_actor_name())
	olr_timers.st_timer("bar_bbaah_explode_msg", 7, "xr_effects.bar_bbaah_explode_msg()")
	particles_object([[explosions\expl_benzin_00]]):play_at_pos(vector():set(-9.68,-90.15,-309.36))
	local snd_obj = xr_sound.get_safe_sound_object([[weapons\f1\explode]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	local obj = alife():object("lvl5_bar_staler_undead_olr_0011")
	local loh = level.object_by_id(obj.id)
	if loh then
		loh:kill(loh)
	end
end

function bar_bbaah_explode_msg()
	olr.hud_tip("", game.translate_string("bar_bbaah_explode_0"), 5, true)
end

function bar_gop_fail()
	local kos = 0
	if kos == 0 then
		if has_alife_info("bar_gop_fail_info") then
			return
		end
		news_manager.send_tip(db.actor, game.translate_string("bar_gop_fail_0"), nil, "default", 5000)
		olr.info("bar_gop_fail_info")
		kos = 1
	end
end

function bar_away_to_wolf()
	level.add_pp_effector("black.ppe", 201831, false)
	local point = patrol("bar_away_to_wolf_way")
	local look = patrol("barman_kamorka_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function bar_dodik_dead()
	olr.del_by_name("lvl5_bar_space_restrictor_0126")
end

function delme(actor, npc)
	if npc then
		olr.del(npc)
	end
end

function del_bar_dudoed(actor)
	local sim = alife()
	local se_obj = sim:object("lvl5_bar_staler_undead_olr_0000")
	if se_obj then
		sim:release(se_obj, true)
		db.actor:give_info_portion("mg_spawen_ludoed_now")
	end
	local se_obj = sim:object("lvl11_deadcity_physic_object_0747")
	if se_obj then
		sim:release(se_obj, true)
	end
end

function sms_magnit_pat(actor, npc)
	if not has_alife_info("bar_magn_profuse") then
		olr.info("bar_magn_profuse")
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_phew_it_works"), math.random(3000, 4000), "info", 15000, nil, "pda_objective", false)
		particles_object([[anomaly2\plasma_generator_death]]):play_at_pos(vector():set(-14,-87,-127))  
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\electric_crash]])
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function use_bar_doska_quests(actor)
	olr_doska_qusts.on_use()
end

function krugliy_help_gop(actor, npc)
	news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_message_bratishka_help"), math.random(3000, 4000), "neutral", 15000, nil, "pda_objective", false)
end

-- удаляем зяблика в баре
function xrbar_zablik_sp()
	local se_obj = alife():object("bar_bar_visitors_3_2_0002")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function kkk_baby_avay_wack()
	local se_obj = alife():object("lvl5_bar_stalker_0035")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_bar_gopstoper1()
	local se_obj = alife():object("lvl5_bar_stalker_0053")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_bar_gopstoper2()
	local se_obj = alife():object("lvl5_bar_stalker_0054")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_bar_rosomaha()
	local se_obj = alife():object("bar_bar_visitor_hunter")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_bar_wolfy()
	local se_obj = alife():object("lvl5_bar_staler_undead_olr_0003_lonewolf")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function del_dead_kontr_robbber()
	local se_obj = alife():object("lvl1_escape_stalker_0040")
	if se_obj then
		alife():release(se_obj, true)
	end
end

-- ЗАЮЗАТЬ
function del_bar_meshkow()
	local se_obj = alife():object("bar_bar_guard_0004_maijor")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function take_bar_bm()
	alife():create("wpn_bm16", db.actor:position(),db.actor:level_vertex_id(),	db.actor:game_vertex_id(),db.actor:id())
	olr.del_by_name("lvl5_bar_physic_object_1399")
end

function take_bar_knife()
	alife():create("wpn_knife", db.actor:position(),db.actor:level_vertex_id(),	 db.actor:game_vertex_id(),db.actor:id())
	olr.del_by_name("lvl5_bar_physic_object_0241")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\glass_break]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

function del_barhaata_novice()
	olr.del_by_name("lvl5_bar_stalker_0052")
end

function tops_stlks()
	level.start_stop_menu(ui_best_stalkers.ui_best_stalkers(),true)
end

function use_lift_bar_verh()
	if not has_alife_info("informer_under_prison_talked") then
		olr.hud_tip("", game.translate_string("use_lift_bar_verh_0"), 10)
		return
	end
	if not has_alife_info("informer_under_prison_first_down") then
		olr.info("informer_under_prison_first_down")
		olr_timers.st_timer("furstunderbar", 4, "nick.first_under_bar()")	
	end
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\power_on]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	level.add_pp_effector("black.ppe", 20131, false)
	local point = patrol("bar_prison_down_walk")
	local look = patrol("bar_prison_down_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function use_lift_bar_niz()
	if not has_alife_info("informer_under_down_power_on") then
		olr.hud_tip("", game.translate_string("use_lift_bar_verh_0"), 10)
	return
	end
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\power_on]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	level.add_pp_effector("black.ppe", 20131, false)
	local point = patrol("bar_prison_verh_walk")
	local look = patrol("agr_u_bandits_walk6")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function use_lift_bar_povon()
	if not has_alife_info("informer_under_down_power_on") then
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\electric_crash]])
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		olr.info("informer_under_down_power_on")
		olr.del_by_name("lvl5_bar_physic_object_1449")
	end
end

function use_telephone_bar()
	if has_alife_info("olr_traders_day") then
		olr.hud_tip("", game.translate_string("st_xr_effects_message_quiet"), 5)
		return
	end
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\bar_phone]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr.disable_walk()
	olr_timers.st_timer("telephone", 40, "olr.enable_walk()")
	olr.del_by_name("lvl5_bar_physic_object_1453")
	olr.to_online("lvl5_bar_physic_object_1454")
	olr.to_online("lvl5_bar_physic_object_1455")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\heartbeat_fast]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Ростка
-- ----------------------------------------------------------------------------------------------------
function kill_rosdolgovecth()
	local obj = alife():object("lvl6_rostok_stalker_0002")
	local bos = level.object_by_id(obj.id)
	if bos then
		bos:kill(bos)
	end
end

function open_rost_diplomat()
	olr.to_online("lvl6_rostok_box_rukzak_0000") -- реальный
	olr.del_by_name("lvl6_rostok_physic_object_0286")
end

function ros_marod_done()
	local snd_obj = xr_sound.get_safe_sound_object([[actor\hit_fist]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)

	level.add_cam_effector("camera_effects\\fusker.anm", 999, false, "")

	olr.del_by_name("lvl6_rostok_stalker_0016")	
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Янтаря
-- ----------------------------------------------------------------------------------------------------
function use_drink_yan()
	if xvars.yan_use_drink_yan == false then
			news_manager.send_tip(db.actor, game.translate_string("use_drink_yan_0"), nil, "info", 9000)
	return
	end
	local ustalost = db.actor.thirst
	if ustalost>0.80 then
		news_manager.send_tip(db.actor, game.translate_string("use_drink_yan_1"), nil, "info", 9000)
		return 
	end
	db.actor:change_actor_thirst(1)
	xvars.yan_use_drink_yan = false
	olr_timers.st_timer("use_drink_yan", 950, "xr_effects.yan_use_drink_yan_on()")
end

function yan_use_drink_yan_on()
	xvars.yan_use_drink_yan = true
end

function yan_poltrs_spawn_ph()
	olr.snd([[ambient\special\yantar_poltergeists_spawn]])
	olr.spawn_on_obj("m_poltergeist_e", "lvl7_yantar_space_restrictor_0004")
	olr.spawn_on_obj("m_poltergeist_e", "lvl7_yantar_space_restrictor_0004")
	olr.del_by_name("lvl7_yantar_space_restrictor_0004")
end

function yan_attack_heli_dead()
	xr_effects.kill_actor()
	db.actor.health = -1
	local snd_obj = xr_sound.get_safe_sound_object([[weapons\svu\shoot]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function del_final_bun_spasen_end()
	olr.del_by_name("lvl7_yantar_stalker_0058")
end

function use_yan_tru_otkl()
	olr.del_by_name("lvl7_yantar_physic_object_0134")
	olr.info("pre_radar_de_done")
end

function use_meatdevice_yan()  -- lvl7_yantar_physic_object_0760 
	if not has_alife_info("yan_biolab_start_quest_done_talked") then
		news_manager.send_tip(db.actor, game.translate_string("use_meatdevice_yan_0"), nil, "hero", 39000)
		return
	end
	local STbronb = db.actor:object("rat_food")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 80
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("crow_food")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 95
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_flesh_eye")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 125
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_boar_leg")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 115
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_dog_tail")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 135
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_psevdodog_tail")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 225
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_krovosos_jaw")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 325
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_burer_hand")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 385
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	local STbronb = db.actor:object("mutant_zombie_hand")
	if STbronb then
		xvars.meat_money = xvars.meat_money + 105
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_item_transfered")..STbronb:get_name().." ", nil, "default", 9000)
		olr.del(STbronb)
		return
	end
	news_manager.send_tip(db.actor, game.translate_string("use_meatdevice_yan_1"), nil, "item", 9000)
end

function yan_labirint_telep_dead_strahovka()
	local point = patrol("to_deadyan_walk")
	local look = patrol("to_deadyan_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("black.ppe", 201831, false)
end

function yan_labirint_telep_dead()
	for i = 1, 65534 do
		local obj = level.object_by_id(i)
		if obj ~= nil then
			if obj:clsid() == clsid.zombie_s or obj:clsid() == clsid.zombie then
				if not obj:alive() then
					olr.del(obj)
				end
			end
		end
	end
	-- local snd_obj = xr_sound.get_safe_sound_object([[ol3\lenin]])
	-- snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	local pos = db.actor:position()
	local x, y, z = pos.x, pos.y, pos.z
	particles_object([[nature\fog_foggy_big]]):play_at_pos(vector():set(x, y, z))
	olr_timers.st_timer("step_yan_dead", 5, "nick.step_yan_dead()")
	bind_stalker.hide_weapon()
	level.disable_input()
	level.hide_indicators()
	olr_timers.st_timer("hit_yan_zombies", 25, "nick.hit_yan_zombies()")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_labyrinth_statue]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr_timers.st_timer("explode_lenin", 15, "nick.explode_lenin()")
	local point = patrol("to_deadyan_walk")
	local look = patrol("to_deadyan_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("black.ppe", 201831, false)
	for k, v in pairs(db.storage) do
		local npc = level.object_by_id(k)
		if npc then
			if npc:is_stalker() or npc:is_monster() then
				if npc:alive() and npc:position():distance_to(db.actor:position()) < 35 then
					npc:enable_memory_object(db.actor, false)
				end
			end
		end
	end
end

function yan_labirint_telep_1()
	local yaz_var = xvars.yan_lab_tele
	if yaz_var < 5 then
		nick.gar_lamb_zombs()
		olr.blow_add(100)
		local rnddir = math.random(1, 5)
		if rnddir == 1 then
			local point = patrol("yan_labirint_telep_1_walk")
			local look = patrol("yan_labirint_telep_1_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 2 then
			local point = patrol("yan_labirint_telep_2_walk")
			local look = patrol("yan_labirint_telep_2_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 3 then
			local point = patrol("yan_labirint_telep_3_walk")
			local look = patrol("yan_labirint_telep_3_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 4 then
			local point = patrol("yan_labirint_telep_4_walk")
			local look = patrol("yan_labirint_telep_4_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 5 then
			local point = patrol("yan_labirint_telep_5_walk")
			local look = patrol("yan_labirint_telep_5_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)

			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
	end
end

function yan_labirint_telep_2()
	local yaz_var = xvars.yan_lab_tele
	if yaz_var < 5 then
		nick.gar_lamb_zombs()
		olr.blow_add(100)
		local rnddir = math.random(1, 5)
		if rnddir == 1 then
			local point = patrol("yan_labirint_telep_1_walk")
			local look = patrol("yan_labirint_telep_1_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 2 then
			local point = patrol("yan_labirint_telep_2_walk")
			local look = patrol("yan_labirint_telep_2_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 3 then
			local point = patrol("yan_labirint_telep_3_walk")
			local look = patrol("yan_labirint_telep_3_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 4 then
			local point = patrol("yan_labirint_telep_4_walk")
			local look = patrol("yan_labirint_telep_4_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 5 then
			local point = patrol("yan_labirint_telep_5_walk")
			local look = patrol("yan_labirint_telep_5_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
	end
end

function yan_labirint_telep_3()
	local yaz_var = xvars.yan_lab_tele
	if yaz_var < 5 then
		nick.gar_lamb_zombs()
		olr.blow_add(100)
		local rnddir = math.random(1, 5)
		if rnddir == 1 then
			local point = patrol("yan_labirint_telep_1_walk")
			local look = patrol("yan_labirint_telep_1_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 2 then
			local point = patrol("yan_labirint_telep_2_walk")
			local look = patrol("yan_labirint_telep_2_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 3 then
			local point = patrol("yan_labirint_telep_3_walk")
			local look = patrol("yan_labirint_telep_3_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 4 then
			local point = patrol("yan_labirint_telep_4_walk")
			local look = patrol("yan_labirint_telep_4_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 5 then
			local point = patrol("yan_labirint_telep_5_walk")
			local look = patrol("yan_labirint_telep_5_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
	end
end

function yan_labirint_telep_4()
	local yaz_var = xvars.yan_lab_tele
	if yaz_var < 5 then
		nick.gar_lamb_zombs()
		olr.blow_add(100)
		local rnddir = math.random(1, 5)
		if rnddir == 1 then
			local point = patrol("yan_labirint_telep_1_walk")
			local look = patrol("yan_labirint_telep_1_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 2 then
			local point = patrol("yan_labirint_telep_2_walk")
			local look = patrol("yan_labirint_telep_2_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 3 then
			local point = patrol("yan_labirint_telep_3_walk")
			local look = patrol("yan_labirint_telep_3_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 4 then
			local point = patrol("yan_labirint_telep_4_walk")
			local look = patrol("yan_labirint_telep_4_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 5 then
			local point = patrol("yan_labirint_telep_5_walk")
			local look = patrol("yan_labirint_telep_5_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
	end
end

function yan_labirint_telep_5()
	local yaz_var = xvars.yan_lab_tele
	if yaz_var < 5 then
		nick.gar_lamb_zombs()
		olr.blow_add(100)
		local rnddir = math.random(1, 5)
		if rnddir == 1 then
			local point = patrol("yan_labirint_telep_1_walk")
			local look = patrol("yan_labirint_telep_1_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 2 then
			local point = patrol("yan_labirint_telep_2_walk")
			local look = patrol("yan_labirint_telep_2_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 3 then
			local point = patrol("yan_labirint_telep_3_walk")
			local look = patrol("yan_labirint_telep_3_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 4 then
			local point = patrol("yan_labirint_telep_4_walk")
			local look = patrol("yan_labirint_telep_4_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		elseif rnddir == 5 then
			local point = patrol("yan_labirint_telep_5_walk")
			local look = patrol("yan_labirint_telep_5_look")
			db.actor:set_actor_position(point:point(0))
			local dir = look:point(0):sub(point:point(0))
			db.actor:set_actor_direction(-dir:getH())
			level.add_pp_effector("black.ppe", 201831, false)
			xvars.yan_lab_tele = xvars.yan_lab_tele + 1
			local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\yantar_demon_voice]])
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
	end
end

function use_yanprib_hata()
	if not has_alife_info("prof_uletel_gde_laborant_start_talked") then
		--news_manager.send_tip(db.actor, game.translate_string("use_yanprib_hata_0"), nil, "default", 30000)
		olr.hud_tip("", game.translate_string("use_yanprib_hata_0"), 3, true)
		return
	end
	if not has_alife_info("yan_dot_start_zamery") then
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_psi_measurer_1").." "..xvars.yan_phase_zam_quest.." "..game.translate_string("st_xr_effects_psi_measurer_2"), nil, "info", 5000, nil, nil, true, "st_xr_effects_psi_measurer")
		db.actor:give_info_portion("yan_dot_start_zamery")
		xvars.yan_phase_zam_quest_flag = false
		olr_timers.st_timer("omsffsss3", 25, "xr_effects.yan_phase_zam_quest_on()")
		if not has_alife_info("yan_dot_start_zamery_done") then
			olr_timers.st_timer("yan_zam_zombies_rush", 8, "nick.yan_zam_zombies_rush_spawen()")
		end
		return
	end
	if xvars.yan_phase_zam_quest_flag == true then
		xvars.yan_phase_zam_quest = xvars.yan_phase_zam_quest + 1
		if xvars.yan_phase_zam_quest < 5 then
			olr_timers.st_timer("omsffsss3", 25, "xr_effects.yan_phase_zam_quest_on()")
		end
		xvars.yan_phase_zam_quest_flag = false
		
		news_manager.send_tip(db.actor, game.translate_string("use_yanprib_hata_1"), nil, "info", 5000, nil, nil, true, "st_xr_effects_psi_measurer")
		if xvars.yan_phase_zam_quest >= 5 then
			db.actor:give_info_portion("yan_dot_start_zamery_done")
			news_manager.send_tip(db.actor, game.translate_string("use_yanprib_hata_2"), nil, "info", 5000, nil, nil, true, "st_xr_effects_psi_measurer")
		end
	end
end

function yan_phase_zam_quest_on()
	if xvars.yan_phase_zam_quest < 5 then
		news_manager.send_tip(db.actor, game.translate_string("yan_phase_zam_quest_on_0"))
		xvars.yan_phase_zam_quest_flag = true
		olr_timers.st_timer("omsffsss3", 5, "xr_effects.yan_phase_zam_quest_off()")
	end
end

function yan_phase_zam_quest_off()
	if xvars.yan_phase_zam_quest < 5 then
		news_manager.send_tip(db.actor, game.translate_string("st_xr_effects_psi_measurer_3")..xvars.yan_phase_zam_quest.." "..game.translate_string("st_xr_effects_psi_measurer_4"), nil, "info", nil, nil, true, "st_xr_effects_psi_measurer")
		xvars.yan_phase_zam_quest_flag = false
		olr_timers.st_timer("omsffsss3", math.random(35,90), "xr_effects.yan_phase_zam_quest_on()")
	end
end

function del_leader_clearsky()
	olr.del_by_name("lvl7_yantar_staler_undead_olr")
	db.actor:give_info_portion("spawn_bar_leader_clearsky_info")
	news_manager.send_tip(db.actor, game.translate_string("del_leader_clearsky_0"), nil, "professor", 9000)
end

function del_contr_pogreb()
	olr.del_by_name("lvl7_yantar_stalker_0065")
end

function take_psyhead_yan()
	local mrandom = math.random
	if has_alife_info("yan_doc_psy_start_has") then
		olr.del_by_name("lvl7_yantar_physic_object_0708")
		nik_dialog.out_item_much("proto_psy_shap",1)
		if mrandom(2) == 1 then
			db.actor.health = -db.actor.health/mrandom(2,5)
		end
		if mrandom(2) == 1 then
			db.actor.power = -db.actor.power/mrandom(2,5)
		end
		if mrandom(2) == 1 then
			db.actor.psy_health = -db.actor.psy_health/mrandom(2,5)
		end
		if mrandom(2) == 1 then
			db.actor.radiation = -db.actor.radiation/mrandom(2,5)
		end
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\low_base]])
		if not snd_obj:playing() then 
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
		end
		alife():create("af_deadhead", db.actor:position(),db.actor:level_vertex_id(),  db.actor:game_vertex_id(),db.actor:id())
		level.add_pp_effector("radar_wake.ppe", 20131, false)
		db.actor:give_info_portion("take_psyhead_yan_have")
		--nik_dialog.out_item_much("proto_psy_shap",1)
	end
end

function use_oldgauss_yan()
	if not has_alife_info("laborant_otpravlaet_spat_gg_finished") then
		olr.hud_tip("", game.translate_string("use_oldgauss_yan_0"), 10)
		return
	end
	olr.del_by_name("lvl7_yantar_physic_object_0013")
	olr.give_item("wpn_gauss")
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Болот
-- ----------------------------------------------------------------------------------------------------
function get_real_actor_name()
	if not has_alife_info("cit_fail_first_task") then
		return "st_actor_name"
	else
		return "st_actor_name_real"
	end
end

function take_lamp_swamp()
	if has_alife_info("swamp_izlom_start_dialog_talked") then 
		olr.del_by_name("lvl8_swamp_physic_object_0252")
		olr.give_item("af_lamp")
		olr.info("has_lamp_swapm")
	end
end

function swamp_izlom_spawn_lampa()
	if has_alife_info("mg_izlom_start_talked") and has_alife_info("pogo_medzalupa_start_done") then
		if not has_alife_info("izlom_blolota_sapawn") then
			news_manager.send_tip(db.actor, game.translate_string("swamp_izlom_spawn_lampa_0"), nil, "unknown", 39000)
			olr.info("izlom_blolota_sapawn")
			olr.to_online("lvl8_swamp_physic_object_0252")
			olr.kill_mon_in_radius(db.actor:position(), 300)
		end
	end
end

function del_mechenyy_swapm(actor)
	local se_obj = alife():object("lvl8_swamp_stalker_0020")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function phantsam_hitted()
	if math.random(1, 25) == 2 then
		nick.phantasms_zombies()
		olr.horror_snd()
	end

	local effect_for_wpn = {
		["wpn_rg-6"] = true,
		["wpn_rg6_m1"] = true,
		["wpn_rpg7"] = true
	}

	local cur_weapon = db.actor:active_item()
	if cur_weapon ~= nil then
		local cur_weapon_sec = cur_weapon:section()
		if effect_for_wpn[cur_weapon_sec] ~= nil then
			db.actor.health = -0.06
			level.add_pp_effector("dead_zone.ppe", 971974, false)
			--level.add_cam_effector("camera_effects\\fatigue.anm", 19749, true, "")
			local song_start = xr_sound.get_safe_sound_object([[ambient\special\heartbeat_fast]])
			song_start:play_at_pos(db.actor, db.actor:position(), sound_object.s3d)
			db.actor.psy_health = -0.1
			nick.phantasms_zombies()
			nick.rnd_ppe_eff()
			phatstm_telep()
		end
	end
end

function phatstm_telep()
	-- Получаем объект фантома напрямую
	local phantom = alife():object("lvl8_swamp_phantasm")
	if not phantom then return end

	-- Таблица возможных позиций для телепортации
	local teleport_positions = {
		vector():set(-3, 3, -213),	 -- позиция 1
		vector():set(127, 2, -179),	  -- позиция 2
		vector():set(184, 3, -202),	  -- позиция 3
		vector():set(65, -6, -181),	  -- позиция 4
		vector():set(0, -6, -207)	  -- позиция 5
	}

	local new_pos = teleport_positions[math.random(1, #teleport_positions)]
	alife():teleport_object(phantom.id, db.actor:game_vertex_id(), db.actor:level_vertex_id(), new_pos)
end

function del_fil_gener()
	olr.del_by_name("lvl5_bar_stalker_0052")
end

function del_fil_swamp()
	olr.del_by_name("lvl8_swamp_stalker_0022")
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Тихих Холмов
-- ----------------------------------------------------------------------------------------------------
function kill_mil_nap()
	local obj = alife():object("lvl9_military_stalker_0033")
	local bos = level.object_by_id(obj.id)
	if bos then
		bos:kill(bos)
	end
end

function mil_contr_house()
	olr.del_by_name("lvl9_military_space_restrictor_0029")
	olr.spawn_on_obj("m_controller_e", "lvl9_military_physic_object_0211")
end

function mil_kamp_killer_dead()
	xvars.mil_kamp_killer_dead_cnt = xvars.mil_kamp_killer_dead_cnt + 1
	if xvars.mil_kamp_killer_dead_cnt >= 3 and not has_alife_info("mil_kamp_killer_dead_has") then
		olr.info("mil_kamp_killer_dead_has")
		news_manager.send_tip(db.actor, game.translate_string("mil_kamp_killer_dead_0"), 12, "hero", 35000)
		olr_timers.st_timer("jaba_otvet_start", 22, "nick.jaba_otvet_start_done()")
	end
end

function kill_mil_karlik()
	xvars.kill_mil_karlik_cnt = xvars.kill_mil_karlik_cnt + 1
	if xvars.kill_mil_karlik_cnt > 2 and not has_alife_info("mil_karlics_deadsnow") then
		olr.info("mil_karlics_deadsnow")
		news_manager.send_tip(db.actor, game.translate_string("kill_mil_karlik_0"), nil, "hero", 35000)
		olr.del_by_name("lvl_mmm_physic_object_0056")
		olr.del_by_name("lvl_mmm_physic_object_0001")
		olr.del_by_name("lvl_mmm_physic_object_0053")
		olr.del_by_name("lvl_mmm_physic_object_0000")
		olr.del_by_name("lvl_mmm_physic_object_0002")
		olr.del_by_name("lvl_mmm_physic_object_0054")
	end
end

function karliks_done_dogdead()
	olr.del_by_name("lvl9_military_physic_object_0449")
	olr.spawn_on_obj("af_thorn_black", "lvl9_military_dog_strong_0003")
	olr.spawn_on_obj("af_magnet", "lvl9_military_dog_strong_0003")
	olr.spawn_on_obj("pseudodog_strong", "lvl9_military_dog_strong_0003")
	local snd_obj1 = xr_sound.get_safe_sound_object([[ambient\special\glass_break]])
	snd_obj1:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	local snd_obj = xr_sound.get_safe_sound_object([[monsters\dog\threaten_1]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	local obj = alife():object("lvl9_military_dog_strong_0003")
	local bos = level.object_by_id(obj.id)
	if bos then
		bos:kill(bos)
	end
	olr.del_by_name("lvl9_military_space_restrictor_0028")
end

function greh_pris_1()
	alife():create("ph_food_conserv1", db.actor:position():add(db.actor:direction():add(0.2)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	alife():create("ph_food_vater", db.actor:position():add(db.actor:direction():add(0.1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	db.actor.health = 1
	db.actor.satiety = 1
	db.actor.thirst = 1
	db.actor.sleep = 1
	db.actor.radiation = -1
	olr_sleep.sleep_main_special(8)
	olr.blow_add(250)
	local STbron = db.actor:object("device_pda") 
	if STbron then
		STbron:set_condition(STbron:condition() + 0.03)
	end
end

function greh_pris_5()
	alife():create("vodka_used_empty", db.actor:position():add(db.actor:direction():add(0.1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	olr.blow_add(250)
	db.actor.health = 1
	db.actor.satiety = 1
	db.actor.thirst = 1
	db.actor.sleep = 1
	db.actor.radiation = -1
	olr_sleep.sleep_main_special(8)
	news_manager.send_tip(db.actor, game.translate_string("greh_pris_5_0"), nil, "barman", 31000, nil, nil, true, "st_barkeep_short")
end

function greh_pris_10()
    olr.blow_add(250)
	db.actor.health = 1
	db.actor.satiety = 1
	db.actor.thirst = 1
	db.actor.sleep = 1
	db.actor.radiation = -1
	olr.hud_tip("", game.translate_string("greh_pris_10_0"), 10, true) -- мысль мессера
    db.actor:give_info_portion("start_greh_prisoning_rush")

    local box = alife():object("lvl9_military_box_rukzak")
    if box then
        alife():create("wpn_knife_bayonet_rusty", box.position, box.m_level_vertex_id, box.m_game_vertex_id, box.id)
        alife():create("battery_change", box.position, box.m_level_vertex_id, box.m_game_vertex_id, box.id)
    end
end

function greh_pris_11()
	olr.blow_add(250)
	olr.hud_tip("", game.translate_string("greh_pris_11_0"), 10, true) -- мысль мессера
	local sim = alife()
	sim:create("sim_respawn_soldier_specnaz", db.actor:position():add(db.actor:direction():mul(-142)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_specnaz", db.actor:position():add(db.actor:direction():mul(-142)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_specnaz", db.actor:position():add(db.actor:direction():mul(-142)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_milstalker", db.actor:position():add(db.actor:direction():mul(-42)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_specnaz", db.actor:position():add(db.actor:direction():mul(142)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_specnaz", db.actor:position():add(db.actor:direction():mul(142)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_specnaz", db.actor:position():add(db.actor:direction():mul(142)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim:create("sim_respawn_soldier_milstalker", db.actor:position():add(db.actor:direction():mul(42)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function use_greh_save()
	local obj = db.actor:object("greh_leader_key") 
	if not obj then
		olr.hud_tip("", game.translate_string("use_greh_save_0"), 10)
		return
	end
	alife():create("vetri_bezumia_doki", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	olr.del(obj)
	news_manager.relocate_item(db.actor, "in", "vetri_bezumia_doki")
end

function mil_dok_feik()
	olr.del_by_name("lvl9_military_space_restrictor_0026")
	olr.disable_walk()
	olr.hud_tip("", game.translate_string("st_xr_effects_message_doctor_surprise"), 5)
	olr_timers.st_timer("dok_feik", 10, "nick.mil_dok_feik_enable()")
end

function mil_doglead_sms()
	xvars.kill_mil_karlik_cnt = 0
	local sobj = alife():object("lvl9_military_physic_object_0449") 
	if sobj then 
		olr.add_spot( sobj.id,"crlc_mdl",game.translate_string("st_xr_effects_message_message_from_unknown") )
	end
	olr.info("mil_dog_spawn")
	local snd_obj = xr_sound.get_safe_sound_object([[monsters\dog\idle_0]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	news_manager.send_tip(db.actor, game.translate_string("mil_doglead_sms_0"), nil, "unknown", 30000)
	olr.del_by_name("lvl9_military_space_restrictor_0027")
	olr.del_by_name("lvl10_radar_physic_fog_center")
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Мёртвого города
-- ----------------------------------------------------------------------------------------------------
function deadcity_monolit_proverka(actor, npc)
	if has_alife_info("olr_traders_night") and has_alife_info("deadcity_mon_quest_start") then
		db.actor:give_info_portion("deadcity_mon_quest_on_place")
	end
end

function del_mg_zombcat_talked()
	olr.spawn_on_obj("af_black_drops", "lvl11_deadcity_stalker_0032")
	olr.del_by_name("lvl11_deadcity_stalker_0032")
end

function mg_boloto_hitted()
	local effect_for_wpn = {
		["wpn_rg-6"] = true,
		["wpn_rg6_m1"] = true,
		["wpn_rpg7"] = true
	}

	local cur_weapon = db.actor:active_item()
	if cur_weapon == nil then return end
	
	local cur_weapon_sec = cur_weapon:section()
	if not effect_for_wpn[cur_weapon_sec] then return end

	-- Применяем эффекты к актору
	db.actor.health = -0.05
	level.add_pp_effector("dead_zone.ppe", 971974, false)
	local song_start = xr_sound.get_safe_sound_object([[ambient\special\heartbeat_fast]])
	song_start:play_at_pos(db.actor, db.actor:position(), sound_object.s3d)
	db.actor.psy_health = -0.05
	nick.rnd_ppe_eff()
	nick.phantasms_zombies()

    local observer = alife():object("lvl11_deadcity_observer")
    if not observer then return end
    
    local level_observer = level.object_by_id(observer.id)
    if not level_observer or level_observer.health <= 0 then return end

	local bez_var = math.random(1, 5)
	local teleport_effects = {
		[1] = function()
			for i = 1, 12 do
				local wait_time = time_global() + i * 1000
				level.add_call(
					function() return time_global() > wait_time end,
					function()
						local rndx = math.random(186, 195)
						local rndy = math.random(146, 165)
						level_observer:set_position(vector():set(rndx, -5, rndy))
						local snd_obj = xr_sound.get_safe_sound_object([[monsters\biting\def_0]])
						snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
					end
				)
			end
			olr.spawen_phantoms()
			xr_sound.get_safe_sound_object([[ambient\weather\earthquake]]):play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 2.0)
		end,
		[2] = function()
			level_observer:set_position(vector():set(178, -9, 186))
			olr.spawen_phantoms()
			olr.horror_snd()
			xr_sound.get_safe_sound_object([[ambient\special\heartbeat_fast]]):play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 3.0)
		end,
		[3] = function()
			level_observer:set_position(vector():set(177, -9, 127))
			olr.spawen_phantoms()
			olr.horror_snd()
			xr_sound.get_safe_sound_object([[anomaly\stancia_thunder]]):play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 4.0)
		end,
		[4] = function()
			level_observer:set_position(vector():set(165, -9, 151))
			olr.spawen_phantoms()
			olr.horror_snd()
			xr_sound.get_safe_sound_object([[actor\hit_fist]]):play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 3.0)
		end,
		[5] = function()
			level_observer:set_position(vector():set(176, -9, 151))
			olr.spawen_phantoms()
			olr.horror_snd()
		end
	}

	-- Выполняем выбранный эффект
	if teleport_effects[bez_var] then
		teleport_effects[bez_var]()
	end
end

function del_mg_ludoed()
	local se_obj = alife():object("lvl11_deadcity_stalker_0048")
	if se_obj then
		alife():release(se_obj, true)
		db.actor:change_character_reputation(-10)
	end
end

function del_final_mg_ds()
	olr.del_by_name("lvl11_deadcity_staler_undead_olr_0003")
	db.actor:change_character_reputation(10)
	db.actor:give_info_portion("mg_ds_now_done")
end

function del_final_mg_izlom_talked()
	news_manager.send_tip(db.actor, game.translate_string("del_final_mg_izlom_talked_0"), nil, "unknown", 39000)
	olr.del_by_name("lvl11_deadcity_m_fracture_e")
end

function use_drink_mg()
	local ustalost = db.actor.thirst
	if ustalost>0.80 then
		news_manager.send_tip(db.actor, game.translate_string("use_drink_mg_0"), nil, "info", 9000)
		return 
	end
	db.actor:change_actor_thirst(1)
	return
	--[[
	if not has_alife_info("bolezn_parazity_info") then
		olr_timers.st_timer("bolezn_parasite_timer", 2250, "nick.bolezn_parasite_timer()")
		db.actor:give_info_portion("bolezn_parazity_info")
		return
	end
	--]]
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Рыжего леса
-- ----------------------------------------------------------------------------------------------------
function rad_psdhym_telep()
	db.actor.psy_health = -0.21
	olr.info("pseudohuman_first_checkup_done")
	olr.del_by_name("lvl10_radar_space_restrictor_0009")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\heartbeat_long]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	level.add_pp_effector("black.ppe", 20131, false)
	local point = patrol("ps_hum_lead_look")
	local look = patrol("ps_hum_lead_walk")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	news_manager.send_tip(db.actor, game.translate_string("rad_psdhym_telep_0"), 6, "unknown", 15000)
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Лаборатории №9
-- ----------------------------------------------------------------------------------------------------
function actor_thought_need_psy_stabilizer(actor, npc)
	olr.hud_tip("", game.translate_string("st_actor_thought_need_psy_stabilizer"), 5, true) -- мысль мессера
end

function rad_bun_ne_lez_suda()
	--bind_stalker.hide_weapon()
	local point = patrol("farbun_gluk_walk")
	local look = patrol("farbun_gluk_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("black.ppe", 20131, false)
	--log1("ssg")
end

function del_swatoy_second()
	local se_obj = alife():object("lvl12_radar_bunker_staler_undead_olr_0000")
	if se_obj then
		alife():release(se_obj, true)
	end
end

function try_radbun_antenaupr()	 -- вводим код
	if not has_alife_info("jornal_1_taken") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_0"), nil, "default", 15000)
		return
	end
	if not has_alife_info("jornal_3_taken") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_1"), nil, "default", 15000)
		return
	end
	if not has_alife_info("spawn_doks_holmy") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_2"), nil, "default", 15000)
		return
	end
	if not has_alife_info("spawn_doks_yantar") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_3"), nil, "default", 15000)
		return
	end
	if not has_alife_info("spawn_doks_radar") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_4"), nil, "default", 15000)
		return
	end
	if not has_alife_info("jornal_6_taken") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_5"), nil, "default", 15000)
		return
	end
	if not has_alife_info("spawn_jourlalist") then
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_6"), nil, "default", 15000)
		return
	end
	if has_alife_info("radbun_antena_bar") then
		olr.info("pre_aes_antenna_off")
		nick.set_level_choosen_zombied("lvl5_bar")
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_7"), 50, "dolg", 35000)
		olr.del_by_name("lvl12_radar_bunker_physic_shitok_zal_0000")
		level.add_pp_effector("blink.ppe", 20131, false)
		return
	end
	if has_alife_info("radbun_antena_mg") then
		olr.info("pre_aes_antenna_off")
		nick.set_level_choosen_zombied("lvl11_deadcity")
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_8"), 50, "freedom", 35000)
		olr.del_by_name("lvl12_radar_bunker_physic_shitok_zal_0000")
		level.add_pp_effector("blink.ppe", 20131, false)
		return
	end
	if has_alife_info("radbun_antena_yan") then
		olr.info("pre_aes_antenna_off")
		nick.set_level_choosen_zombied("lvl7_yantar")
		news_manager.send_tip(db.actor, game.translate_string("try_radbun_antenaupr_9"), 50, "ecolog", 35000)
		olr.del_by_name("lvl12_radar_bunker_physic_shitok_zal_0000")
		level.add_pp_effector("blink.ppe", 20131, false)
		return
	end
end

function use_nasos_pover()
	if has_alife_info("bunlab_light_etqj2") and has_alife_info("bunlab_light_etqj1") then
		db.actor:give_info_portion("on_nasos_radarbun")
	else
		news_manager.send_tip(db.actor, game.translate_string("use_nasos_pover_0"), nil, "default", 19000)
	end
end

function use_pc_radbun()
	if not has_alife_info("pre_aes_antenna_colba_boom") then
		news_manager.send_tip(db.actor, game.translate_string("use_pc_radbun_0"), nil, "default", 39000)
		return
	end
	local STbronb = db.actor:object("radbun_karta_pc")
	if not STbronb then
		news_manager.send_tip(db.actor, game.translate_string("use_pc_radbun_1"), nil, "default", 35000)
		return
	end
	if has_alife_info("radbun_antena_bar") or has_alife_info("radbun_antena_mg") or has_alife_info("radbun_antena_yan") then
		news_manager.send_tip(db.actor, game.translate_string("use_pc_radbun_2"), nil, "default", 39000)
		return
	end
	level.start_stop_menu(olr_pult.verstak_start(),true)
end

function use_ecetr_radbun_door()
	if not has_alife_info("radbun_door_elecr_on") then
		news_manager.send_tip(db.actor, game.translate_string("use_ecetr_radbun_door_0"), nil, "hero", 39000)
		olr.info("ln9_find_switchboard_start")
		return
	end
	olr.info("open_door_rabun_zal")
	olr.del_by_name("lvl12_radar_bunker_physic_shitok_zal")
end

function use_ecetr_radbun()
	if not has_alife_info("rad_olr_door_open") then
		news_manager.send_tip(db.actor, game.translate_string("use_ecetr_radbun_0"), nil, "hero", 39000)
		return
	end
	olr.del_by_name("lvl12_radar_bunker_electt_open")
	olr.del_by_name("l10u_radar_bunker_physic_object_0317")
	olr.del_by_name("l10u_radar_bunker_physic_object_0318")
	olr.info("radbun_door_elecr_on")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\electric_crash]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end	
end

function swatoy_wtf1()
	olr.kill_mon_in_radius(db.actor:position(), 120)
	news_manager.send_tip(db.actor, game.translate_string("swatoy_wtf1_0"), nil, "unknown", 31000, nil, nil, true, "st_sim_test_000_name")
end

function swatoy_wtf2()
	news_manager.send_tip(db.actor, game.translate_string("swatoy_wtf2_0"), nil, "unknown", 31000, nil, nil, true, "st_sim_test_000_name")
end

function swatoy_wtf3()
	news_manager.send_tip(db.actor, game.translate_string("swatoy_wtf3_0"), nil, "unknown", 31000, nil, nil, true, "st_sim_test_000_name")
end

function swatoy_wtf4()
	news_manager.send_tip(db.actor, game.translate_string("swatoy_wtf4_0"), nil, "unknown", 31000, nil, nil, true, "st_sim_test_000_name")
	level.show_indicators()
	level.enable_input()
	db.actor:restore_weapon()
end

function swatoy_wtf5()
	local snd_obj = xr_sound.get_safe_sound_object([[weapons\gauss\shoot]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	olr.kill_by_name("lvl12_radar_bunker_staler_undead_olr_0001")
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Припяти
-- ----------------------------------------------------------------------------------------------------
function prip_sniper_kill()
	if db.actor:alive() then
		db.actor.health = -1
		local snd_obj = xr_sound.get_safe_sound_object([[weapons\svu\shoot]])
		if not snd_obj:playing() then 
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
		end	
	end
end

function lmp_prip()
	olr.info("prp_lamp_start")
	olr.del_by_name("lvl13_prip_space_restrictor_0017")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\electric_crash]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Уровня 12 / Курган
-- ----------------------------------------------------------------------------------------------------
function topim_actora_chaes()
	if db.actor:alive() then
		db.actor.health = -1
		level.add_pp_effector("black.ppe", 20131, false)
		local snd_obj = xr_sound.get_safe_sound_object([[actor\underwater]])
		if not snd_obj:playing() then 
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
		end	
	end
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для ЧАЭС
-- ----------------------------------------------------------------------------------------------------


-- ----------------------------------------------------------------------------------------------------
-- Функции для Саркофага
-- ----------------------------------------------------------------------------------------------------
function sar_monolith_miracle(actor, npc)
	-- продолжаем искать себя
	if has_alife_info("jurn_sudb_done") then
		nick.start_sarcofag_cutscene_findmyself()
		nick.start_sarcofag_findmyself_del_all()
		olr.info("choose_destiny_done")
		return
	end
	olr_monolith.select_fake_ending()	
end

function suker_sarcofag_spwn()
	--log1("k s")
	olr.spawn_on_obj("m_bloodsucker_e", "lvl15_sarcofag_space_restrictor_0014")
	olr.del_by_name("lvl15_sarcofag_space_restrictor_0014")
end

function pokushat_out(actor)
	local point = patrol("tivdiridit2_walk")
	local look = patrol("tivdiridit2_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

-- ----------------------------------------------------------------------------------------------------
-- Функции для Генераторов
-- ----------------------------------------------------------------------------------------------------
function actro_hit_napgen()
	xr_effects.kill_actor()
	level.add_pp_effector("snd_shock.ppe", 2031, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\rostok_bloodsucker_call]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end	
end

function spawn_genrozd()
	olr.del_noparent_weapons()
	olr.del_by_name("lvl16_generators_staler_undead_olr")

	local wait_time = 0
	wait_time = time_global() + 1200
	level.add_call(
		function() return time_global() > wait_time end,
		function() olr.spawn_on_obj("m_gigant_e", "lvl16_generators_space_restrictor_0020") end
	)

	--olr.spawn_on_obj("dead_body_skelet", "lvl16_generators_space_restrictor_0021")
end

function ac_hit_gen_durik()
	--log1("hhh")
	olr.info("oso_start_goavay_visel")
	olr.del_by_name("lvl16_generators_space_restrictor_0056")
	xr_effects.actor_usel_boss()
end

function final_cutscene_start()
	olr.snd([[characters_voice\scenario\generators\end\ending_checkpoint]])
--	level.set_weather("1865",true)
	level.add_cam_effector2("camera_effects\\ending_one.anm", 30, false, "nick.final_cutscene_start_two")
	level.add_pp_effector("black.ppe", 201831, false)
	local point = patrol("actor_plpkor_walk")
	local look = patrol("actor_plpkor_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("snd_shock.ppe", 2031, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\rostok_bloodsucker_call]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	db.actor:hide_weapon()
	level.disable_input()
	level.hide_indicators()
	olr.disable_walk()
end

function gen_labirint_telep()
	local point = patrol("teleport_gen_way_olr2")
	local look = patrol("teleport_gen_look_olr2")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("black.ppe", 20131, false)
end

function rat_ending_death_spawn()
	local wait_time = 0
	wait_time = time_global() + 1100
	level.add_call(
		function() return time_global() > wait_time end,
		function() olr.del_by_name("lvl16_generators_rat_volk") end
	)
	--xr_effects.disable_ui(db.actor, nil)
	alife():create("rat_volk_undead", db.actor:position():add(db.actor:direction():add(1)), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	level.add_pp_effector("black.ppe", 201831, false)
	olr_timers.st_timer("rat_fly_away", 10, "nick.rat_fly_away()")
end

function rat_labirint_telep()
	local point = patrol("start_rat_ending_walk")
	local look = patrol("start_rat_ending_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	level.add_pp_effector("black.ppe", 201831, false)
end

function gen_start_open_door_one()
	news_manager.send_tip(db.actor, game.translate_string("gen_start_open_door_one_0"), nil, "hero", 49000)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\siren_gen]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function use_gen_klava()
	if not has_alife_info("gen_two_door_open_spusk") then
		db.actor:give_info_portion("gen_two_door_open_spusk")
		nick.rad_bun_tv_casuality_room()
		olr.del_by_name("lvl16_generators_controller_tubeman")
		olr.kill_mon_in_radius(db.actor:position(), 95)
		olr.to_online("lvl16_generators_physic_object_0249")
	end
end

function gen_wtoroy_etaj_start()
	olr.del_by_name("lvl16_generators_space_restrictor_0053")
	news_manager.send_tip(db.actor, game.translate_string("gen_wtoroy_etaj_start_0"), nil, "unknown", 5000)
	olr_timers.st_timer("tark_wt_et", 5, "nick.tark_wt_et_one()")
	level.add_pp_effector("black.ppe", 20131, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\psy_noise]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function actor_podosel_boss()
	db.actor:hide_weapon()
	level.add_pp_effector("black.ppe", 20131, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\explosion_1]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
	olr.del_by_name("lvl16_generators_space_restrictor_0056")
	level.add_cam_effector2("camera_effects\\gen_boss_actor_close.anm", 22, false, "xr_effects.hid_bos_scream")
	olr.disable_walk()
	level.disable_input()
	level.hide_indicators()	
	local point = patrol("gen_ac_last_walk")
	local look = patrol("gen_ac_last_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	olr_timers.st_timer("molot_bure54rs", 12, "xr_effects.hid_bos_screamsnd()")
	db.actor:hide_weapon()
end

function hid_bos_screamsnd()
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\sob]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
	olr.horror_snd()
end

function hid_bos_scream()
	dialogs_aes.olr_fin()
end

function boss_dance_boom_black1()
	olr.horror_snd()
	local objp = alife():object("lvl16_generators_staler_undead_olr_0003")
	local bosp = level.object_by_id(objp.id)
	if objp and bosp then
		local boss_particle = particles_object("ghoul\\fx-05-blue-glow_00")
		if not boss_particle:playing() then
			boss_particle:play_at_pos(vector():set(bosp:position().x, bosp:position().y + 1.6, bosp:position().z))
		end
	end
	level.add_pp_effector("black.ppe", 20131, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\explosion_1]])
	if not snd_obj:playing() then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\darklab_ambient]])
	if not snd_obj:playing() then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\thunder_3]])
	if not snd_obj:playing() then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function boss_dance_boom_black2()
	olr.horror_snd()
	local objp = alife():object("lvl16_generators_staler_undead_olr_0003")
	local bosp = level.object_by_id(objp.id)
	if bosp then
		local boss_particle = particles_object("ghoul\\fx-05-blue-glow_00")
		if not boss_particle:playing() then 
			boss_particle:play_at_pos(vector():set(bosp:position().x, bosp:position().y+1.6, bosp:position().z))
		end
	end
	level.add_cam_effector2("camera_effects\\gen_boss_black2.anm", 11, false, "")
	level.add_pp_effector("black.ppe", 20131, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\explosion_2]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function boss_dance_boom_black3()
	olr.horror_snd()
	local objp = alife():object("lvl16_generators_staler_undead_olr_0003")
	local bosp = level.object_by_id(objp.id)
	if bosp then
		local boss_particle = particles_object("ghoul\\fx-05-blue-glow_00")
		if not boss_particle:playing() then 
			boss_particle:play_at_pos(vector():set(bosp:position().x, bosp:position().y+1.6, bosp:position().z))
		end
	end
	level.add_cam_effector2("camera_effects\\gen_boss_black3.anm", 11, false, "")
	level.add_pp_effector("black.ppe", 20131, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\explosion_3]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function boss_dance_boom_black4()
	olr.horror_snd()
	local objp = alife():object("lvl16_generators_staler_undead_olr_0003")
	local bosp = level.object_by_id(objp.id)
	if bosp then
		local boss_particle = particles_object("ghoul\\fx-05-blue-glow_00")
		if not boss_particle:playing() then 
			boss_particle:play_at_pos(vector():set(bosp:position().x, bosp:position().y+1.6, bosp:position().z))
		end
	end
	olr_timers.st_timer("molot_bure54r4s", 9, "xr_effects.en_gen_ui_deadboss()")
	level.add_pp_effector("black.ppe", 20131, false)
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\fear_hata]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function en_gen_ui_deadboss()
	level.remove_cam_effector(3496)
	olr.enable_walk()
	level.show_indicators()
	level.enable_input()
	nick.spawn_warlab_kostri()
	olr.info("choise_exit_or_boss")
end

function actor_usel_boss()
	if not has_alife_info("oso_start_goavay_visel") then
		olr.info("oso_start_goavay_visel")
		olr.horror_snd()
		local objp = alife():object("lvl16_generators_staler_undead_olr_0003")
		local bosp = level.object_by_id(objp.id)
		if bosp then
			local boss_particle = particles_object("ghoul\\fx-05-blue-glow_00")
			if not boss_particle:playing() then
				boss_particle:play_at_pos(vector():set(bosp:position().x, bosp:position().y + 1.6, bosp:position().z))
			end
		end
		olr_blowout.blowout_additional_timer()
		olr.hud_tip("", game.translate_string("actor_usel_boss_0"), 10, true)
		olr.kill_by_name("lvl16_generators_staler_undead_olr_0003")
		olr.del_by_name("lvl16_generators_space_restrictor_0070")
		olr.del_by_name("lvl16_generators_space_restrictor_0057")
		olr.del_by_name("lvl16_generators_space_restrictor_0056")
	end
end

function start_oso_killed_shahta()
	level.add_cam_effector("camera_effects\\shell_shock.anm", 34956, false, "")
	olr.del_by_name("lvl16_generators_space_restrictor_0061")

	local spawn_data = {
		{section = "ph_med_stolik_01"},
		{section = "dead_body_skelet"},
		{section = "ph_med_stoyka_01"},
		{section = "ph_shkaf_4"},
		{section = "ph_item_mks10"}
	}

	local function create_hit_effect(obj)
		local h = hit()
		h.draftsman = obj
		h.type = hit.strike
		h.direction = vector():set(math.random(), 0.1, math.random())
		h.power = 1
		h.impulse = 2
		obj:hit(h)
	end

	for _, data in ipairs(spawn_data) do
		local obj = olr.spawn_on_obj(data.section, "lvl16_generators_space_restrictor_0058")
		level.client_spawn_manager():add(obj.id, 0, 
			function(id, obj) 
				create_hit_effect(obj) 
			end)
	end
	
	for i = 1, 65534 do
		local lokobj = level.object_by_id(i)
		if lokobj then
			if get_clsid(lokobj) == clsid.hanging_lamp and lokobj:position():distance_to(db.actor:position()) < 50 then
				if lokobj:mass() == 0 then
					lokobj:get_hanging_lamp():set_brightness(0.01)
				end
			end
		end
	end
	
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\explosion_2]])
	if not snd_obj:playing() then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function gen_oso_killed_ecolgs()
	bind_stalker.hide_weapon()
	olr_timers.del_timer("blowout_additional_timer")
	olr_timers.del_timer("blowout_additional_timer2")
	olr_timers.del_timer("blowout_additional_timer3")
	olr_timers.del_timer("blowout_additional_timer4")
	olr_timers.del_timer("blowout_additional_timer5")
	level.add_pp_effector("black.ppe", 20131, false)
	olr.del_by_name("lvl16_generators_space_restrictor_0047")
	olr.del_by_name("hidden_final_sr_rest")
	olr.del_by_name("var_sms_1")
	olr.del_by_name("genertsra_matugalnik")
	olr.del_by_name("genertsra_matugalnik_0000")
	local point = patrol("away_from_triway_look")
	local look = patrol("away_from_triway_walk")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	db.actor:give_info_portion("oso_killed_actor_visel")
	olr.kill_mon_in_radius(db.actor:position(), 155)
end

function start_oso_killed_shahta_exit()
	level.add_cam_effector("camera_effects\\shell_shock.anm", 34956, false, "")
	olr.del_by_name("lvl16_generators_space_restrictor_0062")
	local snd_obj = xr_sound.get_safe_sound_object([[ambient\special\explosion_2]])
	if not snd_obj:playing() then 
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)	
	end
end

function go_to_jaba_escgen()
	olr.del_by_name("lvl16_generators_staler_undead_olr_0006")
	level.add_pp_effector("black.ppe", 20131, false)
	local point = patrol("ac_on_jaba_walk")
	local look = patrol("ac_on_jaba_look")
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function gen_talk_1()
	olr.del_by_name("restrictor_monologe_gen")
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_1_0"), nil, "unknown", 30000)
end

function gen_talk_2()
	olr.del_by_name("restrictor_monologe_gen_0000")
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_2_0"), nil, "unknown", 30000)
end

function gen_talk_3()
	olr.del_by_name("restrictor_monologe_gen_0001")
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_3_0"), nil, "hero", 30000)
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_3_1"), 5, "unknown", 30000)
end

function gen_talk_4()
	olr.del_by_name("restrictor_monologe_gen_0002")
	olr_blowout.blowout_additional_timer3()
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_4_0"), 5, "unknown", 30000)
end

function gen_talk_5()
	olr.del_by_name("restrictor_monologe_gen_0003")
	olr_blowout.blowout_additional_timer2()
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_5_0"), 5, "unknown", 30000)
end

function gen_talk_6()
	olr.del_by_name("restrictor_monologe_gen_0004")
	olr_blowout.blowout_additional_timer()
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_6_0"), 5, "unknown", 30000)
end

function gen_talk_7()
	olr.del_by_name("restrictor_monologe_gen_0005")
	olr_blowout.blowout_additional_timer3()
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_7_0"), 5, "unknown", 30000)
end

function gen_talk_8()
	olr.del_by_name("restrictor_monologe_gen_0006")
	olr_blowout.blowout_additional_timer2()
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_8_0"), 5, "unknown", 30000)
end

function gen_talk_9()
	olr.del_by_name("restrictor_monologe_gen_0007")
	olr_blowout.blowout_additional_timer()
	news_manager.send_tip(db.actor, game.translate_string("gen_talk_9_0"), nil, "unknown", 20000)
end
