--[[------------------------------------------------------------------------------------------------------------------
Класс zone_sound. Проигровка звуков при входе в зону. Разрешение проигровки рандомной озвучки в зоне.
Чугай Саша
--------------------------------------------------------------------------------------------------------------------]]

-- типы звуков для зон
local sound_types = {
	floor_wooden = {
		"ambient\\static\\floor_creak_1",
		"ambient\\static\\floor_creak_2",
		"ambient\\static\\floor_creak_3"
	},
	none_idle = {
		"monsters\\biting\\def_0"
	},
	random = {
		"ambient\\rnd_outdoor\\rnd_ak47_1",
		"ambient\\rnd_outdoor\\rnd_ak47_2",
		"ambient\\rnd_outdoor\\rnd_barking",
		"ambient\\rnd_outdoor\\rnd_car",
		"ambient\\rnd_outdoor\\rnd_chimes",
		"ambient\\rnd_outdoor\\rnd_crow_1",
		"ambient\\rnd_outdoor\\rnd_crow_2",
		"ambient\\rnd_outdoor\\rnd_crow_3",
		"ambient\\rnd_outdoor\\rnd_darkwind",
		"ambient\\rnd_outdoor\\rnd_disgusting",
		"ambient\\rnd_outdoor\\rnd_distantmortar",
		"ambient\\rnd_outdoor\\rnd_doubler",
		"ambient\\rnd_outdoor\\rnd_drone_1",
		"ambient\\rnd_outdoor\\rnd_drone_2",
		"ambient\\rnd_outdoor\\rnd_fallscream",
		"ambient\\rnd_outdoor\\rnd_heart",
		"ambient\\rnd_outdoor\\rnd_helicopter",
		"ambient\\rnd_outdoor\\rnd_horror_1",
		"ambient\\rnd_outdoor\\rnd_horror_2",
		"ambient\\rnd_outdoor\\rnd_horror_3",
		"ambient\\rnd_outdoor\\rnd_horror_4",
		"ambient\\rnd_outdoor\\rnd_m-16_1",
		"ambient\\rnd_outdoor\\rnd_m-16_2",
		"ambient\\rnd_outdoor\\rnd_moan_1",
		"ambient\\rnd_outdoor\\rnd_moan_2",
		"ambient\\rnd_outdoor\\rnd_moan_3",
		"ambient\\rnd_outdoor\\rnd_moan_4",
		"ambient\\rnd_outdoor\\rnd_moan_5",
		"ambient\\rnd_outdoor\\rnd_moan_6",
		"ambient\\rnd_outdoor\\rnd_ratchant",
		"ambient\\rnd_outdoor\\rnd_scr_1",
		"ambient\\rnd_outdoor\\rnd_scr_2",
		"ambient\\rnd_outdoor\\rnd_scr_3",
		"ambient\\rnd_outdoor\\rnd_scr_4",
		"ambient\\rnd_outdoor\\rnd_scr_5",
		"ambient\\rnd_outdoor\\rnd_scr_6",
		"ambient\\rnd_outdoor\\rnd_scr_7",
		"ambient\\rnd_outdoor\\rnd_scr_8",
		"ambient\\rnd_outdoor\\rnd_scr_9",
		"ambient\\rnd_outdoor\\rnd_sickened_1",
		"ambient\\rnd_outdoor\\rnd_sickened_2",
		"ambient\\rnd_outdoor\\rnd_squeak",
		"ambient\\rnd_outdoor\\rnd_thunder",
		"ambient\\rnd_outdoor\\rnd_wolfhowl_1",
		"ambient\\rnd_outdoor\\rnd_wolfhowl_2"
	}
}


-- включить в dest все элементы из src. Таблицы индексированы
function table_include( dest, src )
	if dest and src then
		for i, v in src do
			table.insert( dest, v )
		end
	end
end

-- прочитать число из ini
function r_num( spawn_ini, section, line, default )
	if spawn_ini:line_exist( section, line ) then
		return spawn_ini:r_float( section, line )
	else
		return default
	end
end

----------------------------------------------------------------------------------------------------------------------
local pos, ang

class "zone_sound"

function zone_sound:__init( zone, binder, ini )
	self.zone        = zone
	self.sound_names = {}

	local sect = "sound"

	if ini:line_exist( sect, "snd" ) then
		table_include( self.sound_names, parse_names( ini:r_string( sect, "snd" ) ) )
	end

	if ini:line_exist( sect, "type" ) then
		local t = parse_names( ini:r_string( sect, "type" ) )

		for i, v in t do
			if v == "random" then
				self.random_pos = true
			end

			table_include( self.sound_names, sound_types[v] )
		end
	end

	if table.getn( self.sound_names ) == 0 then
		utils.abort( "restrictor '%s': no sounds specified in section 'sound'", zone:name() )
	end

--	printf( table.concat( self.sound_names, "  " ) )
	self.delay   = r_num( ini, sect, "delay", 0 )
	self.idle    = r_num( ini, sect, "idle",  0 ) * 1000 -- секунды->мс
	self.rnd     = r_num( ini, sect, "rnd", 100 )

	self.idle_end = 0
end

function zone_sound:on_enter( obj )
	if self.idle_end < game.time() then
		self.idle_end = game.time() + self.idle

		if get_clsid( obj ) == clsid.actor and math.random( 100 ) <= self.rnd then
			pos = obj:position()

			if self.random_pos then
				ang = math.pi / 180.0 * math.random( 0, 35900 ) * 0.01
				pos:add( vector():set( math.cos( ang ), 0, math.sin( ang ) ):mul( math.random( 1500, 5000 ) * 0.01 ) )
--				printf( "%f", obj:position():distance_to( pos ) )
			end

			sound_object( self.sound_names[math.random(1, table.getn(self.sound_names))] ):play_at_pos( obj, pos, self.delay )
		end
	end
end
