-------------------- пси протитипы---------------------------------

function docs_brain_ment()
     return nik_dialog.item_much("documentacia_zombibrain_doki",1) ~= false    
end

function psy_1()
     return nik_dialog.item_much("wpn_pistol_future",1) ~= false    
end

function psy_2()
     return nik_dialog.item_much("wpn_power_fists",1) ~= false    
end

function give_psy_1()
	nik_dialog.out_item_much("wpn_pistol_future",1)
end

function give_psy_2()
	nik_dialog.out_item_much("wpn_power_fists",1)
end

function psy_shothan()
     return nik_dialog.item_much("wpn_shotgra",1) ~= false    
end

function psy_art()
     return nik_dialog.item_much("wpn_hands_gravity",1) ~= false    
end

function give_shothan()
	nik_dialog.out_item_much("wpn_shotgra",1)
end

function give_psy_art()
	nik_dialog.out_item_much("wpn_hands_gravity",1)
end

function give_docs_brain_ment()
	nik_dialog.out_item_much("documentacia_zombibrain_doki",1)
	olr.give_item("exo_acum_ob")
end





