

function bar_dolg_basee (actor, npc)
    	level_tasks.add_location(501, "crlc_mdl", "dolg_base_marker")
end


function car_task_moskv (actor, npc)
    	level_tasks.add_location(604, "crlc_mdl", "car_task_moskv_tx")
end


function car_task_lada (actor, npc)
    	level_tasks.add_location(602, "crlc_mdl", "car_task_lada_tx")
end


function car_task_zapor (actor, npc)
    	level_tasks.add_location(603, "crlc_mdl", "car_task_zapor_tx")
end





