-- hi_flyer 16/05/16

local jaba_place = alife():object("lvl1_escape_jaba_place")
local gar_docs_place = alife():object("lvl2_garbage_gar_docs_place")
local nii_docs_place_one = alife():object("lvl3_agroprom_space_restrictor_0015")
local nii_docs_place_two = alife():object("lvl3_agroprom_space_restrictor_0016")
local barman_place = alife():object("lvl5_bar_space_restrictor_0087")
local yantar_place = alife():object("lvl7_yantar_space_restrictor_0068")
local yantar_docs_place = alife():object("lvl7_yantar_space_restrictor_0069")
local military_docs_place = alife():object("lvl9_military_space_restrictor_0024")

function teleport_npc_to_barman(sobj)
	if sobj then
	local idsobj = alife():object(sobj.id)
	if sobj then
		smart_terrain.unregister_npc(idsobj)
	end
	local se_obj = barman_place
		if se_obj then
			alife():teleport_object(sobj.id, se_obj.m_game_vertex_id, se_obj.m_level_vertex_id, se_obj.position)
			--olr.add_spot_on_map( sobj.id,"jaba_spotmap", sobj:name() )
		end
	end	
end


function create_nii_chekers()
  local se_obj = nii_docs_place_one
  if se_obj then
	alife():create("agr_stalker_regular", se_obj.position, se_obj.m_level_vertex_id, se_obj.m_game_vertex_id)
  end
  local se_obj = nii_docs_place_two
  if se_obj then
	alife():create("agr_stalker_veteran", se_obj.position, se_obj.m_level_vertex_id, se_obj.m_game_vertex_id)
  end
end


function create_garbage_chekers()
  local se_obj = gar_docs_place
  if se_obj then
	alife():create("gar_dolg_respawn_1", se_obj.position, se_obj.m_level_vertex_id, se_obj.m_game_vertex_id)
  end
end


function create_holmy_chekers()
  local se_obj = military_docs_place
  if se_obj then
	alife():create("gar_stalker_respawn_2", se_obj.position, se_obj.m_level_vertex_id, se_obj.m_game_vertex_id)
  end
end


function create_yantar_chekers()
  local se_obj = yantar_docs_place
  if se_obj then
	alife():create("yan_ecolog_respawn_1", se_obj.position, se_obj.m_level_vertex_id, se_obj.m_game_vertex_id)
  end
end


function create_radar_chekers()
  local se_obj = gar_docs_place
  if se_obj then
	alife():create("rad_freedom_respawn_3", se_obj.position, se_obj.m_level_vertex_id, se_obj.m_game_vertex_id)
  end
end