-- hi_flyer 18/06/17 

local day_sounds={
"$no_sound"
-- "ambient\\outdoor\\rnd_dark3",
-- "ambient\\outdoor\\rnd_squeak",
-- "ambient\\outdoor\\rnd_ak47_1",
-- "ambient\\outdoor\\rnd_ak47_2",
-- "ambient\\outdoor\\rnd_car",
-- "ambient\\outdoor\\rnd_chimes",
--"ambient\\outdoor\\rnd_cow",
-- "ambient\\outdoor\\rnd_crow1",
-- "ambient\\outdoor\\rnd_crow2",
-- "ambient\\outdoor\\rnd_disgusting",
-- "ambient\\outdoor\\rnd_barking",
-- "ambient\\outdoor\\rnd_doubler",
-- "ambient\\outdoor\\rnd_helicopter",
-- "ambient\\outdoor\\rnd_m-16_4",
-- "ambient\\outdoor\\rnd_moan",
-- "ambient\\outdoor\\rnd_moan1",
-- "ambient\\outdoor\\rnd_moan2",
-- "ambient\\outdoor\\rnd_moan3",
-- "ambient\\outdoor\\rnd_moan4",
-- "ambient\\outdoor\\rnd_moan5",
-- "ambient\\outdoor\\rnd_scr1",
-- "ambient\\outdoor\\rnd_scr2",
-- "ambient\\outdoor\\rnd_scr3",
-- "ambient\\outdoor\\rnd_scr7",
-- "ambient\\outdoor\\rnd_sheep",
-- "ambient\\outdoor\rnd_darkwind4",
-- "ambient\\outdoor\rnd_darkwind3",
-- "ambient\\outdoor\rnd_dog",
-- "ambient\\outdoor\rnd_dog1",
-- "ambient\\outdoor\rnd_dog2",
-- "ambient\\outdoor\rnd_dog3",
-- "ambient\\outdoor\rnd_fly3",
-- "ambient\\outdoor\rnd_helicopter",
-- "ambient\\outdoor\rnd_horror1",
-- "ambient\\outdoor\rnd_shooting_4",
-- "ambient\\outdoor\rnd_shooting_5",
-- "ambient\\outdoor\rnd_snake",
-- "ambient\\outdoor\rnd_wind_1",
-- "ambient\\outdoor\rnd_wind_2",
-- "ambient\\outdoor\rnd_wind_3",
-- "ambient\\outdoor\rnd_wind_tree",
-- "ambient\\b1",
-- "ambient\\b2",
-- "ambient\\b3",
-- "ambient\\b4",
-- "ambient\\b5",
-- "ambient\\b6",
-- "ambient\\b7",
-- "ambient\\organic_moan1",
-- "ambient\\organic_moan2",
-- "ambient\\sp1",
-- "ambient\\sp2",
-- "ambient\\sp3",
-- "ambient\\sp4",
-- "ambient\\wind2",
-- "nature\\new_bird1",
-- "nature\\new_bird2",
-- "nature\\new_bird3",
-- "nature\\new_forest_bird1",
-- "nature\\new_forest_bird2",
-- "nature\\new_forest_bird3",
-- "nature\\new_forest_bird4",
-- "nature\\new_forest_bird5",
-- "nature\\random_flies2",
-- "nature\\wind1",
-- "nature\\wind2"
}

local night_sounds={
"$no_sound"
-- "ambient\\outdoor\rnd_squeak",
-- "ambient\\outdoor\rnd_ak47_1",
-- "ambient\\outdoor\rnd_ak47_2",
-- "ambient\\outdoor\rnd_car",
-- "ambient\\outdoor\rnd_crow1",
-- "ambient\\outdoor\rnd_crow2",
-- "ambient\\outdoor\rnd_crow3",
-- "ambient\\outdoor\rnd_disgusting",
-- "ambient\\outdoor\rnd_distantmortar3",
-- "ambient\\outdoor\rnd_barking",
-- "ambient\\outdoor\rnd_drone1",
-- "ambient\\outdoor\rnd_drone2",
-- "ambient\\outdoor\rnd_fallscream",
-- "ambient\\outdoor\rnd_m-16_3",
-- "ambient\\outdoor\rnd_m-16_4",
-- "ambient\\outdoor\rnd_moan",
-- "ambient\\outdoor\rnd_moan1",
-- "ambient\\outdoor\rnd_moan2",
-- "ambient\\outdoor\rnd_moan3",
-- "ambient\\outdoor\rnd_moan4",
-- "ambient\\outdoor\rnd_moan5",
-- "ambient\\outdoor\rnd_heart",
-- "ambient\\outdoor\rnd_doubler",
-- "ambient\\outdoor\rnd_helicopter",
-- "ambient\\outdoor\rnd_m-16_4",
-- "ambient\\outdoor\rnd_scr1",
-- "ambient\\outdoor\rnd_scr2",
-- "ambient\\outdoor\rnd_scr3",
-- "ambient\\outdoor\rnd_scr7",
-- "ambient\\outdoor\rnd_scr8",
-- "ambient\\outdoor\rnd_scr9",
-- "ambient\\outdoor\rnd_horror1",
-- "ambient\\outdoor\rnd_horror2",
-- "ambient\\outdoor\rnd_horror3",
-- "ambient\\outdoor\rnd_horror4",
-- "ambient\\outdoor\rnd_thunder",
-- "ambient\\outdoor\rnd_wolfhowl01",
-- "ambient\\outdoor\rnd_wolfhowl02",
-- "ambient\\outdoor\rnd_darkwind4",
-- "ambient\\outdoor\rnd_darkwind3",
-- "ambient\\outdoor\rnd_dog",
-- "ambient\\outdoor\rnd_dog1",
-- "ambient\\outdoor\rnd_dog2",
-- "ambient\\outdoor\rnd_dog3",
-- "ambient\\outdoor\rnd_fly3",
-- "ambient\\outdoor\rnd_helicopter",
-- "ambient\\outdoor\rnd_horror1",
-- "ambient\\outdoor\rnd_shooting_4",
-- "ambient\\outdoor\rnd_shooting_5",
-- "ambient\\outdoor\rnd_snake",
-- "ambient\\outdoor\rnd_wind_1",
-- "ambient\\outdoor\rnd_wind_2",
-- "ambient\\outdoor\rnd_wind_3",
-- "ambient\\outdoor\rnd_wind_tree",
--"ambient\\rnd_outdoor\\crickets_1",
--"ambient\\rnd_outdoor\\crickets_2",
--"ambient\\rnd_outdoor\\crickets_3",
--"ambient\\rnd_outdoor\\crow1",
--"ambient\\rnd_outdoor\\crow2",
--"ambient\\rnd_outdoor\\crow3",
--"ambient\\rnd_outdoor\\rnd_boar2",
--"ambient\\rnd_outdoor\\rnd_boar3",
--"ambient\\rnd_outdoor\\owl_1",
--"ambient\\rnd_outdoor\\owl_2",
--"ambient\\rnd_outdoor\\owl_3",
--"ambient\\rnd_outdoor\\rnd_dark",
--"ambient\\rnd_outdoor\\rnd_dark0",
--"ambient\\rnd_outdoor\\rnd_dark1",
--"ambient\\rnd_outdoor\\rnd_dark2",
--"ambient\\rnd_outdoor\\rnd_dark3",
--"ambient\\rnd_outdoor\\rnd_dark4",
--"ambient\\rnd_outdoor\\rnd_dark5",
--"ambient\\rnd_outdoor\\rnd_dark6",
--"ambient\\rnd_outdoor\\rnd_dark7",
--"ambient\\rnd_outdoor\\rnd_dark8",
--"ambient\\rnd_outdoor\\rnd_dark9",
--"ambient\\rnd_outdoor\\rnd_dark10",
--"ambient\\rnd_outdoor\\rnd_darkwind1",
--"ambient\\rnd_outdoor\\rnd_darkwind2",
--"ambient\\rnd_outdoor\\rnd_darkwind3",
--"ambient\\rnd_outdoor\\rnd_darkwind4",
--"ambient\\rnd_outdoor\\rnd_darkwind5",
--"ambient\\rnd_outdoor\\rnd_darkwind6",
--"ambient\\rnd_outdoor\\rnd_drone1",
--"ambient\\rnd_outdoor\\rnd_drone2",
--"ambient\\rnd_outdoor\\rnd_horror",
--"ambient\\rnd_outdoor\\rnd_horror1",
--"ambient\\rnd_outdoor\\rnd_howling_1",
--"ambient\\rnd_outdoor\\rnd_howling_2",
--"ambient\\rnd_outdoor\\rnd_krik1",
--"ambient\\rnd_outdoor\\rnd_krik2",
--"ambient\\rnd_outdoor\\rnd_krik3",
--"ambient\\rnd_outdoor\\rnd_krik4",
--"ambient\\rnd_outdoor\\rnd_krik5",
--"ambient\\rnd_outdoor\\rnd_krik6",
--"ambient\\rnd_outdoor\\rnd_krik7",
--"ambient\\rnd_outdoor\\rnd_krik8",
--"ambient\\rnd_outdoor\\rnd_krik9",
--"ambient\\rnd_outdoor\\rnd_moan",
--"ambient\\rnd_outdoor\\rnd_moan1",
--"ambient\\rnd_outdoor\\rnd_moan2",
--"ambient\\rnd_outdoor\\rnd_moan3",
--"ambient\\rnd_outdoor\\rnd_moan4",
--"ambient\\rnd_outdoor\\rnd_moan5",
--"ambient\\rnd_outdoor\\rnd_moan6",
--"ambient\\rnd_outdoor\\rnd_pdog",
--"ambient\\rnd_outdoor\\rnd_pdog1",
--"ambient\\rnd_outdoor\\rnd_pdog2",
--"ambient\\rnd_outdoor\\rnd_pdog3",
--"ambient\\rnd_outdoor\\rnd_wind_1",
--"ambient\\rnd_outdoor\\rnd_wind_2",
--"ambient\\rnd_outdoor\\rnd_wind_3",
--"ambient\\rnd_outdoor\\rnd_wind_tree",
--"ambient\\rnd_outdoor\\rnd_wolfhowl01",
--"ambient\\rnd_outdoor\\rnd_wolfhowl02",
--"ambient\\cold_wind_11",
--"ambient\\cold_wind_12",
--"ambient\\crickets_1",
--"ambient\\crickets_2",
--"ambient\\crickets_3",
--"ambient\\darkwind1",
--"ambient\\darkwind2",
-- "ambient\\earthquake",
-- "ambient\\howling_1",
-- "ambient\\howling_2",
-- "ambient\\howling_wind_11",
-- "ambient\\howling_wind_12",
-- "ambient\\iron_moaning1",
-- "ambient\\organic_moan1",
-- "ambient\\organic_moan2",
-- "ambient\\owl_1",
-- "ambient\\owl_2",
-- "ambient\\owl_3",
-- "ambient\\rats_panic_3",
-- "ambient\\wind2",
-- "ambient\\suck1",
-- "nature\\new_crow1",
-- "nature\\new_crow2",
-- "nature\\new_crow3",
-- "nature\\rt_eerie_wind1",
-- "nature\\rnd_sickened1",
-- "nature\\rnd_sickened2",
-- "nature\\rnd_cooing",
-- "nature\\rt_ambient1",
-- "nature\\rt_ambient2",
-- "nature\\random_flies2",
-- "nature\\wind1",
-- "nature\\wind2",
}

local default_sounds={
"$no_sound"
-- "ambient\\cold_wind_11",
-- "ambient\\cold_wind_12",
-- "ambient\\organic_moan1",
-- "ambient\\organic_moan2",
-- "ambient\\outdoor\\rnd_wind_1",
-- "ambient\\outdoor\\rnd_wind_2",
-- "ambient\\outdoor\\rnd_wind_3",
-- "ambient\\outdoor\\rnd_wind_tree",
-- "nature\\wind1",
-- "nature\\wind2",
--"ambient\\rnd_outdoor\\rnd_dark",
--"ambient\\rnd_outdoor\\rnd_dark0",
--"ambient\\rnd_outdoor\\rnd_dark1",
--"ambient\\rnd_outdoor\\rnd_dark2",
--"ambient\\rnd_outdoor\\rnd_dark3",
--"ambient\\rnd_outdoor\\rnd_dark4",
--"ambient\\rnd_outdoor\\rnd_dark5",
--"ambient\\rnd_outdoor\\rnd_dark6",
--"ambient\\rnd_outdoor\\rnd_dark7",
--"ambient\\rnd_outdoor\\rnd_dark8",
--"ambient\\rnd_outdoor\\rnd_dark9",
--"ambient\\rnd_outdoor\\rnd_dark10",
--"ambient\\rnd_outdoor\\rnd_darkwind1",
--"ambient\\rnd_outdoor\\rnd_darkwind2",
--"ambient\\rnd_outdoor\\rnd_darkwind3",
--"ambient\\rnd_outdoor\\rnd_darkwind4",
--"ambient\\rnd_outdoor\\rnd_darkwind5",
--"ambient\\rnd_outdoor\\rnd_darkwind6"
}

local indoor_lab_sounds = {
"$no_sound"
-- "ambient\\underground\\breath_1",
-- "ambient\\underground\\breath_2",
-- "ambient\\underground\\breath_3",
-- "ambient\\underground\\breath_4",
-- "ambient\\underground\\hit_1",
-- "ambient\\underground\\hit_2",
-- "ambient\\underground\\hit_3",
-- "ambient\\x18\\fan1",
-- "ambient\\x18\\h_am_hit1",
-- "ambient\\x18\\h_am_hit4",
-- "ambient\\x18\\h_or_metal_large",
-- "ambient\\x18\\h_or_metal_rusty",
-- "ambient\\x18\\h_otsteps_wood1",
-- "ambient\\x18\\h_tal_grate_impact_hard2",
-- "ambient\\x18\\h_tal_grate_impact_hard3",
-- "ambient\\x18\\h_tal5",
-- "ambient\\x18\\x18_footsteps",
-- "ambient\\x18\\x18_footsteps_2",
-- "ambient\\x18\\x18_hit_6",
-- "ambient\\x18\\x18_hit_7",
-- "ambient\\x18\\x18_hit_8",
-- "ambient\\x18\\x18_move_1",
-- "ambient\\x18\\x18_move_2",
-- "ambient\\x18\\x18_move_3",
-- "ambient\\x18\\x18_move_4",
-- "ambient\\x18\\x18_move_5",
-- "ambient\\x18\\x18_noise_1",
-- "ambient\\x18\\x18_noise_2",
-- "ambient\\x18\\x18_wind_1",
-- "ambient\\x18\\x18_wind_2",
-- "ambient\\x18\\x18_wind_3",
-- "ambient\\earthquake",
-- "ambient\\floor_creak1",
-- "ambient\\floor_creak2",
-- "ambient\\floor_creak3",
-- "ambient\\new_drops1",
-- "ambient\\organic_moan2",
-- "ambient\\rats_panic_1",
-- "ambient\\rats_panic_2",
-- "ambient\\rats_panic_3",
-- "ambient\\switch_1",
-- "ambient\\switch_2",
-- "ambient\\waterdrops1",
}



local monolith_call = {
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_1",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_2",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_3",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_4",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_5",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_6",
"characters_voice\\scenario\\sarcofag\\monolith\\monolith_call_7"
}

local bsnd_obj = xr_sound.get_safe_sound_object([[music\mon_murderwrecker_l]])

function play_rnd_snd()

		if not level.present() then return end

      		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_bossfight_zone"})) then
			if has_alife_info("oso_killed") then return end

			local snd_obj = xr_sound.get_safe_sound_object(indoor_lab_sounds[math.random(table.getn(indoor_lab_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
			local randd = math.random(1,3)
			if randd == 1 then
				olr.spawen_phantoms()
				nick.clear_chaes_zom()
			elseif randd == 2 then
				nick.stancia_fake_anoms()
			else
				nick.phantasms_zombies()
			end

			if not bsnd_obj:playing() then 
				bsnd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
			end

		end

		if level.name() == "lvl_mars" then return end
		if level.name() == "lvl16_generators" then return end 

		if has_alife_info("olr_traders_night") and not olr.actor_in_lab() then
			local snd_obj = xr_sound.get_safe_sound_object(night_sounds[math.random(table.getn(night_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		elseif has_alife_info("olr_traders_day") and not olr.actor_in_lab() and level.rain_factor() <= 0.1 then
			local snd_obj = xr_sound.get_safe_sound_object(day_sounds[math.random(table.getn(day_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		else
			local snd_obj = xr_sound.get_safe_sound_object(default_sounds[math.random(table.getn(default_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		end
		if olr.actor_in_lab() then
			local snd_obj = xr_sound.get_safe_sound_object(indoor_lab_sounds[math.random(table.getn(indoor_lab_sounds))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
		end
		if actor_on_chaes() then
			local snd_obj = xr_sound.get_safe_sound_object(monolith_call[math.random(table.getn(monolith_call))])
			local a=vector()
			a.x=math.random(0,1)
			a.y=math.random(0,1)
			a.z=math.random(0,1)
			snd_obj:play_at_pos(db.actor, db.actor:position():add(a))
			local rnd = math.random(1,5)
			if rnd == 1 then
				olr.spawen_phantoms()
				nick.clear_chaes_zom()
			else
				nick.stancia_fake_anoms()
			end
		end
end


-- db.actor:is_actor_outdoors() == false


function actor_on_chaes()
	local level_name = level.name()
	if level_name == "lvl14_stancia" and not has_alife_info("actor_ishet_sebbya_info") then
		return true
	end
end


