------Copyright DEXXX-------soundtrack

snd_obj = {}
snd_obj = xr_sound.get_safe_sound_object([[soundtrack\escape_theme]])

function s_stop()
	if snd_obj:playing()==true then snd_obj:stop() end
end

function s_play(path)
	s_stop()
	snd_obj = xr_sound.get_safe_sound_object(path)
	if snd_obj then
		snd_obj:play_at_pos(db.actor, vector ():set (0, 0, 0), 0, sound_object.s2d)
	end
end


--------------------------------------------
function grass_walk()
s_play([[ambient\special\step_grass]])
end


--------------------------------------------

function occusion()
s_play([[heart\2]])
end


function mil_skull_lol()
if has_alife_info("mil_vishka_night_go_del") then
return
end
s_play([[ambient\special\low_base]])
end


function esc_prizrak_agressive()
s_play([[ambient\rnd_outdoor\rnd_horror_3]])
end



function darklab_start_bassz()
s_play([[ambient\special\darklab_ambient]])
end


function bar_skull_lol()
s_play([[ambient\special\low_base]])
end

function gar_zom_woo()
s_play([[ambient\special\zombie_call]])
end

function ros_shoot_max()
s_play([[weapons\protecta_shoot]])
end


function svd_shoot_max()
s_play([[weapons\rc_svd_shot]])
end

function gen_last_sch()
s_play([[ambient\special\rostok_bloodsucker_call]])
end

function gen_last_schs()
news_manager.send_tip(db.actor, game.translate_string("gen_last_schs_0"), 1, "item", 25000)
news_manager.send_tip(db.actor, game.translate_string("gen_last_schs_1"), 5, "saharov", 25000)
olr.del_by_name("lvl16_generators_physic_object_0210")
	olr.kill_mon_in_radius(db.actor:position(), 150)
s_play([[ambient\special\siren_gen]])
end

function ros_veter_plen_snd()
s_play([[ambient\special\bloodsucker_sucking]])
end

function ros_sosichi_roscall_snd()
s_play([[ambient\special\rostok_bloodsucker_call]])
end
---------------------------------------------------

function blowout_snd_pre()
s_play([[ambient\blowout\blowout_begin]])
end

function blowout_snd_go()
s_play([[ambient\blowout\blowout]])
end

--------------------------


function samaya_hata_prip()
s_play([[ambient\special\fear_hata]])
end


function short_siren()
s_play([[scripts\a_siren]])
end


function pridi_gar_mon()
s_play([[characters_voice\scenario\sarcofag\monolith\monolith_call_1]])
end

function ghouls_orut_out()
s_play([[ambient\special\sob]])
end

function vkl_pitanie()
s_play([[ambient\special\power_on]])
end

function vkl_pitanie2()
s_play([[ambient\special\power_switch]])
end

function vkl_pitanie3()
s_play([[ambient\special\use_canister]])
end

function radovoy_talking_srnd_1()
s_play([[characters_voice\scenario\darkvalley\scared_military\scared_military_1]])
end

function radovoy_talking_srnd_2()
s_play([[characters_voice\scenario\darkvalley\scared_military\scared_military_2]])
	news_manager.send_tip(db.actor, game.translate_string("radovoy_talking_srnd_2_0"), nil, "act", 31000)
end

function radovoy_talking_srnd_3()
s_play([[characters_voice\scenario\darkvalley\scared_military\scared_military_3]])
end

function radovoy_talking_srnd_4()
s_play([[characters_voice\scenario\darkvalley\scared_military\scared_military_4]])
end

function radovoy_talking_srnd_5()
s_play([[characters_voice\scenario\darkvalley\scared_military\scared_military_5]])
end

---------------------------------------------------

function musicsd_tea()
s_play([[ambient\special\rostok_film_music]])
end


function sosaka_cut_ros()
s_play([[monsters\bloodsucker\take_damage_0]])
end


function achit1()
s_play([[actor\hurt_1]])
end

function achit2()
s_play([[actor\hurt_4]])
end


------------------------

function flaer_2()
	olr_timers.st_timer("flaer_3", 2, "soundtrack.flaer_3()")
	olr_timers.st_timer("flaer_3", 285, "nick.fraer_yeag_3()")
end

function flaer_3()
	olr.del_by_name("lvl4_darkdolina_stalker_0071")
end
---------wolf----------

function wolf_dontshoot()
s_play([[ol25\01]])
end

function wolf_kontr()
s_play([[ol25\04]])
end

function wolf_disat()
s_play([[ol25\08]])
end


---------dol slizen----------

function sliz1()
s_play([[olr\slizen\222]])
end

function sliz2()
s_play([[sergy_new\otbarmena]])
end

function sliz3()
s_play([[sergy_new\yatoznayu]])
end

function sliz4()
s_play([[sergy_new\davaitopai]])
end

function sliz5()
s_play([[sergy_new\votislavno]])
end


---------bar seryy----------

function ser1()
--s_play([[olr\ser\ser1]])
end

function ser2()
--s_play([[olr\ser\ser2]])
end
function ser3()
--s_play([[olr\ser\ser3]])
end
function ser4()
--s_play([[olr\ser\ser4]])
end

function ser5()
--s_play([[olr\ser\ser5]])
end

function ser6()
--s_play([[olr\ser\ser6]])
end




---------bar seryy----------


function rc_svd_shot()
s_play([[weapons\rc_svd_shot]])
end

function loshok_hello()
s_play([[soundtrack\prof_che_nado]])
end

function nehami_hello()
s_play([[soundtrack\prof_ne_hami]])
end

---------ESCAPE----------

function horek_1()
s_play([[soundtrack\olr_escape\horek_1]])
end


function horek_2()
s_play([[soundtrack\olr_escape\horek_2]])
end

-------------------

function x18_laugh()
s_play([[ambient\special\tun_noise]])
end








