--[[-----------------------------------------------------------------------------------------------
 File         : sr_deadnight.script
 Description  : Модуль включения indoor погоды
 Copyright    : Oblivion Lost Remake 3.0
 Author       : hi_flyer
 Date         : 17.05.15
 Last Edit    : 17.05.15
--]]----------------------------------------------------------------------------------------------- 


local state_nowhere = 0 -- схема только что включилась
local state_inside = 1 -- актер внутри
local state_outside = 2 -- актер снаружи



class "action_deadnight"

function action_deadnight:__init( obj, storage )
	self.object = obj
	self.st = storage
end

function action_deadnight:reset_scheme()
	
	self.state = state_nowhere -- еще неясно, в зоне он, или нет
	
	self:switch_state(db.actor)
end

function action_deadnight:update( delta )
	local actor = db.actor

	if xr_logic.try_switch_to_another_section( self.object, self.st, actor ) then
		return
	end	
	
	self:switch_state( actor )
	
	if self.state == state_inside then
	
             level.set_weather("indoor")
                      	
        end
	 
        if self.state == state_outside and level.name() == "lvl4_darkdolina" then
		if not has_alife_info("bar_1_done") then
             		level.set_weather("tuman")
        	else 
             		level.set_weather("serg")               	
		end
	end

        if self.state == state_outside and level.name() == "lvl3_agroprom" then
        	level.set_weather("1865")
		--log1("agro")               	
	end
        if self.state == state_outside and level.name() == "lvl16_generators" then
		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_space_restrictor_0049"}))  then
			return
		end
		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_space_restrictor_0069"}))  then
			return
		end
		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_space_restrictor_0029"}))  then
			return
		end
		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_space_restrictor_0065"}))  then
			return
		end
		if ( xr_conditions.actor_in_zone(nil,nil,{"lvl16_generators_space_restrictor_0045"}))  then
			return
		end
        	level.set_weather("gen")
		--log1("agro")               	
	end
        if self.state == state_outside and level.name() == "lvl6_rostok" then
        	level.set_weather("1865")
		--log1("agro")               	
	end
end




function action_deadnight:switch_state( actor )
	local state = self.state
	
	if state == state_outside or state == state_nowhere then
		if self.object:inside( actor:center() ) then
			self:zone_enter()
			return
		end
	end
	
	if state == state_inside or state == state_nowhere then
		if not self.object:inside( actor:center() ) then
			self:zone_leave()
			return
		end
	end
end

function action_deadnight:zone_enter()
	self.state = state_inside
end

function action_deadnight:zone_leave()
	self.state = state_outside

        if level.name() == "lvl4_darkdolina" and not has_alife_info("bar_1_done") then
             level.set_weather("tuman")  
        else 
             level.set_weather("serg")                	
	end

        if self.state == state_outside and level.name() == "lvl3_agroprom" then
        	level.set_weather("1865")
		--log1("agro")               	
	end

        if self.state == state_outside and level.name() == "lvl16_generators" then
        	level.set_weather("gen")
		--log1("agro")               	
	end
        if self.state == state_outside and level.name() == "lvl6_rostok" then
        	level.set_weather("1865")
		--log1("agro")               	
	end
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: scheme='%s', section='%s'", scheme, section)

	local new_action = action_deadnight(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end



---------------------------------------------------------------------------------------------------------------------




		
	
	
